import type { Question } from "./types";

// Finance cases. Every answer is a decision with a stated threshold, since a
// hedged view is worth nothing in an investment conversation.
export const FINANCE_CASES: Question[] = [
  {
    slug: "qsr-chain-comparables-valuation",
    shape: "case",
    title: "Value a listed quick service restaurant chain on comparables. Which multiple, and why?",
    type: "Valuation",
    difficulty: 3,
    minutes: 35,
    askedAt: "Goldman Sachs",
    answer: "Enterprise value to EBITDA, on a set built from store economics with lease treatment held consistent. Give a range, never a point.",
    hints: ["Pick the multiple that matches where the business sits in its life cycle."],
    moves: [
      { label: "Move 1", text: "Choose the metric. Price to earnings breaks for a chain in heavy expansion, so EV to EBITDA is the starting point." },
      { label: "Move 2", text: "Build comparables on business model, not sector label. Store economics and franchise mix matter more than the food." },
      { label: "Move 3", text: "Adjust for lease liabilities, since inconsistent treatment across comparables is the most common error here." },
      { label: "Move 4", text: "Explain the premium or discount using same-store sales growth and new store payback." },
      { label: "Close", text: "Give a range with the two or three assumptions that would move it." },
    ],
    pitfalls: [
      "Using price to earnings for a company deliberately suppressing earnings to expand.",
      "Building the comparable set on sector rather than store economics.",
      "Quoting a point valuation with no sensitivity.",
    ],
  },
  {
    slug: "d2c-brand-burn-investment-call",
    shape: "case",
    title: "A D2C brand is burning 4 crore rupees a month. Would you invest?",
    type: "Investment call",
    difficulty: 2,
    minutes: 30,
    askedAt: "Sequoia",
    answer: "Invest only if contribution-margin payback is under twelve months and cohort repeat rate is rising. Otherwise no.",
    hints: ["Burn on its own is meaningless. Burn against what it buys is the question."],
    moves: [
      { label: "Move 1", text: "Split the burn. Marketing spend buying growth differs from overhead funding a team with no demand." },
      { label: "Move 2", text: "Work the unit economics: contribution after cost of goods, shipping, returns and payment fees." },
      { label: "Move 3", text: "Test repeatability through cohort repeat rate and time to second purchase." },
      { label: "Move 4", text: "Check payback. Under twelve months and improving is investable, over eighteen and flat is buying revenue." },
      { label: "Close", text: "Answer directly with a condition attached, since the question asked for a decision." },
    ],
    pitfalls: [
      "Treating gross margin as contribution margin.",
      "Accepting a lifetime value built on an assumed retention curve.",
      "Hedging when the question demanded a decision.",
    ],
  },
  {
    slug: "debt-or-equity-new-plant",
    shape: "case",
    title: "Debt or equity for a manufacturer's new plant?",
    type: "Capital structure",
    difficulty: 2,
    minutes: 25,
    askedAt: "ICICI",
    answer: "Debt-led with an equity component, up to the leverage ceiling the covenants and the cycle allow.",
    hints: ["Match the funding to the cash flow profile of what it is funding."],
    moves: [
      { label: "Move 1", text: "Characterise the asset. A plant produces predictable long-life cash flow, which is what debt is designed for." },
      { label: "Move 2", text: "Check current leverage and covenant headroom, which determines how much debt is actually available." },
      { label: "Move 3", text: "Compare cost. Debt is cheaper and tax-deductible but adds fixed obligations against cyclical revenue." },
      { label: "Move 4", text: "Weigh dilution and control, which for a promoter-led Indian firm often decides it." },
      { label: "Close", text: "Recommend a split and name the leverage threshold at which you would change the mix." },
    ],
    pitfalls: [
      "Answering from theory without checking existing leverage.",
      "Ignoring revenue cyclicality that must service the debt.",
      "Forcing a binary when a mix is what gets recommended.",
    ],
  },
  {
    slug: "quick-commerce-unit-economics",
    shape: "case",
    title: "Break down the unit economics of a ten minute grocery order.",
    type: "Unit economics",
    difficulty: 2,
    minutes: 20,
    askedAt: "Blume",
    answer: "Thin positive contribution per order before store fixed cost. Profitability turns on orders per dark store per day, not on the order itself.",
    hints: ["Start from average order value and work down line by line to contribution."],
    moves: [
      { label: "Move 1", text: "Start at the top. Average order value near 500 rupees with product gross margin around 20%." },
      { label: "Move 2", text: "Subtract variable delivery cost: rider payout of 30 to 40 rupees plus packaging." },
      { label: "Move 3", text: "Allocate dark store fixed cost, divided by orders per day, which is why throughput decides profitability." },
      { label: "Move 4", text: "Add the revenue lines that close the gap: delivery fees, platform fees and in-app brand advertising." },
      { label: "Close", text: "State the break-even in orders per store per day, since that single number is what the model rests on." },
    ],
    pitfalls: [
      "Stopping at gross margin and declaring the order profitable.",
      "Ignoring dark store fixed cost.",
      "Forgetting advertising revenue, which is large and growing.",
    ],
  },
  {
    slug: "nbfc-credit-small-transporters",
    shape: "case",
    title: "Assess the credit of an NBFC lending to small transporters.",
    type: "Credit",
    difficulty: 3,
    minutes: 30,
    answer: "The asset is the truck and the risk is the borrower's route economics. Repossession value and collection capability matter more than the credit score.",
    hints: ["In secured lending to thin-file borrowers, recovery is the underwriting, not the score."],
    moves: [
      { label: "Move 1", text: "Characterise the borrower: typically thin credit file, cash-based income, single-vehicle owner-operators." },
      { label: "Move 2", text: "Assess the collateral. Truck resale values are real but fall sharply with age and regulation changes." },
      { label: "Move 3", text: "Test collection capability, since this book depends on field collection rather than automated repayment." },
      { label: "Move 4", text: "Stress the cycle. Freight rate downturns and fuel spikes hit these borrowers simultaneously and hard." },
      { label: "Close", text: "Give a credit view with the loan-to-value and collection infrastructure conditions you would require." },
    ],
    pitfalls: [
      "Applying salaried underwriting logic to cash-income borrowers.",
      "Assuming stable collateral value across vehicle age and emission norms.",
      "Ignoring correlation, since these borrowers all suffer in the same downturn.",
    ],
  },
  {
    slug: "acquisition-accretive-eps-dilutive-roic",
    shape: "case",
    title: "An acquisition is accretive on EPS but dilutive on returns. Advise.",
    type: "M&A",
    difficulty: 3,
    minutes: 35,
    askedAt: "Morgan Stanley",
    answer: "Do not do it on EPS accretion alone. Cheap debt can make almost any deal accretive, which is why it proves nothing about value creation.",
    hints: ["EPS accretion is an arithmetic result of financing. Returns tell you whether value was created."],
    moves: [
      { label: "Move 1", text: "Explain the mechanism. Debt-funded acquisitions are accretive whenever the earnings yield exceeds the after-tax cost of debt." },
      { label: "Move 2", text: "Note that this says nothing about whether the price paid was sensible." },
      { label: "Move 3", text: "Work the returns view. Return on invested capital below the cost of capital destroys value regardless of EPS." },
      { label: "Move 4", text: "Test the synergy case, which is the only thing that can genuinely justify the premium." },
      { label: "Close", text: "Recommend against unless synergies close the returns gap, and quantify what they would need to be." },
    ],
    pitfalls: [
      "Treating EPS accretion as evidence of a good deal.",
      "Ignoring the added balance sheet risk from acquisition debt.",
      "Accepting synergy estimates without testing them.",
    ],
  },
  {
    slug: "value-a-loss-making-startup",
    shape: "case",
    title: "How would you value a loss-making startup with strong growth?",
    type: "Valuation",
    difficulty: 3,
    minutes: 30,
    answer: "Forward revenue multiple sense-checked against a discounted path to profitability. Neither method alone is defensible.",
    hints: ["Earnings-based methods do not work. Say why, then choose deliberately."],
    moves: [
      { label: "Move 1", text: "Reject earnings multiples explicitly, since there are no earnings to multiply." },
      { label: "Move 2", text: "Use forward revenue multiples from comparable listed and private transactions, adjusted for growth and margin profile." },
      { label: "Move 3", text: "Build a path to profitability and discount it, accepting that the terminal value dominates the result." },
      { label: "Move 4", text: "Triangulate. If the two methods diverge wildly, the growth or margin assumption is doing all the work." },
      { label: "Close", text: "Present a range with the assumption that moves it most, and say what evidence would narrow the range." },
    ],
    pitfalls: [
      "Applying a revenue multiple with no view on the eventual margin.",
      "Building a discounted cash flow where terminal value is 95% of the answer without saying so.",
      "Using peak-market multiples as if they were normal.",
    ],
  },
  {
    slug: "bank-net-interest-margin-compressing",
    shape: "case",
    title: "A bank's net interest margin is compressing. Diagnose it.",
    type: "Profitability",
    difficulty: 3,
    minutes: 30,
    answer: "Usually deposit repricing running ahead of loan repricing, or a mix shift toward safer, lower-yielding assets.",
    hints: ["Margin has two sides. Establish whether the yield fell or the cost of funds rose."],
    moves: [
      { label: "Move 1", text: "Split the margin into asset yield and cost of funds, and see which moved." },
      { label: "Move 2", text: "Check repricing speed. In a rising rate cycle, deposits often reprice faster than the loan book." },
      { label: "Move 3", text: "Check the deposit mix. A shift from current and savings accounts to term deposits raises funding cost sharply." },
      { label: "Move 4", text: "Check the asset mix. Moving toward secured, lower-risk lending lowers yield by design." },
      { label: "Close", text: "Recommend against the driver found, and note that some margin compression is a deliberate risk choice rather than a failure." },
    ],
    pitfalls: [
      "Assuming compression is always bad, when it can reflect a safer book.",
      "Looking only at the asset side.",
      "Ignoring the deposit mix, which is often the actual cause.",
    ],
  },
  {
    slug: "should-company-buy-back-shares",
    shape: "case",
    title: "A cash-rich company is considering a buyback. Advise.",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 25,
    answer: "Only if there is genuinely no investment earning above the cost of capital and the shares are not expensive. Otherwise it is capital destruction dressed as discipline.",
    hints: ["A buyback is an investment in your own shares. Judge it the way you would judge any investment."],
    moves: [
      { label: "Move 1", text: "Establish the alternatives: organic investment, acquisition, debt reduction, dividends, or holding cash." },
      { label: "Move 2", text: "Test the reinvestment case. If projects earn above the cost of capital, they beat a buyback." },
      { label: "Move 3", text: "Test the valuation. Buying back overvalued shares transfers value from continuing to exiting shareholders." },
      { label: "Move 4", text: "Compare against dividends on tax treatment and on signalling, which differ meaningfully in India." },
      { label: "Close", text: "Recommend with the valuation condition stated, and note that EPS improvement is not the justification." },
    ],
    pitfalls: [
      "Justifying a buyback on EPS accretion.",
      "Ignoring the share price, which determines whether it creates or destroys value.",
      "Treating surplus cash as automatically requiring return to shareholders.",
    ],
  },
  {
    slug: "insurance-company-underwriting-loss",
    shape: "case",
    title: "An insurer is making underwriting losses but reports a profit. Explain.",
    type: "Profitability",
    difficulty: 3,
    minutes: 30,
    answer: "Investment income on float is covering the underwriting loss. Sustainable only while investment returns hold and the loss ratio does not worsen.",
    hints: ["Insurers have two businesses. Separate underwriting from investing before judging anything."],
    moves: [
      { label: "Move 1", text: "Separate the two engines: underwriting result and investment income on premiums held before claims." },
      { label: "Move 2", text: "Compute the combined ratio. Above 100% means underwriting is losing money on every policy." },
      { label: "Move 3", text: "Assess sustainability. Investment income depends on rates and on the float, which shrinks if premiums fall." },
      { label: "Move 4", text: "Check the segment mix, since motor third-party is structurally loss-making while health and property may not be." },
      { label: "Close", text: "Recommend on underwriting discipline, and state the combined ratio you would want the business to reach." },
    ],
    pitfalls: [
      "Reading the bottom line without separating the two businesses.",
      "Assuming investment returns are a permanent subsidy for bad underwriting.",
      "Averaging across segments with very different loss ratios.",
    ],
  },
  {
    slug: "leveraged-buyout-feasibility",
    shape: "case",
    title: "Is this business a good leveraged buyout candidate?",
    type: "Investment call",
    difficulty: 3,
    minutes: 35,
    answer: "It needs stable predictable cash flow, low capital intensity and assets that support debt. Growth is nice but cash flow stability is the requirement.",
    hints: ["The question is whether it can service debt through a downturn, not whether it can grow."],
    moves: [
      { label: "Move 1", text: "Test cash flow stability, which is the primary requirement since debt service is not optional." },
      { label: "Move 2", text: "Test capital intensity. A business needing constant capital expenditure has less free cash for debt service." },
      { label: "Move 3", text: "Assess asset backing, since lenders want collateral and it affects how much debt is available." },
      { label: "Move 4", text: "Model the downside. The deal must survive a recession scenario, not merely work in the base case." },
      { label: "Close", text: "Give a view with the leverage level and the exit route you would assume." },
    ],
    pitfalls: [
      "Focusing on growth potential rather than cash flow stability.",
      "Ignoring capital expenditure needs that compete with debt service.",
      "Not stress testing the downside, which is where these deals fail.",
    ],
  },
  {
    slug: "dividend-policy-for-cyclical-business",
    shape: "case",
    title: "Set a dividend policy for a cyclical commodity business.",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 25,
    answer: "A modest sustainable base dividend plus variable special payouts in good years. A high fixed dividend forces borrowing in downturns.",
    hints: ["A dividend cut is punished severely. Set the base at a level you can pay in a bad year."],
    moves: [
      { label: "Move 1", text: "Characterise the cash flows. Commodity earnings swing enormously across the cycle." },
      { label: "Move 2", text: "Note the signalling asymmetry. Markets punish cuts far more than they reward increases." },
      { label: "Move 3", text: "Set the base at trough affordability, not at average or peak earnings." },
      { label: "Move 4", text: "Add special dividends or buybacks in strong years to return surplus without raising the base commitment." },
      { label: "Close", text: "Recommend the structure and state the trough earnings level you sized the base against." },
    ],
    pitfalls: [
      "Setting a payout ratio against average earnings.",
      "Ignoring the asymmetric market reaction to cuts.",
      "Committing to a progressive policy in a business that cannot support one.",
    ],
  },
  {
    slug: "working-capital-crisis-at-supplier",
    shape: "case",
    title: "A key supplier is running out of working capital. What do you do?",
    type: "Risk",
    difficulty: 2,
    minutes: 25,
    answer: "Support them if switching cost exceeds the support cost, through supply chain finance rather than by paying higher prices.",
    hints: ["Compare the cost of helping against the cost of them failing. That is the whole decision."],
    moves: [
      { label: "Move 1", text: "Assess dependence. A sole-source supplier of a critical component is a completely different situation from a commodity vendor." },
      { label: "Move 2", text: "Cost the failure: production stoppage, requalification time and expedited alternative sourcing." },
      { label: "Move 3", text: "Consider supply chain finance, where your credit rating lets them borrow cheaply against your receivable." },
      { label: "Move 4", text: "Avoid simply raising prices, which is expensive, permanent and does not fix their cash cycle." },
      { label: "Close", text: "Recommend the mechanism with the dependence-reduction plan attached, since this should not recur." },
    ],
    pitfalls: [
      "Deciding on sentiment rather than switching cost.",
      "Raising prices as the default remedy.",
      "Solving the immediate problem without reducing single-source dependence.",
    ],
  },
  {
    slug: "currency-hedging-policy",
    shape: "case",
    title: "Design a currency hedging policy for an exporter.",
    type: "Risk",
    difficulty: 3,
    minutes: 30,
    answer: "Hedge net exposure on a rolling horizon with a fixed ratio. The policy matters more than any individual view on the currency.",
    hints: ["A hedging policy exists to remove judgement, not to express a view on the rupee."],
    moves: [
      { label: "Move 1", text: "Compute net exposure. Foreign currency revenue minus foreign currency costs, not revenue alone." },
      { label: "Move 2", text: "Set the objective: reducing earnings volatility, not maximising currency gains." },
      { label: "Move 3", text: "Choose a rolling horizon with a declining hedge ratio further out, since forecasts weaken with distance." },
      { label: "Move 4", text: "Choose instruments. Forwards are simple and adequate for most exporters, options cost premium for optionality." },
      { label: "Close", text: "Recommend the policy with governance attached, since the failure mode is a treasury team taking speculative positions." },
    ],
    pitfalls: [
      "Hedging gross rather than net exposure.",
      "Treating hedging as a profit centre.",
      "Building a policy with no governance to stop discretionary deviation.",
    ],
  },
  {
    slug: "is-this-real-estate-project-viable",
    shape: "case",
    title: "Assess whether a residential real estate project is viable.",
    type: "Investment call",
    difficulty: 3,
    minutes: 30,
    answer: "Land cost as a share of expected sales value decides it. Above roughly a third, the project has almost no margin for error.",
    hints: ["Land cost is sunk before anything is sold. That ratio is the whole risk."],
    moves: [
      { label: "Move 1", text: "Establish land cost per saleable square foot, which is fixed the moment the land is bought." },
      { label: "Move 2", text: "Estimate achievable realisation, based on comparable projects rather than on aspiration." },
      { label: "Move 3", text: "Build construction cost and approval timelines, where delay is the most common source of loss." },
      { label: "Move 4", text: "Model the funding. Pre-sales fund construction in India, so a slow launch creates a financing problem quickly." },
      { label: "Close", text: "Give a view with the pre-sales velocity assumption named, since that is what the whole project depends on." },
    ],
    pitfalls: [
      "Using aspirational pricing rather than comparable transactions.",
      "Ignoring approval delay risk, which is substantial in India.",
      "Missing that construction funding depends on pre-sales pace.",
    ],
  },
  {
    slug: "cost-of-capital-for-a-conglomerate",
    shape: "case",
    title: "How should a conglomerate set the hurdle rate for each business?",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 30,
    answer: "Divisional hurdle rates reflecting each business's own risk. A single group rate systematically overfunds risky divisions and starves safe ones.",
    hints: ["A single group cost of capital misallocates capital in a predictable direction. Explain that direction."],
    moves: [
      { label: "Move 1", text: "Explain the error. A uniform rate makes risky projects look good and safe ones look bad." },
      { label: "Move 2", text: "Derive divisional rates using comparable pure-play companies in each business." },
      { label: "Move 3", text: "Adjust for capital structure, since different businesses support different levels of debt." },
      { label: "Move 4", text: "Address the political problem, since divisions will argue for lower hurdle rates to get funded." },
      { label: "Close", text: "Recommend divisional rates with an independent review process, since the governance matters as much as the arithmetic." },
    ],
    pitfalls: [
      "Applying one group rate for administrative simplicity.",
      "Deriving divisional rates from divisional preferences rather than market comparables.",
      "Ignoring that hurdle rates become political the moment they affect budgets.",
    ],
  },
  {
    slug: "receivables-are-ballooning",
    shape: "case",
    title: "Receivables have grown faster than revenue. Investigate.",
    type: "Operations",
    difficulty: 2,
    minutes: 25,
    answer: "Either credit terms were loosened to hit sales targets, or some customers have stopped paying. Both look identical in the aggregate number.",
    hints: ["Age the receivables. The distribution tells you which problem you have."],
    moves: [
      { label: "Move 1", text: "Age the book. Recent receivables growing is a terms problem, old receivables growing is a collection problem." },
      { label: "Move 2", text: "Check by customer. Concentration in a few accounts suggests specific distress rather than a policy change." },
      { label: "Move 3", text: "Check sales incentives, since revenue-based targets reliably encourage generous credit terms." },
      { label: "Move 4", text: "Test for channel stuffing, where inventory was pushed to distributors who cannot sell it." },
      { label: "Close", text: "Recommend against the cause found, and note the provisioning implication if collection is genuinely impaired." },
    ],
    pitfalls: [
      "Looking at total receivables without ageing them.",
      "Missing sales incentives as the underlying cause.",
      "Not considering channel stuffing, which shows up exactly this way.",
    ],
  },
  {
    slug: "should-we-list-or-stay-private",
    shape: "case",
    title: "Should a profitable family business list publicly?",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 30,
    answer: "Only if capital is genuinely needed or shareholders want liquidity. Listing for prestige buys scrutiny, cost and quarterly pressure with no benefit.",
    hints: ["List for a reason. Ask what the money is for before anything else."],
    moves: [
      { label: "Move 1", text: "Establish the purpose: growth capital, promoter liquidity, acquisition currency, or employee incentives." },
      { label: "Move 2", text: "Cost the listing: compliance, disclosure, investor relations and the permanent management time it consumes." },
      { label: "Move 3", text: "Assess the behaviour change. Quarterly reporting pressure alters decision horizons in ways families often dislike." },
      { label: "Move 4", text: "Consider alternatives: private equity, structured debt, or a partial stake sale that achieves the same goal." },
      { label: "Close", text: "Recommend on the stated purpose, and reject listing where the purpose is prestige." },
    ],
    pitfalls: [
      "Listing without a defined use of proceeds.",
      "Underestimating the ongoing compliance and disclosure burden.",
      "Ignoring private alternatives that achieve the same objective.",
    ],
  },
  {
    slug: "impairment-test-on-an-acquisition",
    shape: "case",
    title: "An acquisition made three years ago is underperforming. Impair it?",
    type: "Valuation",
    difficulty: 3,
    minutes: 30,
    answer: "If the recoverable amount is genuinely below carrying value, yes. Delaying impairment protects nothing and damages credibility when it eventually happens.",
    hints: ["Impairment is an accounting recognition of a decision that has already been made by reality."],
    moves: [
      { label: "Move 1", text: "Compute recoverable amount as the higher of value in use and fair value less costs to sell." },
      { label: "Move 2", text: "Rebuild the value in use projections honestly, rather than reusing the optimistic deal model." },
      { label: "Move 3", text: "Compare against carrying value including allocated goodwill." },
      { label: "Move 4", text: "Consider the incentive problem, since the people testing for impairment often approved the acquisition." },
      { label: "Close", text: "Recommend recognition with the operational plan alongside it, since impairment without a plan reads as surrender." },
    ],
    pitfalls: [
      "Reusing the original deal projections in the impairment test.",
      "Delaying recognition and taking a larger hit later.",
      "Treating impairment as purely an accounting exercise rather than a signal about the business.",
    ],
  },
  {
    slug: "pricing-a-corporate-loan",
    shape: "case",
    title: "How would you price a corporate term loan?",
    type: "Credit",
    difficulty: 2,
    minutes: 25,
    answer: "Cost of funds plus expected credit loss plus capital charge plus a margin, adjusted for the total relationship value.",
    hints: ["Build the price from components rather than quoting a spread over a benchmark."],
    moves: [
      { label: "Move 1", text: "Start with the cost of funds for matching tenure, which is the floor." },
      { label: "Move 2", text: "Add expected credit loss, derived from probability of default and loss given default." },
      { label: "Move 3", text: "Add the capital charge, since regulatory capital held against the exposure has a required return." },
      { label: "Move 4", text: "Adjust for the relationship: cash management, trade finance and treasury business may justify a thinner spread." },
      { label: "Close", text: "State the floor price below which the loan destroys value even with relationship revenue counted." },
    ],
    pitfalls: [
      "Pricing off competitor quotes without building the cost stack.",
      "Ignoring the capital charge, which is a real cost.",
      "Using relationship value to justify a price below the economic floor.",
    ],
  },
  {
    slug: "how-much-cash-should-a-company-hold",
    shape: "case",
    title: "How much cash should a company hold on its balance sheet?",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 25,
    answer: "Enough to cover a realistic stress scenario plus committed spending, with anything above that returned or invested. Idle cash earns below the cost of capital.",
    hints: ["Cash is not free. It earns less than the cost of capital, so excess cash destroys value slowly."],
    moves: [
      { label: "Move 1", text: "Size the operating requirement from the working capital cycle and its volatility." },
      { label: "Move 2", text: "Add a stress buffer sized against a realistic downturn or a supply shock." },
      { label: "Move 3", text: "Add committed capital expenditure and debt maturities in the near term." },
      { label: "Move 4", text: "Consider undrawn credit lines, which substitute for cash more cheaply if reliably available." },
      { label: "Close", text: "State the target range and what should happen to cash above it, since a range with no policy is not a decision." },
    ],
    pitfalls: [
      "Treating cash as costless.",
      "Ignoring committed credit lines as an alternative to holding cash.",
      "Setting a target with no stated action for excess.",
    ],
  },
  {
    slug: "revenue-recognition-question",
    shape: "case",
    title: "A software firm books three-year contracts upfront. Is that right?",
    type: "Profitability",
    difficulty: 3,
    minutes: 25,
    answer: "Almost certainly not. Revenue should follow delivery of the service, and upfront recognition inflates current results while creating an empty future.",
    hints: ["Ask when the customer actually receives the value they paid for."],
    moves: [
      { label: "Move 1", text: "Establish the performance obligation. Revenue is recognised as the service is delivered, not as cash is received." },
      { label: "Move 2", text: "Separate components. Licence, implementation and ongoing support may be recognised on different schedules." },
      { label: "Move 3", text: "Note the consequence. Upfront recognition creates a growth illusion that reverses when new bookings slow." },
      { label: "Move 4", text: "Look at deferred revenue on the balance sheet, which is where the honest picture sits." },
      { label: "Close", text: "Recommend the correct treatment, and note that cash flow was never affected by the accounting choice." },
    ],
    pitfalls: [
      "Confusing cash receipt with revenue recognition.",
      "Treating a bundled contract as a single performance obligation.",
      "Ignoring the deferred revenue balance, which tells the real story.",
    ],
  },
  {
    slug: "should-we-securitise-the-loan-book",
    shape: "case",
    title: "Should a lender securitise part of its loan book?",
    type: "Capital structure",
    difficulty: 3,
    minutes: 30,
    answer: "Yes if capital is the binding constraint on growth and the retained risk is understood. It frees capital but keeps more risk than it appears to.",
    hints: ["Ask what risk actually leaves the balance sheet. Usually less than the headline suggests."],
    moves: [
      { label: "Move 1", text: "Establish the motivation: capital relief, liquidity, or funding cost reduction." },
      { label: "Move 2", text: "Assess what transfers. Credit enhancement and retained tranches mean much of the first-loss risk stays with the originator." },
      { label: "Move 3", text: "Cost the transaction: structuring, rating and servicing fees against the capital freed." },
      { label: "Move 4", text: "Consider the incentive problem, since originating to distribute weakens underwriting discipline over time." },
      { label: "Close", text: "Recommend with the retained risk quantified, since that is what determines whether this is real relief." },
    ],
    pitfalls: [
      "Assuming securitisation removes the credit risk entirely.",
      "Ignoring transaction costs against the capital benefit.",
      "Missing the underwriting incentive problem it creates.",
    ],
  },
  {
    slug: "family-business-succession-valuation",
    shape: "case",
    title: "Two siblings are splitting a family business. How do you value each half?",
    type: "Valuation",
    difficulty: 3,
    minutes: 30,
    answer: "Value the parts separately including what each loses from separation, and price control and liquidity differences explicitly.",
    hints: ["The whole is usually worth more than the parts. That difference has to be allocated somehow."],
    moves: [
      { label: "Move 1", text: "Value the business as a whole using standard methods as the starting reference." },
      { label: "Move 2", text: "Value each division standalone, removing shared functions, brand and purchasing scale." },
      { label: "Move 3", text: "Quantify the separation loss, which is real and must be shared between the parties." },
      { label: "Move 4", text: "Adjust for control and liquidity, since a controlling stake in an operating business differs from a minority holding." },
      { label: "Close", text: "Propose a mechanism rather than a number, since agreed process matters more than a valuation either side can dispute." },
    ],
    pitfalls: [
      "Simply halving the whole-business valuation.",
      "Ignoring the value destroyed by separating shared functions.",
      "Producing a number without a process both parties accept.",
    ],
  },
  {
    slug: "assessing-a-turnaround-investment",
    shape: "case",
    title: "Would you invest in a distressed manufacturer?",
    type: "Investment call",
    difficulty: 3,
    minutes: 35,
    answer: "Only if the distress is financial rather than operational. A good business with a bad balance sheet is fixable, the reverse usually is not.",
    hints: ["Separate the balance sheet problem from the business problem. They have completely different odds."],
    moves: [
      { label: "Move 1", text: "Diagnose the distress. Over-leverage from an aborted expansion differs entirely from structural loss of competitiveness." },
      { label: "Move 2", text: "Test the underlying operations. Is the plant efficient and are the products still wanted at current prices?" },
      { label: "Move 3", text: "Model the restructuring: debt haircut, fresh capital, and the timeline to stabilise operations." },
      { label: "Move 4", text: "Assess the process risk, since insolvency proceedings in India take time and outcomes are uncertain." },
      { label: "Close", text: "Give a decision with the entry price and the operational condition you would require." },
    ],
    pitfalls: [
      "Treating cheap as the same as good value.",
      "Underestimating restructuring timelines.",
      "Assuming operational problems are as fixable as financial ones.",
    ],
  },
  {
    slug: "transfer-pricing-between-divisions",
    shape: "case",
    title: "Two divisions disagree on internal transfer pricing. Resolve it.",
    type: "Operations",
    difficulty: 2,
    minutes: 25,
    answer: "Market price where an external market exists, marginal cost plus a share of contribution where it does not, and never let the dispute distort group decisions.",
    hints: ["Transfer pricing should not change what is optimal for the group. Test any proposal against that."],
    moves: [
      { label: "Move 1", text: "State the principle. Internal prices must not cause a division to make a decision that harms the group." },
      { label: "Move 2", text: "Where an external market exists, use market price, which gives both divisions a fair reference." },
      { label: "Move 3", text: "Where no market exists, use marginal cost plus an agreed contribution share." },
      { label: "Move 4", text: "Address measurement. If divisional profit drives bonuses, the dispute is really about incentives." },
      { label: "Close", text: "Recommend the method plus an arbitration mechanism, since disputes will recur regardless of the rule." },
    ],
    pitfalls: [
      "Choosing full cost plus, which encourages the selling division to be inefficient.",
      "Ignoring that the real dispute is usually about bonuses.",
      "Setting a rule with no escalation path for disagreements.",
    ],
  },
  {
    slug: "hedge-or-pass-through-commodity-cost",
    shape: "case",
    title: "Should a food company hedge wheat or pass the cost through?",
    type: "Risk",
    difficulty: 2,
    minutes: 25,
    answer: "Hedge the near term to buy time, and build contractual pass-through for the longer term. Hedging is not a substitute for pricing power.",
    hints: ["Hedging delays the problem. It does not solve a structural inability to raise prices."],
    moves: [
      { label: "Move 1", text: "Assess pricing power. Branded products can pass through, private label and commodity products often cannot." },
      { label: "Move 2", text: "Check competitor exposure. If everyone faces the same input rise, industry pricing usually adjusts." },
      { label: "Move 3", text: "Use hedging for the transition window, giving time to reprice without a margin shock." },
      { label: "Move 4", text: "Consider recipe and pack changes, which in Indian food markets are a common alternative to visible price rises." },
      { label: "Close", text: "Recommend a hedging horizon plus a repricing plan, and be clear that hedging alone only postpones the decision." },
    ],
    pitfalls: [
      "Treating hedging as a permanent solution to structural cost inflation.",
      "Ignoring that competitors face the same input cost.",
      "Missing pack size reduction as a pricing lever.",
    ],
  },
  {
    slug: "evaluating-a-joint-venture-split",
    shape: "case",
    title: "Two partners are forming a joint venture. How should ownership split?",
    type: "M&A",
    difficulty: 3,
    minutes: 30,
    answer: "In proportion to the value of what each contributes, including non-cash contributions like distribution and regulatory access, which are usually undervalued.",
    hints: ["Cash is easy to value. The contributed capabilities are where the argument is."],
    moves: [
      { label: "Move 1", text: "Inventory the contributions: capital, technology, brand, distribution, regulatory access and management." },
      { label: "Move 2", text: "Value the non-cash items by asking what each would cost to build or buy independently." },
      { label: "Move 3", text: "Consider the time dimension. Technology may matter most at the start, distribution most later." },
      { label: "Move 4", text: "Design governance, since a 50-50 split with no tie-breaker is the classic joint venture failure mode." },
      { label: "Close", text: "Recommend the split plus the exit mechanism, since most joint ventures end and the terms should be set while relations are good." },
    ],
    pitfalls: [
      "Splitting on capital contributed alone.",
      "Agreeing 50-50 with no deadlock resolution.",
      "Not agreeing exit terms at the outset.",
    ],
  },
  {
    slug: "assess-a-subscription-business-quality",
    shape: "case",
    title: "How would you assess the quality of a subscription business?",
    type: "Investment call",
    difficulty: 2,
    minutes: 25,
    answer: "Net revenue retention above 100% with a short payback period. Growth funded by acquisition spend against poor retention is not a subscription business, it is a treadmill.",
    hints: ["Retention is the whole question. Growth can always be bought."],
    moves: [
      { label: "Move 1", text: "Start with net revenue retention, which captures churn, downgrades and expansion in a single number." },
      { label: "Move 2", text: "Check the payback period on customer acquisition cost, ideally under twelve months." },
      { label: "Move 3", text: "Examine cohort curves rather than aggregate churn, since averages hide a deteriorating recent cohort." },
      { label: "Move 4", text: "Check revenue concentration, since a few large customers can make retention look better than it is." },
      { label: "Close", text: "Give a quality verdict with the retention threshold you consider investable." },
    ],
    pitfalls: [
      "Using gross churn without expansion revenue, or the reverse, without saying which.",
      "Reading aggregate churn instead of cohort curves.",
      "Ignoring concentration risk in the retention figure.",
    ],
  },
  {
    slug: "capital-expenditure-approval-decision",
    shape: "case",
    title: "A plant manager wants 200 crore rupees for automation. Approve?",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 25,
    answer: "Only if the savings are real and the volumes that justify them are contracted. Automation payback models routinely assume volumes that never arrive.",
    hints: ["Test the volume assumption underneath the savings. That is where these proposals fail."],
    moves: [
      { label: "Move 1", text: "Break down the claimed savings: labour, yield, quality, throughput. Some are far more certain than others." },
      { label: "Move 2", text: "Test the volume assumption. Fixed automation cost against uncertain volume is the standard failure." },
      { label: "Move 3", text: "Consider flexibility loss, since automated lines are harder to repurpose than manual ones." },
      { label: "Move 4", text: "Compare against alternatives: partial automation, or outsourcing the step entirely." },
      { label: "Close", text: "Recommend conditional approval with the volume threshold and a staged rollout." },
    ],
    pitfalls: [
      "Accepting labour savings without checking whether headcount actually reduces.",
      "Ignoring the volume risk that the payback depends on.",
      "Missing the flexibility cost of dedicated automation.",
    ],
  },
  {
    slug: "why-is-cash-flow-below-profit",
    shape: "case",
    title: "A company reports strong profit but weak cash flow. Investigate.",
    type: "Profitability",
    difficulty: 2,
    minutes: 25,
    answer: "Working capital is absorbing the profit, or revenue is being recognised faster than it is being collected. Both are warning signs.",
    hints: ["Profit is an opinion, cash is a fact. Find where the gap sits."],
    moves: [
      { label: "Move 1", text: "Reconcile profit to operating cash flow line by line, starting with working capital movements." },
      { label: "Move 2", text: "Check receivables and inventory, which are the usual absorbers of reported profit." },
      { label: "Move 3", text: "Check revenue recognition policy, since aggressive recognition creates profit without cash." },
      { label: "Move 4", text: "Check capitalisation, since costs capitalised rather than expensed flatter profit and hit investing cash flow." },
      { label: "Close", text: "Name the driver and say whether it is growth-related and temporary or a quality-of-earnings problem." },
    ],
    pitfalls: [
      "Assuming the gap is always a red flag when fast growth naturally absorbs working capital.",
      "Not checking capitalisation policy.",
      "Reviewing the income statement without the cash flow statement beside it.",
    ],
  },
  {
    slug: "should-we-offer-customer-financing",
    shape: "case",
    title: "Should a consumer durables retailer offer its own financing?",
    type: "Business model",
    difficulty: 3,
    minutes: 30,
    answer: "Partner first, own later. Financing is a genuinely different business with capital requirements and credit risk the retailer is not built for.",
    hints: ["Ask whether the retailer wants the sales lift or the lending profit. They are different businesses."],
    moves: [
      { label: "Move 1", text: "Establish the objective. Financing typically lifts conversion and average ticket size substantially." },
      { label: "Move 2", text: "Compare the partner model, where a lender takes the credit risk and the retailer takes the sales benefit." },
      { label: "Move 3", text: "Cost the owned model: capital, licensing, collections infrastructure and credit losses." },
      { label: "Move 4", text: "Note the risk correlation, since a downturn hits both retail sales and loan repayment at once." },
      { label: "Close", text: "Recommend partnering with an option to build later once volume and data justify it." },
    ],
    pitfalls: [
      "Treating financing as a feature rather than a separate business.",
      "Underestimating collection infrastructure requirements.",
      "Ignoring that retail and credit risk are correlated.",
    ],
  },
  {
    slug: "assessing-a-franchise-investment",
    shape: "case",
    title: "Someone wants to invest their savings in a food franchise. Advise.",
    type: "Investment call",
    difficulty: 2,
    minutes: 25,
    answer: "Model it honestly including their own labour, and compare against the alternative of investing the money and keeping their job. Most single-unit franchises pay a wage, not a return.",
    hints: ["Charge for the owner's own time. Most franchise proposals quietly assume it is free."],
    moves: [
      { label: "Move 1", text: "Build the unit economics: revenue, food cost, rent, staff, royalty and marketing contribution." },
      { label: "Move 2", text: "Charge the owner's labour at market rate, since they could earn that elsewhere." },
      { label: "Move 3", text: "Compute the return on capital invested after that charge, which is usually far lower than the brochure suggests." },
      { label: "Move 4", text: "Assess the risk: location dependence, franchise term, and what happens if the brand declines." },
      { label: "Close", text: "Give a clear recommendation and name the return threshold that would justify the risk." },
    ],
    pitfalls: [
      "Ignoring the owner's opportunity cost of time.",
      "Using franchisor-supplied revenue projections uncritically.",
      "Comparing against a bank deposit rather than against realistic alternative uses of capital and time.",
    ],
  },
  {
    slug: "goodwill-on-a-large-acquisition",
    shape: "case",
    title: "A deal creates goodwill equal to 60% of the purchase price. Comfortable?",
    type: "M&A",
    difficulty: 3,
    minutes: 25,
    answer: "Not without knowing what the goodwill represents. High goodwill is normal for people and brand businesses and alarming for asset-heavy ones.",
    hints: ["Goodwill is what you paid above identifiable assets. Ask what you actually bought."],
    moves: [
      { label: "Move 1", text: "Understand the composition. Goodwill is the residual after allocating value to identifiable assets." },
      { label: "Move 2", text: "Test whether intangibles were properly identified, since brands and customer relationships should be separated out." },
      { label: "Move 3", text: "Assess by business type. A services firm has few tangible assets, so high goodwill is expected." },
      { label: "Move 4", text: "Consider impairment risk, since goodwill sits on the balance sheet until performance forces a write-down." },
      { label: "Close", text: "Give a view tied to the business model and the synergy case rather than to the percentage itself." },
    ],
    pitfalls: [
      "Judging goodwill as a percentage with no reference to business type.",
      "Not checking whether identifiable intangibles were separated.",
      "Ignoring the future impairment risk it creates.",
    ],
  },
  {
    slug: "evaluate-a-power-purchase-agreement",
    shape: "case",
    title: "Evaluate a 25-year solar power purchase agreement.",
    type: "Investment call",
    difficulty: 3,
    minutes: 30,
    answer: "The counterparty's ability to pay for 25 years matters more than the tariff. Several Indian state utilities have renegotiated signed contracts.",
    hints: ["A long contract is only as good as the counterparty behind it."],
    moves: [
      { label: "Move 1", text: "Assess the counterparty. State distribution utilities have a history of payment delays and renegotiation attempts." },
      { label: "Move 2", text: "Model generation realistically, including degradation of roughly half a percent a year." },
      { label: "Move 3", text: "Check the tariff structure: fixed, escalating, or exposed to merchant pricing after a period." },
      { label: "Move 4", text: "Test the financing. Long-tenure debt against a weak counterparty is expensive or unavailable." },
      { label: "Close", text: "Give a view with the payment security mechanism as the condition, since that is what makes the deal financeable." },
    ],
    pitfalls: [
      "Focusing on the tariff and ignoring counterparty credit.",
      "Modelling generation without panel degradation.",
      "Assuming a signed contract is enforceable in practice.",
    ],
  },
  {
    slug: "cost-reduction-in-a-services-firm",
    shape: "case",
    title: "A services firm must cut costs 15%. Where do you look?",
    type: "Cost reduction",
    difficulty: 2,
    minutes: 30,
    answer: "Utilisation and pyramid structure, not headcount reduction. In a people business, how people are deployed matters more than how many there are.",
    hints: ["In a services firm nearly all cost is people. The lever is how they are deployed."],
    moves: [
      { label: "Move 1", text: "Build the cost stack, which for services is overwhelmingly salaries and facilities." },
      { label: "Move 2", text: "Attack utilisation. Bench time and unbilled work is pure cost with no revenue against it." },
      { label: "Move 3", text: "Fix the pyramid. Too many senior people on delivery work is the most common structural cost problem." },
      { label: "Move 4", text: "Review location mix and real estate, where post-hybrid footprint often exceeds actual need." },
      { label: "Close", text: "Recommend the utilisation and pyramid actions first, since layoffs damage delivery capability and reputation." },
    ],
    pitfalls: [
      "Reaching for headcount reduction as the first lever.",
      "Ignoring the pyramid, which is where margin is quietly lost.",
      "Cutting training and travel, which is visible, small and damaging.",
    ],
  },
  {
    slug: "is-the-guidance-credible",
    shape: "case",
    title: "A company guides to 30% growth for three years. Believe it?",
    type: "Investment call",
    difficulty: 2,
    minutes: 25,
    answer: "Test it against market size and capacity. If the implied market share or the required capacity is implausible, the guidance is not.",
    hints: ["Compound the growth out and see what it implies. That usually settles it."],
    moves: [
      { label: "Move 1", text: "Compound the guidance. Three years at 30% roughly doubles revenue, which is a large claim." },
      { label: "Move 2", text: "Test against market growth. Growing far faster than the market means taking share from named competitors." },
      { label: "Move 3", text: "Test capacity. Doubling revenue usually requires people, plant or distribution that must be visible now." },
      { label: "Move 4", text: "Check the track record against previous guidance, which is the strongest single predictor." },
      { label: "Close", text: "Give a view with the specific implausibility named, rather than general scepticism." },
    ],
    pitfalls: [
      "Assessing the annual rate without compounding it out.",
      "Not checking whether required capacity exists or is being built.",
      "Ignoring past guidance accuracy.",
    ],
  },
  {
    slug: "structuring-an-esop-pool",
    shape: "case",
    title: "How large should a startup's employee stock option pool be?",
    type: "Capital structure",
    difficulty: 2,
    minutes: 25,
    answer: "Sized to the hiring plan through the next funding round, typically 10 to 15%, and topped up at each round rather than over-provisioned early.",
    hints: ["Size it against the hiring plan, not against a benchmark percentage."],
    moves: [
      { label: "Move 1", text: "Build the hiring plan to the next round and the equity each role would require." },
      { label: "Move 2", text: "Note the dilution mechanics, since investors typically require the pool to be created before their investment." },
      { label: "Move 3", text: "Avoid over-provisioning early, since unallocated options dilute founders without motivating anyone." },
      { label: "Move 4", text: "Consider the Indian specifics, where option taxation on exercise has historically limited their perceived value." },
      { label: "Close", text: "Recommend a size tied to the plan, with a top-up expected at the next round." },
    ],
    pitfalls: [
      "Copying a benchmark percentage with no hiring plan behind it.",
      "Ignoring that pre-money pool creation dilutes founders alone.",
      "Overlooking exercise taxation, which affects how employees value the grant.",
    ],
  },
  {
    slug: "should-we-take-venture-debt",
    shape: "case",
    title: "Should a growth-stage startup take venture debt?",
    type: "Capital structure",
    difficulty: 2,
    minutes: 25,
    answer: "Yes as a bridge between equity rounds when the path to the next round is clear. No as a substitute for equity when it is not.",
    hints: ["Venture debt has to be repaid on schedule regardless of how the business performs."],
    moves: [
      { label: "Move 1", text: "Establish the purpose: extending runway to a milestone, funding equipment, or avoiding a down round." },
      { label: "Move 2", text: "Compare cost. Venture debt is cheaper than equity in dilution terms but carries covenants and warrants." },
      { label: "Move 3", text: "Model repayment. Debt service starts before the business may be ready, which consumes the very runway it bought." },
      { label: "Move 4", text: "Test the downside. If the next round does not happen, the debt accelerates the failure." },
      { label: "Close", text: "Recommend with a runway condition, since venture debt taken from weakness usually makes things worse." },
    ],
    pitfalls: [
      "Comparing only the interest rate against equity dilution.",
      "Ignoring that repayment begins immediately and reduces effective runway.",
      "Taking debt to avoid a down round that is coming anyway.",
    ],
  },
  {
    slug: "assess-a-hospital-chain-expansion",
    shape: "case",
    title: "A hospital chain wants to add five hospitals in three years. Fund it?",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 30,
    answer: "Only at a pace clinician recruitment can support. Healthcare expansion fails on doctors, not on buildings, and a new hospital takes years to break even.",
    hints: ["Model the ramp honestly. A new hospital loses money for a long time before it does not."],
    moves: [
      { label: "Move 1", text: "Model the ramp. Occupancy builds slowly, so each hospital loses money for two to four years." },
      { label: "Move 2", text: "Aggregate the cash drain. Five hospitals ramping simultaneously creates a large combined loss period." },
      { label: "Move 3", text: "Test the clinician constraint, since senior doctors drive referrals and are genuinely scarce." },
      { label: "Move 4", text: "Compare against acquiring existing hospitals, which buys occupancy and clinicians together." },
      { label: "Close", text: "Recommend a slower pace or acquisition, with the funding requirement through the ramp stated explicitly." },
    ],
    pitfalls: [
      "Modelling new hospitals at mature occupancy.",
      "Ignoring the simultaneous cash drain of multiple ramps.",
      "Treating clinician recruitment as a hiring exercise rather than a constraint.",
    ],
  },
  {
    slug: "pricing-a-distressed-asset-sale",
    shape: "case",
    title: "You must sell an asset quickly. How do you price it?",
    type: "Valuation",
    difficulty: 2,
    minutes: 25,
    answer: "Accept the liquidity discount and run a fast competitive process. A wide auction recovers more than a slow negotiation with one buyer.",
    hints: ["Speed costs money. The question is how to lose the least, not how to avoid the discount."],
    moves: [
      { label: "Move 1", text: "Establish the intrinsic value as a reference, knowing you will not achieve it." },
      { label: "Move 2", text: "Size the liquidity discount, which depends on how many credible buyers can move quickly." },
      { label: "Move 3", text: "Design the process. Competitive tension recovers more value than time does in most distressed sales." },
      { label: "Move 4", text: "Prepare information in advance, since buyer diligence time is the real constraint on speed." },
      { label: "Close", text: "Recommend the process and the reserve price below which you would not sell at all." },
    ],
    pitfalls: [
      "Negotiating with a single buyer who knows you must sell.",
      "Refusing to accept any discount and missing the window entirely.",
      "Starting the process before diligence materials are ready.",
    ],
  },
  {
    slug: "evaluate-a-royalty-agreement",
    shape: "case",
    title: "A parent charges its Indian subsidiary a 4% brand royalty. Fair?",
    type: "Valuation",
    difficulty: 3,
    minutes: 25,
    answer: "Test against what an independent party would pay for the same brand. Four percent of revenue is high if the local business built its own market position.",
    hints: ["Ask what the brand actually contributes to the Indian business, not what the parent would like to charge."],
    moves: [
      { label: "Move 1", text: "Apply the arm's length principle. The test is what an unrelated licensee would pay." },
      { label: "Move 2", text: "Assess brand contribution. If local marketing built the position, the parent brand may add little." },
      { label: "Move 3", text: "Benchmark against comparable licensing arrangements in the same sector." },
      { label: "Move 4", text: "Note the minority shareholder concern, since royalties transfer value out ahead of dividends." },
      { label: "Close", text: "Give a view with the benchmark rate and the governance concern stated plainly." },
    ],
    pitfalls: [
      "Accepting the rate because a parent set it.",
      "Ignoring that local investment may have built the brand position.",
      "Missing the minority shareholder dimension entirely.",
    ],
  },
  {
    slug: "invest-in-a-declining-cash-cow",
    shape: "case",
    title: "Would you buy a profitable business in a declining industry?",
    type: "Investment call",
    difficulty: 3,
    minutes: 30,
    answer: "Yes at the right price. A declining business with strong cash generation and no reinvestment need can be an excellent investment if bought cheaply enough.",
    hints: ["Decline is a valuation question, not a disqualification. The rate of decline is what matters."],
    moves: [
      { label: "Move 1", text: "Quantify the decline rate, since 3% a year and 15% a year are entirely different propositions." },
      { label: "Move 2", text: "Test cash generation. Declining businesses often need little reinvestment, so free cash flow can be strong." },
      { label: "Move 3", text: "Check for a terminal cliff, where a technology or regulatory shift ends the business abruptly rather than gradually." },
      { label: "Move 4", text: "Model the payback purely from cash flows, assuming no terminal value at all." },
      { label: "Close", text: "Give a price at which you would buy, since the answer here is entirely about price." },
    ],
    pitfalls: [
      "Rejecting the investment on the word decline alone.",
      "Assuming a smooth decline where a cliff is possible.",
      "Attributing meaningful terminal value to a shrinking business.",
    ],
  },
  {
    slug: "assess-a-cross-border-acquisition",
    shape: "case",
    title: "An Indian firm wants to buy a European competitor. Assess it.",
    type: "M&A",
    difficulty: 3,
    minutes: 35,
    answer: "The financial case may work while the integration case does not. Cross-border acquisitions fail on labour law, culture and management bandwidth more than on price.",
    hints: ["Ask who will actually run it. Management bandwidth is the constraint nobody models."],
    moves: [
      { label: "Move 1", text: "Establish the rationale: market access, technology, or scale. Each implies a different integration depth." },
      { label: "Move 2", text: "Assess the labour and regulatory environment, since European restructuring is slow and expensive." },
      { label: "Move 3", text: "Test management bandwidth honestly, since running a distant business consumes far more attention than expected." },
      { label: "Move 4", text: "Model currency and funding, since debt raised in one currency against earnings in another creates exposure." },
      { label: "Close", text: "Recommend with the integration plan and the named executive who will run it, or advise against." },
    ],
    pitfalls: [
      "Building the case on financial synergies alone.",
      "Underestimating European labour law constraints on restructuring.",
      "Not naming who will actually manage the acquired business.",
    ],
  },
  {
    slug: "reading-a-suspicious-balance-sheet",
    shape: "case",
    title: "What would make you suspicious reading a set of accounts?",
    type: "Due diligence",
    difficulty: 3,
    minutes: 30,
    answer: "Persistent divergence between profit and cash, related party transactions, and margins well above peers with no explanation.",
    hints: ["Look for the things that are hard to fake: cash, and comparisons to peers."],
    moves: [
      { label: "Move 1", text: "Compare profit to operating cash flow over several years. Persistent divergence is the strongest single signal." },
      { label: "Move 2", text: "Examine related party transactions, which are the most common route for value to leave a company." },
      { label: "Move 3", text: "Benchmark margins against peers. Substantially better economics require a specific, verifiable explanation." },
      { label: "Move 4", text: "Check receivable and inventory days against the industry and against the company's own history." },
      { label: "Close", text: "Name the specific tests you would run rather than expressing general suspicion." },
    ],
    pitfalls: [
      "Relying on ratio analysis without comparing to peers.",
      "Ignoring related party disclosures.",
      "Treating an auditor's clean opinion as sufficient assurance.",
    ],
  },
  {
    slug: "allocate-capital-across-three-projects",
    shape: "case",
    title: "You have 500 crore rupees and three projects. Allocate it.",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 30,
    answer: "Rank by risk-adjusted return per rupee, not by total return, and check whether the projects are genuinely independent before allocating.",
    hints: ["Return per rupee, not total return, is what ranks projects under a capital constraint."],
    moves: [
      { label: "Move 1", text: "Compute return per rupee invested for each, since the constraint is capital rather than opportunity." },
      { label: "Move 2", text: "Risk-adjust, since a higher return with much greater uncertainty may rank lower." },
      { label: "Move 3", text: "Check independence. Projects that share a market or a supply chain are correlated, not diversified." },
      { label: "Move 4", text: "Consider strategic value and option value, where a small investment preserves a future choice." },
      { label: "Close", text: "Give the allocation with the reasoning per project, and say what you would fund with additional capital." },
    ],
    pitfalls: [
      "Ranking on total net present value under a capital constraint.",
      "Ignoring correlation between projects.",
      "Allocating everything with no reserve for opportunities that arise later.",
    ],
  },
  {
    slug: "should-we-factor-our-receivables",
    shape: "case",
    title: "Should a manufacturer factor its receivables?",
    type: "Capital structure",
    difficulty: 2,
    minutes: 25,
    answer: "Compare the discount cost against your own cost of borrowing. Factoring is expensive money, worth it only when cheaper credit is unavailable.",
    hints: ["Convert the factoring discount into an annualised rate. It is usually higher than it looks."],
    moves: [
      { label: "Move 1", text: "Annualise the cost. A 2% discount for 60 days is roughly 12% a year, not 2%." },
      { label: "Move 2", text: "Compare against bank working capital lines, which are usually cheaper if available." },
      { label: "Move 3", text: "Establish whether it is with or without recourse, since transferring credit risk has real value." },
      { label: "Move 4", text: "Consider the customer relationship, since a factor chasing payment can damage it." },
      { label: "Close", text: "Recommend based on availability of cheaper credit, and note that reverse factoring through a large buyer is usually cheapest." },
    ],
    pitfalls: [
      "Comparing a headline discount against an annual interest rate.",
      "Ignoring whether credit risk actually transfers.",
      "Missing reverse factoring, which uses the buyer credit rating instead.",
    ],
  },
  {
    slug: "insurance-distribution-partnership",
    shape: "case",
    title: "A bank is offered an insurance distribution partnership. Assess it.",
    type: "Investment call",
    difficulty: 2,
    minutes: 25,
    answer: "Attractive fee income with no capital required, but the risk is mis-selling damaging the primary banking relationship.",
    hints: ["The revenue is easy. The risk sits with the customer relationship you already have."],
    moves: [
      { label: "Move 1", text: "Size the fee income from commission rates applied to expected sales through the branch network." },
      { label: "Move 2", text: "Note the capital efficiency, since distribution earns fees without underwriting risk." },
      { label: "Move 3", text: "Assess mis-selling risk, which in Indian bancassurance has repeatedly caused regulatory action." },
      { label: "Move 4", text: "Consider exclusivity terms, which raise commissions but limit customer choice." },
      { label: "Close", text: "Recommend with a governance framework, since the relationship value at risk exceeds the fee income." },
    ],
    pitfalls: [
      "Valuing the commission without weighing relationship risk.",
      "Accepting exclusivity without considering customer outcomes.",
      "Ignoring the regulatory history of bancassurance mis-selling.",
    ],
  },
  {
    slug: "evaluating-a-sale-and-leaseback",
    shape: "case",
    title: "Should a retailer sell and lease back its store properties?",
    type: "Capital structure",
    difficulty: 3,
    minutes: 30,
    answer: "Yes if retail returns exceed property returns and lease terms preserve flexibility. It converts an owned asset into a fixed obligation.",
    hints: ["Ask whether the company is better at retailing or at owning property."],
    moves: [
      { label: "Move 1", text: "Compare returns. If retail capital earns more than property appreciation, releasing the capital makes sense." },
      { label: "Move 2", text: "Note what changes. Rent becomes a fixed cost payable in a downturn, unlike owned property." },
      { label: "Move 3", text: "Scrutinise lease length and escalation, since long inflexible leases have bankrupted retailers before." },
      { label: "Move 4", text: "Check tax and accounting effects, since leases now sit on the balance sheet anyway." },
      { label: "Close", text: "Recommend with the maximum lease term and escalation you would accept, since those terms are the whole risk." },
    ],
    pitfalls: [
      "Treating sale proceeds as free money.",
      "Accepting long leases with high escalation for a better headline price.",
      "Ignoring how a fixed rent behaves in a sales downturn.",
    ],
  },
  {
    slug: "deciding-between-two-funding-offers",
    shape: "case",
    title: "A startup has two term sheets at different valuations. Which to take?",
    type: "Capital structure",
    difficulty: 3,
    minutes: 30,
    answer: "Valuation is rarely the deciding factor. Liquidation preference, board composition and investor behaviour in a bad quarter matter more.",
    hints: ["A higher valuation with worse terms is frequently the worse deal. Read past the headline number."],
    moves: [
      { label: "Move 1", text: "Compare economic terms beyond valuation: liquidation preference, participation and anti-dilution." },
      { label: "Move 2", text: "Compare control terms: board seats, veto rights and reserved matters." },
      { label: "Move 3", text: "Reference the investor with founders whose companies struggled, not with the successful ones." },
      { label: "Move 4", text: "Consider signalling, since who sits on the cap table affects the next round." },
      { label: "Close", text: "Recommend on total terms with the specific clause that decided it named explicitly." },
    ],
    pitfalls: [
      "Choosing on headline valuation alone.",
      "Missing participating preferences, which change outcomes substantially at exit.",
      "Referencing an investor only through their successful portfolio.",
    ],
  },
];
