import type { Question } from "./types";

// Finance guesstimates. Sizing pools, books and fee streams with numbers you
// can defend rather than numbers you looked up.
export const FINANCE_GUESSTIMATES: Question[] = [
  {
    slug: "single-screen-cinema-jaipur-revenue",
    shape: "guesstimate",
    title: "Estimate the annual revenue of a single-screen cinema in Jaipur.",
    type: "Revenue estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 3.5 to 4 crore rupees a year including food and beverage, though the cinema keeps far less after the distributor share.",
    hints: ["Seats times shows times occupancy times price, then add food."],
    moves: [
      { label: "Move 1", text: "Fix capacity. A single screen holds around 400 seats and runs 4 shows a day, so about 1,600 seat-slots." },
      { label: "Move 2", text: "Apply realistic occupancy. Weekday afternoons near 15%, weekend evenings near 70%, blending to roughly 30%." },
      { label: "Move 3", text: "Price it. About 480 admissions a day at 150 rupees gives roughly 2.6 crore rupees a year." },
      { label: "Move 4", text: "Add food and beverage at roughly 40% of ticket revenue, plus screen advertising." },
      { label: "Check", text: "The distributor takes a large share of ticket revenue in opening weeks, so revenue and retained revenue differ sharply." },
    ],
    pitfalls: [
      "Using a single occupancy figure across the whole week.",
      "Forgetting food and beverage, which is where a cinema makes money.",
      "Quoting box office as if the cinema keeps it.",
    ],
  },
  {
    slug: "personal-loan-market-under-30",
    shape: "guesstimate",
    title: "Size the personal loan market for salaried Indians under 30.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    askedAt: "Goldman Sachs",
    answer: "An outstanding book near 8 lakh crore rupees, or roughly a third of that as annual disbursement.",
    hints: ["Decide early whether you are sizing annual disbursement or outstanding book. They differ by years."],
    moves: [
      { label: "Move 1", text: "Narrow the population. Roughly 250 million aged 22 to 30, of whom formal salaried employment covers perhaps 40 million." },
      { label: "Move 2", text: "Apply credit eligibility. A credit file and sufficient income cut that to maybe 20 million lendable people." },
      { label: "Move 3", text: "Apply penetration and ticket size. At 20% holding a loan averaging 2 lakh rupees, the book is around 8 lakh crore." },
      { label: "Move 4", text: "Convert to annual disbursement using tenure. At a three year average, origination is roughly a third of the book." },
      { label: "Check", text: "Compare against total Indian retail credit. If the under-30 slice exceeds a plausible share, revise penetration down." },
    ],
    pitfalls: [
      "Confusing outstanding book with annual disbursement.",
      "Skipping the formal employment filter.",
      "Ignoring that much of this group has no credit history at all.",
    ],
  },
  {
    slug: "credit-card-interchange-one-million",
    shape: "guesstimate",
    title: "Estimate interchange revenue on a portfolio of one million credit cards.",
    type: "Fee pool",
    difficulty: 2,
    minutes: 20,
    askedAt: "HSBC",
    answer: "Roughly 200 to 350 crore rupees a year, of which the issuer keeps most but not all.",
    hints: ["Spend per active card is the driver. Dormant cards contribute nothing."],
    moves: [
      { label: "Move 1", text: "Apply activation. Of a million issued cards, perhaps 60 to 70% see regular use." },
      { label: "Move 2", text: "Apply spend, perhaps 15,000 to 25,000 rupees a month on an active card in India." },
      { label: "Move 3", text: "Apply the interchange rate, commonly 1.5 to 2% of transaction value on credit." },
      { label: "Move 4", text: "Split the economics. Interchange is shared between issuer, network and acquirer." },
      { label: "Check", text: "Add interest income on revolved balances, which for many Indian issuers exceeds interchange entirely." },
    ],
    pitfalls: [
      "Applying spend to all issued cards rather than active ones.",
      "Using debit interchange rates, which are far lower and capped.",
      "Missing interest income, which is often the larger revenue line.",
    ],
  },
  {
    slug: "kerala-gold-loan-book",
    shape: "guesstimate",
    title: "How large is the annual gold loan book in Kerala?",
    type: "Book sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 60,000 to 100,000 crore rupees outstanding, unusually high relative to the state's size.",
    hints: ["Work from household gold holdings and the share pledged, not from lender branch counts."],
    moves: [
      { label: "Move 1", text: "Size households at roughly 8 million for a population near 35 million." },
      { label: "Move 2", text: "Estimate gold held per household, which in Kerala is well above the national average." },
      { label: "Move 3", text: "Apply the share pledged at any time, perhaps 10 to 15%, since gold loans are short and rolled." },
      { label: "Move 4", text: "Apply loan-to-value, capped by regulation at 75% of gold value for banks." },
      { label: "Check", text: "Note tenure. Gold loans run months, so annual disbursement is several times the outstanding book." },
    ],
    pitfalls: [
      "Ignoring the loan-to-value cap, which limits the book regardless of gold held.",
      "Confusing disbursement with outstanding balance on a short-tenure product.",
      "Applying national gold holding averages to Kerala.",
    ],
  },
  {
    slug: "mutual-fund-house-fee-income",
    shape: "guesstimate",
    title: "Estimate the fee income of a mid-size Indian mutual fund house.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    askedAt: "Avendus",
    answer: "Roughly 400 to 900 crore rupees a year on assets of 1 to 1.5 lakh crore, depending heavily on equity share.",
    hints: ["Equity and debt funds earn very different fees. The asset mix decides the answer."],
    moves: [
      { label: "Move 1", text: "Size assets under management, perhaps 1 to 1.5 lakh crore rupees for a mid-size house." },
      { label: "Move 2", text: "Split the mix. Equity funds charge well above 1%, debt and liquid funds a fraction of that." },
      { label: "Move 3", text: "Apply blended expense ratio, then subtract distributor commission which comes out of it." },
      { label: "Move 4", text: "Note the regulatory slab structure, which forces expense ratios down as fund size grows." },
      { label: "Check", text: "Compare against costs. Fund management is a high operating leverage business, so margin scales sharply with assets." },
    ],
    pitfalls: [
      "Applying one expense ratio across equity and debt assets.",
      "Treating the expense ratio as net revenue when distributors take a share.",
      "Ignoring the slab structure that reduces fees as funds grow.",
    ],
  },
  {
    slug: "upi-transaction-cost-to-banks",
    shape: "guesstimate",
    title: "Estimate the annual cost of UPI to the Indian banking system.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Several thousand crore rupees a year, borne by banks with essentially no direct revenue against it.",
    hints: ["UPI person-to-person carries no merchant fee. The cost is real and the revenue is not."],
    moves: [
      { label: "Move 1", text: "Size volume at roughly 200 to 250 billion transactions a year and rising." },
      { label: "Move 2", text: "Apply cost per transaction, a small amount covering switching, infrastructure and reconciliation." },
      { label: "Move 3", text: "Add the support cost of failures and disputes, which is disproportionately expensive per incident." },
      { label: "Move 4", text: "Set against revenue, which for person-to-person UPI is zero by regulation." },
      { label: "Check", text: "The offset is deposit float and customer stickiness. Whether that covers the cost is the genuinely contested question." },
    ],
    pitfalls: [
      "Assuming banks earn a fee on UPI transactions.",
      "Ignoring dispute handling, which costs far more per case than the transaction itself.",
      "Missing the indirect benefit of deposits and engagement.",
    ],
  },
  {
    slug: "insurance-premium-pool-motor-india",
    shape: "guesstimate",
    title: "Size the annual motor insurance premium pool in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 90,000 to 110,000 crore rupees, with two-wheelers dominating policy count and cars dominating premium.",
    hints: ["Third-party cover is compulsory, so compliance rate matters as much as vehicle count."],
    moves: [
      { label: "Move 1", text: "Size the vehicle fleet at roughly 300 million, overwhelmingly two-wheelers." },
      { label: "Move 2", text: "Apply compliance. A large share of two-wheelers carry no valid insurance despite the legal requirement." },
      { label: "Move 3", text: "Apply premium by type. Third-party premiums are regulated and small, comprehensive car policies far larger." },
      { label: "Move 4", text: "Weight by mix, since a minority of cars generates the majority of premium." },
      { label: "Check", text: "Note the loss ratio problem. Third-party motor has been persistently unprofitable, which is the interesting observation." },
    ],
    pitfalls: [
      "Assuming full compliance with the insurance mandate.",
      "Applying car premiums to the two-wheeler fleet.",
      "Reporting premium without noting the underwriting losses in the segment.",
    ],
  },
  {
    slug: "annual-remittances-into-india",
    shape: "guesstimate",
    title: "Estimate annual remittances flowing into India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 100 to 125 billion dollars a year, the largest such flow in the world.",
    hints: ["Migrant count times average remittance. Both vary hugely by destination country."],
    moves: [
      { label: "Move 1", text: "Size the diaspora, roughly 18 million Indians living abroad." },
      { label: "Move 2", text: "Split by destination. Gulf workers remit a high share of modest earnings, professionals in the West remit less of a larger income." },
      { label: "Move 3", text: "Apply remittance per migrant per year, weighted by that split." },
      { label: "Move 4", text: "Add informal channels, which have shrunk with digital transfers but have not disappeared." },
      { label: "Check", text: "Compare against India's total foreign exchange earnings. Remittances rivalling major export categories is the correct and striking finding." },
    ],
    pitfalls: [
      "Applying one average remittance across very different migrant populations.",
      "Ignoring that Gulf migrants remit a far higher share of income.",
      "Missing that remittance corridors have very different transfer costs.",
    ],
  },
  {
    slug: "atm-cash-holding-cost",
    shape: "guesstimate",
    title: "Estimate the cost of holding cash in an ATM network of 5,000 machines.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Several hundred crore rupees a year once idle cash, replenishment and insurance are counted.",
    hints: ["The largest cost is the interest forgone on cash sitting idle in machines."],
    moves: [
      { label: "Move 1", text: "Size cash per machine. A machine may hold 10 to 20 lakh rupees to avoid running dry." },
      { label: "Move 2", text: "Multiply across the network to get total idle cash, then apply the cost of funds." },
      { label: "Move 3", text: "Add cash-in-transit costs, since replenishment requires secure logistics several times a week." },
      { label: "Move 4", text: "Add insurance, maintenance and site rental, which are meaningful but smaller." },
      { label: "Check", text: "The trade-off is stockout risk against carrying cost, which is exactly why ATM cash forecasting is a real discipline." },
    ],
    pitfalls: [
      "Ignoring the opportunity cost of idle cash, which is the dominant line.",
      "Assuming uniform cash loading across machines with very different footfall.",
      "Forgetting insurance and transit costs entirely.",
    ],
  },
  {
    slug: "sme-lending-opportunity-india",
    shape: "guesstimate",
    title: "Size the unmet credit demand of Indian small businesses.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 20 to 30 lakh crore rupees of unmet demand, most of it currently served informally at far higher rates.",
    hints: ["Unmet demand is total need minus formal supply. Both halves need estimating."],
    moves: [
      { label: "Move 1", text: "Size the enterprise base, roughly 60 million small and micro enterprises." },
      { label: "Move 2", text: "Estimate working capital need per enterprise, which scales with turnover and is modest for most." },
      { label: "Move 3", text: "Subtract formal credit already extended by banks and non-bank lenders." },
      { label: "Move 4", text: "Note what fills the gap. Informal lending at very high rates, and supplier credit." },
      { label: "Check", text: "The constraint is documentation and collateral, not appetite. That is why the gap persists despite obvious demand." },
    ],
    pitfalls: [
      "Sizing total demand and calling it the opportunity without subtracting existing supply.",
      "Applying a uniform credit need across enterprises of hugely different sizes.",
      "Treating the gap as a demand problem when it is an underwriting problem.",
    ],
  },
  {
    slug: "brokerage-revenue-per-active-client",
    shape: "guesstimate",
    title: "Estimate annual revenue per active client for a discount broker.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 3,000 to 6,000 rupees a year, dominated by a small minority of very high-frequency traders.",
    hints: ["Trading activity is extraordinarily skewed. The average client is not the typical client."],
    moves: [
      { label: "Move 1", text: "Segment clients. A small share trade daily, most trade rarely, and many are dormant." },
      { label: "Move 2", text: "Apply trade frequency per segment and the flat fee per order that discount brokers charge." },
      { label: "Move 3", text: "Add other revenue: margin funding interest, mutual fund distribution and float income." },
      { label: "Move 4", text: "Note the derivatives share, which historically produced most trading volume and most revenue." },
      { label: "Check", text: "Regulatory changes to derivatives can move this number sharply, which is the real risk in the model." },
    ],
    pitfalls: [
      "Applying an average trade frequency across a heavily skewed base.",
      "Missing interest and float income, which are large.",
      "Ignoring regulatory sensitivity of the derivatives segment.",
    ],
  },
  {
    slug: "npa-provisioning-retail-book",
    shape: "guesstimate",
    title: "Estimate the annual provisioning cost on a 50,000 crore retail loan book.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 500 to 1,500 crore rupees a year, entirely dependent on the product mix within the book.",
    hints: ["Secured and unsecured lending have completely different loss rates. Split the book first."],
    moves: [
      { label: "Move 1", text: "Split by product. Home loans lose very little, personal loans and credit cards lose far more." },
      { label: "Move 2", text: "Apply credit cost by product, ranging from a fraction of a percent to several percent annually." },
      { label: "Move 3", text: "Weight by book composition, since one unsecured segment can dominate total provisioning." },
      { label: "Move 4", text: "Add the recovery assumption, since secured lending recovers much of the exposure after default." },
      { label: "Check", text: "Note the cycle. Credit costs are lowest right before they rise, which is the classic trap in lending." },
    ],
    pitfalls: [
      "Applying one credit cost across secured and unsecured lending.",
      "Ignoring recovery rates on secured exposures.",
      "Using benign-cycle loss rates as if they were permanent.",
    ],
  },
  {
    slug: "listed-company-free-float-turnover",
    shape: "guesstimate",
    title: "Estimate the annual traded value of a mid-cap Indian listed company.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly one to three times the free float value in a year, far higher during events.",
    hints: ["Turnover is measured against free float, not against total market capitalisation."],
    moves: [
      { label: "Move 1", text: "Establish market capitalisation, perhaps 10,000 to 30,000 crore rupees for a mid-cap." },
      { label: "Move 2", text: "Apply free float. Promoter holdings in India are often high, so tradable stock is a fraction of the total." },
      { label: "Move 3", text: "Apply turnover velocity, the ratio of annual traded value to free float." },
      { label: "Move 4", text: "Add event spikes. Results, index inclusion and block deals concentrate volume into a few days." },
      { label: "Check", text: "Low free float means thin liquidity, which is exactly why some mid-caps move violently on modest flows." },
    ],
    pitfalls: [
      "Computing velocity against full market capitalisation.",
      "Assuming even trading across the year.",
      "Ignoring that index inclusion can transform liquidity overnight.",
    ],
  },
  {
    slug: "cost-of-a-bank-branch",
    shape: "guesstimate",
    title: "Estimate the annual cost of running a bank branch in a metro.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 2 crore rupees a year, with staff and rent the dominant lines.",
    hints: ["Then ask what deposits the branch must gather to justify that. That is the real question."],
    moves: [
      { label: "Move 1", text: "Size staff. A metro branch might run 8 to 15 people across roles at varying salary levels." },
      { label: "Move 2", text: "Add rent, which in a prime metro location is substantial for the floor area required." },
      { label: "Move 3", text: "Add technology, security, cash handling and compliance costs." },
      { label: "Move 4", text: "Convert to a break-even deposit requirement using the net interest margin the bank earns on deposits." },
      { label: "Check", text: "That break-even deposit figure is the number that actually decides whether branches stay open." },
    ],
    pitfalls: [
      "Costing the branch without translating it into required business.",
      "Ignoring cash handling and security, which are significant.",
      "Using a national average salary for a metro branch.",
    ],
  },
  {
    slug: "ipo-fee-pool-india",
    shape: "guesstimate",
    title: "Estimate the annual investment banking fee pool from Indian IPOs.",
    type: "Fee pool",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 2,000 to 4,000 crore rupees in an active year, and a fraction of that in a weak one.",
    hints: ["Fee rates fall sharply as issue size rises. A weighted average will mislead you."],
    moves: [
      { label: "Move 1", text: "Size annual issuance. Indian IPO volumes swing enormously, from under 20,000 crore to well over a lakh crore." },
      { label: "Move 2", text: "Apply fee rates by size band. Small issues pay several percent, mega issues under 1%." },
      { label: "Move 3", text: "Weight by the actual issue size distribution, which is dominated by a few large deals." },
      { label: "Move 4", text: "Add related fees: qualified placements, rights issues and block trades." },
      { label: "Check", text: "Note the cyclicality. This pool is one of the most volatile revenue lines in banking, which shapes how teams are staffed." },
    ],
    pitfalls: [
      "Applying a single fee percentage across all deal sizes.",
      "Using one year's issuance as a normal year.",
      "Ignoring the fee split across multiple book-running managers.",
    ],
  },
  {
    slug: "cost-of-acquiring-a-fintech-customer",
    shape: "guesstimate",
    title: "Estimate the cost of acquiring a lending customer for an Indian fintech.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 1,500 to 4,000 rupees per disbursed loan, because most acquired leads never convert.",
    hints: ["Cost per install is not cost per customer. Every drop-off stage multiplies the true figure."],
    moves: [
      { label: "Move 1", text: "Start at cost per install, which for finance apps in India runs well above general apps." },
      { label: "Move 2", text: "Apply the funnel: install to registration, registration to KYC completion, KYC to application." },
      { label: "Move 3", text: "Apply approval rate, which for new-to-credit applicants is low." },
      { label: "Move 4", text: "Divide total spend by disbursed loans, which is the only denominator that matters." },
      { label: "Check", text: "Compare against lifetime contribution per borrower. If acquisition exceeds it, the business does not work at any scale." },
    ],
    pitfalls: [
      "Reporting cost per install as customer acquisition cost.",
      "Ignoring approval rate, which is the largest single filter.",
      "Not comparing against lifetime value, which makes the number meaningless.",
    ],
  },
  {
    slug: "warehouse-reit-rental-yield",
    shape: "guesstimate",
    title: "Estimate the annual rental income of a large Indian warehousing portfolio.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 300 to 600 crore rupees on 20 to 30 million square feet, at yields above office property.",
    hints: ["Rent per square foot per month is the unit. Everything else is multiplication."],
    moves: [
      { label: "Move 1", text: "Size the portfolio in leasable square feet, perhaps 20 to 30 million for a large platform." },
      { label: "Move 2", text: "Apply rent per square foot per month, which for grade A warehousing is far below office rates." },
      { label: "Move 3", text: "Apply occupancy, typically high given long leases with e-commerce and third-party logistics tenants." },
      { label: "Move 4", text: "Note the escalation clauses, typically 4 to 5% annually, which are built into most leases." },
      { label: "Check", text: "Warehousing yields exceed office yields, which is precisely why capital moved into the sector." },
    ],
    pitfalls: [
      "Applying office rents to warehousing.",
      "Ignoring lease escalation, which materially changes multi-year income.",
      "Assuming full occupancy on newly built capacity.",
    ],
  },
  {
    slug: "microfinance-book-per-loan-officer",
    shape: "guesstimate",
    title: "Estimate the loan book a microfinance officer can manage.",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1.5 to 3 crore rupees across 400 to 600 borrowers, limited by collection visits rather than by credit capacity.",
    hints: ["The constraint is the number of physical visits a person can make in a week."],
    moves: [
      { label: "Move 1", text: "Establish the working pattern. Group meetings for collection happen weekly or fortnightly." },
      { label: "Move 2", text: "Size capacity. An officer might run two or three group meetings a day across a working week." },
      { label: "Move 3", text: "Multiply by group size, typically 15 to 25 borrowers per group." },
      { label: "Move 4", text: "Apply average ticket size, typically 30,000 to 50,000 rupees per borrower." },
      { label: "Check", text: "Note that digital collection changes this constraint entirely, which is why the sector is investing there." },
    ],
    pitfalls: [
      "Sizing on credit assessment capacity rather than collection logistics.",
      "Ignoring travel time in rural geographies.",
      "Applying urban group sizes to sparse rural areas.",
    ],
  },
  {
    slug: "float-income-payment-wallet",
    shape: "guesstimate",
    title: "Estimate the float income of a large payments wallet.",
    type: "Revenue estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Modest in India, since regulation restricts what can be earned on customer balances and most balances are small and short-lived.",
    hints: ["Ask what the regulator permits before computing anything. That constraint defines the answer."],
    moves: [
      { label: "Move 1", text: "Size balances. Wallet balances in India are typically small, since users top up for immediate spending." },
      { label: "Move 2", text: "Multiply by users to get total float, which is smaller than the user count suggests." },
      { label: "Move 3", text: "Apply the regulatory constraint. Customer funds must be held in escrow with limited earning ability." },
      { label: "Move 4", text: "Note the velocity. Money that moves in and out within days generates little float regardless of user numbers." },
      { label: "Check", text: "The conclusion is that float is not a business model in India, which is why wallets pivoted to lending and commerce." },
    ],
    pitfalls: [
      "Assuming float can be freely invested for yield.",
      "Using bank-like average balances for a spending wallet.",
      "Ignoring velocity, which caps float even at high volume.",
    ],
  },
  {
    slug: "annual-gst-collections-estimate",
    shape: "guesstimate",
    title: "Estimate India's annual GST collections from first principles.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 18 to 22 lakh crore rupees a year, sized from taxable consumption rather than from GDP directly.",
    hints: ["Not all of GDP is taxable consumption. Narrow it before applying any rate."],
    moves: [
      { label: "Move 1", text: "Start from GDP, roughly 300 lakh crore rupees, and isolate private consumption at around 60%." },
      { label: "Move 2", text: "Remove exempt categories: unprocessed food, education, healthcare and much of housing." },
      { label: "Move 3", text: "Apply the effective blended rate, well below the headline 18% given the multi-slab structure." },
      { label: "Move 4", text: "Adjust for the informal economy, which sits largely outside the tax net." },
      { label: "Check", text: "Compare against the monthly collection figures reported publicly, which run in the region of 1.7 to 1.8 lakh crore." },
    ],
    pitfalls: [
      "Applying the headline rate to the whole economy.",
      "Ignoring exemptions, which cover a large share of household spending.",
      "Forgetting the informal sector, which is substantial in India.",
    ],
  },
  {
    slug: "corporate-bond-issuance-india",
    shape: "guesstimate",
    title: "Estimate annual corporate bond issuance in India.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 8 to 10 lakh crore rupees, overwhelmingly through private placement rather than public issues.",
    hints: ["Financial sector issuers dominate this market. Do not size it from manufacturing balance sheets."],
    moves: [
      { label: "Move 1", text: "Identify the issuers. Non-bank lenders and housing finance companies raise far more than industrial firms." },
      { label: "Move 2", text: "Size their funding needs, which scale with their loan book growth." },
      { label: "Move 3", text: "Split by channel. Private placement dominates because it is faster and cheaper than a public issue." },
      { label: "Move 4", text: "Add refinancing, since maturing bonds are routinely rolled over and count as new issuance." },
      { label: "Check", text: "Compare against bank credit growth. The bond market remains far smaller, which is a persistent structural feature of Indian finance." },
    ],
    pitfalls: [
      "Sizing from corporate capital expenditure, which is bank-funded in India.",
      "Ignoring refinancing, which is a large share of gross issuance.",
      "Assuming public issuance is the main channel.",
    ],
  },
  {
    slug: "annual-cost-of-fuel-subsidy",
    shape: "guesstimate",
    title: "Estimate the annual cost of an LPG subsidy programme.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Tens of thousands of crores of rupees, driven by the per-cylinder gap and by how many beneficiaries actually refill.",
    hints: ["Beneficiary count and refill rate are different numbers. The second is what costs money."],
    moves: [
      { label: "Move 1", text: "Size beneficiaries, in the region of 100 million households under a large programme." },
      { label: "Move 2", text: "Apply refill frequency, which is the crucial variable since many beneficiaries refill far less than assumed." },
      { label: "Move 3", text: "Apply the subsidy per cylinder, which is the gap between market price and the price paid." },
      { label: "Move 4", text: "Note the crude price sensitivity. The per-cylinder gap moves with global oil prices, so the total is volatile." },
      { label: "Check", text: "Low refill rates reduce fiscal cost but also mean the policy goal is not being met, which is the interesting tension." },
    ],
    pitfalls: [
      "Multiplying beneficiaries by twelve cylinders a year.",
      "Treating the subsidy per unit as fixed when it moves with crude prices.",
      "Reporting the fiscal cost without noting what low refill implies about outcomes.",
    ],
  },
  {
    slug: "value-of-cricket-media-rights",
    shape: "guesstimate",
    title: "Estimate what a season of Indian cricket media rights is worth.",
    type: "Revenue estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Several thousand crore rupees a season, derived from advertising and subscription revenue the buyer expects to earn.",
    hints: ["A rights holder pays what they expect to earn. Build their revenue model, not a price."],
    moves: [
      { label: "Move 1", text: "Size the audience. Viewership per match runs into hundreds of millions across television and streaming." },
      { label: "Move 2", text: "Build advertising revenue: ad inventory per match multiplied by rates, which are premium for live cricket." },
      { label: "Move 3", text: "Add subscription value, both direct revenue and the subscriber retention the rights deliver." },
      { label: "Move 4", text: "Subtract production and distribution costs to reach what a buyer can afford to pay." },
      { label: "Check", text: "Note that bidders often pay above pure media economics because the rights also defend a platform's overall subscriber base." },
    ],
    pitfalls: [
      "Pricing the rights without modelling the buyer's revenue.",
      "Ignoring the strategic value of subscriber retention.",
      "Treating television and digital rights as one when they are sold and valued separately.",
    ],
  },
  {
    slug: "working-capital-cycle-fmcg",
    shape: "guesstimate",
    title: "Estimate the working capital tied up by an FMCG distributor.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 20 to 40 days of sales, dominated by receivables from retailers rather than by inventory.",
    hints: ["Distributors extend credit downstream while paying upstream quickly. That gap is the whole business problem."],
    moves: [
      { label: "Move 1", text: "Size inventory days. Fast-moving goods turn quickly, so stock is typically held for a couple of weeks." },
      { label: "Move 2", text: "Add receivable days. Retailers are extended credit, which is where most working capital sits." },
      { label: "Move 3", text: "Subtract payable days, which for a distributor buying from a large brand are usually short." },
      { label: "Move 4", text: "Convert the net cycle into rupees using daily sales value." },
      { label: "Check", text: "Distributor margin is thin, so financing cost on this cycle is a large share of their actual profit." },
    ],
    pitfalls: [
      "Focusing on inventory while ignoring receivables, which are larger.",
      "Assuming distributors get long credit terms from brands.",
      "Reporting days without converting into a rupee funding requirement.",
    ],
  },
  {
    slug: "annual-tax-collected-on-fuel",
    shape: "guesstimate",
    title: "Estimate annual tax collected on petrol and diesel in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 5 to 6 lakh crore rupees across central and state levies combined.",
    hints: ["Tax is a large share of the pump price. Get consumption right and the rest follows."],
    moves: [
      { label: "Move 1", text: "Size consumption. India uses roughly 40 million tonnes of petrol and diesel combined annually, and rather more of diesel." },
      { label: "Move 2", text: "Convert to litres, since fuel is taxed and sold by volume." },
      { label: "Move 3", text: "Apply the tax component per litre, which combines central excise and state value added tax." },
      { label: "Move 4", text: "Note the state variation, since value added tax rates differ substantially across states." },
      { label: "Check", text: "Compare against total government revenue. Fuel taxes being a major share is the correct and politically important finding." },
    ],
    pitfalls: [
      "Working in tonnes when the tax is levied per litre.",
      "Applying one tax rate nationally.",
      "Missing that diesel volumes far exceed petrol volumes in India.",
    ],
  },
  {
    slug: "cost-of-capital-for-indian-startup",
    shape: "guesstimate",
    title: "Estimate the effective cost of venture capital for an Indian startup.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Effectively 25 to 40% annualised once expected failure rates and required fund returns are accounted for.",
    hints: ["Work backwards from what the fund must return to its own investors."],
    moves: [
      { label: "Move 1", text: "Start with fund return expectations. Venture investors target multiples that imply high annualised returns." },
      { label: "Move 2", text: "Apply the portfolio failure rate. Most investments return little, so winners must carry the whole fund." },
      { label: "Move 3", text: "Derive the required return per successful investment, which is far above the headline fund target." },
      { label: "Move 4", text: "Add the non-financial cost: board seats, liquidation preferences and control terms." },
      { label: "Check", text: "Compare against debt at 12 to 15%. Equity looks cheap only because it carries no repayment obligation, not because it is inexpensive." },
    ],
    pitfalls: [
      "Treating equity as free because it has no interest payment.",
      "Ignoring portfolio failure rates when deriving required returns.",
      "Missing the value of control and preference terms.",
    ],
  },
  {
    slug: "hospital-revenue-per-bed",
    shape: "guesstimate",
    title: "Estimate annual revenue per bed for a private Indian hospital.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 40 to 80 lakh rupees per bed per year, varying enormously with speciality mix.",
    hints: ["Speciality mix drives this more than occupancy does. A cardiac bed and a general ward bed are not comparable."],
    moves: [
      { label: "Move 1", text: "Apply occupancy, typically 65 to 75% for a well-run private hospital." },
      { label: "Move 2", text: "Apply average length of stay, roughly four days, to derive annual admissions per bed." },
      { label: "Move 3", text: "Apply revenue per admission, which varies from tens of thousands to several lakh by speciality." },
      { label: "Move 4", text: "Weight by case mix, since a few high-value procedures carry a large share of revenue." },
      { label: "Check", text: "Add outpatient and diagnostics revenue, which is not bed-linked but is a significant part of hospital income." },
    ],
    pitfalls: [
      "Applying one revenue per admission across all specialities.",
      "Ignoring outpatient revenue entirely.",
      "Assuming occupancy near 100%, which no hospital sustains.",
    ],
  },
  {
    slug: "annual-cost-of-employee-attrition",
    shape: "guesstimate",
    title: "Estimate the annual cost of attrition at a 10,000 person IT services firm.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 100 to 250 crore rupees a year at 20% attrition, most of it in lost productivity rather than in hiring.",
    hints: ["Replacement cost is the visible part. Ramp-up time is the expensive part."],
    moves: [
      { label: "Move 1", text: "Apply the attrition rate. At 20%, that is 2,000 replacements a year." },
      { label: "Move 2", text: "Cost recruitment: agency fees, referral bonuses and internal recruiter time." },
      { label: "Move 3", text: "Cost ramp-up. A replacement takes months to reach full productivity, which is the largest component." },
      { label: "Move 4", text: "Add project disruption, since losing a person mid-delivery costs more than a bench replacement." },
      { label: "Check", text: "Compare against the cost of retention measures. Often a fraction of this figure would materially reduce attrition." },
    ],
    pitfalls: [
      "Counting only recruitment fees.",
      "Ignoring ramp-up time, which dominates the true cost.",
      "Treating all attrition as equally costly regardless of role or project stage.",
    ],
  },
  {
    slug: "annual-savings-flow-indian-household",
    shape: "guesstimate",
    title: "Estimate how much Indian households save financially each year.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 20 to 25 lakh crore rupees of gross financial savings, though physical assets absorb a comparable amount.",
    hints: ["Indians save heavily into gold and property. Financial savings are only part of the total."],
    moves: [
      { label: "Move 1", text: "Size household income at roughly 60% of GDP, so around 180 lakh crore rupees." },
      { label: "Move 2", text: "Apply the savings rate, historically in the region of 20% of income for households." },
      { label: "Move 3", text: "Split financial from physical. Gold and real estate absorb a large share of Indian household saving." },
      { label: "Move 4", text: "Split financial savings by instrument: deposits, insurance, provident fund, and increasingly equity and mutual funds." },
      { label: "Check", text: "Subtract household borrowing to get net financial savings, which is materially lower and is the number policymakers watch." },
    ],
    pitfalls: [
      "Reporting gross financial savings without netting off borrowing.",
      "Ignoring physical savings, which is where much Indian household wealth goes.",
      "Applying a corporate savings rate to households.",
    ],
  },
  {
    slug: "operating-leverage-airline-vs-software",
    shape: "guesstimate",
    title: "Compare the fixed cost share of an airline and a software firm.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Airlines run roughly 40 to 50% fixed, software closer to 80 to 90%, which is why their earnings behave so differently.",
    hints: ["The point is the ratio, not the absolute numbers. Build both cost stacks."],
    moves: [
      { label: "Move 1", text: "Build the airline stack: fuel and airport charges vary with flights, leases and staff largely do not." },
      { label: "Move 2", text: "Build the software stack: salaries dominate and barely move with an additional customer." },
      { label: "Move 3", text: "Compute the contribution margin per unit for each: a seat and a licence." },
      { label: "Move 4", text: "Model a 10% revenue drop through both, which shows the earnings volatility difference starkly." },
      { label: "Check", text: "High operating leverage is wonderful upward and brutal downward. That symmetry is the actual insight." },
    ],
    pitfalls: [
      "Treating fuel as fixed because it is large.",
      "Ignoring that software infrastructure costs do scale somewhat with usage.",
      "Comparing absolute cost rather than the fixed proportion.",
    ],
  },
  {
    slug: "annual-fee-pool-payment-gateways",
    shape: "guesstimate",
    title: "Size the annual revenue pool for Indian payment gateways.",
    type: "Fee pool",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 8,000 to 15,000 crore rupees, constrained because UPI, the largest volume rail, carries no merchant fee.",
    hints: ["Volume and revenue are decoupled here. Split by rail before applying any rate."],
    moves: [
      { label: "Move 1", text: "Size online transaction value across cards, net banking, wallets and UPI." },
      { label: "Move 2", text: "Apply merchant discount rates by rail. Cards carry 1.5 to 2%, UPI carries nothing." },
      { label: "Move 3", text: "Note the mix problem. UPI dominates volume, which caps the fee pool despite enormous transaction counts." },
      { label: "Move 4", text: "Add value-added services: subscriptions, payouts, lending referrals and reconciliation tools." },
      { label: "Check", text: "The strategic conclusion is that gateways must monetise beyond payments, which is exactly what they have done." },
    ],
    pitfalls: [
      "Applying a blended rate across rails with completely different economics.",
      "Assuming UPI generates merchant fees.",
      "Ignoring value-added revenue, which is where growth actually comes from.",
    ],
  },
  {
    slug: "burn-rate-of-quick-commerce-player",
    shape: "guesstimate",
    title: "Estimate the monthly burn of a quick commerce player at scale.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Tens of crores of rupees a month at moderate scale, driven by dark store fixed costs and delivery subsidy.",
    hints: ["Loss per order times order volume, plus fixed costs that do not scale down."],
    moves: [
      { label: "Move 1", text: "Size monthly orders, perhaps 20 to 40 million for a large player." },
      { label: "Move 2", text: "Estimate contribution per order, which may be slightly negative or slightly positive depending on city maturity." },
      { label: "Move 3", text: "Add dark store fixed costs: rent, staff and electricity across hundreds of locations." },
      { label: "Move 4", text: "Add central costs: technology, marketing and corporate overhead, which are substantial." },
      { label: "Check", text: "Note that mature cities often fund the losses of new ones, so the blended figure hides the real picture." },
    ],
    pitfalls: [
      "Assuming a uniform contribution margin across mature and new cities.",
      "Ignoring central overhead.",
      "Treating a blended national figure as representative of any individual market.",
    ],
  },
  {
    slug: "value-of-a-banking-customer",
    shape: "guesstimate",
    title: "Estimate the lifetime value of a retail banking customer.",
    type: "Revenue estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 50,000 to 200,000 rupees over a relationship, depending almost entirely on whether they borrow.",
    hints: ["Deposits earn a spread. Loans earn far more. The difference decides everything."],
    moves: [
      { label: "Move 1", text: "Start with deposit income: average balance multiplied by the net interest margin the bank earns on it." },
      { label: "Move 2", text: "Add fee income: cards, transactions, and third-party product distribution." },
      { label: "Move 3", text: "Add lending income, which for a customer who takes a home loan dwarfs everything else." },
      { label: "Move 4", text: "Apply relationship tenure, which in banking is long, often measured in decades." },
      { label: "Check", text: "Subtract servicing cost and expected credit losses to reach net value rather than gross revenue." },
    ],
    pitfalls: [
      "Valuing deposits alone and missing the lending relationship.",
      "Ignoring servicing cost, which is significant for low-balance accounts.",
      "Applying one value across customers with wildly different product holdings.",
    ],
  },
  {
    slug: "annual-import-bill-for-crude",
    shape: "guesstimate",
    title: "Estimate India's annual crude oil import bill.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 130 to 180 billion dollars a year, moving sharply with both crude price and the rupee.",
    hints: ["Volume times price times exchange rate. All three move, and they do not always move together."],
    moves: [
      { label: "Move 1", text: "Size consumption, roughly 5 million barrels a day, of which India imports well over 80%." },
      { label: "Move 2", text: "Convert to annual barrels imported, around 1.6 to 1.8 billion." },
      { label: "Move 3", text: "Apply the crude price, using a realistic band rather than a single point." },
      { label: "Move 4", text: "Note the currency effect, since the bill is paid in dollars and felt in rupees." },
      { label: "Check", text: "Compare against total imports and foreign exchange reserves. Crude dominating the trade deficit is the correct conclusion." },
    ],
    pitfalls: [
      "Using consumption rather than imports.",
      "Applying a single crude price to a volatile year.",
      "Ignoring the exchange rate, which compounds price moves.",
    ],
  },
  {
    slug: "revenue-per-square-foot-retail",
    shape: "guesstimate",
    title: "Estimate revenue per square foot for an Indian apparel retailer.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 8,000 to 15,000 rupees per square foot a year for a mall store, and higher in prime high street locations.",
    hints: ["Build it from footfall, conversion and basket size, then divide by area."],
    moves: [
      { label: "Move 1", text: "Size daily footfall for a mall store, perhaps 200 to 400 people entering." },
      { label: "Move 2", text: "Apply conversion, typically 15 to 25% in apparel, and basket size of 1,500 to 3,000 rupees." },
      { label: "Move 3", text: "Compute daily revenue, annualise, then divide by store area of perhaps 2,000 to 3,000 square feet." },
      { label: "Move 4", text: "Adjust for seasonality, since festive months carry a disproportionate share of annual sales." },
      { label: "Check", text: "Compare against rent per square foot. Rent to revenue above roughly 15% is where store economics start failing." },
    ],
    pitfalls: [
      "Estimating revenue per square foot directly without the footfall build.",
      "Ignoring seasonality in an intensely seasonal category.",
      "Not comparing against rent, which is the reason the metric exists.",
    ],
  },
  {
    slug: "cost-of-a-cricket-franchise",
    shape: "guesstimate",
    title: "Estimate the annual operating cost of an IPL franchise.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 200 to 350 crore rupees a year, with the player salary cap the single largest and most predictable line.",
    hints: ["The salary cap is public and fixed. Build outward from there."],
    moves: [
      { label: "Move 1", text: "Start with the player salary cap, which is set by the league and is the largest single cost." },
      { label: "Move 2", text: "Add support staff: coaching, physiotherapy, analysis and management." },
      { label: "Move 3", text: "Add operations: travel, accommodation, stadium hire and match-day costs." },
      { label: "Move 4", text: "Add marketing and franchise fee obligations to the league." },
      { label: "Check", text: "Compare against revenue, which is dominated by the central media rights share distributed to all franchises." },
    ],
    pitfalls: [
      "Forgetting the central revenue share, which makes franchises profitable almost regardless of performance.",
      "Underestimating travel and logistics across a national tournament.",
      "Treating sponsorship as the main revenue when media rights dominate.",
    ],
  },
  {
    slug: "annual-fraud-losses-indian-banking",
    shape: "guesstimate",
    title: "Estimate annual digital fraud losses in Indian banking.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Thousands of crores of rupees annually, though the number depends entirely on whether unreported cases are estimated.",
    hints: ["Reported fraud and actual fraud differ substantially. Say which you are estimating."],
    moves: [
      { label: "Move 1", text: "Size digital transaction volume, which runs into hundreds of billions annually." },
      { label: "Move 2", text: "Apply a fraud rate. Even a very small basis point rate produces a large absolute number at this volume." },
      { label: "Move 3", text: "Split by type: card fraud, UPI social engineering, account takeover and loan fraud." },
      { label: "Move 4", text: "Note underreporting. Small-value frauds are frequently never formally reported." },
      { label: "Check", text: "Add the cost of prevention and investigation, which for banks often exceeds the direct losses." },
    ],
    pitfalls: [
      "Reporting only formally recorded fraud.",
      "Applying card fraud rates to UPI, which fails differently through social engineering.",
      "Ignoring prevention cost, which is a large part of the true economic burden.",
    ],
  },
  {
    slug: "capital-required-to-start-nbfc",
    shape: "guesstimate",
    title: "Estimate the capital needed to start a lending business in India.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Regulatory minimum capital is the entry ticket, but the practical requirement is several times that once a book and losses are funded.",
    hints: ["Regulatory minimum is not the same as what you actually need to operate."],
    moves: [
      { label: "Move 1", text: "Start with the regulatory net owned funds requirement for a non-banking finance company." },
      { label: "Move 2", text: "Add the equity needed to support the intended loan book at a viable leverage ratio." },
      { label: "Move 3", text: "Add operating cost through the loss-making period, since lending takes time to reach scale." },
      { label: "Move 4", text: "Add early credit losses, which are typically higher before underwriting models mature." },
      { label: "Check", text: "Note that debt funding becomes available only after a track record, so early growth is equity-funded and expensive." },
    ],
    pitfalls: [
      "Treating the regulatory minimum as sufficient.",
      "Ignoring that early credit losses exceed steady-state expectations.",
      "Assuming debt lines are available from day one.",
    ],
  },
  {
    slug: "annual-insurance-agent-commission-pool",
    shape: "guesstimate",
    title: "Size the annual commission pool for Indian life insurance agents.",
    type: "Fee pool",
    difficulty: 2,
    minutes: 20,
    answer: "Tens of thousands of crores of rupees, front-loaded heavily into first-year premiums.",
    hints: ["First-year commission rates are far higher than renewal rates. The mix drives the answer."],
    moves: [
      { label: "Move 1", text: "Size new business premium, which for the industry runs into lakhs of crores annually." },
      { label: "Move 2", text: "Apply first-year commission rates, which are regulated but substantial on traditional products." },
      { label: "Move 3", text: "Add renewal commissions, which are much lower per rupee but apply to a far larger premium base." },
      { label: "Move 4", text: "Split by channel, since bank-distributed policies pay differently from individual agent business." },
      { label: "Check", text: "Note the mis-selling incentive that front-loading creates, which is why regulation keeps revisiting these rates." },
    ],
    pitfalls: [
      "Applying one commission rate across first-year and renewal premium.",
      "Ignoring the bancassurance channel, which is large.",
      "Missing that product type dramatically changes commission rates.",
    ],
  },
  {
    slug: "cost-per-kilometre-electric-vs-petrol",
    shape: "guesstimate",
    title: "Compare running cost per kilometre for an electric and a petrol car.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 1.5 rupees per kilometre for electric against 6 to 8 for petrol, before accounting for battery replacement.",
    hints: ["Include battery degradation. Ignoring it flatters electric substantially."],
    moves: [
      { label: "Move 1", text: "Compute petrol cost: fuel price divided by mileage, roughly 100 rupees a litre at 15 kilometres a litre." },
      { label: "Move 2", text: "Compute electric cost: consumption per kilometre multiplied by the tariff, distinguishing home from fast charging." },
      { label: "Move 3", text: "Add maintenance, which is materially lower for electric given fewer moving parts." },
      { label: "Move 4", text: "Amortise battery replacement across expected life, which is the cost usually left out." },
      { label: "Check", text: "Compute the break-even distance against the higher purchase price, since that is what actually decides the buying case." },
    ],
    pitfalls: [
      "Excluding battery replacement from the electric case.",
      "Using home charging tariffs when much charging happens at commercial rates.",
      "Comparing running cost without factoring the purchase price difference.",
    ],
  },
  {
    slug: "annual-turnover-of-a-mandi",
    shape: "guesstimate",
    title: "Estimate the annual turnover of a large agricultural mandi.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Hundreds of crores to a few thousand crore rupees, entirely dependent on the crops traded and the season.",
    hints: ["Arrivals in tonnes times price. Both are wildly seasonal."],
    moves: [
      { label: "Move 1", text: "Size daily arrivals in tonnes, which for a large mandi runs into hundreds or thousands of tonnes." },
      { label: "Move 2", text: "Apply crop prices, which vary by an order of magnitude between grains and horticulture." },
      { label: "Move 3", text: "Account for seasonality. Arrivals concentrate sharply into harvest windows." },
      { label: "Move 4", text: "Add the commission and market fee layer, which is how the mandi and its traders actually earn." },
      { label: "Check", text: "Note that turnover and mandi income are very different. The mandi earns a small percentage of the value transacted." },
    ],
    pitfalls: [
      "Assuming even arrivals across the year.",
      "Applying one price across very different crops.",
      "Confusing traded value with the mandi's own revenue.",
    ],
  },
  {
    slug: "cost-of-a-thirty-second-tv-ad",
    shape: "guesstimate",
    title: "Estimate what a 30-second prime time television ad costs in India.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 15,
    answer: "A few lakh rupees for general entertainment prime time, and several times that for live cricket.",
    hints: ["Price follows audience. Build from cost per thousand viewers rather than guessing a rate."],
    moves: [
      { label: "Move 1", text: "Size the audience for a prime time slot on a leading general entertainment channel." },
      { label: "Move 2", text: "Apply a cost per thousand viewers, which for Indian television is low by global standards." },
      { label: "Move 3", text: "Multiply out to get the slot rate for that audience." },
      { label: "Move 4", text: "Apply the cricket premium, where audiences are many times larger and rates disproportionately higher." },
      { label: "Check", text: "Compare against digital video rates for the same reach, which is the comparison advertisers actually make." },
    ],
    pitfalls: [
      "Quoting a rate without deriving it from audience size.",
      "Applying general entertainment rates to live sport.",
      "Ignoring that reach and frequency are bought together, not as single slots.",
    ],
  },
  {
    slug: "annual-education-loan-market",
    shape: "guesstimate",
    title: "Size India's annual education loan disbursement.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25,000 to 40,000 crore rupees a year, dominated by students going abroad.",
    hints: ["Overseas study drives ticket size. Domestic loans are far smaller per borrower."],
    moves: [
      { label: "Move 1", text: "Split the market. Students studying abroad borrow far larger amounts than domestic students." },
      { label: "Move 2", text: "Size the overseas cohort, in the hundreds of thousands annually, and apply ticket sizes in tens of lakhs." },
      { label: "Move 3", text: "Size the domestic cohort, far larger in number but with much smaller loan sizes and lower borrowing rates." },
      { label: "Move 4", text: "Note that most domestic education is funded from family savings rather than credit." },
      { label: "Check", text: "Note the credit risk profile, since these loans are unsecured against uncertain future earnings, which shapes pricing." },
    ],
    pitfalls: [
      "Applying overseas ticket sizes to domestic students.",
      "Assuming most students borrow, when family funding dominates in India.",
      "Ignoring that the collateral position is weak, which affects both pricing and availability.",
    ],
  },
  {
    slug: "value-of-data-centre-land-bank",
    shape: "guesstimate",
    title: "Estimate the value of land suitable for data centres near Mumbai.",
    type: "Revenue estimation",
    difficulty: 3,
    minutes: 25,
    answer: "A large premium over general industrial land, because power availability and fibre routes, not acreage, set the price.",
    hints: ["Land is not the constraint. Power connection and network routes are what create the value."],
    moves: [
      { label: "Move 1", text: "Establish the requirements: reliable high-capacity power, fibre routes, and low flood and seismic risk." },
      { label: "Move 2", text: "Note how few parcels meet all three, which is what creates scarcity value." },
      { label: "Move 3", text: "Value against the revenue it enables, since a megawatt of data centre capacity generates substantial annual income." },
      { label: "Move 4", text: "Note the submarine cable landing advantage, which is why Mumbai specifically commands a premium." },
      { label: "Check", text: "The land is a small share of total project cost. Power infrastructure and cooling dominate, which is what the valuation should reflect." },
    ],
    pitfalls: [
      "Valuing on comparable industrial land rates.",
      "Ignoring power availability, which is the actual constraint.",
      "Treating land as a large share of data centre project cost when it is not.",
    ],
  },
  {
    slug: "annual-cost-of-free-delivery",
    shape: "guesstimate",
    title: "Estimate what free delivery costs an e-commerce platform annually.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Thousands of crores of rupees, and the honest question is what it buys in order frequency.",
    hints: ["Cost per shipment times shipments. Then ask what the alternative would cost in lost orders."],
    moves: [
      { label: "Move 1", text: "Size annual shipments, in the hundreds of millions for a large Indian platform." },
      { label: "Move 2", text: "Apply delivery cost per shipment, which varies sharply between metro and non-metro destinations." },
      { label: "Move 3", text: "Subtract what customers already pay through membership programmes and minimum order thresholds." },
      { label: "Move 4", text: "Model the counterfactual. Charging for delivery reduces order frequency, particularly on small baskets." },
      { label: "Check", text: "The right frame is customer acquisition and retention spend, not logistics cost, which is why platforms tolerate it." },
    ],
    pitfalls: [
      "Costing delivery without modelling the order loss from charging.",
      "Applying metro delivery costs nationally.",
      "Ignoring membership revenue that partly funds it.",
    ],
  },
  {
    slug: "annual-revenue-of-a-toll-road-concession",
    shape: "guesstimate",
    title: "Estimate the lifetime revenue of a 25-year road concession.",
    type: "Revenue estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Several thousand crore rupees, but the present value is far lower and traffic growth assumptions dominate the answer.",
    hints: ["Traffic growth compounds over 25 years. Small differences in the assumption change everything."],
    moves: [
      { label: "Move 1", text: "Size current daily traffic and the toll per vehicle by category." },
      { label: "Move 2", text: "Compute year one revenue, then apply a traffic growth rate over the concession period." },
      { label: "Move 3", text: "Apply toll escalation, typically linked to inflation under the concession agreement." },
      { label: "Move 4", text: "Discount to present value, which heavily reduces the weight of distant years." },
      { label: "Check", text: "Stress the traffic growth assumption. Concessions have failed precisely because traffic forecasts proved optimistic." },
    ],
    pitfalls: [
      "Summing nominal revenue across 25 years without discounting.",
      "Using an optimistic single traffic growth rate with no downside case.",
      "Ignoring exempt vehicles and local passes, which reduce realised collection.",
    ],
  },
  {
    slug: "size-of-indian-wealth-management-market",
    shape: "guesstimate",
    title: "Size the Indian wealth management fee pool.",
    type: "Fee pool",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 15,000 to 30,000 crore rupees a year, with fee rates falling as assets shift toward passive products.",
    hints: ["Segment by client wealth band. Fee rates differ enormously across them."],
    moves: [
      { label: "Move 1", text: "Size the client base by wealth band: mass affluent, high net worth and ultra high net worth." },
      { label: "Move 2", text: "Size investable assets per band, noting that a small number of families hold a large share." },
      { label: "Move 3", text: "Apply fee rates, which fall sharply as portfolio size rises and as passive products gain share." },
      { label: "Move 4", text: "Add transaction and distribution revenue, which for many Indian firms exceeds advisory fees." },
      { label: "Check", text: "Note the direction. Regulatory pressure and passive adoption are compressing fee rates, so growth must come from assets." },
    ],
    pitfalls: [
      "Applying one fee rate across all wealth bands.",
      "Ignoring the shift from distribution commissions to advisory fees.",
      "Sizing assets without separating financial from physical wealth.",
    ],
  },
  {
    slug: "annual-atm-withdrawals-india",
    shape: "guesstimate",
    title: "Estimate the annual value of ATM withdrawals in India.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 35 to 45 lakh crore rupees a year, and flat or falling as UPI displaces cash.",
    hints: ["Transactions times average withdrawal size. Both are easier to estimate than the total."],
    moves: [
      { label: "Move 1", text: "Size the machine base at roughly 250,000 ATMs across the country." },
      { label: "Move 2", text: "Apply transactions per machine per day, typically 80 to 150 depending on location." },
      { label: "Move 3", text: "Apply average withdrawal size, which in India runs a few thousand rupees per transaction." },
      { label: "Move 4", text: "Annualise, then sense-check against currency in circulation, which is a related but different measure." },
      { label: "Check", text: "State the direction. Withdrawal value has plateaued while digital payments grow, which is the strategically relevant point." },
    ],
    pitfalls: [
      "Confusing withdrawal value with currency in circulation.",
      "Using pre-UPI transaction rates per machine.",
      "Applying metro machine utilisation nationally.",
    ],
  },
  {
    slug: "size-of-indian-gold-etf-market",
    shape: "guesstimate",
    title: "Size the Indian gold exchange traded fund market.",
    type: "Book sizing",
    difficulty: 3,
    minutes: 20,
    answer: "Tens of thousands of crores of rupees, tiny against household physical gold holdings.",
    hints: ["Compare against physical gold. The contrast is the point of the question."],
    moves: [
      { label: "Move 1", text: "Size household gold holdings, estimated near 25,000 tonnes, worth lakhs of crores of rupees." },
      { label: "Move 2", text: "Note that almost none of this is financialised, since Indians hold jewellery rather than paper gold." },
      { label: "Move 3", text: "Size the investor base: demat account holders with an allocation preference for gold." },
      { label: "Move 4", text: "Apply average allocation, typically a small single-digit share of a portfolio." },
      { label: "Check", text: "The gap between physical and financial gold is enormous, which is exactly why sovereign gold bonds were introduced." },
    ],
    pitfalls: [
      "Assuming gold demand translates into gold fund demand.",
      "Ignoring that jewellery serves a social function paper gold cannot.",
      "Sizing against all investors rather than demat account holders.",
    ],
  },
  {
    slug: "estimate-annual-audit-fee-pool-india",
    shape: "guesstimate",
    title: "Size the annual statutory audit fee pool in India.",
    type: "Fee pool",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 8,000 to 15,000 crore rupees, with listed audits a small share of entities but a large share of fees.",
    hints: ["Entity count and fee per entity move in opposite directions. Segment before multiplying."],
    moves: [
      { label: "Move 1", text: "Segment entities: listed companies, large unlisted companies, and the long tail of small private companies." },
      { label: "Move 2", text: "Apply fees by segment, from a few crore rupees for a large listed audit to a few thousand for a small company." },
      { label: "Move 3", text: "Weight by count, noting hundreds of thousands of small entities each paying very little." },
      { label: "Move 4", text: "Add related assurance work: tax audit, internal audit and certification, which often exceeds statutory fees." },
      { label: "Check", text: "Indian audit fees are low by global standards for comparable company size, which is a persistent industry issue." },
    ],
    pitfalls: [
      "Applying listed company fees across all registered entities.",
      "Ignoring non-statutory assurance work, which is where firms actually earn.",
      "Using global fee benchmarks for the Indian market.",
    ],
  },
];
