import type { Question } from "./types";

// HR cases. Attrition, talent, culture and labour situations: the judgement
// calls an HR interview walks you into, each needing structure plus empathy.
export const HR_CASES: Question[] = [
  {
    slug: "fresher-attrition-first-year",
    shape: "case",
    title: "38% of campus hires quit within a year at an IT firm. Diagnose and fix it.",
    type: "Attrition diagnosis",
    difficulty: 2,
    minutes: 25,
    askedAt: "Wipro",
    answer: "Map exits against the joining journey: the spikes usually sit at bench time before allocation, first-project mismatch, and the 9-month salary comparison point. Fix allocation speed and the expectation gap before touching pay.",
    hints: ["Plot when in the year they leave; the timing names the cause."],
    moves: [
      { label: "Move 1", text: "Get the exit curve by month: a spike at months 3 to 5 points at bench frustration; at months 9 to 12, at market re-pricing and better offers." },
      { label: "Move 2", text: "Segment: by college tier, by allocated project type, by location, by trainer batch. Attrition rarely spreads evenly." },
      { label: "Move 3", text: "Listen at scale: exit interviews plus stay interviews with the 62% who remain; the stated versus real reasons differ." },
      { label: "Move 4", text: "Match fix to cause: cut bench time with pre-allocation; reset campus messaging on the first-year reality; deploy skill-growth paths visible in the first 90 days." },
      { label: "Close", text: "Target first-year attrition below 25% in one cohort cycle, measured by joining cohort, not calendar year." },
    ],
    pitfalls: [
      "Throwing a retention bonus at a bench-boredom problem.",
      "Reading exit interviews at face value.",
      "Measuring calendar attrition when cohort curves tell the story.",
    ],
  },
  {
    slug: "sales-team-attrition-comp",
    shape: "case",
    title: "A consumer-finance firm loses its best sales staff to a rival paying 20% more. Respond.",
    type: "Retention strategy",
    difficulty: 2,
    minutes: 25,
    answer: "Do not match blindly: segment who is actually leaving and what the 20% really compares. Counter with a targeted top-performer plan (pay repositioning, faster incentive payout, territory quality) rather than an across-the-board hike that costs more and retains the wrong people.",
    hints: ["Match for whom? Across-the-board matching pays everyone for the top decile's options."],
    moves: [
      { label: "Move 1", text: "Verify the threat: who left, what quartile were they, and is the 20% on fixed, on-target, or inflated offer-letter maximums?" },
      { label: "Move 2", text: "Size the exposure: if the top quartile drives 60% of disbursals, their loss costs far more than their pay." },
      { label: "Move 3", text: "Respond by segment: reposition top-quartile pay to 90th percentile, speed up incentive payment cycles (a hidden differentiator), and fix territory allocation grievances." },
      { label: "Move 4", text: "Strengthen the non-pay moat: faster career gates for proven sellers and manager quality, the top stated reason in most sales exit data." },
      { label: "Close", text: "Present the cost comparison: targeted plan at a fraction of blanket matching, with retention tracked in the top quartile specifically." },
    ],
    pitfalls: [
      "Blanket hikes that pay everyone for a top-decile problem.",
      "Comparing your fixed pay with the rival's inflated on-target claims.",
      "Ignoring payout speed and territory fairness as retention levers.",
    ],
  },
  {
    slug: "appraisal-bell-curve-removal",
    shape: "case",
    title: "The CEO wants the forced bell curve scrapped. Design what replaces it.",
    type: "Performance system design",
    difficulty: 3,
    minutes: 30,
    askedAt: "Infosys",
    answer: "Removing the curve without replacing its functions (differentiation, budget control, calibration) recreates grade inflation in two cycles. Replace with continuous check-ins, calibrated manager judgement inside a fixed rewards budget, and clear handling for the genuine underperformance tail.",
    hints: ["The curve did three jobs badly. What does each job instead?"],
    moves: [
      { label: "Move 1", text: "Name the curve's functions: forcing differentiation, containing the bonus budget, catching inflation-prone managers, and flagging underperformance." },
      { label: "Move 2", text: "Design the replacement: quarterly goal check-ins, a ratings-light summary, and calibration panels that challenge outlier managers with evidence rather than quotas." },
      { label: "Move 3", text: "Keep the budget honest: differentiation moves into the reward distribution (fixed pool, manager-proposed splits reviewed for spread) rather than the label." },
      { label: "Move 4", text: "Handle the tail: underperformance moves to a separate, dignity-preserving improvement process rather than being a rating bucket." },
      { label: "Close", text: "Pilot in two divisions for a full cycle, watching reward spread and top-performer attrition, before firm-wide rollout." },
    ],
    pitfalls: [
      "Dropping the curve and keeping nothing that differentiates.",
      "Letting reward budgets inflate in the first no-curve cycle.",
      "Announcing culture change while pay math stays secretly curved.",
    ],
  },
  {
    slug: "plant-union-wage-negotiation",
    shape: "case",
    title: "Prepare management's strategy for a triennial wage settlement at a strike-prone plant.",
    type: "Labour relations",
    difficulty: 3,
    minutes: 30,
    answer: "Prepare three layers: an economic mandate anchored to plant viability and peer settlements, a relationship track that starts months before the table, and a contingency plan for disruption. The settlement's structure (variable-linked, grade rationalisation) matters more than the headline number.",
    hints: ["The negotiation is won in the six months before the first meeting."],
    moves: [
      { label: "Move 1", text: "Build the fact base: peer plant settlements, plant cost position, productivity trends, and the union's internal politics (election timing changes behaviour)." },
      { label: "Move 2", text: "Define the mandate: a settlement corridor, the walk-away line, and what productivity or flexibility asks (multi-skilling, contract-worker ratios) the raise buys." },
      { label: "Move 3", text: "Work the relationship: pre-table conversations with union leadership, transparency on business realities, and quick wins on pending grievances to bank goodwill." },
      { label: "Move 4", text: "Plan for the worst: inventory buffers, customer communication and legal readiness for a work stoppage, kept quiet but ready." },
      { label: "Close", text: "Aim for a 3-year settlement that trades a fair headline for structural gains, signed before the festival season deadline pressure inverts leverage." },
    ],
    pitfalls: [
      "Arriving at the table without knowing the union's election calendar.",
      "Winning a cheap settlement that buys three years of hostility.",
      "Negotiating the number while ignoring structure and flexibility clauses.",
    ],
  },
  {
    slug: "layoff-design-humane",
    shape: "case",
    title: "A startup must cut 15% of staff after funding fell through. Design the exercise.",
    type: "Restructuring",
    difficulty: 3,
    minutes: 30,
    answer: "Decide selection criteria before names, run it in one clean round with genuinely fair severance, communicate with dignity on the day, and invest visibly in the people leaving (notice, placement support, vesting kindness). One bad layoff destroys the employer brand for years; the survivors are watching harder than the leavers.",
    hints: ["Two audiences: those leaving, and everyone who stays and watches how you did it."],
    moves: [
      { label: "Move 1", text: "Frame the target: 15% of cost, not necessarily 15% of heads; senior salary cuts, shutting projects and vacancy freezes can shrink the layoff itself." },
      { label: "Move 2", text: "Set criteria first: role redundancy and business need, documented, legally reviewed for pattern bias (gender, age, maternity status), and applied before any names enter." },
      { label: "Move 3", text: "Execute in one round: staggered trickles bleed trust. Same-day clarity, managers trained for the conversation, no security-walkout theatre." },
      { label: "Move 4", text: "Support genuinely: severance above statutory, extended insurance, accelerated vesting consideration, placement help, and honest references." },
      { label: "Close", text: "Address survivors within 48 hours with the criteria, the runway math, and what does not change; survivor attrition, not the layoff, is where firms bleed out." },
    ],
    pitfalls: [
      "Choosing names first and constructing criteria after.",
      "Multiple small rounds that keep everyone waiting for the next.",
      "Spending on PR while shorting severance.",
    ],
  },
  {
    slug: "engagement-score-drop-quarter",
    shape: "case",
    title: "Engagement scores fell 12 points in two quarters at a healthy-looking firm. Investigate.",
    type: "Diagnosis",
    difficulty: 2,
    minutes: 25,
    answer: "Cut the data before theorising: by team, tenure, level and question. A uniform drop points to a company-level event (pay decision, leadership change, RTO); a concentrated drop points at specific managers or functions. The comment verbatims usually name it outright.",
    hints: ["Is the drop everywhere, or somewhere? The answer halves the hypothesis space."],
    moves: [
      { label: "Move 1", text: "Decompose: score change by department, manager, tenure band and question cluster (pay, manager, workload, confidence in leadership)." },
      { label: "Move 2", text: "Read the verbatims at scale: theme the open comments; employees usually state the cause plainly." },
      { label: "Move 3", text: "Correlate with events: appraisal payouts, a policy change, senior exits, or workload spikes in the drop window." },
      { label: "Move 4", text: "Respond visibly: name the top two findings back to employees and commit to one fix each; silence after a survey is itself an engagement killer." },
      { label: "Close", text: "Re-pulse the affected segments in 90 days on the specific items, not the whole survey." },
    ],
    pitfalls: [
      "Launching wellness programs before diagnosing.",
      "Averaging away a manager-specific problem.",
      "Surveying, then never reporting back what was heard.",
    ],
  },
  {
    slug: "hipo-program-design",
    shape: "case",
    title: "Design a high-potential program for a 20,000-person firm losing future leaders.",
    type: "Talent management",
    difficulty: 2,
    minutes: 25,
    answer: "Select on evidence not sponsorship, keep the pool honest and refreshed, and make the program consist of real stretch roles rather than classroom flattery. The retention effect comes from visible investment plus accelerated responsibility, not the label.",
    hints: ["The program is the roles you give, not the training you run."],
    moves: [
      { label: "Move 1", text: "Define potential explicitly: ability, aspiration and agility evidence, assessed via structured reviews and psychometrics, not manager nomination alone." },
      { label: "Move 2", text: "Size honestly: 3 to 5% of relevant grades, refreshed yearly with exits for non-performance so the label means something." },
      { label: "Move 3", text: "Build on experience: P&L exposure, cross-functional rotations, turnaround assignments and senior mentorship; classroom content is the garnish." },
      { label: "Move 4", text: "Manage the unlabelled: quiet lists breed resentment; be transparent about criteria and re-entry paths." },
      { label: "Close", text: "Measure what matters: hipo retention versus peers, internal fill rate of senior roles, and time-to-readiness, reviewed yearly." },
    ],
    pitfalls: [
      "Nomination politics filling the pool with sponsors' favourites.",
      "A permanent label with no exits, which kills credibility.",
      "Classroom-heavy programs that change nothing about actual roles.",
    ],
  },
  {
    slug: "m-and-a-culture-integration",
    shape: "case",
    title: "A traditional manufacturer acquired a young software firm. Prevent the talent from fleeing.",
    type: "M&A integration",
    difficulty: 3,
    minutes: 30,
    answer: "The acquisition's value walks out if integration means assimilation. Ring-fence the software unit's ways of working (pay bands, titles, dress, decision speed), integrate only where money moves, retain named critical people with deals plus meaningful roles, and give it 18 months before any harmonisation conversation.",
    hints: ["What did you actually buy? Protect that thing specifically."],
    moves: [
      { label: "Move 1", text: "Identify the asset: it is the 60 engineers and their product velocity, not the office or the brand. Retention of named people is the deal thesis." },
      { label: "Move 2", text: "Ring-fence deliberately: separate comp philosophy, no title mapping onto the manufacturer's grades, protected decision rights for the unit head." },
      { label: "Move 3", text: "Retain the critical 20: stay bonuses tied to milestones, but pair every deal with role enlargement; money without meaning buys one year." },
      { label: "Move 4", text: "Bridge carefully: joint projects with volunteers from both sides, not forced mixing; celebrate early wins publicly in both cultures." },
      { label: "Close", text: "Track regretted attrition in the acquired unit monthly for 24 months as the deal's true scorecard." },
    ],
    pitfalls: [
      "Harmonising policies in month one because inconsistency feels untidy.",
      "Retention bonuses without role meaning, which just schedule the exits.",
      "Measuring integration progress by process merged rather than people kept.",
    ],
  },
  {
    slug: "posh-complaint-surge",
    shape: "case",
    title: "POSH complaints tripled after an awareness campaign. Interpret and respond.",
    type: "Compliance and culture",
    difficulty: 2,
    minutes: 22,
    answer: "A complaint surge after awareness is reporting rising toward reality, not harassment rising: treat it as trust in the system, not a crisis. Respond by scaling IC capacity, protecting timelines and confidentiality, and reading the pattern data for hotspots needing targeted intervention.",
    hints: ["Did incidents rise, or did reporting? The distinction decides everything."],
    moves: [
      { label: "Move 1", text: "Reframe for leadership: prior low numbers meant silence, not safety; the surge is the campaign working." },
      { label: "Move 2", text: "Scale the machinery: IC bandwidth, trained inquiry members and external member availability must match the caseload, or timelines slip and trust collapses." },
      { label: "Move 3", text: "Protect process quality: statutory timelines, confidentiality, no retaliation, and interim measures where needed." },
      { label: "Move 4", text: "Mine the pattern: complaints clustering in a function, location or level point at a management problem beyond individual cases." },
      { label: "Close", text: "Report aggregate trends and actions to the board annually as required, framing rising reporting as a maturity metric." },
    ],
    pitfalls: [
      "Reading rising complaints as a failing culture and killing the campaign.",
      "Letting IC capacity lag and breaching statutory timelines.",
      "Handling cases individually while ignoring cluster patterns.",
    ],
  },
  {
    slug: "contract-worker-regularisation",
    shape: "case",
    title: "A plant runs 60% contract workers doing core work. Advise on the risk and the path.",
    type: "Workforce strategy",
    difficulty: 3,
    minutes: 28,
    answer: "Core-work contract labour at this share is a legal, operational and ethical exposure: courts can order absorption, quality suffers from churn, and disputes brew. Migrate deliberately: regularise a merit-based tranche, convert some roles to fixed-term employment, automate genuinely commoditised tasks, and keep contract labour only for non-core, seasonal work.",
    hints: ["The question is not cost versus compliance; churn already costs quality."],
    moves: [
      { label: "Move 1", text: "Map the exposure: which roles are genuinely core and perennial (the legal test), what the wage differential is, and the dispute history." },
      { label: "Move 2", text: "Count the hidden costs: contract churn of 60%+ yearly means permanent training mode, quality variance and safety incidents concentrated in new workers." },
      { label: "Move 3", text: "Design the migration: yearly regularisation tranches by skill and tenure, fixed-term contracts for cyclical roles, and automation for the truly commodity tasks." },
      { label: "Move 4", text: "Manage both constituencies: permanent workers' union will claim credit; contractors' hopes must be managed against a real, published pathway." },
      { label: "Close", text: "A 3-year glide to 30% contract share in non-core roles, costed against quality gains and dispute risk avoided." },
    ],
    pitfalls: [
      "Treating this purely as a labour-cost arbitrage to defend.",
      "Overnight regularisation that the wage bill cannot carry.",
      "Ignoring the quality and safety cost of perpetual churn.",
    ],
  },
  {
    slug: "cxo-succession-emergency",
    shape: "case",
    title: "The CFO of a listed firm resigned with 30 days' notice and no ready successor. Manage it.",
    type: "Succession management",
    difficulty: 3,
    minutes: 28,
    answer: "Stabilise, then search: appoint a credible interim (controller or deputy) with explicit scope, communicate to the street before rumours price it in, run a parallel internal-external search properly rather than panic-hiring, and fix the pipeline failure that made this an emergency.",
    hints: ["Three clocks run at once: markets, the search, and the team's stability."],
    moves: [
      { label: "Move 1", text: "First 48 hours: agree the narrative, inform the board and audit committee, disclose as required, and announce the interim in the same breath as the exit." },
      { label: "Move 2", text: "Stabilise the function: the interim gets clear authority, banker and auditor introductions, and visible board backing; the finance team hears a retention message early." },
      { label: "Move 3", text: "Run the real search: internal candidates assessed honestly against an external slate; a rushed external hire misfires at the worst level." },
      { label: "Move 4", text: "Bridge the risk window: audit season, covenant discussions or fundraising during the gap get extra board-level oversight." },
      { label: "Close", text: "After landing the successor, run the post-mortem: why was there no ready-now name, and which other seats share that exposure today?" },
    ],
    pitfalls: [
      "Leaving the interim question open while the street speculates.",
      "Panic-hiring externally in six weeks for a two-decade-consequence seat.",
      "Fixing the vacancy but not the pipeline failure behind it.",
    ],
  },
  {
    slug: "hybrid-policy-design-conflict",
    shape: "case",
    title: "Leadership wants five days in office; employees expect flexibility. Design the policy.",
    type: "Policy design",
    difficulty: 2,
    minutes: 25,
    answer: "Anchor the policy in work patterns, not preferences: which work genuinely needs co-presence, which does not, and what the talent market charges for rigidity. A team-level anchor-days model with firm-wide core norms usually beats both extremes, priced openly against its attrition consequences.",
    hints: ["Neither side's preference is the design input; the work and the market are."],
    moves: [
      { label: "Move 1", text: "Segment the work: collaborative design and mentoring benefit from co-presence; production coding and analysis mostly do not. Build the policy on this map." },
      { label: "Move 2", text: "Price the options: model attrition risk of full mandates (the exposed, marketable cohort) against the collaboration and culture costs claimed for remote." },
      { label: "Move 3", text: "Design the middle: 2 to 3 team-anchor days set by team leads within firm guardrails, plus quarterly full-presence weeks for the co-presence work." },
      { label: "Move 4", text: "Make office days worth it: if people commute to sit on video calls, the mandate discredits itself; redesign office days around the collaborative work." },
      { label: "Close", text: "Commit to a 2-quarter review against measured outcomes (attrition, hiring acceptance rates, delivery metrics), not against anecdotes." },
    ],
    pitfalls: [
      "Policy by leadership nostalgia or by employee survey alone.",
      "Mandating presence and then filling office days with video calls.",
      "Ignoring what rigidity does to offer-acceptance rates in hiring.",
    ],
  },
  {
    slug: "comp-benchmarking-startup-correction",
    shape: "case",
    title: "A scaling startup discovers it pays 30% below market for engineers. Fix pay without breaking the budget.",
    type: "Compensation strategy",
    difficulty: 2,
    minutes: 25,
    answer: "Correct surgically: match market for the critical and flight-risk cohorts immediately, glide the rest over two cycles, and use equity refreshes where cash lags. An across-the-board 30% correction is unaffordable and unnecessary; unmanaged, the gap compounds into attrition that costs more.",
    hints: ["Who is actually at risk, and what is the cost of losing them versus paying them?"],
    moves: [
      { label: "Move 1", text: "Validate the benchmark: right survey, right peer set, right percentile; a wrong comparator can invent a crisis." },
      { label: "Move 2", text: "Segment exposure: critical-skill and high-performer cohorts at deep discounts are the fire; solid performers at modest gaps can glide." },
      { label: "Move 3", text: "Correct in tiers: immediate repositioning for the fire (perhaps 20% of people, half the total cost), 2-cycle glide for the rest, equity refresh as the cash bridge." },
      { label: "Move 4", text: "Fix the machinery: annual benchmarking, offer-band discipline and a comp philosophy statement so the drift never rebuilds." },
      { label: "Close", text: "Present the tiered plan against the do-nothing cost: replacement of the at-risk cohort alone usually exceeds the correction budget." },
    ],
    pitfalls: [
      "Across-the-board corrections that spend the budget on the safe middle.",
      "Benchmarking against the wrong peer set or percentile.",
      "Fixing pay once with no machinery to stop the next drift.",
    ],
  },
  {
    slug: "manager-quality-span-problem",
    shape: "case",
    title: "Survey data shows manager quality is the top attrition driver. Build the fix.",
    type: "Capability building",
    difficulty: 2,
    minutes: 25,
    answer: "Treat managing as a skilled role, not a seniority prize: fix who becomes a manager (selection), what they carry (spans, dual tracks for senior ICs), how they learn (practice-based programs), and what happens to chronically poor ones (coaching, then role change). Training alone changes little.",
    hints: ["Four levers: selection, structure, development, consequence. Most firms pull only the third."],
    moves: [
      { label: "Move 1", text: "Quantify the spread: attrition, engagement and performance by manager; the bottom quintile of managers usually drives a third of regretted exits." },
      { label: "Move 2", text: "Fix selection: stop promoting the best coder into management by default; build a respected senior-IC track so management is a choice, not the only raise." },
      { label: "Move 3", text: "Fix structure: spans above 10 to 12 make coaching impossible; rebalance before blaming individuals." },
      { label: "Move 4", text: "Develop and act: practice-heavy first-time-manager programs, manager scorecards visible to their leaders, and genuine consequence paths for the chronic bottom." },
      { label: "Close", text: "Track the bottom-quintile managers' team metrics over two quarters; movement there, not training attendance, is the success measure." },
    ],
    pitfalls: [
      "Running training while selection keeps minting reluctant managers.",
      "Ignoring spans and structure as manager-quality inputs.",
      "Scorecards without consequences for the persistent bottom.",
    ],
  },
  {
    slug: "wellness-program-roi-question",
    shape: "case",
    title: "The CFO wants proof the 8-crore wellness program works or it gets cut. Respond.",
    type: "Program evaluation",
    difficulty: 2,
    minutes: 22,
    answer: "Concede the measurement honestly: most wellness spend cannot show hard ROI, and yoga-app engagement is not an outcome. Re-anchor the program on measurable levers (insurance claims trends, absence, high-risk cohort screening) and cut the decorative spend yourself before proposing what remains.",
    hints: ["Defend outcomes, not activities; cut before being cut."],
    moves: [
      { label: "Move 1", text: "Audit the 8 crore: split into medical-adjacent (screenings, insurance-linked, EAP) and engagement-decorative (apps, events, merchandise)." },
      { label: "Move 2", text: "Find measurable lines: claims-cost trend for screened cohorts, absence days, EAP utilisation against attrition in using groups." },
      { label: "Move 3", text: "Cut the theatre: the step-challenge merchandise and unused app licences go; credibility with the CFO is bought with your own scissors." },
      { label: "Move 4", text: "Restructure what stays: preventive screening tied to insurance pricing, mental-health capacity where utilisation shows need, ergonomic and shift-design fixes that touch actual health." },
      { label: "Close", text: "Return with a 5-crore program, each line owning a metric, and a claims-trend report due in 12 months." },
    ],
    pitfalls: [
      "Defending the full spend with engagement statistics.",
      "Claiming ROI precision that wellness evidence cannot support.",
      "Cutting the medically useful lines with the decorative ones.",
    ],
  },
  {
    slug: "early-career-women-dropoff",
    shape: "case",
    title: "Women are 45% of entry level but 12% of senior management. Fix the pipeline.",
    type: "Diversity strategy",
    difficulty: 3,
    minutes: 28,
    answer: "Find the specific leak points rather than running generic programs: cohort data usually shows the drop concentrating at the manager promotion gate and the return-from-maternity years. Fix those two transitions with promotion-process audits, real flexibility, returner ramps and sponsorship, then hold leaders accountable for cohort flow.",
    hints: ["The funnel leaks at specific gates. Which promotion or life stage?"],
    moves: [
      { label: "Move 1", text: "Cohort the data: retention and promotion rates by gender at each level transition; find where the ratios diverge." },
      { label: "Move 2", text: "Diagnose the gates: promotion-rate gaps point at evaluation bias or sponsorship gaps; post-maternity attrition points at inflexibility and stalled roles on return." },
      { label: "Move 3", text: "Fix transitions: structured returner programs with ramp-back periods and protected ratings, promotion-slate audits (was the slate itself skewed?), and sponsorship pairing for the pre-manager cohort." },
      { label: "Move 4", text: "Make it owned: leader scorecards on cohort flow-through, not just headline percentages that mask the gates." },
      { label: "Close", text: "Target the two worst transition ratios for 2x improvement in three years; the senior number follows the gates arithmetically." },
    ],
    pitfalls: [
      "Celebrating entry-level parity while the manager gate leaks.",
      "Generic sensitisation training instead of gate-specific fixes.",
      "Tracking the headline percentage instead of transition ratios.",
    ],
  },
  {
    slug: "gig-workforce-benefits-design",
    shape: "case",
    title: "A delivery platform faces regulation requiring gig-worker benefits. Design the response.",
    type: "Workforce strategy",
    difficulty: 3,
    minutes: 28,
    answer: "Get ahead of the mandate rather than litigating behind it: build a portable benefits stack (accident cover, health top-ups, contribution-matched savings) sized to engagement hours, priced into unit economics transparently, and positioned as a supply-side moat since worker preference is the scarce asset.",
    hints: ["Benefits cost becomes a competitive weapon if your rivals lag on it."],
    moves: [
      { label: "Move 1", text: "Size the exposure: benefits at 3 to 5% of payouts across the active fleet, modelled against the social-security code's contribution formulas." },
      { label: "Move 2", text: "Design portable and pro-rata: benefits accrue by hours or earnings across platforms, aligned with how the regulation frames aggregator contributions." },
      { label: "Move 3", text: "Prioritise what workers value: accident insurance and hospital cash beat pension promises in worker surveys; sequence spending by valued-per-rupee." },
      { label: "Move 4", text: "Play offence: guaranteed-benefit tiers for high-engagement riders improve retention and reliability, converting a compliance cost into supply quality." },
      { label: "Close", text: "Pilot in two states ahead of enforcement, publish the outcomes, and shape the regulatory conversation from the front foot." },
    ],
    pitfalls: [
      "Treating it purely as a legal fight and losing the worker-preference war.",
      "Flat benefits ignoring the casual-versus-committed engagement spread.",
      "Designing for compliance optics rather than what workers actually value.",
    ],
  },
  {
    slug: "training-transfer-failure",
    shape: "case",
    title: "Sales training scores 4.6/5 but sales behaviour hasn't changed. Diagnose the transfer failure.",
    type: "Program evaluation",
    difficulty: 2,
    minutes: 22,
    answer: "Happy-sheet scores measure the event, not behaviour. Transfer fails in the field: managers don't reinforce, incentives contradict the taught behaviour, and there's no practice loop. Redesign around field application: manager-led reinforcement, incentive alignment, and measurement at the behaviour level.",
    hints: ["What happens in the two weeks after the workshop decides everything."],
    moves: [
      { label: "Move 1", text: "Reframe measurement: move from reaction scores to behaviour markers (call quality audits, funnel conversion at the taught stage) and results." },
      { label: "Move 2", text: "Audit the field context: do managers coach the new method, or do month-end pressures push everyone back to old habits? Does the incentive plan reward the very behaviour training tried to remove?" },
      { label: "Move 3", text: "Rebuild the design: shorter workshops, field assignments between sessions, manager-run practice huddles, and refreshers timed to the forgetting curve." },
      { label: "Move 4", text: "Align the system: tweak the incentive metric or scorecard so the taught behaviour pays; misaligned incentives beat any curriculum." },
      { label: "Close", text: "Re-measure in 90 days at the behaviour level on a pilot region against a control region; scale only what moves the field metric." },
    ],
    pitfalls: [
      "Reporting satisfaction scores as program success.",
      "Training reps while their incentive plan rewards the old behaviour.",
      "No manager involvement in the fortnight after the workshop.",
    ],
  },
  {
    slug: "dual-career-ladder-tech",
    shape: "case",
    title: "Senior engineers keep leaving because growth means becoming managers. Build the alternative.",
    type: "Career architecture",
    difficulty: 2,
    minutes: 25,
    answer: "Build a real individual-contributor ladder: parallel levels to management with equivalent pay bands, genuine seniority signals (architecture ownership, org-wide influence), and visible occupants. The ladder fails if IC levels pay less, carry no authority, or exist on paper only.",
    hints: ["The test of a dual ladder: does anyone senior actually stand on it?"],
    moves: [
      { label: "Move 1", text: "Evidence the leak: exit data for senior engineers citing growth, and the current reality that all levels above X are managerial." },
      { label: "Move 2", text: "Design parallel levels: staff, principal and distinguished engineer grades with pay bands matching manager grades at each rung." },
      { label: "Move 3", text: "Give the rungs substance: architecture decision rights, cross-team technical authority, hiring-bar ownership; not just a title and a talk slot." },
      { label: "Move 4", text: "Seed and signal: promote two or three respected engineers into the new levels immediately, visibly, with the CTO narrating why." },
      { label: "Close", text: "Success metric: senior-engineer regretted attrition and the share of engineers who see a non-manager future internally, survey-tracked yearly." },
    ],
    pitfalls: [
      "IC levels that pay a grade below their manager equivalents.",
      "Titles without decision rights, which engineers detect instantly.",
      "Launching the ladder with zero occupants.",
    ],
  },
  {
    slug: "hr-business-partner-model-broken",
    shape: "case",
    title: "Business heads call HR 'admin with meetings'. Redesign the HRBP model.",
    type: "Function design",
    difficulty: 2,
    minutes: 25,
    answer: "The model breaks when HRBPs carry transactional load and lack business fluency. Move transactions to shared services and self-serve aggressively, staff BP roles with people who can read a P&L and an attrition model, and contract explicitly with each business head on the two or three people problems that matter this year.",
    hints: ["What do BPs actually spend hours on? The timesheet answers the insult."],
    moves: [
      { label: "Move 1", text: "Audit the reality: time-log a month of BP work; typically 60%+ is transactional (letters, queries, payroll chasing) that belongs in shared services." },
      { label: "Move 2", text: "Fix the plumbing first: portal, chatbot and shared-services migration to strip transactions out of BP calendars." },
      { label: "Move 3", text: "Upgrade the role: business-literate BPs (some hired from the business), each owning explicit priorities agreed with their business head, with analytics support behind them." },
      { label: "Move 4", text: "Contract and cadence: a quarterly people-plan review per business on attrition, capability and org design, with metrics the business head actually tracks." },
      { label: "Close", text: "Re-survey business heads in two quarters on one question: does HR help you make better people decisions? That score is the model's KPI." },
    ],
    pitfalls: [
      "Retitling the same people without removing the transactional load.",
      "BPs who cannot speak the business's numbers.",
      "Serving HR's calendar (cycles, audits) instead of the business's problems.",
    ],
  },
  {
    slug: "night-shift-women-safety-compliance",
    shape: "case",
    title: "A BPO expands night operations for women employees. Design safety and compliance.",
    type: "Policy design",
    difficulty: 2,
    minutes: 22,
    answer: "Go beyond the legal floor: state rules require transport, security and consent; the operational design is door-to-door tracked cabs with escorts, verified drivers, route protocols, control-room monitoring and a genuine opt-in. The reputational stake makes over-compliance the rational standard.",
    hints: ["Compliance is the floor; one incident defines the company for years."],
    moves: [
      { label: "Move 1", text: "Map obligations: state shops-and-establishments night-shift conditions for women: consent, transport, security, often meal and rest provisions." },
      { label: "Move 2", text: "Design transport: door-to-door pickup and drop, women not first-pickup or last-drop alone, security escort on late routes, GPS-tracked vehicles, driver verification and rotation records." },
      { label: "Move 3", text: "Build response: a 24x7 control room tracking trips, escalation SLAs, an SOS app channel, and periodic drills that keep it real." },
      { label: "Move 4", text: "Keep consent honest: opt-in without career penalty, monitored via shift-allocation and promotion data of night versus day cohorts." },
      { label: "Close", text: "Audit quarterly with actual trip data and near-miss reviews; publish internal compliance scores so the standard survives management churn." },
    ],
    pitfalls: [
      "Treating consent as a signed form rather than a penalty-free choice.",
      "Security theatre without route-level operational detail.",
      "Letting standards decay after the first incident-free year.",
    ],
  },
  {
    slug: "performance-improvement-plan-ethics",
    shape: "case",
    title: "Managers use PIPs as exit paperwork. Rebuild the improvement process credibly.",
    type: "Performance management",
    difficulty: 2,
    minutes: 22,
    answer: "A PIP that never rescues anyone is a legal document, not a process, and everyone knows it. Split the paths honestly: a genuine improvement track with real support and a fair pass rate, and a separate, dignified managed-exit conversation where the decision is already made. Pretending one is the other corrodes trust and invites litigation.",
    hints: ["What fraction of PIPs end in success? That number is the diagnosis."],
    moves: [
      { label: "Move 1", text: "Measure the truth: if 90%+ of PIPs end in exit, the instrument is mislabelled; managers decided first and documented after." },
      { label: "Move 2", text: "Rebuild the genuine track: specific gaps, real support (coaching, training, workload reset), 60 to 90 days, and a reviewer independent of the initiating manager." },
      { label: "Move 3", text: "Create the honest alternative: where fit is truly gone, a respectful separation conversation with fair terms beats a theatrical PIP for both sides." },
      { label: "Move 4", text: "Fix upstream: most PIP cases are years of unaddressed feedback; manager courage in regular conversations is the real prevention." },
      { label: "Close", text: "Track PIP success rate and post-PIP performance; a healthy process rescues a third or more, and that number belongs on HR's own scorecard." },
    ],
    pitfalls: [
      "Using improvement language for a decision already taken.",
      "PIP goals designed to be unachievable, which courts read accurately.",
      "Ignoring the years of missing feedback that precede most PIPs.",
    ],
  },
  {
    slug: "employer-brand-glassdoor-crisis",
    shape: "case",
    title: "Ratings on job sites crashed after a badly-handled layoff. Rebuild the employer brand.",
    type: "Employer branding",
    difficulty: 2,
    minutes: 22,
    answer: "You cannot PR your way out; the reviews describe something real. Fix the underlying grievances (severance disputes, manager behaviour), let current employees speak voluntarily, respond to reviews with specifics and humility, and accept a 12 to 18 month recovery measured in offer-acceptance rates, not stars.",
    hints: ["The reviews are data before they are a PR problem."],
    moves: [
      { label: "Move 1", text: "Mine the reviews: theme the complaints; layoff execution, manager conduct and broken promises usually lead. Verify internally which are true." },
      { label: "Move 2", text: "Fix the real things: settle severance disputes, act on the named-pattern manager complaints, and honour whatever promises were broken where possible." },
      { label: "Move 3", text: "Respond credibly: official replies that acknowledge specifics and state changes made; never incentivised review-stuffing, which platforms and candidates both detect." },
      { label: "Move 4", text: "Rebuild through evidence: real employee stories, transparent salary bands in postings, and candidate-experience fixes that generate their own positive signal." },
      { label: "Close", text: "Track offer-acceptance rate and quality-of-applicant metrics quarterly; stars lag reality by quarters and are the vanity metric here." },
    ],
    pitfalls: [
      "Coordinated positive-review campaigns that backfire on discovery.",
      "Treating symptoms in comms while severance disputes stay open.",
      "Managing the rating instead of the offer-acceptance rate.",
    ],
  },
  {
    slug: "acqui-hire-retention-cliff",
    shape: "case",
    title: "An acqui-hired team's retention bonuses vest next month; half may leave. Act.",
    type: "Retention strategy",
    difficulty: 2,
    minutes: 22,
    answer: "The cliff was designed badly; now buy time with meaning, not just money. Triage the truly critical people, offer forward-loaded refreshes paired with role upgrades they actually want, accept some departures gracefully, and capture knowledge fast where exits look certain.",
    hints: ["A month out, money alone re-rents people; roles retain them."],
    moves: [
      { label: "Move 1", text: "Triage: of the 20, perhaps 6 are irreplaceable this year. Name them and focus; blanket panic offers reward everyone for the cliff." },
      { label: "Move 2", text: "Diagnose intent: skip-level conversations this week; leaving-for-what matters (startup itch versus manager friction versus pure vesting logic)." },
      { label: "Move 3", text: "Make paired offers: refresh grants vesting quarterly (no new cliff) tied to role enlargements (own the next product line) for the critical six." },
      { label: "Move 4", text: "De-risk regardless: documentation sprints, pairing critical-system knowledge, and succession shadows for the likely leavers." },
      { label: "Close", text: "Whatever retains, fix the template: future deals vest monthly after year one, with role integration planned at signing, so cliffs stop manufacturing crises." },
    ],
    pitfalls: [
      "Blanket retention offers a month before vesting, which reprice loyalty for everyone.",
      "Money-only counters for people leaving over meaning.",
      "No knowledge capture from the probable leavers.",
    ],
  },
  {
    slug: "festival-season-absenteeism-plant",
    shape: "case",
    title: "A plant loses 25% of workers for 3 weeks around harvest and festivals yearly. Plan for it.",
    type: "Workforce planning",
    difficulty: 2,
    minutes: 22,
    answer: "Stop fighting a cultural certainty; plan around it. Stagger leave with incentives, build a trained seasonal buffer, schedule maintenance into the trough, and co-design the calendar with the union. Plants that fight festival absence lose both output and trust; plants that plan it lose neither.",
    hints: ["This absence is predictable to the week. Predictable problems get planned, not punished."],
    moves: [
      { label: "Move 1", text: "Map the pattern: absence by week, by department, by home region; migration-heavy sections spike hardest and most predictably." },
      { label: "Move 2", text: "Shape it: staggered leave windows with attendance incentives for off-peak slots, and travel-aligned shift swaps agreed with worker committees." },
      { label: "Move 3", text: "Buffer it: a pre-trained seasonal pool (retirees, certified contractors) for the low-skill positions, cross-training so critical stations always have cover." },
      { label: "Move 4", text: "Use the trough: schedule annual maintenance, deep cleaning and training into the low-attendance weeks, converting lost production time into required downtime." },
      { label: "Close", text: "Measure output per planning cycle rather than attendance: the goal is hitting the monthly plan around the absence, not defeating the absence." },
    ],
    pitfalls: [
      "Punitive attendance policies that trade trust for nothing.",
      "Discovering the same absence spike fresh every year.",
      "Buffer hires who first touch the machine during the crisis week.",
    ],
  },
  {
    slug: "whistleblower-senior-leader",
    shape: "case",
    title: "An anonymous complaint accuses a star business head of expense fraud and bullying. Handle it.",
    type: "Ethics and investigation",
    difficulty: 3,
    minutes: 28,
    answer: "Investigate exactly as you would for a junior employee: independent inquiry, evidence preservation, interim safeguards for the team, and a decision that follows findings regardless of the leader's revenue. Star-shielding is how one case becomes a culture and later a scandal.",
    hints: ["The test of an ethics program is what it does when the accused is valuable."],
    moves: [
      { label: "Move 1", text: "Secure the process: log the complaint formally, preserve expense records and communications before word spreads, and involve legal plus the audit committee for a senior-level accusation." },
      { label: "Move 2", text: "Choose independent investigators: internal audit for the expenses, an external firm for the conduct allegations; nobody in the leader's chain runs it." },
      { label: "Move 3", text: "Protect people during: no retaliation watch on the suspected complainant pool, interim reporting-line changes if intimidation risk is real, confidentiality discipline." },
      { label: "Move 4", text: "Decide on findings: substantiated fraud has one answer irrespective of quota performance; partial findings get proportionate, documented consequences applied as they would be at any level." },
      { label: "Close", text: "Close the loop: sanitised communication that the process ran and concluded, because silence teaches everyone that reporting is pointless." },
    ],
    pitfalls: [
      "A quiet chat instead of an investigation because revenue is at stake.",
      "Letting the accused's chain of command run the inquiry.",
      "Substantiating the findings and then negotiating the consequence away.",
    ],
  },
  {
    slug: "two-hr-systems-merger",
    shape: "case",
    title: "Post-merger, two firms run different payrolls, grades and policies. Sequence the harmonisation.",
    type: "M&A integration",
    difficulty: 3,
    minutes: 28,
    answer: "Sequence by risk and emotion: payroll accuracy first (day-one continuity), statutory compliance immediately, then grades and pay ranges within a year, and culture-touching policies (leave, titles, benefits) last with generous grandfathering. Big-bang harmonisation optimises tidiness at the price of trust.",
    hints: ["Order by what breaks versus what bruises: payroll breaks, titles bruise."],
    moves: [
      { label: "Move 1", text: "Day one: everyone gets paid correctly on their existing terms; nothing else matters if this fails. Freeze structural changes for 90 days and say so." },
      { label: "Move 2", text: "Quarter one: statutory alignment (PF trusts, gratuity, insurance continuity) and a policy-difference inventory with cost deltas." },
      { label: "Move 3", text: "Year one: grade mapping via job evaluation, not title vanity; pay-range harmonisation with red-circling (no one cut, frozen till the band catches up)." },
      { label: "Move 4", text: "Year two: benefits and leave harmonisation, choosing the better-of positions where affordable, grandfathering where not; title changes land with the new grade structure." },
      { label: "Close", text: "Publish the sequence openly at the start; uncertainty about when harmonisation hits is more corrosive than any single change in it." },
    ],
    pitfalls: [
      "Harmonising titles and leave in month one while payroll wobbles.",
      "Levelling pay down anywhere, which poisons the whole integration.",
      "Keeping the sequence secret and letting rumour set expectations.",
    ],
  },
  {
    slug: "campus-batch-deferral-decision",
    shape: "case",
    title: "A downturn hits after 2,000 campus offers were made. Joining is 6 months away. Decide.",
    type: "Workforce planning",
    difficulty: 3,
    minutes: 28,
    answer: "Honour the commitment in structure even if timing flexes: rescinding torches a decade of campus trust. Options ladder: absorb with slowed lateral hiring, stagger joining in tranches with stipends, offer paid deferrals with skilling, and only then voluntary opt-outs with compensation. Communicate early and specifically; silence is what campuses remember.",
    hints: ["Price the rescission not in severance but in ten years of placement-cell memory."],
    moves: [
      { label: "Move 1", text: "Size the true gap: revised demand versus 2,000 joiners; often absorbing 60 to 70% is feasible with lateral freezes and attrition backfill redirection." },
      { label: "Move 2", text: "Build the ladder: tranche joining across 3 quarters with monthly stipends for the waiting; optional 12-month skill-deferral with certification support; opt-out packages for those with alternatives." },
      { label: "Move 3", text: "Communicate first and honestly: students and placement cells hear the plan, the dates and the stipend from you before rumours; ambiguity destroys more trust than delay." },
      { label: "Move 4", text: "Protect the relationship: keep deferred joiners warm with mentors, projects and campus visits; they are next year's ambassadors either way." },
      { label: "Close", text: "Whatever the mix, publish and honour a final-joining outer date; an open-ended deferral is a rescission in slow motion." },
    ],
    pitfalls: [
      "Rescinding to save one year's cost and losing tier-1 campus access for five.",
      "Silent deferrals communicated through joining-date emails alone.",
      "Open-ended waits with no stipend, which convert quietly into rescissions.",
    ],
  },
  {
    slug: "hr-chatbot-replaces-queries",
    shape: "case",
    title: "Leadership wants AI to cut the 40-person HR helpdesk in half. Assess and plan.",
    type: "HR technology",
    difficulty: 2,
    minutes: 25,
    answer: "Feasible for the transactional half of tickets, but sequence it honestly: measure the deflectable share, deploy the assistant on knowledge and status queries first, keep humans on judgement and distress cases, and redeploy rather than fire where possible since the same people carry process knowledge the bot needs.",
    hints: ["Which tickets are lookups, and which are judgement or distress? Split before promising."],
    moves: [
      { label: "Move 1", text: "Audit the ticket mix: typically 50 to 60% are policy lookups and status checks (deflectable), 25% transactions needing system integration, 15% judgement, exceptions and sensitive matters (not deflectable)." },
      { label: "Move 2", text: "Deploy in layers: knowledge answers with citations first, then integrated transactions (letters, leave fixes), with confident handoff to humans on frustration or sensitive keywords." },
      { label: "Move 3", text: "Protect the human lane: payroll distress, grievances, medical and exit conversations route to people by design, not after bot failure." },
      { label: "Move 4", text: "Handle the 20 people affected: redeploy into the judgement tier, content curation and BP support roles; their process knowledge is the bot's training corpus." },
      { label: "Close", text: "Commit to service metrics, not headcount metrics: resolution time and satisfaction must improve or the halving claim was the wrong goal." },
    ],
    pitfalls: [
      "Promising a headcount number before measuring the deflectable share.",
      "Routing distressed employees to a bot that answers with policy citations.",
      "Discarding the people whose knowledge the automation runs on.",
    ],
  },
  {
    slug: "salary-transparency-law-prep",
    shape: "case",
    title: "Pay-range disclosure in job postings becomes mandatory. Prepare the company.",
    type: "Compensation strategy",
    difficulty: 2,
    minutes: 25,
    answer: "The posting is the trivial part; the exposure is internal: current employees will compare their pay to advertised ranges. Audit and fix internal compression and inequities before the law bites, tighten band governance, and train managers for the conversations that follow the first transparent posting.",
    hints: ["Who reads your posted ranges most attentively? Your own employees."],
    moves: [
      { label: "Move 1", text: "Model the exposure: overlay current employee pay on the ranges you would post; every incumbent below the advertised minimum for their own role is a conversation waiting." },
      { label: "Move 2", text: "Fix before disclosing: correct the worst compression cases (often tenured staff under new-hire rates) in the cycles before enforcement; the law's date is your deadline." },
      { label: "Move 3", text: "Govern the bands: honest, defensible ranges rather than 40-lakh-wide postings that comply in letter and signal chaos." },
      { label: "Move 4", text: "Equip managers: scripts and authority for pay conversations, plus a comp philosophy document that explains how placement in range works." },
      { label: "Close", text: "Treat it as a forcing function: firms that used the runway for equity fixes report the transition as a non-event; firms that didn't meet it in employee-relations firefighting." },
    ],
    pitfalls: [
      "Treating it as a job-portal formatting task.",
      "Posting ranges so wide they advertise evasion.",
      "Leaving known compression cases to be discovered by the postings.",
    ],
  },
  {
    slug: "leadership-team-conflict-cofounders",
    shape: "case",
    title: "Two co-founders' public disagreements are splitting the company into camps. Intervene as CHRO.",
    type: "Leadership dynamics",
    difficulty: 3,
    minutes: 28,
    answer: "This is a governance problem wearing an HR costume: name it to the founders directly with evidence of organisational cost, broker explicit decision-rights (who owns what, disagreement protocol), involve the board if brokering fails, and protect the executives below from proxy warfare meanwhile.",
    hints: ["You cannot mediate values, but you can contract decision rights."],
    moves: [
      { label: "Move 1", text: "Document the cost: decisions reversed, executives triangulated, attrition in the crossfire, and camp formation in survey and exit data. Facts make the conversation possible." },
      { label: "Move 2", text: "Confront privately: each founder separately, then together, with the evidence and a simple frame: the company is paying for this in named ways." },
      { label: "Move 3", text: "Contract the mechanics: domain ownership split, a disagreement protocol (argue privately, one voice publicly), and a tie-breaker (board or agreed metric)." },
      { label: "Move 4", text: "Shield the organisation: stop proxy escalations by routing cross-domain decisions through the agreed protocol, and coach the executives caught between." },
      { label: "Close", text: "If the contract breaks repeatedly, escalate to the board honestly; a CHRO who manages around founder dysfunction indefinitely becomes its enabler." },
    ],
    pitfalls: [
      "Message-carrying between founders, which institutionalises the split.",
      "Team-building offsites for what is a decision-rights vacuum.",
      "Waiting for it to resolve while the executive layer quietly exits.",
    ],
  },
  {
    slug: "variable-pay-cut-communication",
    shape: "case",
    title: "A bad year means zero bonus for the first time in a decade. Design the communication.",
    type: "Communication strategy",
    difficulty: 2,
    minutes: 22,
    answer: "Say it early, plainly and consistently: the number, the business reason with real financials, what leadership is taking (their cut should be deeper and stated), and what would make next year different. The damage comes not from the zero but from spin, surprise timing, or leadership exemption.",
    hints: ["People forgive a bad year; they do not forgive discovering it in their bank statement."],
    moves: [
      { label: "Move 1", text: "Sequence: leaders and managers briefed first with a Q&A pack, then all-hands announcement, then manager-led team conversations within 48 hours." },
      { label: "Move 2", text: "Show the math: the profit shortfall, what the bonus pool formula produced, and confirmation that the same formula paid out in good years; consistency is the credibility." },
      { label: "Move 3", text: "Leadership takes more, visibly: executive bonuses zeroed and a salary measure at the top, stated plainly; the fastest way to lose the room is a leadership carve-out leaking later." },
      { label: "Move 4", text: "Give the path back: the specific numbers that restore payouts, tracked quarterly in town halls, converting resentment into a shared target." },
      { label: "Close", text: "Watch the aftermath: top-performer flight risk spikes now; pair the message with targeted retention for the people the recovery needs." },
    ],
    pitfalls: [
      "Letting payslips deliver the news.",
      "Corporate euphemism where a number and a reason were needed.",
      "Executive payouts surviving the year the staff's went to zero.",
    ],
  },
  {
    slug: "skills-taxonomy-overhaul",
    shape: "case",
    title: "The CEO wants a skills-based organisation. Translate the buzzword into a program.",
    type: "Capability building",
    difficulty: 3,
    minutes: 28,
    answer: "Start from decisions, not taxonomy: pick the two or three talent decisions that skills data would change (staffing, hiring screens, learning spend), build a minimal skills model for the few job families where those decisions bite, prove value, then expand. Enterprise-wide taxonomies built first die in spreadsheets.",
    hints: ["Which decision, made differently, would justify this program? Start there."],
    moves: [
      { label: "Move 1", text: "Anchor on use cases: internal project staffing in tech, capability-gap-driven L&D budgets, and degree-free hiring screens are the usual three with real money attached." },
      { label: "Move 2", text: "Scope minimally: 3 job families, 20 to 30 skills each, proficiency defined behaviourally; resist the 5,000-skill ontology." },
      { label: "Move 3", text: "Get honest data: self-rating alone inflates; blend manager validation, assessment for critical skills, and inference from work artefacts." },
      { label: "Move 4", text: "Wire it to the decisions: staffing tools read the profiles, learning budget follows measured gaps, job posts drop degree proxies where skills evidence exists." },
      { label: "Close", text: "Report the decision-level wins (fill time, redeployment, hiring funnel width) after two quarters, and only then argue for expansion." },
    ],
    pitfalls: [
      "Building the full taxonomy before any decision uses it.",
      "Self-declared skills data driving real staffing calls.",
      "A vendor platform purchase substituting for the use-case design.",
    ],
  },
  {
    slug: "long-tenure-stagnation-pocket",
    shape: "case",
    title: "A profitable division has 15-year average tenure, no attrition, and flat performance. Is this a problem?",
    type: "Organisational health",
    difficulty: 2,
    minutes: 22,
    answer: "Zero attrition is a symptom worth investigating, not a triumph: check whether stability reflects mastery or comfort. If pay sits above market with skills below it, the division is fragile to change. The move is gentle circulation (rotations in and out), skill refresh, and succession depth, not manufactured attrition.",
    hints: ["Would these skills be hired today at this pay? That question splits mastery from stagnation."],
    moves: [
      { label: "Move 1", text: "Test the health: skill currency against market, internal mobility rates, age and succession profile, and how the division absorbs new tools or process changes." },
      { label: "Move 2", text: "Diagnose the lock-in: above-market pay for location-specific roles plus obsolete-elsewhere skills equals golden handcuffs; nobody leaves because nobody can." },
      { label: "Move 3", text: "Circulate deliberately: two-way rotations with other divisions, new-blood hiring into a few seats yearly, and stretch mandates for the strongest tenured people." },
      { label: "Move 4", text: "Refresh capability: skill investment tied to the division's next 5-year technology reality, before the change arrives as a crisis." },
      { label: "Close", text: "Track leading indicators (skill currency, succession cover, change-absorption speed) rather than celebrating the lagging zero in attrition." },
    ],
    pitfalls: [
      "Reading zero attrition as pure health.",
      "Shock therapy (forced exits) on a functioning profitable unit.",
      "Ignoring succession: fifteen-year tenures retire in clusters.",
    ],
  },
  {
    slug: "medical-leave-abuse-suspicion",
    shape: "case",
    title: "Sick leave in one department runs 3x the company average. Managers allege abuse. Proceed.",
    type: "Diagnosis",
    difficulty: 2,
    minutes: 22,
    answer: "Investigate the work before the workers: a 3x concentration is more often a symptom of that department's conditions (workload, shift design, a toxic manager, genuine occupational strain) than coordinated malingering. Audit patterns fairly, but walk the floor first; policing before diagnosis poisons whatever you find.",
    hints: ["Concentrated absence usually indicts the environment, not 40 coincidental malingerers."],
    moves: [
      { label: "Move 1", text: "Profile the absence: day-of-week patterns, certificate rates, tenure bands, and shift versus non-shift; Monday-heavy uncertified absence reads differently from scattered certified leave." },
      { label: "Move 2", text: "Study the department: workload trend, overtime, injury and ergonomic data, engagement scores, manager 360 feedback, and what changed when the spike began." },
      { label: "Move 3", text: "Listen safely: skip-levels and anonymous channels; burnt-out or bullied teams take refuge in sick leave before they resign." },
      { label: "Move 4", text: "Act on findings: fix the workload or manager if that is the story; where individual abuse is clear, apply policy consistently and privately." },
      { label: "Close", text: "Recheck in two quarters: if absence normalises after environmental fixes, the diagnosis stands proven and no crackdown was needed." },
    ],
    pitfalls: [
      "Leading with certificate audits and surveillance.",
      "Treating identical numbers as identical causes across people.",
      "Fixing nothing about the department after disciplining individuals.",
    ],
  },
  {
    slug: "notice-period-length-debate",
    shape: "case",
    title: "Engineering demands 30-day notice periods; HR policy says 90. Arbitrate.",
    type: "Policy design",
    difficulty: 2,
    minutes: 22,
    answer: "Long notice is a weak retention tool and a real hiring deterrent: candidates with 90-day locks get fewer offers, and resentful leavers deliver little in months two and three. Move engineering to 60 with knowledge-transfer gates, invest in documentation and bus-factor reduction, and let retention be earned by the job, not the exit clause.",
    hints: ["What does day 61 to 90 of a resigned engineer actually produce?"],
    moves: [
      { label: "Move 1", text: "Examine the 90-day case honestly: knowledge transfer and replacement lead time are real, but measure what resigned employees contribute in month three: mostly attendance." },
      { label: "Move 2", text: "Count the hidden costs: offer dropouts citing joining time, buyout budgets, and the market signal of distrust to exactly the candidates you court." },
      { label: "Move 3", text: "Fix the dependency instead: documentation standards, pairing on critical systems and succession shadows shrink the knowledge-transfer argument structurally." },
      { label: "Move 4", text: "Land the compromise: 60 days for engineering with a transfer-checklist early-release clause, revisited after the bus-factor program matures." },
      { label: "Close", text: "Track offer-acceptance rates and post-resignation productivity before and after; the data will likely argue for going shorter still." },
    ],
    pitfalls: [
      "Using notice length as a substitute for retention.",
      "Ignoring what 90-day locks do to your own lateral hiring.",
      "Cutting notice without fixing the knowledge-dependency it papered over.",
    ],
  },
  {
    slug: "plant-accident-response-hr",
    shape: "case",
    title: "A serious accident injured two workers on the night shift. Lead HR's response.",
    type: "Crisis response",
    difficulty: 3,
    minutes: 28,
    answer: "People first, process fast, learning honest: medical response and family support without asking about fault, statutory reporting on the clock, a no-blame investigation that reaches systemic causes, and visible changes before asking anyone to trust the machine again. How this week is handled becomes the plant's safety culture.",
    hints: ["Everything you do this week teaches workers what reporting hazards is worth."],
    moves: [
      { label: "Move 1", text: "First hours: medical care fully company-borne, families contacted personally with a support owner assigned, the site secured, and statutory notifications (factory inspector, ESIC) filed within timelines." },
      { label: "Move 2", text: "Support sustained: wage continuity beyond the legal minimum, hospital logistics, counselling for the injured and the witnesses; the night crew saw it happen." },
      { label: "Move 3", text: "Investigate for causes, not culprits: guard removal, bypassed interlocks and time pressure trace upward to maintenance gaps and production pressure; punishing the operator buries the next hazard report." },
      { label: "Move 4", text: "Change visibly: the specific fixes (interlocks, procedures, staffing) announced with dates, plus a hazard-reporting channel whose reports get answered." },
      { label: "Close", text: "Review the pattern: near-miss data before the accident almost always flagged it; if reports existed and died in a file, that process failure is the deepest finding." },
    ],
    pitfalls: [
      "Legal-defensiveness with the family in week one.",
      "Root-causing to operator error and stopping there.",
      "Safety-week theatre replacing the specific engineering fixes.",
    ],
  },
  {
    slug: "referral-program-stagnant",
    shape: "case",
    title: "Referral hiring fell from 30% to 12% of hires in two years. Revive it.",
    type: "Talent acquisition",
    difficulty: 1,
    minutes: 20,
    answer: "Referral decay usually tracks employee sentiment and process friction, not bonus size. Check eNPS first (people refer where they are proud to work), then fix the funnel insults: slow responses to referred candidates, opaque status, delayed payouts. Raise the bonus last.",
    hints: ["People refer friends into places they like, through processes that respect them."],
    moves: [
      { label: "Move 1", text: "Correlate the decline: overlay referral rates with engagement scores, layoff events and hiring-bar changes; sentiment usually leads the fall." },
      { label: "Move 2", text: "Audit the experience: how fast does a referred CV get a response, can the referrer see status, how long after joining does the bonus pay? Weeks-long silence kills the second referral." },
      { label: "Move 3", text: "Rebuild mechanics: 48-hour response SLA on referrals, live status for referrers, payout at joining rather than after six months, and targeted campaigns for hard roles." },
      { label: "Move 4", text: "Work the trust: if the decline began with a badly-handled layoff, referrals return only as broad trust does; the program rides the culture, not the other way." },
      { label: "Close", text: "Measure referral submission rate per employee, not just hires; submissions show willingness, and willingness is the leading indicator." },
    ],
    pitfalls: [
      "Doubling the bonus while referred candidates wait weeks for replies.",
      "Reading referral decline as a program problem when it is a pride problem.",
      "Paying out so late the bonus feels like a rumour.",
    ],
  },
  {
    slug: "exec-compensation-esop-refresh",
    shape: "case",
    title: "The founding CTO's equity fully vested; motivation and market both worry the board. Structure a refresh.",
    type: "Compensation strategy",
    difficulty: 3,
    minutes: 26,
    answer: "Design a forward-looking package that re-ties wealth to future value creation: performance-vested refresh grants (milestone or multiple-based), sized against market for the role and dilution tolerance, with the conversation framed around the next chapter's mandate rather than retention anxiety.",
    hints: ["Time-vested refreshes rent tenure; performance-vested ones buy the next chapter."],
    moves: [
      { label: "Move 1", text: "Define the mandate first: what must the CTO build in the next 3 to 5 years? The grant is payment for that, and saying so reframes the negotiation." },
      { label: "Move 2", text: "Size against market and dilution: comparable-stage CTO refreshes, board dilution appetite, and internal equity optics with the rest of the exec team." },
      { label: "Move 3", text: "Structure for performance: a base time-vested layer for stability plus a larger tranche vesting on product, revenue or valuation milestones." },
      { label: "Move 4", text: "Mind the signals: the exec team reads this grant as precedent; pair it with a refresh framework for all senior leaders so it is policy, not exception." },
      { label: "Close", text: "Board approval with a clear rationale documented; founder-adjacent grants without governance discipline become tomorrow's proxy-advisor problem." },
    ],
    pitfalls: [
      "A pure time-vested top-up that pays for staying, not building.",
      "Negotiating one-off with no framework for the rest of the team.",
      "Ignoring how public the private math becomes inside an exec team.",
    ],
  },
  {
    slug: "probation-failure-rate-zero",
    shape: "case",
    title: "100% of hires clear probation, yet a third underperform in year one. Fix the gate.",
    type: "Performance management",
    difficulty: 1,
    minutes: 20,
    answer: "A gate everyone passes is not a gate: managers avoid the confirmation conversation because it lacks structure and support. Give probation real criteria set at offer, a 45-day check-in, an extension option that is normal rather than shameful, and HR backbone when a manager recommends non-confirmation.",
    hints: ["Zero failures at the gate plus one-third failures after it: the gate is decorative."],
    moves: [
      { label: "Move 1", text: "Diagnose the rubber stamp: confirmation forms auto-approved, no criteria beyond attendance, and managers who see the process as paperwork rather than a decision." },
      { label: "Move 2", text: "Define the bar at entry: 3 to 5 role-specific outcomes for the first 90 days, written into the offer conversation so the joiner knows the test." },
      { label: "Move 3", text: "Build the checkpoints: a structured 45-day review where problems surface while fixable, with extension (not just pass/fail) as a legitimate middle outcome." },
      { label: "Move 4", text: "Support the hard call: templated evidence requirements, HR partnership in the conversation, and fair terms for non-confirmation; managers duck what they must do alone." },
      { label: "Close", text: "A healthy gate fails or extends 5 to 10%; track that rate alongside year-one performance to prove the gate started working." },
    ],
    pitfalls: [
      "Blaming managers for avoiding a conversation the process never supported.",
      "Criteria invented in week 11 of a 12-week probation.",
      "Treating extension as failure instead of as the honest middle option.",
    ],
  },
  {
    slug: "office-relocation-workforce-impact",
    shape: "case",
    title: "The company moves offices across the city; commutes change drastically for 8,000 people. Manage it.",
    type: "Change management",
    difficulty: 2,
    minutes: 22,
    answer: "Model the commute impact person by person before announcing: the attrition risk concentrates in specific corridors and life situations. Respond with transport solutions, transition-period flexibility, relocation support for the worst-hit, and enough notice to let people re-plan lives rather than just resign.",
    hints: ["The average commute change is irrelevant; the distribution decides who quits."],
    moves: [
      { label: "Move 1", text: "Map the pain: plot employee pin codes against both sites; identify the cohort whose commute doubles and the corridor where it triples." },
      { label: "Move 2", text: "Give real notice: 6+ months lets people move homes, change schools or negotiate patterns; 6 weeks manufactures resignations." },
      { label: "Move 3", text: "Blunt the worst: shuttle routes on the pain corridors, staggered and flexible hours for long-commute cohorts, relocation allowances for movers, and hybrid weighting during transition." },
      { label: "Move 4", text: "Watch the flight risk: senior women with school-age children and specialists with rival offices near the old site are the classic first losses; talk to them individually early." },
      { label: "Close", text: "Track corridor-wise attrition for four quarters post-move against baseline; the move's true cost sits in that delta, not the rent savings deck." },
    ],
    pitfalls: [
      "Announcing with average-commute math that insults the worst-hit third.",
      "Notice periods too short to re-plan a family's logistics.",
      "Ignoring that attrition clusters by geography and life stage, not randomly.",
    ],
  },
  {
    slug: "seasonal-hiring-blue-collar-quality",
    shape: "case",
    title: "Festive temp hires damage packages and customer ratings yearly. Fix seasonal quality.",
    type: "Workforce planning",
    difficulty: 2,
    minutes: 22,
    answer: "Treat seasonality as a permanent operating pattern, not an annual surprise: build an alumni pool of returning seasonal workers with return bonuses and rating history, simplify roles for the true first-timers, front-load the training weeks before the surge, and station experienced anchors in every temp-heavy zone.",
    hints: ["The best temp worker is last year's temp worker. Do you know where yours went?"],
    moves: [
      { label: "Move 1", text: "Quantify the quality gap: damage, error and rating deltas between permanent, returning-temp and first-time-temp cohorts; the first-timer gap usually dominates." },
      { label: "Move 2", text: "Build the returning pool: contact-keeping between seasons, return bonuses, badge levels carrying pay bumps, and priority rehire for high-raters; a 50% return rate transforms the maths." },
      { label: "Move 3", text: "Redesign for novices: fool-proofed packing stations, simplified single-task roles, visual work instructions, and training cohorts that finish before the volume hits." },
      { label: "Move 4", text: "Anchor the floor: one experienced worker per 8 to 10 temps with an explicit mentor role and allowance, not just proximity." },
      { label: "Close", text: "Measure the season on quality-adjusted throughput, not bodies hired; report the returning-worker share as the program's leading indicator." },
    ],
    pitfalls: [
      "Rediscovering the training need in the surge week itself.",
      "Losing every trained temp's contact the day the season ends.",
      "Complex multi-task roles handed to day-three workers.",
    ],
  },
  {
    slug: "middle-management-layer-cut",
    shape: "case",
    title: "The board wants a management delayering: 6 layers to 4. Assess and execute.",
    type: "Organisation design",
    difficulty: 3,
    minutes: 28,
    answer: "Delayer for speed, not just cost: map decision flows first to find where layers add delay without judgement, widen spans where work is homogeneous, and handle the displaced humanely with IC roles and fair exits. Cutting layers without redesigning decision rights just makes the same bottlenecks busier.",
    hints: ["A layer earns its place by adding judgement, not by relaying messages."],
    moves: [
      { label: "Move 1", text: "Map before cutting: trace 10 real decisions through the hierarchy; layers that only aggregate reports and forward approvals name themselves." },
      { label: "Move 2", text: "Design the future spans: homogeneous, process-driven teams take spans of 12 to 15; complex creative work stays at 6 to 8. One span rule across both breaks one of them." },
      { label: "Move 3", text: "Redistribute the work: approvals delegated downward with thresholds, coordination replaced by clearer interfaces, and reporting automated rather than re-assigned." },
      { label: "Move 4", text: "Handle the people: some displaced managers become senior ICs or span-widened leaders through selection, not seniority; the rest exit with dignity and fair terms." },
      { label: "Close", text: "Measure decision velocity (proposal-to-decision days) before and after; if it didn't improve, the exercise was a headcount cut wearing a design costume." },
    ],
    pitfalls: [
      "Delayering by decree with no decision-flow analysis.",
      "Keeping displaced managers in pseudo-roles that rebuild the layer informally.",
      "Widening spans without stripping the reporting burden that filled them.",
    ],
  },
  {
    slug: "candidate-ghosting-blue-collar",
    shape: "case",
    title: "Half of selected blue-collar candidates never show up on day one. Fix joining.",
    type: "Talent acquisition",
    difficulty: 1,
    minutes: 20,
    answer: "Ghosting reflects competition and friction, not character: candidates hold multiple offers and pick late. Compress selection-to-joining time, pay a joining-day incentive, keep human contact in the gap (a call, not an SMS), and fix the frictions (documents, advances, transport) that tip last-minute decisions.",
    hints: ["Your offer competes until the minute they board someone's bus. Shorten that window."],
    moves: [
      { label: "Move 1", text: "Map the funnel timing: selection-to-joining gaps of 7 to 10 days lose half the pool; same-week joining loses far less." },
      { label: "Move 2", text: "Stay human in the gap: a named contact calls at offer, at day minus 2, and answers doubts about wages, housing and shift; silence hands them to the competing recruiter who calls." },
      { label: "Move 3", text: "Ease the frictions: document help, first-week wage advance, pickup transport on day one, and a buddy from their home region waiting." },
      { label: "Move 4", text: "Align incentives: joining bonuses paid day one (not month three), and referral-sourced candidates ghost less because a known person vouches both ways." },
      { label: "Close", text: "Track show-rate weekly by source and recruiter; the fixes are cheap and the metric moves within a month." },
    ],
    pitfalls: [
      "Reading ghosting as ingratitude instead of a competitive market.",
      "Week-long gaps between selection and joining.",
      "Bonuses that pay too late to influence the day-one decision.",
    ],
  },
  {
    slug: "psychometric-testing-validity",
    shape: "case",
    title: "The CEO wants personality tests to screen all hiring. Advise on it.",
    type: "Assessment strategy",
    difficulty: 2,
    minutes: 22,
    answer: "Push back with evidence: personality instruments predict job performance weakly and some popular ones barely at all; using them as screens invites legal risk and false negatives. Redirect the intent to validated tools: structured interviews, work samples and cognitive measures where appropriate, with personality data used for development conversations only.",
    hints: ["Ranked by validity: work samples and structured interviews beat personality types by a distance."],
    moves: [
      { label: "Move 1", text: "Ground the science: meta-analyses put work samples, structured interviews and GMA at the top for predictive validity; type-based personality tools sit near the bottom and test-retest poorly." },
      { label: "Move 2", text: "Name the risks: screening on personality invites adverse-impact challenges, coached faking, and rejection of capable candidates who answered honestly." },
      { label: "Move 3", text: "Serve the underlying need: the CEO usually wants culture fit and fewer bad hires; structured values-based interviews and job previews serve that with defensible methods." },
      { label: "Move 4", text: "Give personality its right place: development, team-working conversations and onboarding style awareness, explicitly outside selection decisions." },
      { label: "Close", text: "Propose a validation pilot: score candidates on the proposed battery, hire without using it, and correlate with performance a year later before any tool becomes a screen." },
    ],
    pitfalls: [
      "Adopting a famous instrument because a rival uses it.",
      "Letting an unvalidated score silently become a cutoff.",
      "Dismissing the CEO's intent instead of redirecting it to valid tools.",
    ],
  },
  {
    slug: "attendance-biometric-privacy",
    shape: "case",
    title: "Workers object to a new face-recognition attendance system. Resolve the standoff.",
    type: "Policy design",
    difficulty: 2,
    minutes: 22,
    answer: "Take the objection seriously: biometric data sits under India's data-protection law as sensitive, and trust costs are real. Run a necessity test (what problem does face recognition solve that cards plus spot checks don't?), offer a less-invasive alternative track, and if biometrics stay, wrap them in consent, purpose limitation, retention rules and worker communication.",
    hints: ["Is the biometric necessary, or merely convenient? The law and the workforce ask the same question."],
    moves: [
      { label: "Move 1", text: "Interrogate the need: buddy-punching losses quantified against alternatives (card plus random verification, geo-punch for field staff); face recognition is often convenience dressed as necessity." },
      { label: "Move 2", text: "Check the legal frame: DPDP treats biometric data with higher care: purpose limitation, consent quality, security safeguards, retention limits and processor accountability all apply." },
      { label: "Move 3", text: "Engage the objectors: works committee consultation, transparency on what is stored (templates versus images), where, for how long, and who accesses it." },
      { label: "Move 4", text: "Design the compromise: opt-in biometrics with a card-based alternative, deletion on exit, on-device processing where possible, and an audit trail workers can query." },
      { label: "Close", text: "Whatever lands, publish the data policy in plain language; surveillance introduced by memo becomes the union's best organising material." },
    ],
    pitfalls: [
      "Rolling out biometrics as an IT project with no consultation.",
      "Collecting more data than the attendance purpose needs.",
      "Ignoring that consent under employment power imbalance needs a real alternative.",
    ],
  },
  {
    slug: "global-capability-center-talent-war",
    shape: "case",
    title: "A new GCC is poaching your product engineers with 40% hikes. Defend.",
    type: "Retention strategy",
    difficulty: 2,
    minutes: 24,
    answer: "You cannot win a pure pay war against a cost-arbitraging entrant; defend on the dimensions they cannot copy quickly: product ownership depth, growth velocity, and targeted counter-economics for the critical core. Accept losses at the periphery gracefully and speed up your bench's readiness.",
    hints: ["Their 40% is your product ownership: fight where your currency is stronger."],
    moves: [
      { label: "Move 1", text: "Segment the exposure: who has been approached, who is critical, and where the GCC's offer is genuinely better versus merely louder." },
      { label: "Move 2", text: "Counter selectively: pay repositioning plus equity for the critical 15%, communicated with career maps; blanket matching resets your whole cost base to the entrant's." },
      { label: "Move 3", text: "Sell the real difference: end-to-end product ownership and faster scope growth against the GCC's captive-scope reality; alumni who return are the best evidence, so keep doors open." },
      { label: "Move 4", text: "Build resilience: succession shadows on every critical system, documentation debt paydown, and a hiring pipeline that assumes elevated churn for four quarters." },
      { label: "Close", text: "Measure regretted-critical attrition, not total attrition; losing the movable middle to a payer of 40% premiums is survivable arithmetic." },
    ],
    pitfalls: [
      "Matching 40% across the board and financing the rival's market entry with your margins.",
      "Pretending career narrative alone outbids a 40% cash gap for everyone.",
      "Leaving critical-system knowledge in single heads during a poaching season.",
    ],
  },
  {
    slug: "internal-mobility-hoarding",
    shape: "case",
    title: "Internal job applications get blocked by managers hoarding talent. Unblock mobility.",
    type: "Talent management",
    difficulty: 2,
    minutes: 22,
    answer: "Hoarding is rational under current incentives: managers lose a performer and gain a vacancy. Change the rules (no-veto internal applications, transfer timelines, backfill priority) and the incentives (talent-exporter recognition in manager scorecards), because exhortation against rational behaviour always loses.",
    hints: ["Managers hoard because the system fines them for releasing. Change the fine."],
    moves: [
      { label: "Move 1", text: "Evidence the cost: internal-mobility rate versus benchmark, and exit interviews showing people quit to move because moving internally was blocked; external attrition is the price of hoarding." },
      { label: "Move 2", text: "Rewrite the rules: employees apply confidentially, current managers get informed-not-consulted after selection, and releases happen within a fixed 4 to 8 week window." },
      { label: "Move 3", text: "Fix the manager's downside: priority backfill for releasing teams, transition overlap funding, and vacancy cover so release is not a punishment." },
      { label: "Move 4", text: "Flip the incentive: track and celebrate net talent exporters in calibration and promotion discussions; growing people for the company becomes the badge." },
      { label: "Close", text: "Watch internal-fill rate and quit-to-move attrition for two quarters; both move quickly once the veto dies." },
    ],
    pitfalls: [
      "Culture campaigns against behaviour the incentives still reward.",
      "Instant releases that genuinely damage the releasing team's delivery.",
      "Letting managers interview their own flight-risk applicants informally.",
    ],
  },
  {
    slug: "union-social-media-organizing",
    shape: "case",
    title: "Gig workers are organising strikes via social media with no formal union. Advise the platform.",
    type: "Labour relations",
    difficulty: 3,
    minutes: 26,
    answer: "The absence of a formal union means nobody to negotiate with and everybody to answer to: engage rather than suppress. Build structured worker voice (elected rider councils, grievance SLAs), fix the top grievances that fuel the organising (pay opacity, arbitrary deactivations), and treat retaliation as the accelerant it is.",
    hints: ["Leaderless movements are fed by specific grievances. Which three top the posts?"],
    moves: [
      { label: "Move 1", text: "Read the organising: scrape the public grievances; pay-per-order cuts, opaque incentives, deactivation without appeal and ID-block fears usually lead." },
      { label: "Move 2", text: "Do not retaliate: deactivating vocal workers converts a grievance into a martyrdom story and invites legal and press escalation." },
      { label: "Move 3", text: "Create the channel: city-level elected worker councils with scheduled management dialogue, published grievance SLAs, and an appeal process for deactivations with human review." },
      { label: "Move 4", text: "Fix the fuel: transparent pay math per order, incentive changes with notice periods, and floor earnings pilots in the loudest cities." },
      { label: "Close", text: "Measure strike propensity through leading indicators (grievance volumes, council attendance, sentiment) and treat sustained silence as danger, not peace." },
    ],
    pitfalls: [
      "Deactivating organisers and creating the movement's heroes.",
      "Waiting for a formal union to appear before engaging anyone.",
      "PR responses to what are arithmetic grievances about pay math.",
    ],
  },
  {
    slug: "return-from-career-break",
    shape: "case",
    title: "Design a returnship program for professionals re-entering after career breaks.",
    type: "Program design",
    difficulty: 1,
    minutes: 20,
    answer: "Treat returners as experienced hires with a confidence and currency gap, not as freshers: paid 4 to 6 month returnships with real projects, a skills-refresh layer, mentoring, and a high conversion bar you actually intend to clear. The talent arbitrage is real; the program fails only when it is charity theatre.",
    hints: ["The market misprices career-break resumes. That mispricing is your hiring edge."],
    moves: [
      { label: "Move 1", text: "Target honestly: roles where experience transfers and refresh is feasible (finance, engineering, analytics), with cohort sizes the org can genuinely absorb." },
      { label: "Move 2", text: "Structure the ramp: paid returnship at near-market rates, a real deliverable with a supportive manager, technical refresh modules, and a mentor plus returner-buddy pair." },
      { label: "Move 3", text: "De-bias the entry: screening that reads pre-break experience properly, interviewers briefed against recency bias, and gap questions banned from evaluation." },
      { label: "Move 4", text: "Convert seriously: 70%+ conversion targets at proper levels and pay; programs that convert 20% at deflated grades become known and die." },
      { label: "Close", text: "Track 2-year retention and performance of converts against lateral hires; the data typically wins the program its scale-up argument." },
    ],
    pitfalls: [
      "Levelling returners as freshers and losing them within the year.",
      "PR-driven cohorts with no real roles behind them.",
      "Ignoring the manager-preparation half of the program.",
    ],
  },
];
