import type { Question } from "./types";

// HR guesstimates. Workforces, hiring funnels, attrition and people costs:
// the numbers an HR interview expects you to construct from first principles.
export const HR_GUESSTIMATES: Question[] = [
  {
    slug: "recruiters-needed-it-giant",
    shape: "guesstimate",
    title: "How many recruiters does a 3-lakh-employee IT firm need?",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "TCS",
    answer: "Roughly 800 to 1,200 recruiters, driven almost entirely by attrition replacement plus growth hiring.",
    hints: ["Hiring volume comes from attrition times headcount plus net growth. Start there."],
    moves: [
      { label: "Move 1", text: "Derive hiring need: 3 lakh employees at 15% attrition means 45,000 replacements; add 15,000 growth hires for 60,000 a year." },
      { label: "Move 2", text: "Split the mix: perhaps 40% campus (high volume per recruiter) and 60% lateral (slow, search-heavy)." },
      { label: "Move 3", text: "Recruiter productivity: a lateral recruiter closes 4 to 6 hires a month; campus teams process thousands per drive with a smaller crew." },
      { label: "Move 4", text: "Compute: 36,000 laterals over 60 hires a year per recruiter gives 600; campus and leadership hiring add 200 to 400 more." },
      { label: "Check", text: "Recruiter load collapses in a hiring freeze; the function is sized to the cycle, which is why RPO buffers exist." },
    ],
    pitfalls: [
      "Sizing from headcount directly instead of from annual hires.",
      "Using one productivity number for campus and lateral hiring.",
      "Forgetting attrition, which usually exceeds growth as a hiring driver.",
    ],
  },
  {
    slug: "resumes-screened-per-opening",
    shape: "guesstimate",
    title: "Estimate resumes screened yearly by a bank hiring 10,000 people.",
    type: "Funnel estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 8 to 12 lakh resumes touched across the funnel.",
    hints: ["Work the funnel backward from offers to applications."],
    moves: [
      { label: "Move 1", text: "Set funnel ratios: about 1.2 offers per join, 3 final interviews per offer, 3 first-rounds per final, 10 screens per first-round." },
      { label: "Move 2", text: "Multiply back: 10,000 joins needs 12,000 offers, 36,000 finals, about 1 lakh first-rounds." },
      { label: "Move 3", text: "Screening layer: 10 resumes screened per interview shortlist gives about 10 lakh resumes." },
      { label: "Move 4", text: "Adjust for role mix: mass roles (tellers, sales) run wider funnels than specialist roles." },
      { label: "Check", text: "At 2 minutes a screen this is 33,000 hours of work, which is why screening automated first." },
    ],
    pitfalls: [
      "Forgetting offer declines between offer and join.",
      "Using specialist funnel ratios for mass hiring.",
      "Counting unique applicants when one person applies to many roles.",
    ],
  },
  {
    slug: "attrition-cost-tech-company",
    shape: "guesstimate",
    title: "Estimate the annual cost of 20% attrition at a 50,000-person tech firm.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    askedAt: "Infosys",
    answer: "Roughly 1,500 to 2,500 crore rupees a year, or 50 to 100% of each leaver's annual salary.",
    hints: ["Cost per exit has four parts: vacancy, hiring, onboarding, lost productivity."],
    moves: [
      { label: "Move 1", text: "Volume: 20% of 50,000 is 10,000 exits a year." },
      { label: "Move 2", text: "Cost per exit: hiring cost (agency, recruiter time) about 1 lakh; vacancy-period lost output 2 to 3 lakh; ramp-up at half productivity for 3 months, another 2 lakh." },
      { label: "Move 3", text: "Add knowledge and disruption: project delays and client transitions, hardest to measure, often another 1 to 2 lakh for experienced roles." },
      { label: "Move 4", text: "Multiply: 10,000 exits at 1.5 to 2.5 lakh blended gives 1,500 to 2,500 crore." },
      { label: "Check", text: "Cost is convex in seniority: one senior architect exit can cost 3x salary while a fresher exit costs a fraction." },
    ],
    pitfalls: [
      "Counting only the recruitment fee as the cost.",
      "Using one flat cost across junior and senior exits.",
      "Ignoring the productivity ramp of the replacement.",
    ],
  },
  {
    slug: "hr-professionals-india",
    shape: "guesstimate",
    title: "Estimate the number of HR professionals working in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 8 to 12 lakh HR professionals in the organised sector.",
    hints: ["Anchor on organised-sector employment and an HR-to-employee ratio."],
    moves: [
      { label: "Move 1", text: "Base: organised-sector employment in India is roughly 8 to 10 crore across private and public." },
      { label: "Move 2", text: "Ratio: firms run 1 HR person per 80 to 120 employees, thinner in factories, thicker in services." },
      { label: "Move 3", text: "Divide: 9 crore over 100 gives about 9 lakh." },
      { label: "Move 4", text: "Adjust: small firms below 50 people often have no HR at all, offset by consulting, staffing and HR-tech professionals outside company payrolls." },
      { label: "Check", text: "LinkedIn India lists over a million HR-titled profiles; the estimate should not be far below that." },
    ],
    pitfalls: [
      "Applying an HR ratio to the entire workforce including informal labour.",
      "Ignoring the staffing-industry and consulting HR population.",
      "Using MNC ratios for the whole economy.",
    ],
  },
  {
    slug: "campus-hiring-slots-day",
    shape: "guesstimate",
    title: "How many candidates can a company interview in one campus placement day?",
    type: "Capacity estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 80 to 150 candidates with 8 to 10 parallel panels.",
    hints: ["Panels times interviews per panel per day, minus process friction."],
    moves: [
      { label: "Move 1", text: "Panels: a serious campus visit brings 8 to 10 interviewer pairs." },
      { label: "Move 2", text: "Cycle time: 30 minutes per first-round plus 10 minutes of notes and shuffle gives 12 to 14 interviews per panel across a long day." },
      { label: "Move 3", text: "Multiply: 9 panels times 13 gives about 115 first-rounds." },
      { label: "Move 4", text: "Layer the rounds: second rounds for a third of candidates eat panel slots from the same day, cutting unique candidates seen." },
      { label: "Check", text: "The shortlist size the night before is the real constraint; a 300-name shortlist cannot be honoured in one day." },
    ],
    pitfalls: [
      "Forgetting second rounds consume the same panels.",
      "Zero slack for delays and no-shows.",
      "Confusing candidates tested online with candidates interviewed.",
    ],
  },
  {
    slug: "gig-workforce-india-size",
    shape: "guesstimate",
    title: "Estimate India's app-based gig workforce.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 1.5 crore workers across delivery, mobility and services platforms.",
    hints: ["Sum the big categories: mobility, food delivery, e-commerce logistics, home services."],
    moves: [
      { label: "Move 1", text: "Mobility: ride-hailing drivers across platforms, roughly 30 to 40 lakh registered, fewer active." },
      { label: "Move 2", text: "Delivery: food delivery 8 to 10 lakh active, e-commerce and quick-commerce logistics another 15 to 20 lakh." },
      { label: "Move 3", text: "Services and freelance: home services, beauty, care and micro-tasking add 10 to 15 lakh." },
      { label: "Move 4", text: "Sum actives: about 70 to 90 lakh active, with registered counts far higher; a growth trajectory pushes past 1 crore." },
      { label: "Check", text: "Multi-homing inflates platform-reported numbers: one rider on three apps is three registrations, one worker." },
    ],
    pitfalls: [
      "Adding platform-reported registrations with heavy double counting.",
      "Equating registered with active workers.",
      "Missing the services segment beyond delivery and rides.",
    ],
  },
  {
    slug: "training-hours-bank-compliance",
    shape: "guesstimate",
    title: "Estimate annual training hours a 1-lakh-employee bank must deliver.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 40 to 60 lakh person-hours a year across mandatory and role training.",
    hints: ["Mandatory compliance hours times everyone, plus role-based programs for subsets."],
    moves: [
      { label: "Move 1", text: "Mandatory layer: compliance, AML, security and conduct training run 15 to 20 hours per employee per year, so about 18 lakh hours." },
      { label: "Move 2", text: "Role layer: new joiners (say 15,000) get 2 to 4 weeks of induction, roughly 100 hours each, adding 15 lakh hours." },
      { label: "Move 3", text: "Development layer: leadership and skill programs touch a fifth of staff at 20 to 30 hours, another 5 lakh." },
      { label: "Move 4", text: "Sum: around 40 lakh hours, more in years of system migrations or regulation changes." },
      { label: "Check", text: "Divide by working hours: 40 lakh hours is about 2% of the bank's total work time, a sane training load." },
    ],
    pitfalls: [
      "Forgetting induction, which dominates per-person hours.",
      "Counting e-learning assigned versus actually completed.",
      "Ignoring trainer-side hours when sizing the delivery team.",
    ],
  },
  {
    slug: "employee-referral-share-hires",
    shape: "guesstimate",
    title: "Estimate hires a 20,000-person company gets from employee referrals yearly.",
    type: "Funnel estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 900 to 1,500 referral hires, typically 25 to 35% of all hiring.",
    hints: ["Start from total hires, then apply a referral share; or build from referrals per employee."],
    moves: [
      { label: "Move 1", text: "Total hiring: 20,000 people at 18% attrition plus growth needs about 4,000 to 4,500 hires a year." },
      { label: "Move 2", text: "Referral participation: about 20 to 30% of employees refer at least once a year, giving 8,000 to 10,000 referrals." },
      { label: "Move 3", text: "Conversion: referrals convert at 10 to 15%, far above the 2 to 3% of cold applications." },
      { label: "Move 4", text: "Compute: 9,000 referrals at 12% gives about 1,100 hires, or roughly a quarter of total hiring." },
      { label: "Check", text: "If referral share crosses half of hiring, check for homogeneity risk; the funnel inherits the current workforce's networks." },
    ],
    pitfalls: [
      "Applying cold-application conversion rates to referrals.",
      "Assuming every employee refers.",
      "Ignoring the diversity trade-off at very high referral shares.",
    ],
  },
  {
    slug: "office-space-hybrid-company",
    shape: "guesstimate",
    title: "How much office space does a 10,000-person hybrid company need?",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 6 to 8 lakh square feet with desk sharing, versus 10 to 12 lakh fully in-office.",
    hints: ["Peak simultaneous occupancy drives space, not headcount."],
    moves: [
      { label: "Move 1", text: "Attendance pattern: 3 days a week mandated means average occupancy 60%, but peak days (Tuesday to Thursday) hit 75 to 80%." },
      { label: "Move 2", text: "Size to peak: 8,000 people present needs seats, not 10,000." },
      { label: "Move 3", text: "Space per seat: 80 to 100 square feet including meeting rooms, cafeterias and circulation." },
      { label: "Move 4", text: "Multiply: 8,000 times 90 gives about 7.2 lakh square feet, with desk-booking smoothing the Tuesday peak." },
      { label: "Check", text: "If everyone picks the same three days, sharing saves nothing; the policy design, not the ratio, delivers the savings." },
    ],
    pitfalls: [
      "Sizing to average occupancy when peak days bind.",
      "Using open-desk-only space norms and forgetting meeting rooms.",
      "Assuming attendance spreads evenly across weekdays.",
    ],
  },
  {
    slug: "payroll-cost-share-it-services",
    shape: "guesstimate",
    title: "Estimate people cost as a share of revenue for an IT services firm.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 55 to 65% of revenue goes to employee costs.",
    hints: ["Build from revenue per employee versus cost per employee."],
    moves: [
      { label: "Move 1", text: "Revenue side: large Indian IT firms earn 25 to 35 lakh rupees of revenue per employee per year." },
      { label: "Move 2", text: "Cost side: blended salary plus benefits across the pyramid runs 15 to 20 lakh per employee." },
      { label: "Move 3", text: "Divide: 17 over 29 gives about 58%." },
      { label: "Move 4", text: "Reconcile: listed IT firms report employee expenses near 55 to 60% of revenue; your build should land there." },
      { label: "Check", text: "The pyramid is the profit engine: freshers billed at multiples of cost subsidise expensive seniors; pyramid flattening shows up directly in this ratio." },
    ],
    pitfalls: [
      "Using senior salaries as the blended average.",
      "Forgetting benefits, bonuses and gratuity above base salary.",
      "Ignoring subcontractor costs that sit near employee cost lines.",
    ],
  },
  {
    slug: "poSH-trainings-corporate-india",
    shape: "guesstimate",
    title: "Estimate annual POSH training sessions conducted across corporate India.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Several lakh sessions a year, roughly 3 to 5 lakh, across companies above 10 employees.",
    hints: ["Companies covered by the Act times sessions per company per year."],
    moves: [
      { label: "Move 1", text: "Coverage: the POSH Act applies to workplaces with 10+ employees; registered companies of that size number 8 to 10 lakh." },
      { label: "Move 2", text: "Compliance reality: perhaps 30 to 40% actively conduct annual training, concentrated in larger firms." },
      { label: "Move 3", text: "Sessions per firm: a 200-person firm runs 2 to 4 batches; a 10,000-person firm runs dozens, mostly e-learning plus live IC training." },
      { label: "Move 4", text: "Blend: 3 lakh complying firms at an average 1.5 live sessions gives 4 to 5 lakh sessions." },
      { label: "Check", text: "E-learning completions dwarf live sessions; be clear which the question counts." },
    ],
    pitfalls: [
      "Assuming full compliance across all covered workplaces.",
      "Mixing e-learning completions with live sessions.",
      "Forgetting IC member training as a separate mandated layer.",
    ],
  },
  {
    slug: "canteen-meals-factory-township",
    shape: "guesstimate",
    title: "Estimate daily meals served across a steel township's facilities.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 60,000 to 90,000 meals a day for a 30,000-worker plant township.",
    hints: ["Plant canteens run by shift; township adds schools, hospitals and guest houses."],
    moves: [
      { label: "Move 1", text: "Plant canteens: 30,000 workers across 3 shifts, with 70% eating one canteen meal per shift, gives about 21,000 meals." },
      { label: "Move 2", text: "Second meals: tea, breakfast and night-shift extras add half a meal equivalent per worker, another 15,000." },
      { label: "Move 3", text: "Township load: schools, hospital, guest houses and contractor camps add 20,000 to 30,000." },
      { label: "Move 4", text: "Sum: about 60,000 to 75,000 on normal days, spiking during shutdowns when contractor counts double." },
      { label: "Check", text: "Shutdown maintenance months add 10,000+ contractors; kitchen capacity is sized for that spike, not the average." },
    ],
    pitfalls: [
      "Counting only the plant canteen and missing township institutions.",
      "Ignoring contractor workforce meals.",
      "Sizing kitchens to average rather than shutdown peaks.",
    ],
  },
  {
    slug: "exit-interviews-conducted-year",
    shape: "guesstimate",
    title: "Estimate the exit interviews HR conducts yearly at a 40,000-person retailer.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 15,000 to 20,000 conversations, given retail's high frontline attrition.",
    hints: ["Retail frontline attrition is far above corporate rates."],
    moves: [
      { label: "Move 1", text: "Split the workforce: 35,000 store staff, 5,000 corporate." },
      { label: "Move 2", text: "Attrition rates: frontline retail runs 40 to 60%; corporate runs 15%." },
      { label: "Move 3", text: "Exits: 35,000 times 0.5 gives 17,500 frontline; corporate adds 750." },
      { label: "Move 4", text: "Coverage: not every exit gets a live interview; 70% coverage means about 13,000 conversations, the rest surveys." },
      { label: "Check", text: "At 30 minutes each, that is 6,500 HR hours a year, which is why frontline exits get digitised surveys." },
    ],
    pitfalls: [
      "Using corporate attrition for store staff.",
      "Assuming 100% exit-interview coverage.",
      "Ignoring seasonal staff whose planned exits differ from attrition.",
    ],
  },
  {
    slug: "women-workforce-participation-tech",
    shape: "guesstimate",
    title: "Estimate women in India's IT services workforce.",
    type: "Market sizing",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 18 to 20 lakh women, about 34 to 36% of the sector.",
    hints: ["Sector size times participation share, checked against entry versus senior ratios."],
    moves: [
      { label: "Move 1", text: "Sector size: IT services and BPM employ about 50 to 55 lakh people." },
      { label: "Move 2", text: "Share: the sector reports roughly 34 to 36% women, far above manufacturing." },
      { label: "Move 3", text: "Multiply: 52 lakh times 0.35 gives about 18 lakh." },
      { label: "Move 4", text: "Note the pyramid: entry cohorts approach parity while senior levels drop below 15%; the average hides the funnel." },
      { label: "Check", text: "Attrition at mid-career (the maternity-to-manager stretch) is where the ratio erodes; any policy question hinges there." },
    ],
    pitfalls: [
      "Quoting the average without the level-wise fall.",
      "Mixing IT services with the broader tech startup workforce.",
      "Using global tech ratios for India.",
    ],
  },
  {
    slug: "appraisal-hours-company-cycle",
    shape: "guesstimate",
    title: "Estimate total hours a 15,000-person firm spends on annual appraisals.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 3 to 5 lakh person-hours per cycle, worth 40 to 80 crore in loaded time cost.",
    hints: ["Count every role in the ritual: employee, manager, reviewer, HR, calibration."],
    moves: [
      { label: "Move 1", text: "Employee time: self-review and goal documentation, 4 to 6 hours each, gives about 75,000 hours." },
      { label: "Move 2", text: "Manager time: writing reviews and holding conversations for 7 reports at 4 hours each; 2,000 managers times 28 hours is 56,000 hours." },
      { label: "Move 3", text: "Calibration and HR: committee sessions, normalisation meetings and appeals add 30,000 to 50,000 hours." },
      { label: "Move 4", text: "Sum and monetise: about 2 lakh core hours, doubled if mid-year reviews run; at 1,500 rupees a loaded hour this is a 30 to 60 crore ritual." },
      { label: "Check", text: "Cost is the argument for lighter continuous feedback; quote hours and rupees together for impact." },
    ],
    pitfalls: [
      "Counting only HR's time and missing the line organisation's.",
      "Ignoring calibration meetings, the hidden time sink.",
      "Forgetting mid-year cycles double the load.",
    ],
  },
  {
    slug: "security-guards-employed-india",
    shape: "guesstimate",
    title: "Estimate people employed as private security guards in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 80 lakh to 1 crore guards, one of India's largest formal-adjacent employers.",
    hints: ["Sum the demand sites: residential complexes, offices, retail, industry, banks."],
    moves: [
      { label: "Move 1", text: "Residential: several lakh gated societies and buildings averaging 3 to 5 guard posts with shift multipliers." },
      { label: "Move 2", text: "Commercial: offices, malls, hospitals, banks and ATMs each carry posts around the clock." },
      { label: "Move 3", text: "Industrial and events: factories, warehouses and construction sites add heavily." },
      { label: "Move 4", text: "Aggregate: industry bodies place the sector near 90 lakh workers; a bottom-up build should land within 30% of it." },
      { label: "Check", text: "The 24x7 post arithmetic (3 shifts plus relievers, so 4+ guards per post) is what makes the number this large." },
    ],
    pitfalls: [
      "Counting posts instead of people across shifts.",
      "Missing the residential segment, the largest demand pool.",
      "Assuming all guards are formally registered.",
    ],
  },
  {
    slug: "notice-period-cost-buyouts",
    shape: "guesstimate",
    title: "Estimate what companies spend yearly buying out notice periods in Indian IT.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 22,
    answer: "Roughly 2,000 to 4,000 crore rupees a year across the sector in a hot market.",
    hints: ["Lateral hires times buyout share times buyout size."],
    moves: [
      { label: "Move 1", text: "Lateral volume: the sector makes 8 to 10 lakh lateral hires a year in normal times." },
      { label: "Move 2", text: "Buyout incidence: perhaps 25 to 35% of laterals get notice buyouts, higher in hot markets." },
      { label: "Move 3", text: "Buyout size: 1 to 2 months of salary; at a 12 lakh average package that is 1 to 2 lakh rupees." },
      { label: "Move 4", text: "Multiply: 9 lakh times 0.3 times 1.3 lakh gives about 3,500 crore." },
      { label: "Check", text: "The spend is cyclical: it doubles in talent wars and nearly vanishes in freezes; quote it as a range with the cycle caveat." },
    ],
    pitfalls: [
      "Assuming every lateral hire involves a buyout.",
      "Using senior salaries for the buyout average.",
      "Ignoring the hiring-cycle sensitivity of the estimate.",
    ],
  },
  {
    slug: "hrms-software-market-india",
    shape: "guesstimate",
    title: "Size the HR software market in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 6,000 to 10,000 crore rupees a year across payroll, HRMS and talent tools.",
    hints: ["Employees on software times per-employee-per-month pricing."],
    moves: [
      { label: "Move 1", text: "Addressable base: 8 to 10 crore organised workers, of whom perhaps 4 to 5 crore sit in companies that buy HR software." },
      { label: "Move 2", text: "Penetration: half of those companies use paid tools today, covering about 2.5 crore employees." },
      { label: "Move 3", text: "Pricing: blended 20 to 40 rupees per employee per month for payroll plus modules." },
      { label: "Move 4", text: "Multiply: 2.5 crore times 30 rupees times 12 gives about 9,000 crore, enterprise suites skewing the top." },
      { label: "Check", text: "Cross-check with vendor revenues: the leading Indian players sum to low thousands of crores, consistent with a fragmented market this size." },
    ],
    pitfalls: [
      "Pricing everyone at enterprise-suite rates.",
      "Counting the informal workforce in the addressable base.",
      "Missing that payroll outsourcing services compete with software spend.",
    ],
  },
  {
    slug: "interview-hours-unicorn-scaling",
    shape: "guesstimate",
    title: "Estimate engineering interview hours a startup burns to grow from 200 to 500 engineers.",
    type: "Funnel estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25,000 to 40,000 interviewer hours over the scaling year.",
    hints: ["Hires needed exceeds 300 because of attrition; each hire costs many interview loops."],
    moves: [
      { label: "Move 1", text: "True hiring need: 300 net adds plus 20% attrition on the growing base means about 380 hires." },
      { label: "Move 2", text: "Funnel per hire: 4 onsite loops of 4 interviews for every offer, 1.4 offers per join, plus phone screens: roughly 25 to 30 interview-hours per join." },
      { label: "Move 3", text: "Multiply: 380 joins times 28 hours gives about 10,600 onsite hours; screens and debriefs roughly double it." },
      { label: "Move 4", text: "Load it: 25,000 hours across 150 trained interviewers is 3 to 4 hours a week each, a real engineering tax." },
      { label: "Check", text: "Interviewer capacity, not candidate supply, is usually what breaks scaling plans; state it as the binding constraint." },
    ],
    pitfalls: [
      "Planning for 300 hires when attrition makes it 380.",
      "Counting interview time but not debrief and calibration time.",
      "Ignoring the productivity cost on the engineers interviewing.",
    ],
  },
  {
    slug: "apprentices-manufacturing-india",
    shape: "guesstimate",
    title: "Estimate apprentices engaged by Indian manufacturing at any time.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 5 to 8 lakh apprentices under formal schemes, against far larger potential.",
    hints: ["Factories covered by apprenticeship rules times typical apprentice ratios."],
    moves: [
      { label: "Move 1", text: "Base: registered factories number about 2.5 lakh; the larger 50,000 drive most apprenticeship." },
      { label: "Move 2", text: "Ratio: rules allow 2.5 to 15% of strength as apprentices; active firms run 3 to 5%." },
      { label: "Move 3", text: "Compute: large-factory employment near 1 crore times 4% gives 4 lakh, plus services-sector schemes adding more." },
      { label: "Move 4", text: "Reconcile: national scheme dashboards report mid-single-digit lakhs engaged, matching the build." },
      { label: "Check", text: "The gap between permitted (15%) and actual (4%) is the policy story every discussion circles." },
    ],
    pitfalls: [
      "Assuming every factory participates.",
      "Confusing cumulative trained with currently engaged.",
      "Ignoring services-sector apprentices under newer schemes.",
    ],
  },
  {
    slug: "relocation-cost-annual-company",
    shape: "guesstimate",
    title: "Estimate annual relocation spend for a firm moving 800 employees between cities.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 25 to 50 crore rupees depending on seniority mix and family moves.",
    hints: ["Cost per move differs 5x between a bachelor transfer and a senior family move."],
    moves: [
      { label: "Move 1", text: "Segment moves: say 500 junior single moves, 250 mid-level family moves, 50 senior moves." },
      { label: "Move 2", text: "Cost tiers: junior moves (travel, a month's stay, small shipment) cost 1 to 2 lakh; family moves (shipment, school support, brokerage, settling allowance) 4 to 6 lakh; senior moves with temporary housing 10 to 15 lakh." },
      { label: "Move 3", text: "Multiply: 500 times 1.5 plus 250 times 5 plus 50 times 12 gives about 26 crore." },
      { label: "Move 4", text: "Add the hidden lines: notice-period overlaps, dual-rent support and attrition of refused moves." },
      { label: "Check", text: "A fifth of asked employees typically decline; the cost of their attrition belongs in the policy's full economics." },
    ],
    pitfalls: [
      "Flat per-move budgeting across seniority tiers.",
      "Ignoring refusal-driven attrition as a relocation cost.",
      "Forgetting dual-rent and school-year timing supports.",
    ],
  },
  {
    slug: "linkedin-recruiter-inmails-daily",
    shape: "guesstimate",
    title: "Estimate recruiter InMails sent to Indian software engineers daily.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 3 to 6 lakh recruiter messages a day in active markets.",
    hints: ["Active recruiters with paid seats times daily outreach quota."],
    moves: [
      { label: "Move 1", text: "Recruiter seats: agencies, IT firms and startups hold perhaps 60,000 to 1 lakh paid recruiter seats targeting tech talent in India." },
      { label: "Move 2", text: "Outreach rate: an active sourcing recruiter sends 20 to 50 messages a day." },
      { label: "Move 3", text: "Multiply: 80,000 seats times 30 messages at 70% daily activity gives about 5 lakh." },
      { label: "Move 4", text: "Sanity-check from the receiver side: 15 lakh experienced engineers getting 1 to 3 messages a week implies 4 to 6 lakh daily, consistent." },
      { label: "Check", text: "Response rates under 10% are why volumes stay this high; the spam equilibrium is the market's design flaw." },
    ],
    pitfalls: [
      "Counting all recruiters as tech-focused.",
      "Ignoring the two-sided sanity check.",
      "Treating hiring-freeze months like peak months.",
    ],
  },
  {
    slug: "hr-shared-services-team",
    shape: "guesstimate",
    title: "Size the HR shared-services team for a 60,000-person conglomerate.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 150 to 250 people handling queries, payroll inputs and employee lifecycle transactions.",
    hints: ["Ticket volume per employee per year divided by tickets per agent."],
    moves: [
      { label: "Move 1", text: "Ticket volume: employees raise 8 to 12 HR queries or transactions a year, giving about 6 lakh tickets." },
      { label: "Move 2", text: "Self-serve deflection: a decent portal absorbs 50 to 60%, leaving 2.5 lakh handled tickets." },
      { label: "Move 3", text: "Agent capacity: 15 to 25 resolved tickets a day gives about 4,500 a year per agent." },
      { label: "Move 4", text: "Divide and add: 55 agents for tickets, plus payroll processing, onboarding administration, letters and audits roughly tripling the total." },
      { label: "Check", text: "Benchmark: shared services typically run 1 per 300 to 500 employees served; 60,000 over 400 gives 150, matching the build." },
    ],
    pitfalls: [
      "Counting only query agents and missing transaction processing.",
      "Assuming portal deflection without measuring it.",
      "Using one ratio across white-collar and factory populations.",
    ],
  },
  {
    slug: "creche-demand-it-park",
    shape: "guesstimate",
    title: "Estimate creche seats an IT park of 40,000 workers should provide.",
    type: "Demand estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 800 to 1,500 seats against the realistic take-up, far above the token 50-seat facilities common today.",
    hints: ["Work from parents of creche-age children times willingness to use workplace care."],
    moves: [
      { label: "Move 1", text: "Demographics: at a median age near 30, perhaps 25 to 30% of the 40,000 have children under 6, say 11,000 parents." },
      { label: "Move 2", text: "Deduplicate and screen: one seat per family, and many rely on family care; realistic interest is 15 to 25% of eligible families." },
      { label: "Move 3", text: "Compute: 8,000 families times 20% gives about 1,600 potential; price and distance cut take-up toward 1,000." },
      { label: "Move 4", text: "Compare with mandate: the Maternity Benefit Act requires creche access for 50+ employee establishments; token compliance meets the letter, not this demand." },
      { label: "Check", text: "Waitlists at existing park creches are the observable evidence; if they are full with 100 seats, latent demand is a multiple." },
    ],
    pitfalls: [
      "Counting both parents as separate demand.",
      "Equating legal compliance capacity with actual demand.",
      "Ignoring price sensitivity in take-up.",
    ],
  },
  {
    slug: "festival-bonus-payout-manufacturing",
    shape: "guesstimate",
    title: "Estimate Diwali bonus payouts across Indian organised manufacturing.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 30,000 to 50,000 crore rupees across the organised manufacturing workforce.",
    hints: ["Workers covered times a bonus of roughly one month's wages."],
    moves: [
      { label: "Move 1", text: "Base: organised manufacturing employs about 2 to 2.5 crore workers across factories." },
      { label: "Move 2", text: "Coverage: statutory bonus and customary Diwali payouts reach most of them, at 8.33% to 20% of annual wages, roughly one month." },
      { label: "Move 3", text: "Wage anchor: average monthly wages near 15,000 to 20,000 rupees for covered workers." },
      { label: "Move 4", text: "Multiply: 2.2 crore times 17,000 gives about 37,000 crore." },
      { label: "Check", text: "The number explains the October consumption spike; economists track it as a demand pulse." },
    ],
    pitfalls: [
      "Including the informal workforce where payouts are irregular.",
      "Using white-collar salaries as the wage anchor.",
      "Confusing statutory minimum with actual customary payouts.",
    ],
  },
  {
    slug: "teachers-needed-india-schools",
    shape: "guesstimate",
    title: "Estimate the school teachers India employs.",
    type: "Market sizing",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 90 lakh to 1 crore teachers across government and private schools.",
    hints: ["Students divided by pupil-teacher ratio."],
    moves: [
      { label: "Move 1", text: "Students: about 25 crore children enrolled in schools." },
      { label: "Move 2", text: "Pupil-teacher ratio: policy targets 30:1; reality blends to 25 to 30 across stages." },
      { label: "Move 3", text: "Divide: 25 crore over 27 gives about 92 lakh." },
      { label: "Move 4", text: "Sanity: government data reports around 95 lakh teachers; the build matches." },
      { label: "Check", text: "The average hides distribution: urban private schools run rich ratios while single-teacher rural schools exist; a hiring question hinges on the tail." },
    ],
    pitfalls: [
      "Forgetting private schools, nearly half of enrolment.",
      "Using the policy ratio as the actual ratio.",
      "Ignoring subject-wise shortages hidden in the aggregate.",
    ],
  },
  {
    slug: "offer-dropout-cost-startup",
    shape: "guesstimate",
    title: "Estimate the yearly cost of a 30% offer-dropout rate at a 5,000-person startup.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 15 to 30 crore rupees in wasted funnel effort and delayed work.",
    hints: ["Dropouts waste the full funnel cost and stretch vacancy periods."],
    moves: [
      { label: "Move 1", text: "Volume: 5,000 people at 20% attrition plus growth needs 1,500 joins; at 30% dropout, about 640 offers evaporate." },
      { label: "Move 2", text: "Funnel waste per dropout: recruiter and interviewer hours, assessments and background checks, roughly 1 to 1.5 lakh of loaded effort." },
      { label: "Move 3", text: "Vacancy extension: each dropout adds 45 to 60 days of re-search on a role, with lost-output cost of another 2 to 3 lakh." },
      { label: "Move 4", text: "Multiply: 640 times 3.5 lakh gives about 22 crore." },
      { label: "Check", text: "Compare with prevention cost: engagement between offer and join, faster joining dates and competitive revisions cost a fraction of 22 crore." },
    ],
    pitfalls: [
      "Counting only recruiter fees as the loss.",
      "Ignoring the vacancy-extension cost, the bigger half.",
      "Treating dropout rate as fixed rather than manageable.",
    ],
  },
  {
    slug: "background-checks-market-india",
    shape: "guesstimate",
    title: "Estimate background checks conducted yearly on Indian white-collar hires.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 1.5 to 2.5 crore verifications a year across joiners.",
    hints: ["White-collar hires per year times checks per hire."],
    moves: [
      { label: "Move 1", text: "Hire volume: organised white-collar joining (replacement plus growth) runs 1.5 to 2 crore a year." },
      { label: "Move 2", text: "Coverage: most mid and large firms verify; small firms often skip. Call it 60 to 70% of hires checked." },
      { label: "Move 3", text: "Checks per candidate: education, past employment, address, criminal and reference bundle into one case." },
      { label: "Move 4", text: "Compute: 1.8 crore hires times 0.65 gives about 1.2 crore cases, each with 4 to 5 component checks." },
      { label: "Check", text: "Discrepancy rates near 8 to 10% are the industry's selling point; a question here usually pivots to what firms do with red flags." },
    ],
    pitfalls: [
      "Counting component checks as separate cases inconsistently.",
      "Assuming blue-collar hiring gets the same verification.",
      "Missing gig-platform onboarding checks as a new volume pool.",
    ],
  },
  {
    slug: "learning-budget-per-employee",
    shape: "guesstimate",
    title: "Estimate a reasonable L&D budget for a 25,000-person services firm.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 60 to 120 crore rupees a year, or 1 to 2% of payroll.",
    hints: ["Anchor as a share of payroll, then sanity-check per head."],
    moves: [
      { label: "Move 1", text: "Payroll base: 25,000 people at 8 lakh average cost is 2,000 crore." },
      { label: "Move 2", text: "Benchmark share: firms invest 1 to 2% of payroll in learning; take 1.5%." },
      { label: "Move 3", text: "Compute: about 30 crore direct spend... add trainee time cost, which usually doubles or triples the visible budget." },
      { label: "Move 4", text: "Per head check: 30 crore over 25,000 is 12,000 rupees per employee, buying a few programs and platform seats each." },
      { label: "Check", text: "The invisible cost is paid time in training; leaders who quote only vendor spend undercount by half." },
    ],
    pitfalls: [
      "Quoting vendor spend as the full cost.",
      "Even per-head allocation when leadership programs concentrate spend.",
      "Benchmarking against tech-giant budgets for a services pyramid.",
    ],
  },
  {
    slug: "union-membership-auto-plant",
    shape: "guesstimate",
    title: "Estimate union membership at a 12,000-worker auto plant cluster.",
    type: "Demand estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 4,000 to 6,000 members, concentrated among permanent workers.",
    hints: ["Split permanent versus contract; membership skews sharply to permanent."],
    moves: [
      { label: "Move 1", text: "Workforce split: typical cluster runs 40% permanent (4,800) and 60% contract (7,200)." },
      { label: "Move 2", text: "Permanent membership: 80 to 90% of permanent workers unionise, about 4,200." },
      { label: "Move 3", text: "Contract membership: legally trickier and employer-resisted; 10 to 20% join affiliated bodies, adding 1,000." },
      { label: "Move 4", text: "Total: about 5,000 members across recognised and rival unions." },
      { label: "Check", text: "The permanent-contract divide is the fault line in most plant disputes; membership math mirrors it exactly." },
    ],
    pitfalls: [
      "Assuming contract workers unionise at permanent rates.",
      "Counting one union when plants often have rivals.",
      "Ignoring that membership spikes around wage-settlement years.",
    ],
  },
  {
    slug: "cab-spend-employee-transport-bpo",
    shape: "guesstimate",
    title: "Estimate annual employee-transport spend for a 20,000-person BPO.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 150 to 250 crore rupees a year for night-shift-heavy operations.",
    hints: ["Riders per day times cost per seat-trip times working days."],
    moves: [
      { label: "Move 1", text: "Eligible riders: night and odd-shift staff get transport; say 60% of 20,000 use it daily, 12,000 riders." },
      { label: "Move 2", text: "Trips: pickup and drop is 24,000 seat-trips a day." },
      { label: "Move 3", text: "Cost per seat-trip: shared cab routing runs 150 to 250 rupees including security escorts for late-night routes." },
      { label: "Move 4", text: "Multiply: 24,000 times 200 times 300 days gives about 145 crore, plus admin and no-show waste." },
      { label: "Check", text: "Transport is often the third-largest cost after salaries and rent in BPOs; routing efficiency moves crores." },
    ],
    pitfalls: [
      "Assuming all employees use company transport.",
      "Ignoring mandated security escorts on night routes.",
      "Costing per cab instead of per occupied seat.",
    ],
  },
  {
    slug: "healthcare-nurses-shortage",
    shape: "guesstimate",
    title: "Estimate India's nursing workforce gap against WHO norms.",
    type: "Gap estimation",
    difficulty: 2,
    minutes: 20,
    answer: "A shortage of roughly 15 to 20 lakh nurses against the 3-per-1,000 norm.",
    hints: ["Norm-based need minus active registered nurses."],
    moves: [
      { label: "Move 1", text: "Need: WHO suggests about 3 nurses per 1,000 people; for 140 crore that is 42 lakh." },
      { label: "Move 2", text: "Stock: registrations exceed 30 lakh, but active-in-India practice is nearer 22 to 25 lakh after migration and dropouts." },
      { label: "Move 3", text: "Gap: 42 minus 24 gives about 18 lakh." },
      { label: "Move 4", text: "Distribution: the gap concentrates rurally; metros hover near norms while districts run at a third." },
      { label: "Check", text: "Annual graduation near 2 to 3 lakh minus emigration means the gap closes only over decades at current rates." },
    ],
    pitfalls: [
      "Using registered counts as active counts.",
      "Ignoring emigration of trained nurses.",
      "Quoting a national gap without the rural skew.",
    ],
  },
  {
    slug: "onboarding-cost-per-hire",
    shape: "guesstimate",
    title: "Estimate the full first-90-day cost of onboarding one lateral hire.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 3 to 6 lakh rupees for a mid-level hire, beyond the salary itself.",
    hints: ["Sum recruiter cost, equipment, training time, manager time and the productivity ramp."],
    moves: [
      { label: "Move 1", text: "Acquisition: agency fee or sourcing cost plus interview hours, about 1 to 2 lakh for a mid-level role." },
      { label: "Move 2", text: "Setup: equipment, licences, access provisioning and induction programs, 50,000 to 1 lakh." },
      { label: "Move 3", text: "Ramp: 90 days at perhaps half productivity on a 20 lakh package costs about 2.5 lakh of paid-but-unproductive time." },
      { label: "Move 4", text: "People time: manager and buddy hours coaching the joiner add 30,000 to 50,000 of loaded time." },
      { label: "Check", text: "Early attrition multiplies this: a 90-day quit burns the full amount with zero recovery, which is why day-30 check-ins exist." },
    ],
    pitfalls: [
      "Counting only the recruitment fee.",
      "Assuming full productivity from day one.",
      "Ignoring manager coaching time as a real cost.",
    ],
  },
  {
    slug: "employee-engagement-survey-volume",
    shape: "guesstimate",
    title: "Estimate survey responses a 70,000-person conglomerate collects yearly.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 2 to 4 lakh responses across annual, pulse and lifecycle surveys.",
    hints: ["Layer the survey types: annual, quarterly pulses, lifecycle triggers."],
    moves: [
      { label: "Move 1", text: "Annual survey: 70,000 invited at 75% response gives about 52,000." },
      { label: "Move 2", text: "Pulses: quarterly short surveys at 60% response add about 1.7 lakh." },
      { label: "Move 3", text: "Lifecycle: onboarding, exit and manager-feedback surveys tied to events add 50,000 to 80,000." },
      { label: "Move 4", text: "Sum: about 3 lakh responses, each with 10 to 50 answers, feeding the analytics stack." },
      { label: "Check", text: "Response fatigue is the design constraint: every added survey drops response rates on the others." },
    ],
    pitfalls: [
      "Assuming 100% response rates.",
      "Forgetting lifecycle surveys triggered by events.",
      "Counting invitations as responses.",
    ],
  },
  {
    slug: "leadership-pipeline-cfo-pool",
    shape: "guesstimate",
    title: "Estimate the internal pipeline needed to reliably fill 10 CXO seats.",
    type: "Pipeline estimation",
    difficulty: 3,
    minutes: 22,
    answer: "Roughly 60 to 100 identified successors across two levels, given readiness decay and attrition.",
    hints: ["Work backward through readiness probabilities and time horizons."],
    moves: [
      { label: "Move 1", text: "Demand: 10 seats turning over every 5 to 7 years means 1 to 2 successions a year." },
      { label: "Move 2", text: "Ready-now pool: each seat needs 2 to 3 ready-now or ready-soon names, so 25 to 30 at level one." },
      { label: "Move 3", text: "Decay: successors leave, stall or get poached; half the pool churns in 3 years, demanding a feeder bench of 40 to 60 below them." },
      { label: "Move 4", text: "Total: 70 to 90 people under active development across two levels, refreshed yearly." },
      { label: "Check", text: "External hires filling more than a third of CXO seats is the signal the pipeline math failed years earlier." },
    ],
    pitfalls: [
      "One successor per seat with no churn allowance.",
      "Confusing a names-on-slide exercise with actual development investment.",
      "Ignoring that the best successors are exactly whom rivals poach.",
    ],
  },
  {
    slug: "contract-staffing-industry-india",
    shape: "guesstimate",
    title: "Size India's formal contract staffing industry by headcount.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 50 to 60 lakh workers on formal staffing-company payrolls.",
    hints: ["Sum the deployment sectors: manufacturing, logistics, retail, banking ops, IT."],
    moves: [
      { label: "Move 1", text: "Anchor: the organised staffing industry reports employing around 1.5% of the organised workforce." },
      { label: "Move 2", text: "Sector build: manufacturing shop floors, e-commerce logistics, retail store staff and banking operations each deploy lakhs." },
      { label: "Move 3", text: "Cross-check with leaders: the top 5 staffing firms carry 15 to 20 lakh associates; the long tail of licensed firms roughly doubles it." },
      { label: "Move 4", text: "Land: 50 lakh formal, sitting inside a far larger informal contractor ecosystem." },
      { label: "Check", text: "Formalisation is the growth story: every labour-code change shifts workers from informal contractors to licensed staffing rolls." },
    ],
    pitfalls: [
      "Mixing informal contract labour with formal staffing rolls.",
      "Counting gig platforms as staffing headcount.",
      "Using one leader's share to extrapolate wrongly.",
    ],
  },
  {
    slug: "moonlighting-detection-scale",
    shape: "guesstimate",
    title: "Estimate how many IT employees moonlight at any given time.",
    type: "Prevalence estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Plausibly 5 to 10% of the sector, a few lakh people, concentrated in fully-remote roles.",
    hints: ["Triangulate: PF dual-contribution flags, survey self-reports, platform sign-ups."],
    moves: [
      { label: "Move 1", text: "Frame the definition: second payrolled jobs versus freelance gigs; the second is far larger." },
      { label: "Move 2", text: "Hard signal: dual PF contributions flagged during the remote-work peak suggested single-digit percentages in checked cohorts." },
      { label: "Move 3", text: "Soft signal: anonymous surveys report 15 to 20% 'have ever'; sustained concurrent work is a fraction of that." },
      { label: "Move 4", text: "Blend: 5 to 10% concurrent moonlighting across 50 lakh employees gives 2.5 to 5 lakh people." },
      { label: "Check", text: "Remote share is the driver: mandated office returns measurably compress the estimate, which tells you the mechanism." },
    ],
    pitfalls: [
      "Treating survey 'ever done it' as current prevalence.",
      "Ignoring the payroll-versus-freelance definitional split.",
      "Quoting a point estimate where only a range is defensible.",
    ],
  },
  {
    slug: "esops-value-startup-employees",
    shape: "guesstimate",
    title: "Estimate the paper ESOP wealth held by Indian startup employees.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 22,
    answer: "Roughly 60,000 to 1 lakh crore rupees of paper value, thinly distributed.",
    hints: ["ESOP pools as a share of startup valuations, times the funded universe."],
    moves: [
      { label: "Move 1", text: "Universe: funded Indian startups carry a combined valuation in the range of 25 to 35 lakh crore rupees." },
      { label: "Move 2", text: "Pool share: ESOP pools run 5 to 10% of cap tables; allocated portions are perhaps 60% of pools." },
      { label: "Move 3", text: "Compute: 30 lakh crore times 7% times 0.6 gives about 1.2 lakh crore allocated... haircut private valuations by a third for realism." },
      { label: "Move 4", text: "Distribution: a small senior cohort holds most of it; the median holder's stake is modest." },
      { label: "Check", text: "Actual liquidity events (buybacks) total only a few thousand crore a year; paper wealth and realised wealth differ by an order of magnitude." },
    ],
    pitfalls: [
      "Valuing pools at peak-cycle marks.",
      "Assuming allocation equals the full pool.",
      "Confusing paper value with realisable value.",
    ],
  },
  {
    slug: "absenteeism-cost-factory",
    shape: "guesstimate",
    title: "Estimate the annual cost of 12% absenteeism at a 5,000-worker plant.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 40 to 70 crore rupees through buffer staffing, overtime and lost output.",
    hints: ["Absenteeism is paid for three times: buffer heads, overtime, and disruption."],
    moves: [
      { label: "Move 1", text: "Direct buffer: covering 12% absence needs about 600 extra workers on rolls; at 3 lakh a year each, 18 crore." },
      { label: "Move 2", text: "Overtime: unpredictable spikes covered at 2x wage rates add several crore." },
      { label: "Move 3", text: "Disruption: line rebalancing, quality dips and supervisor time when skilled positions go empty; conservatively 1 to 2% of plant output value." },
      { label: "Move 4", text: "Sum: direct plus overtime plus disruption lands between 40 and 70 crore for a mid-size plant." },
      { label: "Check", text: "Absence is not uniform: Mondays, festivals and harvest weeks spike; the cost lives in the spikes, not the average." },
    ],
    pitfalls: [
      "Costing only the buffer headcount.",
      "Using average absence when spikes drive the pain.",
      "Ignoring skill-specific absences that stop whole lines.",
    ],
  },
  {
    slug: "campus-placement-season-volume",
    shape: "guesstimate",
    title: "Estimate offers made in one MBA placement season across India.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 3 to 4 lakh offers across all MBA programs in a season.",
    hints: ["Graduating MBA seats times placement and multiple-offer rates."],
    moves: [
      { label: "Move 1", text: "Seats: India graduates about 3.5 to 4 lakh MBA students a year across 3,000+ institutes." },
      { label: "Move 2", text: "Placement reach: top institutes place near 100% with multiple offers; the long tail places 50 to 70% with single offers." },
      { label: "Move 3", text: "Offer multiplier: blending 1.3 offers per placed student at the top with 1.0 in the tail gives about 1.1." },
      { label: "Move 4", text: "Compute: 3.7 lakh students times 75% placed times 1.1 gives about 3 lakh offers." },
      { label: "Check", text: "Median salary and offer count move oppositely down the institute tail; any question about 'MBA placements' must say which segment." },
    ],
    pitfalls: [
      "Extrapolating top-20 campus statistics to 3,000 institutes.",
      "Ignoring multiple offers at top schools.",
      "Counting internship PPOs and final offers twice.",
    ],
  },
  {
    slug: "hr-analytics-team-size",
    shape: "guesstimate",
    title: "Size the people-analytics team a 1-lakh-employee firm should run.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 10 to 20 people spanning reporting, analytics and data engineering.",
    hints: ["Benchmark per 10,000 employees, then split by maturity of the stack."],
    moves: [
      { label: "Move 1", text: "Benchmark: mature firms run 1 to 2 analytics people per 10,000 employees." },
      { label: "Move 2", text: "Compute: 1 lakh employees suggests 10 to 20." },
      { label: "Move 3", text: "Split roles: half on recurring reporting and dashboards, a third on deep-dives (attrition models, comp equity), the rest on data plumbing." },
      { label: "Move 4", text: "Adjust for stack maturity: messy multi-system data doubles the plumbing share for two years." },
      { label: "Check", text: "If the team only produces dashboards nobody acts on, size was never the problem; anchor the question in decisions served." },
    ],
    pitfalls: [
      "Building a large team atop unintegrated data systems.",
      "Counting HRMS admin staff as analytics capacity.",
      "Sizing by fashion rather than by decisions the team serves.",
    ],
  },
  {
    slug: "blue-collar-jobs-ecommerce-festive",
    shape: "guesstimate",
    title: "Estimate temporary jobs e-commerce creates each festive season.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 8 to 12 lakh seasonal roles across warehousing, delivery and support.",
    hints: ["Scale the permanent logistics workforce by the surge ratio."],
    moves: [
      { label: "Move 1", text: "Base workforce: e-commerce logistics employs roughly 15 to 20 lakh across the year." },
      { label: "Move 2", text: "Surge: festive volume runs 2.5 to 3x normal for 6 to 8 weeks, but productivity stretch and overtime absorb part of it." },
      { label: "Move 3", text: "Hiring ratio: platforms add 50 to 70% temporary headcount over base during the window." },
      { label: "Move 4", text: "Compute: 17 lakh times 0.6 gives about 10 lakh seasonal roles, concentrated in warehousing and last-mile." },
      { label: "Check", text: "The same worker cycles through multiple seasons and platforms; jobs created is not unique people employed." },
    ],
    pitfalls: [
      "Scaling headcount linearly with volume, ignoring overtime absorption.",
      "Double counting workers across platforms.",
      "Treating 8-week roles as annual employment in comparisons.",
    ],
  },
  {
    slug: "workplace-canteen-subsidy-cost",
    shape: "guesstimate",
    title: "Estimate the annual canteen subsidy bill for a 30,000-person campus.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 50 to 90 crore rupees a year at meaningful subsidy levels.",
    hints: ["Meals served times subsidy per meal times working days."],
    moves: [
      { label: "Move 1", text: "Meals: 70% of 30,000 eat one subsidised meal daily, plus snacks; call it 25,000 meal-equivalents a day." },
      { label: "Move 2", text: "Subsidy: a 120-rupee meal charged at 40 means an 80-rupee subsidy." },
      { label: "Move 3", text: "Multiply: 25,000 times 80 times 250 working days gives 50 crore." },
      { label: "Move 4", text: "Add hidden lines: kitchen capex amortisation, staff cafeterias running below scale, and event catering push it higher." },
      { label: "Check", text: "Per-employee this is about 17,000 rupees a year, a benefits line worth stating in CTC discussions." },
    ],
    pitfalls: [
      "Assuming everyone eats every meal at the canteen.",
      "Quoting food cost while ignoring operating subsidy.",
      "Forgetting hybrid attendance cuts meal counts.",
    ],
  },
  {
    slug: "six-day-week-productivity-debate",
    shape: "guesstimate",
    title: "Estimate the output change if a 10,000-person firm moves from 5 to 6 working days.",
    type: "Productivity estimation",
    difficulty: 3,
    minutes: 22,
    answer: "Far less than the naive 20%: realistically 5 to 10% initially, decaying toward zero within quarters as fatigue and attrition bite.",
    hints: ["Hours in does not equal output out; model fatigue and attrition explicitly."],
    moves: [
      { label: "Move 1", text: "Naive math: 6 days over 5 suggests 20% more hours." },
      { label: "Move 2", text: "Fatigue discount: sustained-overwork studies show hourly productivity falling as weekly hours rise; the sixth day delivers perhaps half its nominal hours." },
      { label: "Move 3", text: "Attrition effect: if the policy lifts attrition even 3 points in a knowledge workforce, replacement and ramp costs erase several points of output." },
      { label: "Move 4", text: "Net: 8 to 10% early, eroding as fatigue accumulates and the best-optioned employees leave first." },
      { label: "Check", text: "Selection matters: the people most able to leave over a sixth day are the highest-value ones; the average hides who exits." },
    ],
    pitfalls: [
      "Equating scheduled hours with productive output.",
      "Ignoring differential attrition of top performers.",
      "Treating factory-floor and knowledge-work responses as identical.",
    ],
  },
  {
    slug: "diversity-hiring-funnel-target",
    shape: "guesstimate",
    title: "A firm wants 40% women in campus hiring. Estimate the funnel it needs.",
    type: "Funnel estimation",
    difficulty: 2,
    minutes: 18,
    answer: "For 1,000 hires, roughly 10,000+ women applicants given typical conversion, which forces campus selection and outreach changes upstream.",
    hints: ["Work the target backward through each funnel stage's conversion."],
    moves: [
      { label: "Move 1", text: "Target: 400 women among 1,000 hires." },
      { label: "Move 2", text: "Funnel: at 4% application-to-offer conversion, 400 offers need about 10,000 women applicants." },
      { label: "Move 3", text: "Supply reality: if target campuses graduate 30% women in relevant streams, a 33,000-applicant pool yields the 10,000 only with proportionate outreach." },
      { label: "Move 4", text: "Levers: add women-majority campuses, remove biased screens (verified by pass-through analysis), and separate shortlists before interviews." },
      { label: "Check", text: "If conversion rates differ by gender at any stage, fix the stage before inflating the top of the funnel." },
    ],
    pitfalls: [
      "Setting outcome targets without funnel math.",
      "Inflating applications while a biased screen wastes them.",
      "Ignoring the campus mix as the upstream constraint.",
    ],
  },
  {
    slug: "sales-incentive-payout-fmcg",
    shape: "guesstimate",
    title: "Estimate the annual sales-incentive pool for an FMCG field force of 3,000.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 90 to 180 crore rupees, at 20 to 40% of fixed pay for the field force.",
    hints: ["Incentive as a share of on-target earnings, times the force."],
    moves: [
      { label: "Move 1", text: "Pay anchor: field sales fixed pay averages 4 to 6 lakh across levels." },
      { label: "Move 2", text: "Variable design: on-target incentive runs 25 to 35% of fixed for frontline sales." },
      { label: "Move 3", text: "Compute: 3,000 people times 5 lakh times 30% gives 45 crore at target." },
      { label: "Move 4", text: "Overachievement and contests: actual payouts run 1.2 to 1.5x target pools in good years; add managerial layers to reach 90+ crore." },
      { label: "Check", text: "Payout curves define behaviour: caps suppress stretch, cliffs manufacture quarter-end dumping; the pool's shape matters more than its size." },
    ],
    pitfalls: [
      "Budgeting exactly at target with no overachievement provision.",
      "One incentive ratio across frontline and managers.",
      "Ignoring contest and scheme spends outside the formal plan.",
    ],
  },
  {
    slug: "remote-work-attrition-difference",
    shape: "guesstimate",
    title: "Estimate the attrition impact of revoking full-remote work at a 10,000-person firm.",
    type: "Impact estimation",
    difficulty: 3,
    minutes: 22,
    answer: "Plausibly 5 to 10 extra points of attrition in the first year, concentrated in the most marketable cohorts.",
    hints: ["Segment by who moved cities and who has remote-friendly alternatives."],
    moves: [
      { label: "Move 1", text: "Exposure: survey data typically shows 15 to 25% relocated or arranged life around remote; for 10,000 people, say 2,000 highly exposed." },
      { label: "Move 2", text: "Alternatives: the exposed skew senior and marketable; perhaps 30 to 40% can land remote roles elsewhere within months." },
      { label: "Move 3", text: "Compute: 2,000 times 0.35 gives 700 elevated-risk exits, or 7 points over baseline." },
      { label: "Move 4", text: "Time path: exits spread over 2 to 3 quarters as people search; the cliff is delayed, not absent." },
      { label: "Check", text: "The composition costs more than the count: leavers over this issue are disproportionately the ones with options." },
    ],
    pitfalls: [
      "Averaging risk over everyone instead of the exposed cohort.",
      "Expecting the attrition on announcement day rather than over quarters.",
      "Counting heads while ignoring the seniority skew of leavers.",
    ],
  },
  {
    slug: "pf-accounts-active-india",
    shape: "guesstimate",
    title: "Estimate active EPF contributors in India.",
    type: "Market sizing",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 6.5 to 7.5 crore active monthly contributors.",
    hints: ["Formal employees above the wage threshold in covered establishments."],
    moves: [
      { label: "Move 1", text: "Base: organised-sector employment of 8 to 10 crore." },
      { label: "Move 2", text: "Coverage: establishments above 20 employees must enrol most staff; exclusions and exempted trusts trim it." },
      { label: "Move 3", text: "Estimate: about 70 to 80% of the organised base contributes monthly, giving around 7 crore." },
      { label: "Move 4", text: "Distinguish stocks: total accounts (25+ crore) versus active contributors (about 7 crore); dormancy from job churn explains the gap." },
      { label: "Check", text: "EPFO's monthly payroll data is the cleanest formal-jobs signal in India precisely because of this arithmetic." },
    ],
    pitfalls: [
      "Quoting cumulative accounts as active members.",
      "Forgetting exempted establishments running own trusts.",
      "Mixing EPS pensioners into contributor counts.",
    ],
  },
  {
    slug: "town-hall-cost-quarterly",
    shape: "guesstimate",
    title: "Estimate what a quarterly all-hands costs a 50,000-person company.",
    type: "Cost estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 15 to 25 crore rupees per edition, almost all of it attention time.",
    hints: ["The venue is cheap; 50,000 salaries for 90 minutes are not."],
    moves: [
      { label: "Move 1", text: "Time cost: 50,000 people times 1.5 hours at an 800-rupee loaded hour gives 6 crore." },
      { label: "Move 2", text: "Add preparation: leadership rehearsals, content teams, production and dry runs involve hundreds of people for days, another 1 to 2 crore." },
      { label: "Move 3", text: "Add disruption: shift-covered functions need backfill; global time zones force repeats." },
      { label: "Move 4", text: "Sum: 8 to 10 crore per edition conservatively; grand physical events multiply it." },
      { label: "Check", text: "Cost per minute of airtime focuses the mind: a rambling 30 minutes costs crores; the estimate is an argument for editing." },
    ],
    pitfalls: [
      "Counting event production but not audience time.",
      "Using average salary instead of loaded cost.",
      "Ignoring time-zone repeat sessions.",
    ],
  },
  {
    slug: "skilling-mission-throughput",
    shape: "guesstimate",
    title: "Estimate training centres needed to skill 1 crore youth in 3 years.",
    type: "Network sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 10,000 to 15,000 centres running multiple batches a year.",
    hints: ["Annual throughput per centre times centres times years must reach 1 crore."],
    moves: [
      { label: "Move 1", text: "Annual need: 1 crore over 3 years is about 33 lakh trainees a year." },
      { label: "Move 2", text: "Centre throughput: a centre with 4 classrooms of 30 running 3-month courses turns out about 1,000 to 1,400 trainees a year at realistic utilisation." },
      { label: "Move 3", text: "Divide: 33 lakh over 1,200 gives about 2,750 centres... at claimed utilisation. Real fill rates near 60% push it past 4,500." },
      { label: "Move 4", text: "Add distribution: district-level coverage forces centres where demand is thin, inflating the count toward 10,000+." },
      { label: "Check", text: "Placement, not enrolment, is the honest metric; centres sized to enrolment targets routinely train for jobs that do not exist locally." },
    ],
    pitfalls: [
      "Assuming full batch occupancy year-round.",
      "Optimising centre count against enrolment rather than placement.",
      "Ignoring trainer supply as the real constraint.",
    ],
  },
];
