import type { Question } from "./types";

// Marketing and brand cases. Every answer commits to a position and names what
// it is giving up, because a marketing plan that sacrifices nothing is not a plan.
export const MARKETING_CASES: Question[] = [
  {
    slug: "biscuit-brand-south-share-loss",
    shape: "case",
    title: "A biscuit brand lost four share points in the south. Find out why.",
    type: "Share loss",
    difficulty: 3,
    minutes: 30,
    askedAt: "Britannia",
    answer: "Distribution rather than brand: lost reach and stock availability against a regional entrant, compounded by dealer margin.",
    hints: ["Share is relative. Confirm whether you lost volume or someone else grew faster."],
    moves: [
      { label: "Move 1", text: "Establish whether absolute volume fell or the category grew around a flat business." },
      { label: "Move 2", text: "Work distribution first: numeric and weighted reach, out-of-stock rates, and dealer margin against the competitor." },
      { label: "Move 3", text: "Check price and pack, since a competitor holding pack size while you shrink it reads as a price rise." },
      { label: "Move 4", text: "Only then examine brand and taste preference, and check for a regional entrant with local advantage." },
      { label: "Close", text: "Localise the response. A national campaign for a three-state problem costs more than the share is worth." },
    ],
    pitfalls: [
      "Starting with brand perception when the answer is nearly always at the shelf.",
      "Not separating volume decline from category growth.",
      "Missing dealer margin, invisible to consumers and decisive to stockists.",
    ],
  },
  {
    slug: "protein-drink-tier-2-gtm",
    shape: "case",
    title: "Launch a protein drink for tier-2 India. Build the go-to-market.",
    type: "Go-to-market",
    difficulty: 2,
    minutes: 30,
    askedAt: "Nestle",
    answer: "One low price point in a small pack, chemist plus kirana, with local trainer and doctor credibility. One state first.",
    hints: ["Decide who this is for before deciding anything else. Protein means different things to different buyers."],
    moves: [
      { label: "Move 1", text: "Define the buyer. A gym-goer and a mother buying child nutrition are different products under one word." },
      { label: "Move 2", text: "Set the price point first and let it dictate pack size, since the affordable unit determines the format." },
      { label: "Move 3", text: "Choose channels deliberately. Chemists carry health credibility, kirana carries reach, quick commerce barely exists here." },
      { label: "Move 4", text: "Build credibility locally, since doctor and trainer endorsement travels further than national advertising." },
      { label: "Close", text: "Give a phased plan with a named first market and a measurable trigger for expanding." },
    ],
    pitfalls: [
      "Copying a metro launch plan into a different channel and price environment.",
      "Choosing pack size before price point.",
      "Producing a plan with no first market and no expansion trigger.",
    ],
  },
  {
    slug: "premium-tea-discounting",
    shape: "case",
    title: "A premium tea brand is being discounted into irrelevance. Fix the positioning.",
    type: "Positioning",
    difficulty: 3,
    minutes: 30,
    askedAt: "Unilever",
    answer: "Rebuild on a defensible difference such as single-estate origin, pull back from mass discount channels, and accept the volume loss.",
    hints: ["Persistent discounting is a symptom. Find what stopped justifying the premium."],
    moves: [
      { label: "Move 1", text: "Find the source. Brand-led promotion, trade-led price cutting and marketplace undercutting need different responses." },
      { label: "Move 2", text: "Test whether the premium is perceivable. If blind use cannot tell the difference, positioning will not hold the price." },
      { label: "Move 3", text: "Examine the channel, since sitting under the same discount banner as mass brands destroys the frame of reference." },
      { label: "Move 4", text: "Rebuild differentiation on something defensible: origin, single estate, or a ritual occasion." },
      { label: "Close", text: "Accept the volume loss explicitly. Recovering a premium always costs share, and pretending otherwise is dishonest." },
    ],
    pitfalls: [
      "Treating discounting as the disease rather than the symptom.",
      "Repositioning on a claim competitors can copy in a quarter.",
      "Promising premium recovery with no volume cost.",
    ],
  },
  {
    slug: "channel-mix-two-crore-budget",
    shape: "case",
    title: "Choose the channel mix for a two crore rupee launch budget.",
    type: "Channel mix",
    difficulty: 2,
    minutes: 25,
    answer: "One region, high frequency, measurable digital and retail media first, with about 15% held back to reallocate after the first read.",
    hints: ["Two crore is small. Spreading it across every channel guarantees invisibility everywhere."],
    moves: [
      { label: "Move 1", text: "Fix the objective and the geography, since national awareness is not achievable on this budget." },
      { label: "Move 2", text: "Establish the frequency threshold. Reaching a small audience often beats reaching a large one once." },
      { label: "Move 3", text: "Bias allocation toward measurable channels early, which give a read within weeks." },
      { label: "Move 4", text: "Hold back roughly 15% for reallocation, and name the metric that triggers the shift." },
      { label: "Close", text: "Present the split with reasoning per line. The allocation is not the answer, the logic is." },
    ],
    pitfalls: [
      "Spreading a small budget across every available channel.",
      "Allocating before naming objective and geography.",
      "Leaving no budget or plan for measurement.",
    ],
  },
  {
    slug: "quick-commerce-coupon-spend-up",
    shape: "case",
    title: "A quick commerce app's coupon spend is up 60% and orders are flat. Act.",
    type: "Promotion",
    difficulty: 3,
    minutes: 30,
    askedAt: "Zepto",
    answer: "Coupons are subsidising customers who would have ordered anyway. Move to targeted offers and accept a short-term order dip.",
    hints: ["Ask whether the coupons are buying incremental orders or discounting existing ones."],
    moves: [
      { label: "Move 1", text: "Split coupon redemptions by user type. Existing frequent users redeeming is pure margin loss." },
      { label: "Move 2", text: "Run a holdout. Withhold coupons from a matched group and measure the actual order difference." },
      { label: "Move 3", text: "Check the competitive context, since matching a rival's discounting can be defensive rather than growth spend." },
      { label: "Move 4", text: "Redesign targeting: offers to lapsed and low-frequency users, none to already-loyal ones." },
      { label: "Close", text: "Recommend the change with the expected order dip stated, since hiding it makes the plan unacceptable when it happens." },
    ],
    pitfalls: [
      "Judging coupons on redemption rate rather than incrementality.",
      "Never running a holdout, which is the only clean measurement.",
      "Cutting promotions without warning stakeholders about the dip.",
    ],
  },
  {
    slug: "reposition-masala-brand-for-young-households",
    shape: "case",
    title: "Reposition a 40 year old masala brand for households under 30.",
    type: "Brand",
    difficulty: 2,
    minutes: 25,
    askedAt: "MDH",
    answer: "Change the format and the occasion, not the brand's meaning. Heritage is the asset, inconvenience is the problem.",
    hints: ["Ask what young households actually reject: the brand, or how the product fits their cooking."],
    moves: [
      { label: "Move 1", text: "Diagnose the rejection. Younger households often cook less and differently, rather than distrusting the brand." },
      { label: "Move 2", text: "Protect the equity. Heritage and authenticity are the brand's asset and should not be discarded." },
      { label: "Move 3", text: "Change the format: smaller packs, ready blends, and formats that suit less experienced cooks." },
      { label: "Move 4", text: "Change the channel and communication, since this audience discovers food through digital, not through television." },
      { label: "Close", text: "Recommend format-led repositioning, and name what must not change about the brand." },
    ],
    pitfalls: [
      "Modernising the brand identity and losing the authenticity that gave it value.",
      "Assuming the problem is perception rather than product fit.",
      "Chasing a young audience while alienating the existing loyal base.",
    ],
  },
  {
    slug: "launch-a-brand-with-no-media-budget",
    shape: "case",
    title: "Launch a consumer brand with almost no media budget.",
    type: "Go-to-market",
    difficulty: 3,
    minutes: 30,
    answer: "Win a narrow audience completely rather than reaching a broad one thinly. Distribution focus and word of mouth substitute for spend.",
    hints: ["Without money you need concentration. Pick a narrow enough audience that you can dominate it."],
    moves: [
      { label: "Move 1", text: "Narrow the target until domination is affordable, whether that is one city, one community or one channel." },
      { label: "Move 2", text: "Concentrate distribution. Being available everywhere your narrow audience shops beats thin national presence." },
      { label: "Move 3", text: "Engineer word of mouth through a product feature worth talking about, not through a campaign asking people to share." },
      { label: "Move 4", text: "Use owned and earned channels: community, founder presence and content rather than paid reach." },
      { label: "Close", text: "Define the expansion trigger, since the plan only works if the narrow win is genuinely reinvested." },
    ],
    pitfalls: [
      "Spreading a small budget thinly to look national.",
      "Relying on virality without a product reason for it.",
      "Never defining what success in the narrow market looks like.",
    ],
  },
  {
    slug: "brand-facing-a-social-media-backlash",
    shape: "case",
    title: "A brand is facing a social media backlash. Respond.",
    type: "Brand",
    difficulty: 3,
    minutes: 25,
    answer: "Establish whether the criticism is valid first. A genuine fault needs correction and apology, a manufactured outrage needs a calm factual reply and patience.",
    hints: ["The first question is whether they are right. Everything else follows from that."],
    moves: [
      { label: "Move 1", text: "Establish the facts. If the criticism is valid, no communication strategy will substitute for fixing it." },
      { label: "Move 2", text: "Assess the scale honestly, since social volume often overstates how many people actually care." },
      { label: "Move 3", text: "Choose the channel. Responding where the criticism lives, once, beats a press release." },
      { label: "Move 4", text: "Act visibly if at fault. An apology without a corrective action is read as public relations." },
      { label: "Close", text: "Recommend the response and the internal fix, and note that over-responding to a small backlash amplifies it." },
    ],
    pitfalls: [
      "Responding before establishing whether the criticism is valid.",
      "Treating a small vocal group as representative.",
      "Apologising with no corrective action attached.",
    ],
  },
  {
    slug: "should-we-sponsor-a-cricket-team",
    shape: "case",
    title: "Should a mid-size brand sponsor a cricket team?",
    type: "Channel mix",
    difficulty: 2,
    minutes: 25,
    answer: "Only with activation budget alongside the rights fee. Buying the logo and doing nothing with it wastes most of the value.",
    hints: ["Sponsorship needs money on top of the fee. Budget for that or do not do it."],
    moves: [
      { label: "Move 1", text: "Value the media exposure at discounted advertising equivalent, since logo exposure is passive." },
      { label: "Move 2", text: "Value the rights beyond the logo: player access, hospitality and content creation." },
      { label: "Move 3", text: "Budget activation, typically comparable to the rights fee itself, to actually use what was bought." },
      { label: "Move 4", text: "Compare against buying the same reach directly through advertising, which is usually cheaper per impression." },
      { label: "Close", text: "Recommend only if the activation budget exists and the brand has a reason to be in this context." },
    ],
    pitfalls: [
      "Valuing sponsorship at full advertising rates.",
      "Buying rights without activation budget.",
      "Sponsoring for internal enthusiasm rather than audience fit.",
    ],
  },
  {
    slug: "private-label-attacking-our-brand",
    shape: "case",
    title: "A retailer's private label is taking share from your brand. Respond.",
    type: "Competitive response",
    difficulty: 3,
    minutes: 30,
    answer: "Do not match the price. Widen the gap through demonstrable product difference, or accept a smaller but defensible share.",
    hints: ["You cannot win a price war against a retailer who controls the shelf and pays no marketing cost."],
    moves: [
      { label: "Move 1", text: "Understand the retailer's advantage: no marketing cost, controlled shelf position and full margin capture." },
      { label: "Move 2", text: "Assess your differentiation honestly. If the product is indistinguishable, the brand cannot hold a premium." },
      { label: "Move 3", text: "Consider the relationship, since the retailer is both competitor and route to market." },
      { label: "Move 4", text: "Choose: invest in genuine product difference, or accept lower share at defended margin." },
      { label: "Close", text: "Recommend one path clearly and note that matching price simply funds the retailer's margin from yours." },
    ],
    pitfalls: [
      "Entering a price war you cannot win.",
      "Ignoring that the retailer is also your distribution channel.",
      "Assuming brand equity alone will hold a premium on a commodity product.",
    ],
  },
  {
    slug: "pricing-a-new-product-with-no-reference",
    shape: "case",
    title: "Price a product with no direct comparison in the market.",
    type: "Pricing",
    difficulty: 3,
    minutes: 30,
    answer: "Price against the alternative the customer uses today, not against your cost. What they currently spend and suffer is the real reference.",
    hints: ["There is always a reference price. Find what the customer does instead of buying you."],
    moves: [
      { label: "Move 1", text: "Identify the substitute, which may be a different product, a service or doing nothing." },
      { label: "Move 2", text: "Quantify the value delivered against that alternative in money or time saved." },
      { label: "Move 3", text: "Choose a share of that value to capture, leaving enough to make switching worthwhile." },
      { label: "Move 4", text: "Test the price point rather than deriving it, since willingness to pay is rarely predictable in a new category." },
      { label: "Close", text: "Recommend launching high with promotional flexibility, since raising prices later is far harder than discounting." },
    ],
    pitfalls: [
      "Cost-plus pricing, which ignores what the product is worth.",
      "Assuming no comparison exists when the customer always has an alternative.",
      "Launching low and trying to raise prices later.",
    ],
  },
  {
    slug: "declining-relevance-of-a-legacy-brand",
    shape: "case",
    title: "A legacy brand's buyers are ageing and not being replaced. Fix it.",
    type: "Brand",
    difficulty: 3,
    minutes: 30,
    answer: "Recruit younger buyers through a new occasion or format while protecting the existing base. Attempting to become young usually loses both.",
    hints: ["Chasing youth while ignoring the loyal base is how legacy brands accelerate their own decline."],
    moves: [
      { label: "Move 1", text: "Quantify the demographics. Establish the actual replacement rate and how long the current base sustains the business." },
      { label: "Move 2", text: "Diagnose the non-adoption. Younger consumers may reject the occasion rather than the brand." },
      { label: "Move 3", text: "Find a bridge: a new format, occasion or channel that recruits without repudiating the heritage." },
      { label: "Move 4", text: "Protect the existing base, which still funds everything and is easily alienated by a repositioning." },
      { label: "Close", text: "Recommend the bridge strategy, and be explicit that a full youth repositioning risks losing both audiences." },
    ],
    pitfalls: [
      "Repositioning wholesale toward a younger audience.",
      "Assuming the brand is rejected when the occasion is what changed.",
      "Ignoring how long the existing base can fund the transition.",
    ],
  },
  {
    slug: "distribution-expansion-into-rural",
    shape: "case",
    title: "An urban FMCG brand wants to expand into rural markets. How?",
    type: "Go-to-market",
    difficulty: 2,
    minutes: 30,
    answer: "Change the pack and the price point before changing anything else, and use a distributor structure built for low volumes per outlet.",
    hints: ["Rural is not a smaller version of urban. The pack, the price and the route to market are all different."],
    moves: [
      { label: "Move 1", text: "Fix the price point first. Rural buying is anchored to small denominations, which dictates pack size." },
      { label: "Move 2", text: "Redesign distribution. Reaching thousands of tiny outlets needs sub-distributors and van operations." },
      { label: "Move 3", text: "Rethink communication, since rural media consumption and language differ substantially from urban." },
      { label: "Move 4", text: "Set realistic expectations on rate of sale per outlet, which is a fraction of urban levels." },
      { label: "Close", text: "Recommend phased state-by-state expansion, and name the distribution economics that must hold." },
    ],
    pitfalls: [
      "Taking urban packs and prices into rural markets unchanged.",
      "Underestimating the cost of servicing scattered small outlets.",
      "Expecting urban rates of sale per outlet.",
    ],
  },
  {
    slug: "measure-brand-campaign-effectiveness",
    shape: "case",
    title: "How would you measure whether a brand campaign worked?",
    type: "Metrics",
    difficulty: 2,
    minutes: 25,
    answer: "A regional holdout comparing sales where the campaign ran against where it did not. Recall surveys alone measure the campaign, not the business.",
    hints: ["The only clean measurement is a region that did not see the campaign."],
    moves: [
      { label: "Move 1", text: "Reject attribution as sufficient, since brand advertising rarely produces a traceable click." },
      { label: "Move 2", text: "Design a geographic holdout, matching regions on prior sales trend and running the campaign in only some." },
      { label: "Move 3", text: "Measure sales difference over a window long enough to capture the effect, which for brand work is months not weeks." },
      { label: "Move 4", text: "Track brand metrics alongside as intermediate indicators, but do not treat them as the outcome." },
      { label: "Close", text: "Recommend the holdout design with the measurement window and the required sales difference named." },
    ],
    pitfalls: [
      "Measuring campaign success by recall alone.",
      "Using too short a window for brand effects to appear.",
      "Not matching holdout and test regions on prior trend.",
    ],
  },
  {
    slug: "two-brands-cannibalising-each-other",
    shape: "case",
    title: "Two of your own brands are cannibalising each other. Resolve it.",
    type: "Positioning",
    difficulty: 2,
    minutes: 25,
    answer: "Separate them on occasion or price tier, and if they cannot be separated, merge them and stop funding two marketing budgets.",
    hints: ["Ask whether both brands earn their marketing budget or whether one is simply history."],
    moves: [
      { label: "Move 1", text: "Quantify the overlap. Buyer overlap and switching data show whether they genuinely compete." },
      { label: "Move 2", text: "Test differentiation. If consumers cannot articulate the difference, there is not one." },
      { label: "Move 3", text: "Consider re-tiering: separating clearly on price and occasion rather than on communication alone." },
      { label: "Move 4", text: "Consider merging, since two half-funded brands usually lose to one properly funded one." },
      { label: "Close", text: "Recommend one path and quantify the marketing efficiency gain, which is the main argument for merging." },
    ],
    pitfalls: [
      "Assuming cannibalisation is always bad when it can pre-empt a competitor.",
      "Differentiating through communication when the products are identical.",
      "Keeping both brands out of internal attachment rather than economics.",
    ],
  },
  {
    slug: "influencer-campaign-underperformed",
    shape: "case",
    title: "An influencer campaign delivered views but no sales. Diagnose it.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Usually an audience mismatch or a missing path to purchase. Views are the cheapest metric to buy and the least meaningful.",
    hints: ["Views measure delivery, not fit. Check who actually watched."],
    moves: [
      { label: "Move 1", text: "Check audience fit. A creator's audience may be large and entirely wrong for the product." },
      { label: "Move 2", text: "Check authenticity of the audience, since inflated follower counts remain common." },
      { label: "Move 3", text: "Check the path to purchase. Views with no easy route to buy convert poorly regardless of interest." },
      { label: "Move 4", text: "Check the product-content fit, since forced integrations are visibly promotional and convert badly." },
      { label: "Close", text: "Recommend measuring on tracked conversion rather than views, and name the creator selection criteria you would apply next." },
    ],
    pitfalls: [
      "Selecting creators on follower count.",
      "Measuring on views, which are cheap to inflate.",
      "Not building a trackable purchase path before the campaign runs.",
    ],
  },
  {
    slug: "expand-into-a-new-category",
    shape: "case",
    title: "A successful hair oil brand wants to enter face care. Advise.",
    type: "New product",
    difficulty: 2,
    minutes: 30,
    answer: "Test brand permission before investing. Trust in one category does not automatically transfer to another, particularly across body areas.",
    hints: ["Ask whether consumers would accept this brand on their face. That is an empirical question, not a strategic one."],
    moves: [
      { label: "Move 1", text: "Test brand permission directly with consumers rather than assuming equity transfers." },
      { label: "Move 2", text: "Assess capability. Face care formulation, regulation and claims differ substantially from hair oil." },
      { label: "Move 3", text: "Check the competitive set, which is more crowded and more marketing-intensive than hair care." },
      { label: "Move 4", text: "Consider the channel, since face care skews more toward modern trade and e-commerce." },
      { label: "Close", text: "Recommend a test launch in one channel, and name the permission result that would stop the plan." },
    ],
    pitfalls: [
      "Assuming brand trust transfers across body areas.",
      "Underestimating formulation and regulatory differences.",
      "Committing to full national launch before testing permission.",
    ],
  },
  {
    slug: "trade-promotion-not-reaching-consumers",
    shape: "case",
    title: "Trade promotions are not reaching consumers. Investigate.",
    type: "Promotion",
    difficulty: 3,
    minutes: 30,
    answer: "The margin is being retained by the trade rather than passed to shoppers. Move to consumer-facing promotions where you control the mechanism.",
    hints: ["Money given to the trade tends to stay with the trade unless the mechanism prevents it."],
    moves: [
      { label: "Move 1", text: "Audit shelf prices during promotion periods to confirm whether prices actually fell." },
      { label: "Move 2", text: "Check for diversion, where stock bought at promotional rates is sold in other regions or held for later." },
      { label: "Move 3", text: "Examine the mechanism, since a margin given upfront is easily retained." },
      { label: "Move 4", text: "Shift to consumer promotions: on-pack offers, coupons or price-marked packs the retailer cannot capture." },
      { label: "Close", text: "Recommend the mechanism change with the monitoring you would put in place to verify pass-through." },
    ],
    pitfalls: [
      "Assuming trade discounts reach shoppers.",
      "Ignoring stock diversion between regions.",
      "Increasing promotional depth rather than changing the mechanism.",
    ],
  },
  {
    slug: "communicating-a-price-increase",
    shape: "case",
    title: "You must raise prices 12%. How do you communicate it?",
    type: "Pricing",
    difficulty: 2,
    minutes: 25,
    answer: "Stage it, give the trade notice, and consider grammage reduction where the price point is psychologically fixed.",
    hints: ["In India the price point is often more rigid than the quantity. That opens an option."],
    moves: [
      { label: "Move 1", text: "Check the price point. Crossing a psychological threshold causes disproportionate volume loss." },
      { label: "Move 2", text: "Consider grammage reduction, which is standard practice and preserves the price point." },
      { label: "Move 3", text: "Stage the increase, since two smaller rises are absorbed better than one large one." },
      { label: "Move 4", text: "Manage the trade. Distributors need notice to manage stock they bought at the old price." },
      { label: "Close", text: "Recommend the approach with the expected volume impact stated and the competitor response anticipated." },
    ],
    pitfalls: [
      "Crossing a psychological price point without recognising the effect.",
      "Raising prices with no trade notice, which causes stock disputes.",
      "Ignoring what competitors are likely to do.",
    ],
  },
  {
    slug: "our-ad-is-working-but-competitors-benefit",
    shape: "case",
    title: "Your advertising is growing the category, and competitors are benefiting. Act?",
    type: "Competitive response",
    difficulty: 3,
    minutes: 25,
    answer: "Only if you are not capturing your fair share of the growth. Category-building advertising is worthwhile when you are the leader with distribution to convert it.",
    hints: ["Ask whether you capture growth in proportion to your share or less than it."],
    moves: [
      { label: "Move 1", text: "Measure your share of the incremental category growth against your existing market share." },
      { label: "Move 2", text: "Check distribution, since spillover happens when a customer motivated by your ad cannot find your product." },
      { label: "Move 3", text: "Assess the branding. Generic category advertising benefits everyone, distinctive brand assets do not." },
      { label: "Move 4", text: "Consider whether category growth is worth it anyway, which for a dominant leader it usually is." },
      { label: "Close", text: "Recommend distinctive branding plus distribution fixes rather than reducing spend." },
    ],
    pitfalls: [
      "Cutting spend that is genuinely growing your own business.",
      "Ignoring distribution gaps that cause the spillover.",
      "Running category-generic creative with weak brand attribution.",
    ],
  },
  {
    slug: "brand-entering-a-crowded-category",
    shape: "case",
    title: "How would you enter a category with five entrenched brands?",
    type: "Market entry",
    difficulty: 3,
    minutes: 30,
    answer: "Find the underserved segment the incumbents ignore, and win it completely before broadening. Attacking the centre against five funded competitors fails.",
    hints: ["Do not attack the centre. Find the edge nobody is defending."],
    moves: [
      { label: "Move 1", text: "Map the incumbents on positioning and price to find gaps rather than contested ground." },
      { label: "Move 2", text: "Identify the underserved segment, whether defined by need, occasion, geography or price." },
      { label: "Move 3", text: "Build a product genuinely better for that segment rather than marginally different overall." },
      { label: "Move 4", text: "Concentrate distribution and spend on that segment, since spreading thin against funded incumbents fails." },
      { label: "Close", text: "Recommend the beachhead with the expansion trigger, and name the incumbent response you expect." },
    ],
    pitfalls: [
      "Entering with a me-too product at a slightly lower price.",
      "Spreading limited resources across the whole category.",
      "Not anticipating how incumbents will respond to early success.",
    ],
  },
  {
    slug: "packaging-redesign-hurt-sales",
    shape: "case",
    title: "Sales fell after a packaging redesign. What happened?",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Shoppers stopped recognising the product on shelf. Distinctive assets were probably removed in the name of modernisation.",
    hints: ["Shoppers find products by pattern recognition in seconds. Changing the pattern breaks it."],
    moves: [
      { label: "Move 1", text: "Check shelf visibility. Shoppers locate familiar products by colour and shape, not by reading." },
      { label: "Move 2", text: "Identify which distinctive assets changed: colour block, logo position, pack shape." },
      { label: "Move 3", text: "Check whether the trade cooperated, since old and new stock coexisting causes confusion." },
      { label: "Move 4", text: "Test recognition directly with a shelf test measuring find-time for both designs." },
      { label: "Close", text: "Recommend restoring the key distinctive assets, and note that modernisation should be evolutionary in fast-moving categories." },
    ],
    pitfalls: [
      "Judging packaging on design quality rather than shelf findability.",
      "Removing distinctive assets in pursuit of a cleaner look.",
      "Changing everything at once, which makes diagnosis impossible.",
    ],
  },
  {
    slug: "customer-acquisition-cost-rising",
    shape: "case",
    title: "Customer acquisition cost has doubled in a year. Diagnose it.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Usually channel saturation or increased competition for the same auction, not a creative problem.",
    hints: ["Check whether you have exhausted the cheap audience in your existing channels."],
    moves: [
      { label: "Move 1", text: "Check saturation. Repeatedly targeting the same audience reaches the expensive tail after the cheap core." },
      { label: "Move 2", text: "Check auction dynamics, since new competitors bidding on the same terms raise costs for everyone." },
      { label: "Move 3", text: "Check creative fatigue, which raises cost per acquisition through falling click rates." },
      { label: "Move 4", text: "Check tracking changes, since privacy restrictions have degraded attribution and can inflate apparent cost." },
      { label: "Close", text: "Recommend channel diversification with the first alternative named, since squeezing a saturated channel gets worse." },
    ],
    pitfalls: [
      "Blaming creative when the channel is saturated.",
      "Ignoring measurement changes that inflate apparent cost.",
      "Increasing spend in the saturated channel to hit volume targets.",
    ],
  },
  {
    slug: "should-we-run-a-sale",
    shape: "case",
    title: "Should a full-price fashion brand run a discount sale?",
    type: "Promotion",
    difficulty: 2,
    minutes: 25,
    answer: "Yes for genuine end-of-season clearance, but never on a predictable schedule, because trained customers simply wait.",
    hints: ["The danger is not the discount. It is teaching customers when to expect it."],
    moves: [
      { label: "Move 1", text: "Establish the purpose. Clearing seasonal stock is legitimate, driving traffic through discounts is corrosive." },
      { label: "Move 2", text: "Model the training effect. Predictable sales shift full-price buyers into discount buyers permanently." },
      { label: "Move 3", text: "Consider alternatives: outlet channels, member-only events, or bundling that clears stock without a public sale." },
      { label: "Move 4", text: "Size the inventory problem honestly, since unsold fashion inventory loses value fast." },
      { label: "Close", text: "Recommend unpredictable timing and a separated clearance channel, protecting the full-price proposition." },
    ],
    pitfalls: [
      "Running sales on a fixed calendar that customers learn.",
      "Using discounts to solve a demand problem rather than an inventory problem.",
      "Discounting the current season alongside clearance stock.",
    ],
  },
  {
    slug: "b2b-brand-with-no-differentiation",
    shape: "case",
    title: "A B2B industrial brand says its product is identical to competitors. Position it.",
    type: "Positioning",
    difficulty: 3,
    minutes: 30,
    answer: "Differentiate on everything around the product: delivery reliability, technical support and total cost of ownership. In commoditised B2B, service is the product.",
    hints: ["If the product is genuinely identical, the differentiation has to sit around it."],
    moves: [
      { label: "Move 1", text: "Verify the claim. Products described as identical usually differ in consistency or specification tolerance." },
      { label: "Move 2", text: "Map the buying process, since B2B decisions weigh reliability, terms and risk alongside price." },
      { label: "Move 3", text: "Differentiate on service: delivery reliability, technical support, credit terms and inventory management." },
      { label: "Move 4", text: "Shift the conversation to total cost of ownership, which reframes a price comparison into a value one." },
      { label: "Close", text: "Recommend service-led positioning with the specific proof points a procurement team would accept." },
    ],
    pitfalls: [
      "Accepting the commodity framing without verifying it.",
      "Positioning on brand emotion in a procurement-driven purchase.",
      "Competing on price in a category where you have no cost advantage.",
    ],
  },
  {
    slug: "regional-brand-going-national",
    shape: "case",
    title: "A strong regional food brand wants to go national. Advise.",
    type: "Go-to-market",
    difficulty: 3,
    minutes: 30,
    answer: "Expand to adjacent states where taste preferences overlap, and be honest that regional strength often does not transfer.",
    hints: ["Regional food brands are strong precisely because they suit local taste. That is also the constraint."],
    moves: [
      { label: "Move 1", text: "Diagnose the regional strength. Taste, distribution relationships and local familiarity each transfer differently." },
      { label: "Move 2", text: "Test taste transferability, since food preferences vary sharply across Indian regions." },
      { label: "Move 3", text: "Assess the distribution build, which in a new state means starting from nothing against entrenched local brands." },
      { label: "Move 4", text: "Consider adjacent expansion first, where taste and language overlap reduce the risk." },
      { label: "Close", text: "Recommend contiguous expansion with a state-level success threshold before continuing." },
    ],
    pitfalls: [
      "Assuming regional success predicts national success.",
      "Underestimating the cost of building distribution from scratch.",
      "Expanding to distant markets before proving the adjacent ones.",
    ],
  },
  {
    slug: "loyalty-programme-not-working",
    shape: "case",
    title: "A loyalty programme has high enrolment and no behaviour change. Fix it.",
    type: "Promotion",
    difficulty: 2,
    minutes: 25,
    answer: "It is rewarding existing behaviour rather than changing it. Redesign around the marginal customer, not the loyal one.",
    hints: ["Ask whether the rewards change what anyone does, or simply discount what they already did."],
    moves: [
      { label: "Move 1", text: "Check who enrolled. Existing frequent buyers join first and change nothing." },
      { label: "Move 2", text: "Measure incrementality against a matched non-member group rather than comparing members to non-members." },
      { label: "Move 3", text: "Examine the reward structure. Rewards too distant or too small do not change behaviour." },
      { label: "Move 4", text: "Redesign for the marginal customer, targeting frequency or basket size increases specifically." },
      { label: "Close", text: "Recommend the redesign with an incrementality measurement built in from the start." },
    ],
    pitfalls: [
      "Measuring success by enrolment.",
      "Comparing members to non-members, which confuses selection with effect.",
      "Rewarding behaviour that would have happened anyway.",
    ],
  },
  {
    slug: "product-recall-communication",
    shape: "case",
    title: "A quality issue requires a product recall. Handle the communication.",
    type: "Brand",
    difficulty: 3,
    minutes: 30,
    answer: "Recall fast and broadly, communicate directly, and over-compensate affected customers. Cost of the recall is always less than the cost of appearing to have hidden it.",
    hints: ["Speed and completeness matter more than cost. A partial recall that expands later is far worse."],
    moves: [
      { label: "Move 1", text: "Establish scope quickly and err toward a wider recall, since expanding one later destroys credibility." },
      { label: "Move 2", text: "Communicate directly and first, before the story is told by someone else." },
      { label: "Move 3", text: "Make returning easy and compensate generously, since friction here becomes the story." },
      { label: "Move 4", text: "Explain the corrective action, since customers accept mistakes but not repetition." },
      { label: "Close", text: "Recommend the plan and note that recall cost is small against the brand cost of appearing evasive." },
    ],
    pitfalls: [
      "Limiting recall scope to control cost.",
      "Waiting for regulatory instruction before acting.",
      "Making the return process difficult.",
    ],
  },
  {
    slug: "marketplace-versus-own-website",
    shape: "case",
    title: "Should a D2C brand sell on marketplaces or only on its own site?",
    type: "Channel mix",
    difficulty: 2,
    minutes: 25,
    answer: "Both, with different assortments. Marketplaces bring discovery and volume, the own site holds margin and the customer relationship.",
    hints: ["Ask what each channel gives you that the other cannot."],
    moves: [
      { label: "Move 1", text: "Compare the economics. Marketplace commissions are high but acquisition cost is low, and the reverse on own site." },
      { label: "Move 2", text: "Value the customer data, which marketplaces do not share and which drives repeat purchase." },
      { label: "Move 3", text: "Consider discovery. Marketplaces are where category search happens, particularly for unfamiliar brands." },
      { label: "Move 4", text: "Design differentiated assortment so the channels do not compete directly on identical items." },
      { label: "Close", text: "Recommend the dual approach with the assortment split and the margin floor for marketplace listings." },
    ],
    pitfalls: [
      "Comparing channels on gross margin without including acquisition cost.",
      "Listing identical assortment on both at different prices.",
      "Undervaluing customer data ownership.",
    ],
  },
  {
    slug: "seasonal-brand-off-season-strategy",
    shape: "case",
    title: "An air conditioner brand has nine quiet months. What should marketing do?",
    type: "Channel mix",
    difficulty: 2,
    minutes: 25,
    answer: "Build consideration ahead of season rather than advertising during it, and use the off season for service revenue and dealer relationships.",
    hints: ["Purchase decisions form before the season starts. Advertising during peak is often too late."],
    moves: [
      { label: "Move 1", text: "Map the decision timeline. Consideration begins weeks before the first hot day." },
      { label: "Move 2", text: "Shift spend to the pre-season window, where it shapes a decision rather than chasing one already made." },
      { label: "Move 3", text: "Use the off season for service and annual maintenance contracts, which generate revenue and keep contact." },
      { label: "Move 4", text: "Invest in dealer relationships off season, since dealer recommendation drives a large share of purchases." },
      { label: "Close", text: "Recommend the calendar shift with the service revenue target as the off-season objective." },
    ],
    pitfalls: [
      "Concentrating all spend into the peak season.",
      "Treating the off season as dead rather than as preparation.",
      "Ignoring the dealer's influence on the final purchase.",
    ],
  },
  {
    slug: "should-we-drop-a-legacy-sku",
    shape: "case",
    title: "A legacy product line is 3% of sales and 20% of complexity. Drop it?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Usually yes, but check whether it anchors a customer relationship or a shelf listing before removing it.",
    hints: ["Small revenue lines sometimes carry disproportionate strategic weight. Check before cutting."],
    moves: [
      { label: "Move 1", text: "Quantify the true cost: manufacturing changeovers, inventory, packaging variants and management attention." },
      { label: "Move 2", text: "Check the halo. Some low-volume items anchor a range or hold a shelf listing." },
      { label: "Move 3", text: "Check customer concentration, since a key account may buy the whole range together." },
      { label: "Move 4", text: "Plan the transition, offering a migration path to remaining products." },
      { label: "Close", text: "Recommend with the customer communication plan, and name the accounts to be handled individually." },
    ],
    pitfalls: [
      "Deciding on revenue share alone.",
      "Missing that a key account may buy the range as a bundle.",
      "Discontinuing without a migration path for existing buyers.",
    ],
  },
  {
    slug: "launch-timing-around-a-festival",
    shape: "case",
    title: "Should a new product launch before or after Diwali?",
    type: "Go-to-market",
    difficulty: 2,
    minutes: 20,
    answer: "Before, if supply and distribution are genuinely ready. Festive demand amplifies a good launch and equally amplifies a failed one.",
    hints: ["Festive timing raises the stakes both ways. Readiness matters more than the calendar."],
    moves: [
      { label: "Move 1", text: "Assess the upside. Festive demand and gifting occasions can accelerate trial substantially." },
      { label: "Move 2", text: "Assess the risk. Stock-outs during peak season waste the demand and damage trade relationships." },
      { label: "Move 3", text: "Check competitive clutter, since every brand advertises in this window and media costs peak." },
      { label: "Move 4", text: "Consider a soft launch before the festival to fix problems, then scale into the peak." },
      { label: "Close", text: "Recommend timing conditional on supply readiness, with a named readiness checkpoint." },
    ],
    pitfalls: [
      "Launching into peak season with unproven supply.",
      "Ignoring the higher media costs during the festive window.",
      "Treating the festival as a deadline rather than an opportunity.",
    ],
  },
  {
    slug: "customers-love-it-but-nobody-buys",
    shape: "case",
    title: "Research says people love the product but sales are weak. Explain.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Liking is not buying. The gap is usually price, availability or the absence of a trigger to purchase.",
    hints: ["Stated preference and actual purchase diverge routinely. Find where the gap sits."],
    moves: [
      { label: "Move 1", text: "Check availability first, since people cannot buy what they cannot find." },
      { label: "Move 2", text: "Check price against the alternative, since liking a product does not mean valuing it at that price." },
      { label: "Move 3", text: "Check the purchase trigger. Products without an occasion attached are liked and never bought." },
      { label: "Move 4", text: "Question the research, since respondents are consistently polite about products they will never buy." },
      { label: "Close", text: "Recommend the specific fix and note that research should measure purchase intent at price, not liking." },
    ],
    pitfalls: [
      "Trusting stated preference research.",
      "Assuming a marketing problem when the product is not on shelves.",
      "Never asking about price in the research.",
    ],
  },
  {
    slug: "brand-ambassador-controversy",
    shape: "case",
    title: "Your brand ambassador is in a public controversy. What do you do?",
    type: "Brand",
    difficulty: 2,
    minutes: 25,
    answer: "Pause visibility immediately while you establish the facts. Suspending is reversible, defending prematurely is not.",
    hints: ["Buy time. You can always resume, but you cannot unsay a defence that turns out to be wrong."],
    moves: [
      { label: "Move 1", text: "Pause campaign visibility immediately, which is reversible and buys assessment time." },
      { label: "Move 2", text: "Establish the facts and the seriousness, since an allegation differs from a proven act." },
      { label: "Move 3", text: "Assess audience reaction rather than social media volume, since these often diverge substantially." },
      { label: "Move 4", text: "Check contractual terms, since morality clauses determine what options exist and at what cost." },
      { label: "Close", text: "Recommend a decision timeline rather than an immediate permanent call, and name what would trigger termination." },
    ],
    pitfalls: [
      "Defending publicly before the facts are established.",
      "Terminating instantly on unverified allegations.",
      "Reading social media volume as consumer sentiment.",
    ],
  },
  {
    slug: "how-to-price-a-premium-line-extension",
    shape: "case",
    title: "Price a premium variant of an existing mass product.",
    type: "Pricing",
    difficulty: 2,
    minutes: 25,
    answer: "Price at a gap wide enough to signal difference but narrow enough to invite trade-up, typically 40 to 100% above the base.",
    hints: ["The gap must be visible enough to signal quality but bridgeable enough to cross."],
    moves: [
      { label: "Move 1", text: "Establish the purpose: capturing more from existing buyers, or reaching new premium buyers." },
      { label: "Move 2", text: "Set the gap. Too small and the difference is not believed, too large and nobody trades up." },
      { label: "Move 3", text: "Justify the premium with a visible, demonstrable difference in product or packaging." },
      { label: "Move 4", text: "Manage cannibalisation, which is acceptable if the premium variant carries higher absolute margin." },
      { label: "Close", text: "Recommend the price gap with the product difference that must exist to support it." },
    ],
    pitfalls: [
      "Setting a premium with no demonstrable product difference.",
      "Pricing so high that no existing customer trades up.",
      "Treating cannibalisation as failure when margin per unit improves.",
    ],
  },
  {
    slug: "cause-marketing-decision",
    shape: "case",
    title: "Should the brand attach itself to a social cause?",
    type: "Brand",
    difficulty: 2,
    minutes: 25,
    answer: "Only where the brand has genuine standing and will sustain it for years. Opportunistic cause marketing is detected and punished.",
    hints: ["Ask whether the brand has a real connection to the cause or is borrowing one."],
    moves: [
      { label: "Move 1", text: "Test authenticity. A connection to the product, supply chain or workforce gives standing that a campaign cannot." },
      { label: "Move 2", text: "Assess commitment. Cause association requires sustained action, since a single campaign reads as opportunism." },
      { label: "Move 3", text: "Consider the risk. Any gap between claim and practice will be found and publicised." },
      { label: "Move 4", text: "Assess audience fit, since some causes divide the customer base rather than uniting it." },
      { label: "Close", text: "Recommend only with the multi-year commitment and internal practice change named alongside the communication." },
    ],
    pitfalls: [
      "Attaching to a cause with no genuine connection.",
      "Announcing commitments the operations cannot support.",
      "Treating it as a campaign rather than a long-term position.",
    ],
  },
  {
    slug: "declining-conversion-in-retail-stores",
    shape: "case",
    title: "Store footfall is steady but conversion is falling. Investigate.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Usually assortment, availability or staffing, not traffic quality. Check what shoppers came for and could not find.",
    hints: ["Conversion falling with steady footfall points inside the store, not outside it."],
    moves: [
      { label: "Move 1", text: "Check availability. Out-of-stock on popular sizes and variants kills conversion invisibly." },
      { label: "Move 2", text: "Check assortment relevance, since a buying miss shows up as browsing without purchase." },
      { label: "Move 3", text: "Check staffing, particularly during peak hours where assistance affects conversion materially." },
      { label: "Move 4", text: "Check whether shoppers are researching in store and buying online, which is common and measurable." },
      { label: "Close", text: "Recommend against the specific cause, and note that footfall counters do not measure intent." },
    ],
    pitfalls: [
      "Assuming falling conversion means lower quality traffic.",
      "Ignoring size and variant availability, which is the most common cause.",
      "Not considering channel switching to online.",
    ],
  },
  {
    slug: "should-we-advertise-during-a-downturn",
    shape: "case",
    title: "Sales are falling in a downturn. Cut the marketing budget?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 25,
    answer: "Maintain or increase share of voice if the balance sheet allows, since media is cheaper and competitors are retreating. Cut only if survival requires it.",
    hints: ["Downturns are when share of voice is cheapest to buy. That is the argument to weigh."],
    moves: [
      { label: "Move 1", text: "Establish the constraint. If cash survival is at stake, that overrides every share argument." },
      { label: "Move 2", text: "Note the opportunity. Media costs fall and competitors cut, so relative share of voice rises for less money." },
      { label: "Move 3", text: "Shift the mix toward performance and value messaging, which fits consumer mood better than aspiration." },
      { label: "Move 4", text: "Protect brand investment where possible, since brands that cut entirely take years to recover position." },
      { label: "Close", text: "Recommend maintaining spend with a shifted message, conditional on the cash position." },
    ],
    pitfalls: [
      "Cutting marketing first because it is the easiest budget to reduce.",
      "Maintaining aspirational messaging when consumers are trading down.",
      "Ignoring genuine cash constraints in favour of a theoretical share argument.",
    ],
  },
  {
    slug: "distributor-conflict-over-ecommerce",
    shape: "case",
    title: "Distributors are threatening to stop stocking because of your online prices. Resolve it.",
    type: "Channel mix",
    difficulty: 3,
    minutes: 30,
    answer: "Enforce price parity and give the trade something online cannot: exclusive packs, service, or immediate availability.",
    hints: ["The complaint is about being undercut. Remove that, and the conflict largely goes away."],
    moves: [
      { label: "Move 1", text: "Establish whether the complaint is factually correct, which it usually is during platform discounting." },
      { label: "Move 2", text: "Recognise the leverage. General trade still carries the large majority of Indian FMCG volume." },
      { label: "Move 3", text: "Enforce price parity where legally possible, and control which platforms receive stock." },
      { label: "Move 4", text: "Differentiate assortment, giving the trade exclusive pack sizes that cannot be price-compared." },
      { label: "Close", text: "Recommend the parity and assortment approach, and name what you will do if a platform breaches it." },
    ],
    pitfalls: [
      "Dismissing distributor concerns while they still carry most of your volume.",
      "Promising parity you cannot enforce on marketplace sellers.",
      "Solving it by withdrawing from online entirely.",
    ],
  },
  {
    slug: "which-market-research-to-run",
    shape: "case",
    title: "You have limited research budget before a launch. What do you test?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Test the assumption that would be most expensive to get wrong, which is usually price or repeat rate rather than concept appeal.",
    hints: ["Test what you cannot fix later. Concept appeal is cheap to change, a wrong price point is not."],
    moves: [
      { label: "Move 1", text: "List the assumptions the plan depends on and rank them by cost of being wrong." },
      { label: "Move 2", text: "Deprioritise concept liking, which is cheap to test badly and rarely predicts purchase." },
      { label: "Move 3", text: "Prioritise price sensitivity and repeat intent, which determine whether the business works at all." },
      { label: "Move 4", text: "Prefer behavioural tests over stated preference wherever the budget allows." },
      { label: "Close", text: "Recommend the specific tests with what each result would change in the plan." },
    ],
    pitfalls: [
      "Testing what is easy rather than what is decisive.",
      "Relying on stated preference for price questions.",
      "Running research whose result would not change any decision.",
    ],
  },
  {
    slug: "brand-architecture-after-acquisition",
    shape: "case",
    title: "You acquired a competitor. Keep both brands or merge them?",
    type: "Positioning",
    difficulty: 3,
    minutes: 30,
    answer: "Keep both if they serve genuinely different segments, merge if they compete for the same buyer. Two half-funded brands lose to one funded one.",
    hints: ["Ask whether the two brands' buyers are the same people. That mostly decides it."],
    moves: [
      { label: "Move 1", text: "Measure buyer overlap. Serving different segments justifies keeping both, competing for the same buyer does not." },
      { label: "Move 2", text: "Assess regional strength, since the acquired brand may dominate specific markets." },
      { label: "Move 3", text: "Cost the alternative, since supporting two brands means two marketing budgets and two supply chains." },
      { label: "Move 4", text: "If merging, plan the migration carefully, since abrupt brand removal loses loyal customers." },
      { label: "Close", text: "Recommend with the overlap data behind it, and name the migration timeline if merging." },
    ],
    pitfalls: [
      "Deciding on brand sentiment rather than buyer overlap.",
      "Merging abruptly and losing the acquired brand's loyal base.",
      "Keeping both without funding either adequately.",
    ],
  },
  {
    slug: "premiumisation-versus-volume",
    shape: "case",
    title: "Should the brand chase premiumisation or volume growth?",
    type: "Positioning",
    difficulty: 3,
    minutes: 30,
    answer: "Depends on where the category is growing and what the brand can credibly claim. Attempting both simultaneously usually produces a confused middle.",
    hints: ["Both is rarely the answer. Pick, and say what you are giving up."],
    moves: [
      { label: "Move 1", text: "Establish where category growth is coming from: more users, or existing users trading up." },
      { label: "Move 2", text: "Assess brand permission. A mass brand may lack credibility to command a premium." },
      { label: "Move 3", text: "Compare the economics. Premium adds margin per unit, volume adds absolute profit and scale advantages." },
      { label: "Move 4", text: "Consider a portfolio approach with separate brands, which avoids the confused middle." },
      { label: "Close", text: "Commit to one direction for the main brand and name what is being sacrificed." },
    ],
    pitfalls: [
      "Pursuing both on one brand and occupying a confused middle.",
      "Assuming premiumisation is always the better strategy.",
      "Ignoring the scale advantages that volume brings in distribution.",
    ],
  },
  {
    slug: "what-to-do-when-a-competitor-cuts-price",
    shape: "case",
    title: "A competitor cut prices 15%. Match, or hold?",
    type: "Competitive response",
    difficulty: 2,
    minutes: 25,
    answer: "Hold unless volume loss threatens scale economics. Matching invites a spiral that damages the category and rarely recovers the share.",
    hints: ["Work out whether they can sustain the cut before deciding how to respond."],
    moves: [
      { label: "Move 1", text: "Assess their sustainability. A cut funded by investor money differs from one funded by a cost advantage." },
      { label: "Move 2", text: "Segment your exposure, since loyal buyers may not switch while price-sensitive ones certainly will." },
      { label: "Move 3", text: "Model the economics of matching, which usually loses more margin than the share it protects." },
      { label: "Move 4", text: "Consider targeted responses: promotions to at-risk segments rather than a general price cut." },
      { label: "Close", text: "Recommend holding with targeted defence, and name the volume loss threshold at which you would reconsider." },
    ],
    pitfalls: [
      "Matching immediately to protect share.",
      "Not assessing whether the competitor can sustain the price.",
      "Cutting price everywhere to defend against a threat in one segment.",
    ],
  },
  {
    slug: "designing-a-referral-programme-for-a-brand",
    shape: "case",
    title: "Design a referral programme for a consumer brand.",
    type: "Promotion",
    difficulty: 2,
    minutes: 25,
    answer: "Reward both sides, keep the mechanic simple enough to explain in a sentence, and measure on retained referred customers rather than referrals sent.",
    hints: ["Complexity kills referral programmes. If it needs explaining twice, nobody uses it."],
    moves: [
      { label: "Move 1", text: "Decide who to reward. Two-sided rewards work best, since the referrer needs a reason and the friend needs a nudge." },
      { label: "Move 2", text: "Choose the reward type. Product credit keeps value inside the business better than cash." },
      { label: "Move 3", text: "Simplify the mechanic to something explainable in one sentence." },
      { label: "Move 4", text: "Build in fraud controls, since any referral programme with real value attached will be gamed." },
      { label: "Close", text: "Measure on retained referred customers per rupee of incentive, not on referral volume." },
    ],
    pitfalls: [
      "Rewarding only the referrer.",
      "Designing a mechanic too complex to explain.",
      "Measuring referrals sent rather than customers retained.",
    ],
  },
  {
    slug: "should-we-enter-quick-commerce-as-a-brand",
    shape: "case",
    title: "Should a snack brand list on quick commerce platforms?",
    type: "Channel mix",
    difficulty: 2,
    minutes: 25,
    answer: "Yes, with channel-specific packs and an explicit view on how much general trade volume it moves rather than adds.",
    hints: ["Ask whether these are new occasions or the same purchases moving channel."],
    moves: [
      { label: "Move 1", text: "Size the channel for your category, since impulse snacking behaves differently online than at a counter." },
      { label: "Move 2", text: "Work the economics. Commissions, listing fees and higher return rates compress margin materially." },
      { label: "Move 3", text: "Assess incrementality. If the same shopper simply switches channel, you have paid commission for existing volume." },
      { label: "Move 4", text: "Design channel-specific packs, typically larger multipacks that suit planned rather than impulse buying." },
      { label: "Close", text: "Recommend listing with a differentiated pack architecture and a margin floor stated." },
    ],
    pitfalls: [
      "Listing the same impulse packs that work at a kirana counter.",
      "Assuming all online volume is incremental.",
      "Ignoring the general trade reaction to platform discounting.",
    ],
  },
  {
    slug: "communicating-a-product-improvement",
    shape: "case",
    title: "You improved the product. How do you communicate it without implying it was bad?",
    type: "Brand",
    difficulty: 2,
    minutes: 20,
    answer: "Frame it as an addition rather than a correction, and be careful that regular buyers do not feel the product they loved has been taken away.",
    hints: ["The risk is not confusion. It is the loyal buyer who liked the old version."],
    moves: [
      { label: "Move 1", text: "Assess how noticeable the change is, since a taste or texture change is far riskier than an invisible improvement." },
      { label: "Move 2", text: "Frame as addition, since new and improved implies the previous version was deficient." },
      { label: "Move 3", text: "Protect loyal buyers, who are the most likely to notice and object to a change." },
      { label: "Move 4", text: "Consider running both versions temporarily where the change is significant and divisive." },
      { label: "Close", text: "Recommend the framing with a monitoring plan for complaints from the loyal base." },
    ],
    pitfalls: [
      "Announcing improvements that highlight prior deficiency.",
      "Underestimating loyal buyers' attachment to the existing product.",
      "Changing a recognisable product characteristic without a fallback plan.",
    ],
  },
  {
    slug: "allocating-budget-across-brand-and-performance",
    shape: "case",
    title: "How should budget split between brand building and performance marketing?",
    type: "Channel mix",
    difficulty: 3,
    minutes: 30,
    answer: "Weighted toward brand over the long run, but the honest answer depends on business stage. Performance-only growth stalls once the cheap audience is exhausted.",
    hints: ["Performance harvests demand. Brand creates it. A business that only harvests eventually runs out."],
    moves: [
      { label: "Move 1", text: "Distinguish the functions. Performance captures existing demand, brand creates future demand." },
      { label: "Move 2", text: "Note the measurement asymmetry, which systematically biases budgets toward the measurable channel." },
      { label: "Move 3", text: "Adjust for stage. An early business needs proof of conversion, an established one needs demand creation." },
      { label: "Move 4", text: "Watch the signal. Rising acquisition cost usually means brand demand is not being replenished." },
      { label: "Close", text: "Recommend a split with a review mechanism, since the right ratio changes as the business matures." },
    ],
    pitfalls: [
      "Allocating entirely to the measurable channel.",
      "Treating brand spend as unmeasurable rather than measurable over longer windows.",
      "Applying a fixed ratio regardless of business stage.",
    ],
  },
  {
    slug: "reviving-a-dormant-customer-base",
    shape: "case",
    title: "Half your customer base has not purchased in a year. Revive them.",
    type: "Promotion",
    difficulty: 2,
    minutes: 25,
    answer: "Segment by reason and recency, target only the winnable, and accept that some of the base is permanently gone.",
    hints: ["Some dormant customers no longer have the need. Spending on them is waste."],
    moves: [
      { label: "Move 1", text: "Segment by recency, since a customer dormant three months differs completely from one dormant two years." },
      { label: "Move 2", text: "Diagnose reasons: price, a bad experience, a competitor, or a life change ending the need." },
      { label: "Move 3", text: "Match intervention to reason, since a service failure needs acknowledgement rather than a discount." },
      { label: "Move 4", text: "Test on a subset before spending across the base, since win-back economics are frequently negative." },
      { label: "Close", text: "Recommend targeting the recent and winnable, and state what share of the base you are writing off." },
    ],
    pitfalls: [
      "Sending one discount to the entire dormant base.",
      "Ignoring why each segment stopped buying.",
      "Not testing before committing the full budget.",
    ],
  },
  {
    slug: "handling-a-viral-negative-review",
    shape: "case",
    title: "A negative review of your product has gone viral. Respond.",
    type: "Brand",
    difficulty: 2,
    minutes: 20,
    answer: "Reply once, publicly and specifically, resolve it visibly, and then stop. Prolonged engagement extends the story's life.",
    hints: ["Your response is now the story. Keep it short, specific and final."],
    moves: [
      { label: "Move 1", text: "Verify the claim quickly, since responding to something accurate as though it were false is fatal." },
      { label: "Move 2", text: "Respond where it happened, once, specifically and without corporate language." },
      { label: "Move 3", text: "Resolve visibly, since watchers judge the resolution more than the original complaint." },
      { label: "Move 4", text: "Stop engaging after the resolution, since continued replies keep the item circulating." },
      { label: "Close", text: "Recommend the response plus the process fix, since a viral complaint usually reveals a systemic gap." },
    ],
    pitfalls: [
      "Responding defensively before verifying.",
      "Using legal or corporate language in a consumer conversation.",
      "Continuing to engage long after the matter is resolved.",
    ],
  },
  {
    slug: "should-we-use-regional-celebrities",
    shape: "case",
    title: "Should a national brand use regional celebrities instead of one national face?",
    type: "Brand",
    difficulty: 2,
    minutes: 25,
    answer: "Yes where regional film industries command genuine local loyalty, since relevance usually beats reach in those markets.",
    hints: ["Regional stars often out-influence national ones in their own state. Weigh relevance against reach."],
    moves: [
      { label: "Move 1", text: "Compare reach against relevance. A national face reaches everyone shallowly, a regional star reaches one state deeply." },
      { label: "Move 2", text: "Assess where sales actually come from, since a brand strong in four states does not need national fame." },
      { label: "Move 3", text: "Cost the alternative. Several regional endorsements can cost less than one national celebrity." },
      { label: "Move 4", text: "Consider production complexity, since multiple versions multiply shoot and media planning costs." },
      { label: "Close", text: "Recommend regional where sales concentration justifies it, and name the states you would start with." },
    ],
    pitfalls: [
      "Choosing a national face for prestige rather than audience fit.",
      "Underestimating the production cost of multiple regional versions.",
      "Ignoring where the sales actually concentrate.",
    ],
  },
];
