import type { Question } from "./types";

// Marketing and brand guesstimates. Sizing categories, reach and spend where no
// published number exists.
export const MARKETING_GUESSTIMATES: Question[] = [
  {
    slug: "shampoo-sachet-market-uttar-pradesh",
    shape: "guesstimate",
    title: "Size the shampoo sachet market in Uttar Pradesh.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "HUL",
    answer: "A few thousand crore rupees a year, roughly in line with UP holding about 17% of the national sachet market.",
    hints: ["Sachets and bottles are different markets serving different people. Separate them early."],
    moves: [
      { label: "Move 1", text: "Set the base. Uttar Pradesh has roughly 240 million people and about 45 million households, heavily rural." },
      { label: "Move 2", text: "Split by pack format. Sachet buyers are predominantly rural and lower-income urban, perhaps 70% of households." },
      { label: "Move 3", text: "Build from occasions. Roughly 3 hair washes a week per person across about 3 users per household." },
      { label: "Move 4", text: "Price it at 1 to 3 rupees a sachet against that occasion count." },
      { label: "Check", text: "UP is around 17% of India's population, so the state figure should sit near that share of the national sachet market." },
    ],
    pitfalls: [
      "Sizing all shampoo and never separating the sachet format asked about.",
      "Assuming western wash frequency, which overstates volume substantially.",
      "Working from households buying packs rather than from usage occasions.",
    ],
  },
  {
    slug: "ipl-mid-innings-ad-reach",
    shape: "guesstimate",
    title: "How many people saw a single mid-innings IPL ad slot?",
    type: "Reach estimation",
    difficulty: 1,
    minutes: 15,
    askedAt: "Star",
    answer: "Tens of millions of viewers, discounted 30 to 40% from in-play peak. Say whether you are answering reach or impressions.",
    hints: ["Television and streaming are separate audiences that need separate builds."],
    moves: [
      { label: "Move 1", text: "Split the platforms, since television and streaming reach different audiences with different measurement." },
      { label: "Move 2", text: "Size television at roughly 30 to 50 million viewers for a good match, with several people per set." },
      { label: "Move 3", text: "Size streaming at tens of millions of concurrent viewers for a marquee fixture." },
      { label: "Move 4", text: "Apply the break drop, since mid-innings loses a meaningful share of attention." },
      { label: "Check", text: "Distinguish reach from impressions. One slot delivers many impressions but smaller unique reach." },
    ],
    pitfalls: [
      "Reporting peak concurrency as if it were ad exposure.",
      "Merging television and streaming into one undifferentiated number.",
      "Using reach and impressions interchangeably.",
    ],
  },
  {
    slug: "d2c-skincare-annual-ad-spend",
    shape: "guesstimate",
    title: "Estimate the annual ad spend of a mid-size D2C skincare brand.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    askedAt: "Mamaearth",
    answer: "Roughly 25 to 40% of revenue, which for a 300 crore brand means 75 to 120 crore rupees a year.",
    hints: ["Work backwards from revenue and the acquisition cost the category requires."],
    moves: [
      { label: "Move 1", text: "Size revenue, perhaps 200 to 400 crore rupees for a mid-size D2C brand." },
      { label: "Move 2", text: "Apply the marketing ratio, which in D2C beauty runs far above traditional FMCG." },
      { label: "Move 3", text: "Split the spend: performance marketing for acquisition, influencer for credibility, and some brand building." },
      { label: "Move 4", text: "Cross-check via acquisition cost. New customers times cost per acquisition should approximate performance spend." },
      { label: "Check", text: "Note that spend at this ratio means profitability depends entirely on repeat purchase, which is the real business question." },
    ],
    pitfalls: [
      "Applying traditional FMCG marketing ratios to a D2C brand.",
      "Missing influencer spend, which is a large line in this category.",
      "Not cross-checking against acquisition cost, which catches errors quickly.",
    ],
  },
  {
    slug: "kirana-stores-snack-brand-pune",
    shape: "guesstimate",
    title: "How many kirana stores does a snack brand need to reach in Pune?",
    type: "Distribution sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "ITC",
    answer: "Roughly 25,000 to 35,000 outlets exist, but the top 30% carry most of the volume, so effective coverage is far smaller.",
    hints: ["Total outlets and outlets worth serving are very different numbers."],
    moves: [
      { label: "Move 1", text: "Size total outlets from population and catchment, giving tens of thousands in a city of 7 million." },
      { label: "Move 2", text: "Segment by size. A handful of large stores per locality carry disproportionate volume." },
      { label: "Move 3", text: "Apply weighted distribution thinking. Reaching 30% of outlets can capture 70% of category sales." },
      { label: "Move 4", text: "Cost the servicing. Each outlet needs regular visits, which is what limits realistic coverage." },
      { label: "Check", text: "Numeric and weighted distribution differ sharply. Quoting one without the other misleads." },
    ],
    pitfalls: [
      "Targeting numeric distribution rather than weighted distribution.",
      "Ignoring the servicing cost per outlet.",
      "Treating all kirana stores as equivalent.",
    ],
  },
  {
    slug: "festive-gifting-market-india",
    shape: "guesstimate",
    title: "Estimate the size of the paid festive gifting market in India.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 1 to 2 lakh crore rupees, dominated by sweets, dry fruits and corporate gifting rather than by consumer electronics.",
    hints: ["Separate household gifting from corporate gifting. They behave completely differently."],
    moves: [
      { label: "Move 1", text: "Split the market. Household gifting between families, and corporate gifting to clients and employees." },
      { label: "Move 2", text: "For households, size the gifting population and average spend, which rises steeply with income." },
      { label: "Move 3", text: "For corporate, size firms by employee count and apply per-head gifting budgets." },
      { label: "Move 4", text: "Note category composition, since sweets and dry fruits dominate volume while electronics dominate value in the top segment." },
      { label: "Check", text: "Note the concentration. Most of this happens in a three-week window, which defines the entire supply chain." },
    ],
    pitfalls: [
      "Ignoring corporate gifting, which is a large organised segment.",
      "Applying one average spend across income bands.",
      "Missing the extreme seasonality of the category.",
    ],
  },
  {
    slug: "toothpaste-market-india-volume",
    shape: "guesstimate",
    title: "Size the Indian toothpaste market by volume.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 550,000 to 700,000 tonnes a year, with per-person consumption still well below developed markets.",
    hints: ["Grams per person per year is the anchor. Brushing frequency is the variable that matters."],
    moves: [
      { label: "Move 1", text: "Size the population using toothpaste, which is high in urban India and lower in rural areas." },
      { label: "Move 2", text: "Apply brushing frequency, typically once a day in India rather than twice." },
      { label: "Move 3", text: "Apply grams per use, roughly half a gram to a gram, which most people overestimate." },
      { label: "Move 4", text: "Scale up and convert to tonnes, then note the share still using powder or non-branded alternatives." },
      { label: "Check", text: "Per-person consumption in India is a fraction of developed markets, which is exactly why the category still grows." },
    ],
    pitfalls: [
      "Assuming twice-daily brushing across the whole population.",
      "Overestimating grams per use, which inflates the answer several times over.",
      "Ignoring tooth powder and traditional alternatives.",
    ],
  },
  {
    slug: "outdoor-advertising-market-mumbai",
    shape: "guesstimate",
    title: "Estimate the outdoor advertising market in Mumbai.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 800 to 1,500 crore rupees a year, concentrated on a small number of premium sites.",
    hints: ["Inventory times occupancy times rate. Rates vary enormously by location."],
    moves: [
      { label: "Move 1", text: "Size the inventory: hoardings, bus shelters, station media and transit advertising." },
      { label: "Move 2", text: "Apply monthly rates, which range from lakhs for prime hoardings to modest sums for local sites." },
      { label: "Move 3", text: "Apply occupancy, since not all inventory is sold at all times outside peak seasons." },
      { label: "Move 4", text: "Add digital outdoor screens, which command higher rates and are growing quickly." },
      { label: "Check", text: "Note the concentration. A few dozen premium sites carry a large share of total market value." },
    ],
    pitfalls: [
      "Applying an average rate across wildly different site qualities.",
      "Assuming full occupancy year round.",
      "Missing transit and station media, which are large in Mumbai specifically.",
    ],
  },
  {
    slug: "influencer-marketing-spend-india",
    shape: "guesstimate",
    title: "Size India's influencer marketing spend.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 2,000 to 4,000 crore rupees a year, growing fast and concentrated in beauty, fashion and gaming.",
    hints: ["Build from creators and deals, or from brands and budgets. Doing both and reconciling is stronger."],
    moves: [
      { label: "Move 1", text: "Size the creator base by tier: a few thousand large creators, tens of thousands of mid-tier, and many micro creators." },
      { label: "Move 2", text: "Apply deals per creator per year and average deal value by tier, which differs by orders of magnitude." },
      { label: "Move 3", text: "Cross-check from the brand side by taking digital ad spend and applying the influencer share." },
      { label: "Move 4", text: "Add barter and product-only deals, which are common at the micro tier and carry no cash value." },
      { label: "Check", text: "Note category concentration. Beauty, fashion and gaming account for a disproportionate share of spend." },
    ],
    pitfalls: [
      "Applying top-tier rates across the whole creator base.",
      "Counting barter arrangements as cash spend.",
      "Sizing from one side only when two independent builds would catch errors.",
    ],
  },
  {
    slug: "cost-of-a-national-tv-campaign",
    shape: "guesstimate",
    title: "Estimate the cost of a national television campaign for a new FMCG brand.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 15 to 40 crore rupees for a meaningful launch burst over six to eight weeks.",
    hints: ["Reach alone does nothing. Frequency is what makes a launch campaign work, and it multiplies the cost."],
    moves: [
      { label: "Move 1", text: "Set the reach target, typically a large share of the target audience within the launch window." },
      { label: "Move 2", text: "Set frequency, since a new brand needs multiple exposures before recall forms." },
      { label: "Move 3", text: "Convert reach times frequency into gross rating points and apply the cost per point." },
      { label: "Move 4", text: "Add production, which for a national campaign with talent is a meaningful additional cost." },
      { label: "Check", text: "Compare against expected first-year revenue. If media spend exceeds it, the launch plan needs rethinking." },
    ],
    pitfalls: [
      "Buying reach with insufficient frequency, producing awareness that does not stick.",
      "Forgetting production and talent costs.",
      "Not comparing spend against realistic first-year sales.",
    ],
  },
  {
    slug: "packaged-snacks-market-india",
    shape: "guesstimate",
    title: "Size the Indian packaged snacks market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 45,000 to 60,000 crore rupees, with traditional namkeen larger than western-style chips.",
    hints: ["Traditional Indian snacks are the bigger half. Do not size only the western formats."],
    moves: [
      { label: "Move 1", text: "Split the category into western snacks and traditional namkeen and bhujia." },
      { label: "Move 2", text: "Size consumption occasions, since snacking is frequent but individual pack sizes are small." },
      { label: "Move 3", text: "Apply the price point. The five and ten rupee packs dominate volume in most of India." },
      { label: "Move 4", text: "Add the unorganised segment, which in traditional snacks is very large and locally supplied." },
      { label: "Check", text: "Note the price point rigidity. Manufacturers reduce grammage rather than raise the price, which shapes the whole category." },
    ],
    pitfalls: [
      "Sizing only branded western snacks.",
      "Ignoring the unorganised sector, which is most of traditional snacking.",
      "Assuming price increases when the industry reduces pack weight instead.",
    ],
  },
  {
    slug: "market-size-mens-grooming-india",
    shape: "guesstimate",
    title: "Size the Indian men's grooming market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 20,000 to 30,000 crore rupees, with shaving still dominant and skincare growing fastest.",
    hints: ["Split by product type. Shaving, hair and skincare have very different penetration."],
    moves: [
      { label: "Move 1", text: "Size the male population in the relevant age band, roughly 350 million aged 15 to 55." },
      { label: "Move 2", text: "Split by category: shaving products, hair oil and styling, deodorant, and face care." },
      { label: "Move 3", text: "Apply penetration by category, which is near universal for soap and low for face care." },
      { label: "Move 4", text: "Apply spend per user per year, which is modest in absolute terms even in urban India." },
      { label: "Check", text: "Note the growth driver. Category growth comes from new categories being adopted, not from higher spend in existing ones." },
    ],
    pitfalls: [
      "Applying urban penetration rates nationally.",
      "Missing that soap and general products are often not counted as grooming.",
      "Ignoring the salon channel, which is a separate and large market.",
    ],
  },
  {
    slug: "how-much-does-a-brand-lose-to-counterfeits",
    shape: "guesstimate",
    title: "Estimate what a consumer brand loses to counterfeits in India.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Counterfeits may equal 10 to 25% of genuine volume in vulnerable categories, but lost revenue is far less since many buyers would not pay full price.",
    hints: ["Counterfeit units are not lost sales one for one. Adjust for who would never have bought the real product."],
    moves: [
      { label: "Move 1", text: "Assess vulnerability. Cosmetics, lubricants and spare parts are far more affected than perishable food." },
      { label: "Move 2", text: "Size counterfeit volume as a share of category volume, higher in rural and unorganised channels." },
      { label: "Move 3", text: "Apply a substitution rate, since many counterfeit buyers are price-driven and would not buy genuine." },
      { label: "Move 4", text: "Add the brand damage cost, since a poor counterfeit experience is often blamed on the real brand." },
      { label: "Check", text: "The reputational cost frequently exceeds the direct revenue loss, which is the more important finding." },
    ],
    pitfalls: [
      "Treating every counterfeit unit as a lost genuine sale.",
      "Ignoring reputational damage, which is the larger cost.",
      "Applying one counterfeit rate across very different categories.",
    ],
  },
  {
    slug: "size-of-quick-commerce-ad-inventory",
    shape: "guesstimate",
    title: "Size the advertising revenue available inside quick commerce apps.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 2 to 5% of gross merchandise value, which at scale becomes a very high-margin revenue stream.",
    hints: ["Retail media monetises intent. Compare rates against search advertising, not display."],
    moves: [
      { label: "Move 1", text: "Size platform gross merchandise value, in the tens of thousands of crores for leading players." },
      { label: "Move 2", text: "Identify the ad formats: sponsored product placement, category banners and brand takeovers." },
      { label: "Move 3", text: "Apply the retail media take rate, benchmarked against mature e-commerce platforms globally." },
      { label: "Move 4", text: "Note the margin. Advertising revenue carries almost no incremental cost, unlike product sales." },
      { label: "Check", text: "This is why quick commerce economics improve with scale. Advertising, not delivery margin, is the profit engine." },
    ],
    pitfalls: [
      "Pricing this inventory like display advertising rather than intent-based search.",
      "Ignoring the margin difference between ad revenue and product revenue.",
      "Assuming brand budgets shift instantly to a new channel.",
    ],
  },
  {
    slug: "reach-of-a-regional-newspaper",
    shape: "guesstimate",
    title: "Estimate the readership of a leading regional newspaper.",
    type: "Reach estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Readership typically runs three to five times circulation, since a single copy is read by several people.",
    hints: ["Circulation and readership are different. The copies-per-reader multiplier is the whole question."],
    moves: [
      { label: "Move 1", text: "Start from circulation, which for a leading regional daily runs into millions of copies." },
      { label: "Move 2", text: "Apply readers per copy, which in India is high because copies are shared at home and in shops." },
      { label: "Move 3", text: "Adjust for the language market size, since regional dailies often outsell English ones substantially." },
      { label: "Move 4", text: "Note the digital shift, which reduces print circulation while total readership may hold." },
      { label: "Check", text: "Compare against the literate population of the state, since readership cannot exceed it." },
    ],
    pitfalls: [
      "Reporting circulation as readership.",
      "Applying Western readers-per-copy assumptions.",
      "Ignoring that regional language dailies outsell English titles in most states.",
    ],
  },
  {
    slug: "sampling-cost-for-a-new-product",
    shape: "guesstimate",
    title: "Estimate the cost of a sampling campaign for a new food product.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 15 to 40 rupees per sample delivered, so a million samples costs a few crore rupees.",
    hints: ["Distribution labour, not the product itself, is the dominant cost per sample."],
    moves: [
      { label: "Move 1", text: "Cost the sample unit, which for a small food pack is a few rupees at best." },
      { label: "Move 2", text: "Add distribution. Staff at a location can hand out a limited number per hour, and that labour dominates." },
      { label: "Move 3", text: "Choose the channel: retail store sampling, residential distribution or event-based, each with different costs." },
      { label: "Move 4", text: "Apply conversion. A modest share of samplers convert to purchase, which sets the effective acquisition cost." },
      { label: "Check", text: "Compare cost per converted customer against lifetime value, which is the only test that matters." },
    ],
    pitfalls: [
      "Costing the product without the distribution labour.",
      "Assuming high conversion from sampling.",
      "Not converting to cost per acquired customer.",
    ],
  },
  {
    slug: "market-size-organic-food-india",
    shape: "guesstimate",
    title: "Size the Indian organic food market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 6,000 to 12,000 crore rupees domestically, small relative to total food but growing quickly in metros.",
    hints: ["The addressable base is much narrower than total food buyers. Narrow it hard."],
    moves: [
      { label: "Move 1", text: "Narrow the audience to metro households with income to pay a substantial premium." },
      { label: "Move 2", text: "Apply the share of their food basket bought organic, which is small even among buyers." },
      { label: "Move 3", text: "Apply the price premium, typically 30 to 100% above conventional produce." },
      { label: "Move 4", text: "Separate the export market, which for Indian organic produce is larger than domestic consumption." },
      { label: "Check", text: "Note the certification problem, since much product sold as organic in India is not certified, which distorts any market figure." },
    ],
    pitfalls: [
      "Applying an organic share of the entire food market.",
      "Ignoring exports, which dominate Indian organic production.",
      "Treating uncertified claims as genuine organic supply.",
    ],
  },
  {
    slug: "brand-recall-after-a-campaign",
    shape: "guesstimate",
    title: "Estimate how many people will recall a brand after a campaign.",
    type: "Reach estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Aided recall might reach 30 to 50% of those exposed, unaided far less, and both decay within weeks without sustained spend.",
    hints: ["Exposure, recall and unaided recall are three shrinking numbers. Track all three."],
    moves: [
      { label: "Move 1", text: "Start from reach: how many people saw the campaign at least once." },
      { label: "Move 2", text: "Apply the frequency effect, since recall rises sharply between one and three exposures." },
      { label: "Move 3", text: "Split aided from unaided recall, which differ by a large factor." },
      { label: "Move 4", text: "Apply decay. Recall falls quickly once spend stops, which is why campaigns come in bursts." },
      { label: "Check", text: "Note that recall does not equal preference or purchase, which is a separate and much smaller conversion." },
    ],
    pitfalls: [
      "Treating everyone reached as everyone who remembers.",
      "Conflating aided and unaided recall.",
      "Assuming recall persists without continued spend.",
    ],
  },
  {
    slug: "size-of-indian-quick-service-restaurant-market",
    shape: "guesstimate",
    title: "Size the Indian quick service restaurant market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 30,000 to 45,000 crore rupees for the organised chain segment, a fraction of total eating out.",
    hints: ["Organised chains are a small slice of Indian eating out. Say what you are including."],
    moves: [
      { label: "Move 1", text: "Define scope. Organised chains only, excluding standalone restaurants and street food." },
      { label: "Move 2", text: "Size from the supply side: chain outlets multiplied by average revenue per outlet." },
      { label: "Move 3", text: "Cross-check from demand: urban households, eating out frequency and average spend per occasion." },
      { label: "Move 4", text: "Add delivery, which has grown to a large share of chain revenue and changes outlet economics." },
      { label: "Check", text: "Note that organised chains are a small share of total Indian food service, which is the headline observation." },
    ],
    pitfalls: [
      "Not stating whether unorganised outlets are included.",
      "Missing delivery, which is now a major revenue channel.",
      "Using one average revenue per outlet across metro and small-town locations.",
    ],
  },
  {
    slug: "cost-per-lead-for-an-edtech-brand",
    shape: "guesstimate",
    title: "Estimate the cost per enrolled student for an Indian edtech brand.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Often tens of thousands of rupees per paying student, because the funnel from lead to enrolment is extremely narrow.",
    hints: ["Every stage of the funnel multiplies the true cost. Work through each one."],
    moves: [
      { label: "Move 1", text: "Start with cost per lead from digital advertising, which is modest in isolation." },
      { label: "Move 2", text: "Apply lead-to-demo conversion, which is a small fraction of raw leads." },
      { label: "Move 3", text: "Apply demo-to-enrolment conversion, and add the sales team cost of conducting those demos." },
      { label: "Move 4", text: "Divide total acquisition spend, including sales salaries, by paying students enrolled." },
      { label: "Check", text: "Compare against course fee. When acquisition cost approaches the fee, the model only works with strong repeat enrolment." },
    ],
    pitfalls: [
      "Reporting cost per lead as customer acquisition cost.",
      "Excluding the inside sales team cost, which is a large share.",
      "Not comparing against the fee, which is what makes the number meaningful.",
    ],
  },
  {
    slug: "size-of-the-indian-diaper-market",
    shape: "guesstimate",
    title: "Size the Indian disposable diaper market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 8,000 to 12,000 crore rupees, with penetration still low outside metros and urban middle-class homes.",
    hints: ["Penetration, not birth rate, is the binding variable here."],
    moves: [
      { label: "Move 1", text: "Size the addressable population: children under three, roughly 60 to 70 million." },
      { label: "Move 2", text: "Apply penetration, which is high in urban affluent households and very low in rural India." },
      { label: "Move 3", text: "Apply usage intensity, since many Indian families use diapers only at night or when travelling." },
      { label: "Move 4", text: "Apply price per unit, noting that single-piece purchase is common at lower income levels." },
      { label: "Check", text: "Note the growth driver. Category growth comes from usage intensity rising among existing users more than from new users." },
    ],
    pitfalls: [
      "Assuming full-time diaper use where partial use is the norm.",
      "Applying urban penetration nationally.",
      "Missing that single-piece purchase changes both pricing and distribution.",
    ],
  },
  {
    slug: "size-of-wedding-catering-market",
    shape: "guesstimate",
    title: "Size the Indian wedding catering market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 50,000 to 80,000 crore rupees a year, sized from guest counts rather than from wedding counts.",
    hints: ["Guests per wedding varies enormously by region and income. That variance drives the answer."],
    moves: [
      { label: "Move 1", text: "Start from roughly 9 to 10 million weddings a year." },
      { label: "Move 2", text: "Segment by scale, since guest counts range from fifty to several thousand." },
      { label: "Move 3", text: "Apply catering spend per guest, which varies from a couple of hundred rupees to a few thousand." },
      { label: "Move 4", text: "Weight by segment, noting that a small share of large weddings carries much of the value." },
      { label: "Check", text: "Note the organised share is small. Most wedding catering is handled by local unorganised caterers." },
    ],
    pitfalls: [
      "Applying one guest count across all weddings.",
      "Using metro per-guest pricing nationally.",
      "Ignoring that the market is overwhelmingly unorganised.",
    ],
  },
  {
    slug: "market-size-pet-food-india",
    shape: "guesstimate",
    title: "Size the Indian packaged pet food market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 4,000 to 7,000 crore rupees, small but growing fast from a low base of packaged feeding.",
    hints: ["Pet ownership is one number. Packaged feeding is a much smaller one."],
    moves: [
      { label: "Move 1", text: "Size pet ownership, roughly 30 to 35 million dogs and cats in Indian households." },
      { label: "Move 2", text: "Apply the packaged feeding share, since most Indian pets are still fed household food." },
      { label: "Move 3", text: "Apply consumption and price, which differ sharply between economy and premium brands." },
      { label: "Move 4", text: "Add treats and supplements, which are high-margin adjacent categories." },
      { label: "Check", text: "Note the driver. Growth comes from converting home-fed pets to packaged food, not from more pets." },
    ],
    pitfalls: [
      "Applying Western packaged feeding rates.",
      "Ignoring that most Indian pets eat household food.",
      "Missing the premium segment, which carries disproportionate value.",
    ],
  },
  {
    slug: "share-of-voice-in-a-category",
    shape: "guesstimate",
    title: "Estimate what share of voice a challenger brand needs to gain share.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Share of voice must exceed share of market for share to grow, typically by a meaningful margin sustained over time.",
    hints: ["The relationship between share of voice and share of market is the whole framework here."],
    moves: [
      { label: "Move 1", text: "State the principle. Brands whose share of voice exceeds their share of market tend to gain share over time." },
      { label: "Move 2", text: "Size the category's total advertising spend to establish what a point of voice costs." },
      { label: "Move 3", text: "Compute the excess share of voice required and convert it into a rupee budget." },
      { label: "Move 4", text: "Assess affordability against the challenger's revenue, which is where the plan usually breaks." },
      { label: "Close", text: "Note the alternative. A challenger unable to outspend must win on distribution, price or product instead." },
    ],
    pitfalls: [
      "Assuming spend alone shifts share regardless of product or distribution.",
      "Ignoring that leaders can respond by raising their own spend.",
      "Planning a spend level the challenger cannot sustain for long enough to work.",
    ],
  },
  {
    slug: "size-of-modern-trade-versus-general-trade",
    shape: "guesstimate",
    title: "Estimate the split between modern trade and general trade in Indian FMCG.",
    type: "Distribution sizing",
    difficulty: 2,
    minutes: 20,
    answer: "General trade still carries roughly 80 to 85% of FMCG sales, with modern trade and e-commerce sharing the rest.",
    hints: ["Metro perception badly overstates modern trade. Weight by where India actually shops."],
    moves: [
      { label: "Move 1", text: "Size outlets. India has millions of kirana stores and a few thousand modern trade stores." },
      { label: "Move 2", text: "Note the per-outlet difference, since a supermarket sells far more than a kirana store." },
      { label: "Move 3", text: "Weight by geography. Modern trade is concentrated in metros, general trade is everywhere." },
      { label: "Move 4", text: "Add e-commerce and quick commerce, which are growing quickly but from a small base nationally." },
      { label: "Check", text: "Note the metro distortion. In metros the split looks very different, which is why people overestimate modern trade." },
    ],
    pitfalls: [
      "Generalising the metro channel mix to all of India.",
      "Counting outlets without weighting by throughput.",
      "Overstating e-commerce share of total FMCG.",
    ],
  },
  {
    slug: "size-of-indian-cosmetics-imports",
    shape: "guesstimate",
    title: "Estimate the size of imported cosmetics sold in India.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "A small share of the total beauty market, concentrated in metros and skewed heavily toward colour cosmetics and fragrance.",
    hints: ["Import duty pushes prices high, which narrows the buyer base sharply."],
    moves: [
      { label: "Move 1", text: "Size the total beauty and personal care market, then isolate the premium segment." },
      { label: "Move 2", text: "Apply the imported share within premium, since many international brands manufacture locally." },
      { label: "Move 3", text: "Note duty effects. Import duty plus logistics raises shelf prices well above origin market levels." },
      { label: "Move 4", text: "Add grey market and personal imports, which are substantial in fragrance and colour cosmetics." },
      { label: "Check", text: "Grey channels distort official import figures considerably, which is worth stating rather than ignoring." },
    ],
    pitfalls: [
      "Counting locally manufactured international brands as imports.",
      "Ignoring grey market volumes.",
      "Applying premium penetration rates beyond the metro population.",
    ],
  },
  {
    slug: "estimate-the-value-of-a-retail-loyalty-database",
    shape: "guesstimate",
    title: "Estimate the value of a retailer's loyalty customer database.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Value it from incremental margin generated through targeted marketing, not from a per-record price.",
    hints: ["A database is worth what it can generate, not what data brokers quote per record."],
    moves: [
      { label: "Move 1", text: "Size the active member base, which is far smaller than total enrolled members." },
      { label: "Move 2", text: "Estimate incremental spend from targeted campaigns versus untargeted, which is the real value." },
      { label: "Move 3", text: "Apply contribution margin on that incremental spend, over a realistic member lifetime." },
      { label: "Move 4", text: "Add retail media value, since brands pay for access to this audience inside the retailer's channels." },
      { label: "Check", text: "Note privacy constraints, since regulation increasingly limits how this data can be used or shared." },
    ],
    pitfalls: [
      "Valuing per record rather than by generated margin.",
      "Counting enrolled members rather than active ones.",
      "Ignoring data protection constraints on usage.",
    ],
  },
  {
    slug: "market-size-of-indian-ayurvedic-products",
    shape: "guesstimate",
    title: "Size the Indian ayurvedic consumer products market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 30,000 to 50,000 crore rupees, spanning personal care, health supplements and traditional medicine.",
    hints: ["Define the boundary first. Ayurvedic personal care and ayurvedic medicine are very different markets."],
    moves: [
      { label: "Move 1", text: "Define scope: personal care with ayurvedic positioning, supplements, and traditional medicine." },
      { label: "Move 2", text: "Size the largest, personal care, where ayurvedic claims now appear across mainstream brands." },
      { label: "Move 3", text: "Add supplements and health products, which grew substantially after the pandemic." },
      { label: "Move 4", text: "Add classical medicine, much of which is dispensed through practitioners rather than retail." },
      { label: "Check", text: "Note the definitional problem. Nearly every Indian personal care brand now makes some ayurvedic claim, which inflates any market figure." },
    ],
    pitfalls: [
      "Not defining the boundary, which changes the answer several times over.",
      "Ignoring the practitioner channel.",
      "Treating brand positioning claims as evidence of a distinct category.",
    ],
  },
  {
    slug: "estimate-return-on-a-sponsorship",
    shape: "guesstimate",
    title: "Estimate the return on sponsoring a cricket team.",
    type: "Spend estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Value the media exposure at equivalent advertising rates, then discount it heavily since logo exposure is far weaker than an ad.",
    hints: ["Convert exposure seconds into an advertising equivalent, then discount for passive exposure."],
    moves: [
      { label: "Move 1", text: "Size the exposure: seconds of logo visibility across matches, multiplied by audience size." },
      { label: "Move 2", text: "Convert to advertising equivalent value using comparable spot rates." },
      { label: "Move 3", text: "Discount heavily, since a jersey logo is passive and far less effective than a dedicated advertisement." },
      { label: "Move 4", text: "Add the activation rights: hospitality, player appearances and content, which often carry more value than the logo." },
      { label: "Check", text: "Note that sponsorship needs activation spend on top of the fee. Buying the rights and doing nothing wastes most of the value." },
    ],
    pitfalls: [
      "Valuing exposure at full advertising rates.",
      "Ignoring the activation budget needed to make sponsorship work.",
      "Missing the non-media rights that often justify the deal.",
    ],
  },
  {
    slug: "size-of-the-indian-bottled-beverage-market",
    shape: "guesstimate",
    title: "Size the Indian packaged non-alcoholic beverage market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 70,000 to 90,000 crore rupees, with carbonated drinks, juices and packaged water all substantial.",
    hints: ["Consumption is intensely seasonal and geographically skewed. Build accordingly."],
    moves: [
      { label: "Move 1", text: "Split by segment: carbonated soft drinks, juices and nectars, packaged water, and dairy-based drinks." },
      { label: "Move 2", text: "Size consumption occasions, noting that per-person consumption in India is low by global standards." },
      { label: "Move 3", text: "Apply seasonality, since summer months carry a disproportionate share of annual volume." },
      { label: "Move 4", text: "Apply price per litre by segment, which varies widely between water and packaged juice." },
      { label: "Check", text: "Note the distribution constraint. Chilled availability determines sales, which is why coolers matter as much as advertising." },
    ],
    pitfalls: [
      "Ignoring seasonality in a category where it dominates.",
      "Applying one price per litre across water and juice.",
      "Missing that chilled distribution is the real constraint on volume.",
    ],
  },
  {
    slug: "cost-of-entering-modern-trade",
    shape: "guesstimate",
    title: "Estimate the cost for a new brand to enter modern trade.",
    type: "Distribution sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Listing fees, margins and promotional commitments can consume 25 to 40% of the shelf price before any advertising.",
    hints: ["Listing fee is only the entry ticket. Ongoing trade margin and promotions cost far more."],
    moves: [
      { label: "Move 1", text: "Cost the listing fee, charged per stock keeping unit per chain, which is significant for a small brand." },
      { label: "Move 2", text: "Add trade margin, which in modern trade is substantially higher than general trade." },
      { label: "Move 3", text: "Add promotional commitments: end-cap displays, catalogue features and price promotions." },
      { label: "Move 4", text: "Add merchandising staff, since shelf presence must be maintained physically." },
      { label: "Check", text: "Compute the break-even sales rate per store per week. Below that, delisting follows within a couple of quarters." },
    ],
    pitfalls: [
      "Budgeting only the listing fee.",
      "Applying general trade margins to modern trade.",
      "Not computing the rate of sale needed to avoid delisting.",
    ],
  },
  {
    slug: "size-of-the-indian-gaming-market",
    shape: "guesstimate",
    title: "Size the Indian mobile gaming market by revenue.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 20,000 to 30,000 crore rupees, with real-money gaming historically dominating despite far fewer players.",
    hints: ["Separate real-money gaming from casual gaming. Revenue concentration differs enormously."],
    moves: [
      { label: "Move 1", text: "Size the player base, in the hundreds of millions, though most spend nothing at all." },
      { label: "Move 2", text: "Split real-money gaming from casual and mid-core titles, which monetise completely differently." },
      { label: "Move 3", text: "Apply paying user share and average revenue per paying user, both far higher in real-money gaming." },
      { label: "Move 4", text: "Add in-app advertising, which is how the large free-to-play audience is monetised." },
      { label: "Check", text: "Note the regulatory and taxation risk, which has already reshaped the real-money segment substantially." },
    ],
    pitfalls: [
      "Applying one monetisation rate across gaming types.",
      "Ignoring advertising revenue from non-paying players.",
      "Treating the regulatory environment as stable.",
    ],
  },
  {
    slug: "estimate-shelf-space-required",
    shape: "guesstimate",
    title: "Estimate the shelf space a brand needs in a supermarket.",
    type: "Distribution sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Share of shelf should roughly match share of category sales, since space is allocated on rate of sale.",
    hints: ["Retailers allocate space by sales per square foot. That is the whole logic."],
    moves: [
      { label: "Move 1", text: "State the retailer's objective: maximising sales and margin per unit of shelf space." },
      { label: "Move 2", text: "Compute the brand's rate of sale relative to competitors in the same category." },
      { label: "Move 3", text: "Note the feedback loop, since more facings drive more sales, which then justifies more facings." },
      { label: "Move 4", text: "Consider out-of-stock risk, since insufficient facings cause gaps between replenishment cycles." },
      { label: "Check", text: "Note that a new brand must buy its way past this logic, which is what listing and promotion fees are for." },
    ],
    pitfalls: [
      "Arguing for space on brand importance rather than rate of sale.",
      "Ignoring the self-reinforcing loop between facings and sales.",
      "Missing that replenishment frequency affects how many facings are needed.",
    ],
  },
  {
    slug: "size-of-indian-fitness-market",
    shape: "guesstimate",
    title: "Size the Indian organised fitness market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 12,000 to 20,000 crore rupees including gyms, studios and equipment, with membership churn very high.",
    hints: ["Memberships sold and members attending differ hugely. Say which you are sizing."],
    moves: [
      { label: "Move 1", text: "Size urban adults with disposable income, then apply gym membership penetration." },
      { label: "Move 2", text: "Apply annual membership value, which varies from a few thousand rupees to premium chain pricing." },
      { label: "Move 3", text: "Add boutique studios, personal training and home equipment, which are separate revenue pools." },
      { label: "Move 4", text: "Apply churn, since a large share of memberships lapse within months of joining." },
      { label: "Check", text: "Note that the business model depends on non-attendance. Gyms are priced assuming most members rarely come." },
    ],
    pitfalls: [
      "Applying Western fitness penetration rates.",
      "Ignoring churn, which is central to the economics.",
      "Missing home equipment and app-based fitness as adjacent markets.",
    ],
  },
  {
    slug: "estimate-print-versus-digital-ad-spend",
    shape: "guesstimate",
    title: "Estimate the split between print and digital advertising in India.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Digital has overtaken print and continues to grow, though print retains disproportionate strength in regional markets.",
    hints: ["Print declined more slowly in India than globally. The regional press is why."],
    moves: [
      { label: "Move 1", text: "Size total advertising spend across all media, in the region of a lakh crore rupees." },
      { label: "Move 2", text: "Apply the digital share, which has grown rapidly and now leads." },
      { label: "Move 3", text: "Note the print exception, since regional language newspapers retain readership and advertiser trust." },
      { label: "Move 4", text: "Split digital between search, social, video and retail media, which have different growth rates." },
      { label: "Check", text: "Note that television remains substantial in India, unlike in several Western markets where it has fallen faster." },
    ],
    pitfalls: [
      "Applying Western media mix trends directly to India.",
      "Underestimating regional print, which held up far better than English titles.",
      "Treating digital as one homogeneous channel.",
    ],
  },
  {
    slug: "estimate-repeat-rate-for-a-food-brand",
    shape: "guesstimate",
    title: "Estimate the repeat purchase rate a new snack brand needs to survive.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Repeat rate above roughly 30% within a quarter, since trial can be bought but only repeat sustains the business.",
    hints: ["Trial is a marketing outcome. Repeat is a product verdict."],
    moves: [
      { label: "Move 1", text: "Separate trial from repeat. Sampling and promotion generate trial regardless of product quality." },
      { label: "Move 2", text: "Model the economics. Trial is bought at a cost, and only repeat purchases recover it." },
      { label: "Move 3", text: "Compute the repeat rate needed for contribution to cover acquisition within a reasonable window." },
      { label: "Move 4", text: "Note the shelf consequence, since retailers delist on rate of sale, which depends on repeat." },
      { label: "Check", text: "State that a low repeat rate cannot be fixed with more advertising. That is the real conclusion." },
    ],
    pitfalls: [
      "Judging a launch on trial volume alone.",
      "Responding to weak repeat with more promotion.",
      "Ignoring the retailer's delisting threshold.",
    ],
  },
  {
    slug: "size-the-market-for-a-new-city-launch",
    shape: "guesstimate",
    title: "Size the opportunity for launching a delivery service in a new city.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Addressable households times order frequency times basket size, discounted heavily for the first year while habit forms.",
    hints: ["The first-year number is far below steady state. Model the ramp, not the potential."],
    moves: [
      { label: "Move 1", text: "Size addressable households: urban, smartphone-owning, with the income to pay delivery premiums." },
      { label: "Move 2", text: "Apply expected order frequency, benchmarked against a comparable city at similar maturity." },
      { label: "Move 3", text: "Apply basket size, which is typically lower outside metros." },
      { label: "Move 4", text: "Discount for the ramp, since habit formation takes quarters and supply must be built alongside." },
      { label: "Check", text: "Compare against the fixed cost of launching. Many city launches fail because steady state was modelled instead of year one." },
    ],
    pitfalls: [
      "Modelling steady-state penetration in year one.",
      "Applying metro basket sizes to a smaller city.",
      "Ignoring the supply build required before demand can be served.",
    ],
  },
  {
    slug: "size-of-corporate-gifting-market",
    shape: "guesstimate",
    title: "Size the Indian corporate gifting market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 20,000 to 35,000 crore rupees, concentrated around Diwali and heavily skewed toward larger employers.",
    hints: ["Employees and clients are two different gifting budgets. Size both."],
    moves: [
      { label: "Move 1", text: "Size the organised employer base by company size, since gifting scales with formal employment." },
      { label: "Move 2", text: "Apply per-employee gifting budgets, which range from a few hundred to several thousand rupees." },
      { label: "Move 3", text: "Add client gifting, which is smaller in volume but far higher in value per unit." },
      { label: "Move 4", text: "Note the concentration into the festive window, which defines supply chain and pricing." },
      { label: "Check", text: "Note the shift toward vouchers and experiences, which changes who captures the value." },
    ],
    pitfalls: [
      "Applying a uniform gifting budget across company sizes.",
      "Missing client gifting, which is high value.",
      "Ignoring the shift from physical gifts to digital vouchers.",
    ],
  },
  {
    slug: "estimate-word-of-mouth-contribution",
    shape: "guesstimate",
    title: "Estimate what share of a brand's new customers come from word of mouth.",
    type: "Reach estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Often 20 to 40% for a well-liked consumer brand, though attribution systematically undercounts it.",
    hints: ["Attribution tools credit the last click. Word of mouth rarely produces one."],
    moves: [
      { label: "Move 1", text: "Note the measurement problem. Referred customers often arrive through a search click and are credited to search." },
      { label: "Move 2", text: "Use survey attribution, asking customers directly how they heard about the brand." },
      { label: "Move 3", text: "Use a holdout test. Reducing paid spend in one region reveals the organic baseline." },
      { label: "Move 4", text: "Compare organic and direct traffic growth against paid spend to spot the underlying trend." },
      { label: "Close", text: "Note the strategic implication. Underestimating word of mouth leads to overspending on paid acquisition." },
    ],
    pitfalls: [
      "Trusting last-click attribution for a channel that produces no click.",
      "Assuming organic traffic is independent of brand spend.",
      "Never running a holdout test, which is the only clean measurement.",
    ],
  },
  {
    slug: "estimate-price-elasticity-for-a-staple",
    shape: "guesstimate",
    title: "Estimate the price elasticity of a staple food product.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Category demand is inelastic but brand demand is highly elastic, since switching brands is easy and cheap.",
    hints: ["Category elasticity and brand elasticity are entirely different. Say which you are estimating."],
    moves: [
      { label: "Move 1", text: "Separate the two. People buy roughly the same quantity of salt regardless of price, but choose freely between brands." },
      { label: "Move 2", text: "Assess switching cost, which for an undifferentiated staple is essentially zero." },
      { label: "Move 3", text: "Consider availability, since a shopper faced with only one brand on the shelf has no elasticity at all." },
      { label: "Move 4", text: "Note the price point effect, where crossing a psychological threshold causes a disproportionate volume drop." },
      { label: "Check", text: "The practical conclusion is that distribution matters more than price in staples, which is why brands fight for shelf presence." },
    ],
    pitfalls: [
      "Conflating category and brand elasticity.",
      "Ignoring availability, which caps elasticity in practice.",
      "Missing psychological price points, which produce non-linear responses.",
    ],
  },
  {
    slug: "size-of-second-hand-fashion-india",
    shape: "guesstimate",
    title: "Size the market for second-hand fashion in India.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Small in organised terms, though informal resale and hand-me-down circulation is enormous and largely unmeasured.",
    hints: ["The informal market dwarfs the organised one here. Say so rather than ignoring it."],
    moves: [
      { label: "Move 1", text: "Note the cultural context. Hand-me-downs within families are normal but generate no transaction." },
      { label: "Move 2", text: "Size the organised resale market, which is small and metro-concentrated." },
      { label: "Move 3", text: "Size informal resale through local markets and vendors, which is substantial and cash-based." },
      { label: "Move 4", text: "Note the premium exception, where luxury resale is growing with authentication services." },
      { label: "Check", text: "The organised opportunity is narrow. Recognising that, rather than quoting a large total, is the honest answer." },
    ],
    pitfalls: [
      "Applying Western resale market penetration.",
      "Counting non-transactional hand-me-downs as market value.",
      "Missing that authentication is the binding constraint on premium resale.",
    ],
  },
  {
    slug: "estimate-cost-of-a-rebrand",
    shape: "guesstimate",
    title: "Estimate the cost of rebranding a national retail chain.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Physical signage and store refits dwarf the design fee, often by a factor of ten or more.",
    hints: ["The design work is the smallest line. Signage across hundreds of stores is the real cost."],
    moves: [
      { label: "Move 1", text: "Cost the design and strategy work, which is meaningful but modest in the total." },
      { label: "Move 2", text: "Cost physical implementation: signage, interiors, uniforms and vehicle livery across every location." },
      { label: "Move 3", text: "Cost the communication campaign needed so customers recognise the changed brand." },
      { label: "Move 4", text: "Add packaging, stationery, digital assets and the transition period where both identities coexist." },
      { label: "Check", text: "Weigh against the risk of losing existing recognition, which is the real cost nobody budgets for." },
    ],
    pitfalls: [
      "Budgeting the agency fee and treating implementation as an afterthought.",
      "Forgetting the communication spend needed to transfer recognition.",
      "Ignoring the equity lost in the old identity.",
    ],
  },
  {
    slug: "estimate-market-share-from-shelf-observation",
    shape: "guesstimate",
    title: "Estimate a brand's market share from shelf observation alone.",
    type: "Distribution sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Shelf facings approximate share of sales in that store, but store selection bias makes extrapolation unreliable.",
    hints: ["Facings reflect the retailer's view of rate of sale, which makes them a useful but biased proxy."],
    moves: [
      { label: "Move 1", text: "Note why facings work as a proxy. Retailers allocate space by rate of sale, so facings track sales." },
      { label: "Move 2", text: "Note the limitations. Facings lag actual sales and can be bought through trade deals." },
      { label: "Move 3", text: "Address sampling. Metro modern trade stores are not representative of national sales." },
      { label: "Move 4", text: "Cross-check with a second method, such as distributor interviews or observed purchase counts." },
      { label: "Close", text: "State the confidence honestly. This method gives a directional estimate, not a share figure you would publish." },
    ],
    pitfalls: [
      "Extrapolating from a handful of convenient stores.",
      "Ignoring that facings can be purchased rather than earned.",
      "Presenting a directional estimate with false precision.",
    ],
  },
  {
    slug: "size-of-the-indian-coaching-market",
    shape: "guesstimate",
    title: "Size the Indian test preparation coaching market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 50,000 to 70,000 crore rupees, dominated by engineering, medical and government exam preparation.",
    hints: ["A few exams drive most of the spend. Size those rather than education generally."],
    moves: [
      { label: "Move 1", text: "Identify the major exams: engineering entrance, medical entrance, civil services and banking." },
      { label: "Move 2", text: "Size the candidate pool for each, which runs into millions for the largest." },
      { label: "Move 3", text: "Apply the coached share and fee levels, which vary from a few thousand to lakhs of rupees." },
      { label: "Move 4", text: "Add school tuition, which is enormous in aggregate but highly fragmented and mostly informal." },
      { label: "Check", text: "Note the repeat candidate effect, since many students attempt these exams more than once, extending the coaching relationship." },
    ],
    pitfalls: [
      "Sizing all private education rather than test preparation.",
      "Missing repeat attempts, which extend spend per student.",
      "Ignoring the informal home tuition market.",
    ],
  },
  {
    slug: "estimate-effect-of-a-price-increase",
    shape: "guesstimate",
    title: "Estimate the volume loss from a 10% price increase on a branded product.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Depends entirely on whether competitors follow. Alone, volume loss can far exceed the price gain. Together, it may be minimal.",
    hints: ["The competitive response determines the answer more than any elasticity estimate."],
    moves: [
      { label: "Move 1", text: "Establish the competitive context. A category-wide input cost rise usually means everyone raises prices." },
      { label: "Move 2", text: "Estimate brand elasticity if raising alone, which for a substitutable product is high." },
      { label: "Move 3", text: "Compute the revenue effect. Volume loss beyond a threshold makes the increase value-destroying." },
      { label: "Move 4", text: "Consider grammage reduction, which in Indian FMCG is the standard alternative to a visible price rise." },
      { label: "Check", text: "State the threshold volume loss at which the increase stops being worthwhile, which makes the answer decision-ready." },
    ],
    pitfalls: [
      "Estimating elasticity without considering competitor response.",
      "Ignoring grammage reduction as the preferred Indian alternative.",
      "Not computing the break-even volume loss.",
    ],
  },
  {
    slug: "size-of-the-indian-baby-care-market",
    shape: "guesstimate",
    title: "Size the Indian baby care products market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 15,000 to 25,000 crore rupees across diapers, skincare, feeding and toiletries.",
    hints: ["A falling birth rate against rising spend per child is the tension in this category."],
    moves: [
      { label: "Move 1", text: "Size the birth cohort at roughly 23 to 25 million a year, and the under-three population." },
      { label: "Move 2", text: "Split by category: diapers, skincare, feeding products and toiletries." },
      { label: "Move 3", text: "Apply penetration and spend per child, both far higher in urban affluent households." },
      { label: "Move 4", text: "Note the premiumisation effect, since parents trade up in this category more readily than in most." },
      { label: "Check", text: "Note the structural tension. Fewer births but more spend per child is what drives category growth." },
    ],
    pitfalls: [
      "Applying urban spend patterns nationally.",
      "Ignoring the declining birth rate.",
      "Missing that safety concerns make this category unusually brand-loyal.",
    ],
  },
  {
    slug: "estimate-social-media-reach-for-a-brand",
    shape: "guesstimate",
    title: "Estimate organic social media reach for a mid-size Indian brand.",
    type: "Reach estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Typically 3 to 8% of followers see any given post organically, so follower count vastly overstates actual reach.",
    hints: ["Followers are not reach. Platform algorithms show posts to a small fraction."],
    moves: [
      { label: "Move 1", text: "Start from follower count, which is the vanity number." },
      { label: "Move 2", text: "Apply organic reach rate, which platforms have compressed steadily to encourage paid promotion." },
      { label: "Move 3", text: "Apply engagement rate on those reached, which is a fraction again." },
      { label: "Move 4", text: "Note the amplification effect, where engagement can extend reach beyond the follower base." },
      { label: "Check", text: "The conclusion is that follower count is a poor proxy for reach, which is why brands must pay to reach their own audience." },
    ],
    pitfalls: [
      "Reporting follower count as reach.",
      "Using historical organic reach rates, which have fallen sharply.",
      "Ignoring that a small share of posts capture most of the reach.",
    ],
  },
  {
    slug: "size-of-the-indian-furniture-market",
    shape: "guesstimate",
    title: "Size the Indian furniture market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 2.5 to 4 lakh crore rupees, overwhelmingly unorganised carpenter-made rather than branded.",
    hints: ["Most Indian furniture is made to order by local carpenters, not bought off a shelf."],
    moves: [
      { label: "Move 1", text: "Size demand drivers: new household formation, home purchases and replacement." },
      { label: "Move 2", text: "Apply spend per household event, which is substantial and lumpy." },
      { label: "Move 3", text: "Split organised from unorganised, where local carpentry dominates outside metros." },
      { label: "Move 4", text: "Add office and institutional furniture, which is more organised than the residential segment." },
      { label: "Check", text: "Note that the organised share is small, which is exactly the opportunity branded players are pursuing." },
    ],
    pitfalls: [
      "Sizing only branded furniture retail.",
      "Ignoring the office and institutional segment.",
      "Treating furniture as a regular purchase rather than an infrequent lumpy one.",
    ],
  },
  {
    slug: "estimate-conversion-from-a-mall-activation",
    shape: "guesstimate",
    title: "Estimate the return on a weekend mall activation.",
    type: "Spend estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Contact volume is high but conversion is low, so cost per acquired customer is usually higher than digital.",
    hints: ["Count actual meaningful interactions, not everyone who walks past."],
    moves: [
      { label: "Move 1", text: "Size footfall past the activation site, then apply the share who stop and engage." },
      { label: "Move 2", text: "Apply conversion from engagement to trial or purchase, which is modest." },
      { label: "Move 3", text: "Cost the activation: space rental, staff, materials and product samples." },
      { label: "Move 4", text: "Compute cost per acquired customer and compare against digital acquisition." },
      { label: "Check", text: "Note the secondary value: physical product experience and content generated, which digital cannot replicate." },
    ],
    pitfalls: [
      "Counting passers-by as contacts.",
      "Ignoring space rental, which is the largest cost line.",
      "Missing the non-acquisition value of physical product trial.",
    ],
  },
  {
    slug: "estimate-market-for-regional-language-content",
    shape: "guesstimate",
    title: "Size the market for regional language streaming content in India.",
    type: "Category sizing",
    difficulty: 3,
    minutes: 25,
    answer: "The audience is far larger than the English-speaking one, but revenue per user is much lower, which inverts the picture.",
    hints: ["Audience size and revenue move in opposite directions here. State both."],
    moves: [
      { label: "Move 1", text: "Size the audience by language, where regional language internet users far outnumber English ones." },
      { label: "Move 2", text: "Apply willingness to pay, which is lower and pushes most consumption to ad-funded tiers." },
      { label: "Move 3", text: "Size advertising revenue, which is the primary monetisation for this audience." },
      { label: "Move 4", text: "Note content cost, which is far lower per hour for regional production than for national or international content." },
      { label: "Check", text: "The economics can work despite lower revenue per user, because production cost scales down with the audience's willingness to pay." },
    ],
    pitfalls: [
      "Applying English-audience subscription rates to regional viewers.",
      "Ignoring that content cost also differs by language market.",
      "Treating regional language as one homogeneous audience.",
    ],
  },
  {
    slug: "size-of-indian-perfume-market",
    shape: "guesstimate",
    title: "Size the Indian perfume and deodorant market.",
    type: "Category sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 8,000 to 12,000 crore rupees, with deodorants dominating volume and fine fragrance a small premium slice.",
    hints: ["Deodorant and perfume are different markets at different price points. Split them."],
    moves: [
      { label: "Move 1", text: "Split the category. Mass deodorants sell at a few hundred rupees, fine fragrance at several thousand." },
      { label: "Move 2", text: "Size deodorant users among urban adults, where penetration is high and usage frequent." },
      { label: "Move 3", text: "Size the fragrance buyer, a narrower group buying occasionally rather than routinely." },
      { label: "Move 4", text: "Add traditional attars and the gifting occasion, which is a meaningful share of fragrance volume." },
      { label: "Check", text: "Note the grey market in imported fragrance, which is large and absent from official figures." },
    ],
    pitfalls: [
      "Merging deodorant and fine fragrance into one market.",
      "Ignoring the gifting occasion, which drives fragrance purchase.",
      "Missing grey market imports.",
    ],
  },
];
