import type { Question } from "./types";

// Operations guesstimates. Throughput, capacity, fleets and workforces:
// numbers an operations interview expects you to build, not look up.
export const OPERATIONS_GUESSTIMATES: Question[] = [
  {
    slug: "dabbawala-tiffins-mumbai-daily",
    shape: "guesstimate",
    title: "How many tiffins do Mumbai's dabbawalas deliver in a day?",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Around 2 lakh tiffins a day, moved by roughly 5,000 dabbawalas.",
    hints: ["Work from the workforce side: dabbawalas times tiffins each can handle per day."],
    moves: [
      { label: "Move 1", text: "Anchor on the workforce. The system runs on roughly 5,000 dabbawalas." },
      { label: "Move 2", text: "Estimate individual load. Each handles 30 to 40 tiffins across collection, sorting and delivery." },
      { label: "Move 3", text: "Multiply: 5,000 times 35 gives about 1.75 to 2 lakh tiffins." },
      { label: "Move 4", text: "Sanity-check demand: of Mumbai's several million office-goers, only a small share uses home-cooked tiffin delivery." },
      { label: "Check", text: "Each tiffin is handled 3 to 4 times in the relay, so handling events far exceed tiffin count. Don't confuse the two." },
    ],
    pitfalls: [
      "Sizing from Mumbai's whole working population instead of the niche that uses the service.",
      "Counting handling events as deliveries.",
      "Ignoring that the system also carries the empty tiffin back.",
    ],
  },
  {
    slug: "delhi-metro-trains-morning-peak",
    shape: "guesstimate",
    title: "Estimate how many trains Delhi Metro runs during the morning peak.",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 250 to 300 trains in service across the network during peak hours.",
    hints: ["Trains per line equals route length divided by headway times speed. Then sum lines."],
    moves: [
      { label: "Move 1", text: "Take the network: about 10 lines, 390 km total, average line around 40 km end to end." },
      { label: "Move 2", text: "A round trip at 32 kmph average takes about 2.5 hours on a 40 km line." },
      { label: "Move 3", text: "At a 3-minute peak headway, one line needs 2.5 hours divided by 3 minutes, so about 50 trains, though shorter lines need fewer." },
      { label: "Move 4", text: "Blend line lengths and headways: roughly 25 to 30 trains per line average across 10 lines." },
      { label: "Check", text: "DMRC's fleet is around 350 train sets; a peak deployment near 80% of fleet is plausible." },
    ],
    pitfalls: [
      "Forgetting the return direction when computing trains needed per headway.",
      "Using top speed instead of average speed with dwell times.",
      "Assuming every line runs the same headway as the busiest one.",
    ],
  },
  {
    slug: "zomato-delivery-fleet-india",
    shape: "guesstimate",
    title: "How many delivery partners does Zomato need on a normal weekday?",
    type: "Fleet sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Zomato",
    answer: "Around 3 to 4 lakh active partners on a weekday, against a much larger registered base.",
    hints: ["Start from daily orders, then divide by orders one rider completes in a shift."],
    moves: [
      { label: "Move 1", text: "Anchor daily orders: roughly 5 to 6 million on a normal weekday." },
      { label: "Move 2", text: "Rider productivity: about 30 minutes per order door to door means a 7 hour active shift completes 12 to 15 orders." },
      { label: "Move 3", text: "Divide: 5.5 million by 14 gives about 4 lakh rider-shifts." },
      { label: "Move 4", text: "Adjust for part-timers who work only the dinner peak, pushing headcount above shift count." },
      { label: "Check", text: "Peak-hour concurrency is the binding constraint: dinner needs far more riders per hour than the daily average implies." },
    ],
    pitfalls: [
      "Sizing to average demand when the fleet must clear the dinner peak.",
      "Treating registered riders as active riders.",
      "Ignoring stacked orders, which raise effective productivity in dense zones.",
    ],
  },
  {
    slug: "flipkart-warehouse-pickers-bbd",
    shape: "guesstimate",
    title: "Estimate the pickers one Flipkart mega-warehouse needs on a sale day.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Flipkart",
    answer: "Roughly 2,500 to 3,500 pickers per shift for a warehouse shipping a million units a day.",
    hints: ["Units per day divided by picks per picker per shift."],
    moves: [
      { label: "Move 1", text: "Set the sale-day target: a flagship fulfilment centre ships around 1 million units." },
      { label: "Move 2", text: "Picker productivity: 40 to 60 picks an hour with handhelds, so about 400 per 8-hour shift." },
      { label: "Move 3", text: "Divide: 1 million over two shifts is 500,000 per shift, needing about 1,250 pickers at ideal productivity." },
      { label: "Move 4", text: "Load for reality: absenteeism, congestion in aisles and new temp hires at half productivity roughly double the need." },
      { label: "Check", text: "Picking is only one role; packing, sorting and loading typically add as many people again." },
    ],
    pitfalls: [
      "Using trained-picker productivity for a workforce that is half temporary hires.",
      "Forgetting the second shift.",
      "Sizing pickers and presenting it as total warehouse headcount.",
    ],
  },
  {
    slug: "mumbai-airport-baggage-peak-hour",
    shape: "guesstimate",
    title: "How many bags does Mumbai airport's system handle in a peak hour?",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 12,000 to 15,000 bags an hour across departures, arrivals and transfers.",
    hints: ["Flights per hour times seats times load factor times bags per passenger."],
    moves: [
      { label: "Move 1", text: "Peak movements: about 45 to 50 flights an hour, split between arrivals and departures." },
      { label: "Move 2", text: "Passengers: 170-seat average at 85% load gives about 145 passengers per flight." },
      { label: "Move 3", text: "Bags: roughly 0.8 checked bags per domestic passenger, higher for international." },
      { label: "Move 4", text: "Multiply: 48 flights times 145 passengers times 0.9 bags is about 6,300, doubled for both directions gives 12,000+." },
      { label: "Check", text: "The system is sized above demand for redundancy; quoted design capacity will exceed your throughput number." },
    ],
    pitfalls: [
      "Counting only departures when arrivals also ride the belts.",
      "Using international bag ratios for a mostly domestic peak.",
      "Confusing design capacity with actual peak flow.",
    ],
  },
  {
    slug: "kirana-restock-visits-distributor",
    shape: "guesstimate",
    title: "How many kirana stores can one FMCG distributor salesman cover in a day?",
    type: "Route sizing",
    difficulty: 1,
    minutes: 15,
    askedAt: "ITC",
    answer: "About 30 to 40 productive store visits a day on a dense urban beat.",
    hints: ["Divide the working day by time per visit including travel between stores."],
    moves: [
      { label: "Move 1", text: "Set the working window: about 8 hours on the beat." },
      { label: "Move 2", text: "Time per visit: 8 to 10 minutes taking an order plus 3 to 4 minutes moving to the next store in a dense market." },
      { label: "Move 3", text: "Divide: 480 minutes by 13 gives about 35 visits." },
      { label: "Move 4", text: "Adjust for strike rate: not every visit yields an order; rural beats halve the count through travel." },
      { label: "Check", text: "A weekly beat cycle means one salesman services roughly 200 unique stores." },
    ],
    pitfalls: [
      "Ignoring travel time between stores.",
      "Assuming every visit converts to an order.",
      "Using urban density for rural route math.",
    ],
  },
  {
    slug: "toll-plaza-lanes-expressway",
    shape: "guesstimate",
    title: "How many FASTag lanes does a busy expressway toll plaza need?",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 20,
    answer: "About 6 to 8 lanes per direction for a plaza passing 60,000 vehicles a day.",
    hints: ["Size to the peak hour, not the daily average."],
    moves: [
      { label: "Move 1", text: "Daily volume: a busy plaza sees about 60,000 vehicles, 30,000 per direction." },
      { label: "Move 2", text: "Peak-hour share: roughly 10% of daily traffic, so 3,000 vehicles per direction per hour." },
      { label: "Move 3", text: "Lane throughput: a flowing FASTag lane passes a vehicle every 6 to 8 seconds, about 500 an hour." },
      { label: "Move 4", text: "Divide: 3,000 over 500 gives 6 lanes, plus buffer for failed reads and oversize vehicles." },
      { label: "Check", text: "One stalled read halves a lane's throughput; the buffer lane is what keeps queues short." },
    ],
    pitfalls: [
      "Sizing to average hourly flow instead of the peak.",
      "Using the advertised per-transaction time as sustained throughput.",
      "Forgetting trucks take longer than cars at the boom." ,
    ],
  },
  {
    slug: "amul-milk-collection-daily",
    shape: "guesstimate",
    title: "Estimate the milk Amul collects across India every day.",
    type: "Network sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 250 to 300 lakh litres a day from over 30 lakh member farmers.",
    hints: ["Farmers times animals times yield, or work backward from Amul's market share of dairy."],
    moves: [
      { label: "Move 1", text: "Anchor the member base: around 35 lakh farmer members across village societies." },
      { label: "Move 2", text: "Not all pour daily: perhaps 70% deliver on a given day." },
      { label: "Move 3", text: "Per-farmer pour: 2 to 3 buffalo or cows at 4 to 5 litres marketable surplus gives 10 to 12 litres." },
      { label: "Move 4", text: "Multiply: 25 lakh pouring farmers times 11 litres is about 275 lakh litres." },
      { label: "Check", text: "Collection swings 20% between flush and lean season; quote a range, not a point." },
    ],
    pitfalls: [
      "Using total milk yield instead of marketable surplus after home consumption.",
      "Ignoring seasonality between flush and lean months.",
      "Assuming every registered member pours every day.",
    ],
  },
  {
    slug: "hospital-ot-surgeries-per-day",
    shape: "guesstimate",
    title: "How many surgeries can a 10-theatre hospital run in a day?",
    type: "Capacity estimation",
    difficulty: 1,
    minutes: 15,
    answer: "About 40 to 50 surgeries a day at realistic utilisation.",
    hints: ["Theatre hours divided by average procedure time including turnover."],
    moves: [
      { label: "Move 1", text: "Set theatre hours: 10 theatres running 10 planned hours gives 100 theatre-hours." },
      { label: "Move 2", text: "Average procedure: 90 minutes of surgery plus 30 minutes of cleaning and setup, so 2 hours per case." },
      { label: "Move 3", text: "Divide: 100 hours over 2 gives 50 cases at perfect flow." },
      { label: "Move 4", text: "Apply utilisation: delays, emergencies and cancellations bring realistic throughput to 80%, about 40 cases." },
      { label: "Check", text: "Case mix moves the answer: a cataract line does 10 an hour, a cardiac theatre does 2 a day." },
    ],
    pitfalls: [
      "Forgetting turnover time between cases.",
      "Averaging across wildly different case types without saying so.",
      "Assuming theatres run at 100% of planned hours.",
    ],
  },
  {
    slug: "bengaluru-water-tankers-summer",
    shape: "guesstimate",
    title: "Estimate the private water tankers operating in Bengaluru in peak summer.",
    type: "Fleet sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 3,000 to 5,000 tankers making several trips a day to bridge a large supply gap.",
    hints: ["Size the demand gap in litres first, then divide by tanker capacity times trips."],
    moves: [
      { label: "Move 1", text: "Population without reliable piped supply in summer: perhaps 30 lakh people across outer wards." },
      { label: "Move 2", text: "Tanker-served need: about 50 litres per person per day of the shortfall comes by tanker." },
      { label: "Move 3", text: "Total gap: 30 lakh times 50 litres is 15 crore litres a day." },
      { label: "Move 4", text: "Tanker supply: a 6,000-litre tanker doing 6 trips moves 36,000 litres, so about 4,000 tankers." },
      { label: "Check", text: "Trip count is constrained by borewell filling time and traffic; 6 trips is a full day." },
    ],
    pitfalls: [
      "Sizing total city demand instead of the unmet gap.",
      "Ignoring that apartments buy in bulk while slums buy in pots.",
      "Using highway travel times for city tanker trips.",
    ],
  },
  {
    slug: "railway-station-footfall-howrah",
    shape: "guesstimate",
    title: "Estimate daily passenger footfall at Howrah station.",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 8 to 10 lakh passengers a day across suburban and long-distance services.",
    hints: ["Split suburban and long-distance; suburban dominates the count."],
    moves: [
      { label: "Move 1", text: "Count services: Howrah handles around 250 suburban and 250 long-distance train movements daily." },
      { label: "Move 2", text: "Suburban load: a 12-car EMU carries 3,000+ in peak; average 1,500 per movement gives about 4 lakh." },
      { label: "Move 3", text: "Long-distance load: 1,000 to 1,500 per train gives another 3 lakh." },
      { label: "Move 4", text: "Add non-travellers: vendors, porters and those receiving passengers add 10 to 20%." },
      { label: "Check", text: "Footfall counts entries, not journeys; a person entering to receive someone still crosses the gate." },
    ],
    pitfalls: [
      "Using rated coach capacity instead of crush-hour reality for suburban trains.",
      "Ignoring off-peak emptiness when averaging.",
      "Double counting passengers who change trains.",
    ],
  },
  {
    slug: "atm-cash-refills-mumbai",
    shape: "guesstimate",
    title: "How many cash-van trips does Mumbai need daily to keep ATMs filled?",
    type: "Route sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 800 to 1,200 van trips servicing a few thousand of the city's ATMs each day.",
    hints: ["ATMs times refill frequency divided by machines one van services per trip."],
    moves: [
      { label: "Move 1", text: "Count machines: Mumbai has roughly 10,000 ATMs." },
      { label: "Move 2", text: "Refill frequency: a busy machine needs cash every 2 days, a quiet one weekly; average every 3 days, so about 3,300 refills a day." },
      { label: "Move 3", text: "Van productivity: security protocol means 25 to 40 minutes per stop; a van covers 8 to 10 machines a shift." },
      { label: "Move 4", text: "Divide: 3,300 over 9 gives about 370 vans, but each does one route, so trips equal routes; add spare capacity for outages." },
      { label: "Check", text: "Salary week doubles withdrawal velocity; the network is sized for month-start, not month-middle." },
    ],
    pitfalls: [
      "Assuming every ATM refills daily.",
      "Ignoring the security dwell time that dominates each stop.",
      "Forgetting demand spikes at month start.",
    ],
  },
  {
    slug: "qsr-burgers-lunch-rush",
    shape: "guesstimate",
    title: "How many burgers can one McDonald's kitchen produce in the lunch rush?",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 300 to 400 burgers an hour at full line staffing.",
    hints: ["Find the bottleneck station; the grill sets the pace, not the counter."],
    moves: [
      { label: "Move 1", text: "Identify the bottleneck: the grill. One platen cooks 8 to 12 patties in about 2 minutes." },
      { label: "Move 2", text: "Grill throughput: two platens cycling gives roughly 300 patties an hour." },
      { label: "Move 3", text: "Assembly keeps pace: a staffed line dresses a burger in 20 to 30 seconds across parallel stations." },
      { label: "Move 4", text: "Cap at the slowest station: about 300 to 400 units an hour leaves the kitchen." },
      { label: "Check", text: "Counter demand above that shows up as wait time, not more burgers; capacity is the grill's, not the queue's." },
    ],
    pitfalls: [
      "Sizing from cashier speed instead of the cooking bottleneck.",
      "Ignoring parallel assembly stations.",
      "Confusing peak-hour capacity with all-day average.",
    ],
  },
  {
    slug: "mumbai-port-containers-daily",
    shape: "guesstimate",
    title: "Estimate the containers JNPT moves on a typical day.",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 17,000 to 20,000 TEUs a day, consistent with 6+ million TEUs a year.",
    hints: ["Cranes times moves per hour times hours, summed across berths."],
    moves: [
      { label: "Move 1", text: "Count the machinery: about 30 quay cranes across the port's terminals." },
      { label: "Move 2", text: "Crane rate: 25 to 30 moves an hour when a vessel is at berth." },
      { label: "Move 3", text: "Utilisation: cranes work vessels perhaps 60% of hours; 30 cranes times 27 moves times 14 effective hours gives about 11,000 lifts." },
      { label: "Move 4", text: "Convert lifts to TEUs: many boxes are 40-foot, so TEUs run 1.6 times lifts, near 18,000." },
      { label: "Check", text: "Cross-check annually: 18,000 a day times 350 days lands near the port's reported 6 million TEUs." },
    ],
    pitfalls: [
      "Equating one crane lift with one TEU.",
      "Assuming cranes work around the clock at rated speed.",
      "Ignoring that yard and gate moves are separate from quay moves.",
    ],
  },
  {
    slug: "ecommerce-returns-processing-center",
    shape: "guesstimate",
    title: "Size the returns processing operation for a fashion e-commerce site.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Myntra",
    answer: "For a million orders a day, returns processing needs 2,500 to 3,500 people handling roughly 250,000 items.",
    hints: ["Fashion return rates are far higher than electronics; start there."],
    moves: [
      { label: "Move 1", text: "Anchor return volume: fashion runs 25 to 30% returns, so a million daily orders send back about 250,000 items." },
      { label: "Move 2", text: "Process steps: receive, quality-check, refurbish or grade, restock; about 5 minutes of touch time per item." },
      { label: "Move 3", text: "Convert to labour: 250,000 items times 5 minutes is about 21,000 hours, or 2,600 people at 8 hours." },
      { label: "Move 4", text: "Add the reverse logistics leg: pickup riders and line-haul are usually the larger cost." },
      { label: "Check", text: "Roughly half of fashion returns can be resold as new; the grading decision drives recovery economics." },
    ],
    pitfalls: [
      "Applying electronics return rates to fashion.",
      "Counting only warehouse labour and ignoring doorstep pickup.",
      "Assuming every return restocks as new.",
    ],
  },
  {
    slug: "petrol-pump-vehicles-daily",
    shape: "guesstimate",
    title: "How many vehicles does a busy city petrol pump serve daily?",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 1,200 to 1,800 vehicles across 4 to 6 dispensing points.",
    hints: ["Nozzles times vehicles per nozzle-hour times operating hours, weighted for peaks."],
    moves: [
      { label: "Move 1", text: "Count dispensing points: a busy pump runs 4 to 6 nozzles in parallel." },
      { label: "Move 2", text: "Service time: 3 to 4 minutes per two-wheeler or car including payment, so 15 to 18 vehicles per nozzle-hour." },
      { label: "Move 3", text: "Operating window: 16 active hours with morning and evening peaks near capacity, midday at half." },
      { label: "Move 4", text: "Blend: 5 nozzles times 16 vehicles times 16 hours at 70% utilisation gives about 1,400." },
      { label: "Check", text: "Fuel volume cross-check: 1,400 vehicles at 4 litres average is under 6,000 litres, plausible for a city pump." },
    ],
    pitfalls: [
      "Running all hours at peak throughput.",
      "Ignoring two-wheelers, which dominate count but not volume.",
      "Forgetting payment time in the service cycle.",
    ],
  },
  {
    slug: "cold-chain-trucks-vaccine-drive",
    shape: "guesstimate",
    title: "Estimate refrigerated vehicles needed to vaccinate a state of 8 crore in 6 months.",
    type: "Fleet sizing",
    difficulty: 3,
    minutes: 25,
    answer: "A few hundred refrigerated vehicles, roughly 300 to 500, layered over static cold storage.",
    hints: ["Doses per day sets the flow; vehicles move doses between depots, not to arms."],
    moves: [
      { label: "Move 1", text: "Daily dose need: 8 crore people, two doses, over 180 days is about 9 lakh doses a day." },
      { label: "Move 2", text: "Distribution tiers: state depot to district to block; vehicles run the two upper legs." },
      { label: "Move 3", text: "Vehicle load: a small reefer van moves 50,000+ doses; district legs need volume less than capacity, so frequency drives count." },
      { label: "Move 4", text: "Count routes: 40 districts times 8 blocks each needing twice-weekly replenishment gives about 100 routes a day, plus state legs and buffers." },
      { label: "Check", text: "The binding constraint is usually cold storage at the block level, not trucks; note it." },
    ],
    pitfalls: [
      "Sizing trucks to carry doses to individual centres rather than between depots.",
      "Ignoring wastage, which inflates dose demand 10 to 15%.",
      "Forgetting the second dose doubles the campaign.",
    ],
  },
  {
    slug: "apparel-factory-shirts-daily",
    shape: "guesstimate",
    title: "How many shirts does a 1,000-worker garment factory produce daily?",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 18,
    askedAt: "Arvind",
    answer: "Roughly 8,000 to 12,000 shirts a day depending on style complexity.",
    hints: ["Work from minutes of sewing per shirt against available line minutes."],
    moves: [
      { label: "Move 1", text: "Standard time: a formal shirt takes about 40 to 50 machine-minutes across all operations." },
      { label: "Move 2", text: "Direct labour share: of 1,000 workers, about 700 sit on sewing lines; the rest cut, finish, check and pack." },
      { label: "Move 3", text: "Available minutes: 700 workers times 480 minutes at 80% efficiency gives about 270,000 productive minutes." },
      { label: "Move 4", text: "Divide: 270,000 over 45 minutes per shirt is about 6,000; better-balanced lines push toward 10,000." },
      { label: "Check", text: "Line balancing is the swing factor: an unbalanced line idles half its machines waiting for the bottleneck operation." },
    ],
    pitfalls: [
      "Counting all 1,000 workers as sewing operators.",
      "Using 100% efficiency on standard minutes.",
      "Quoting one number for both basic tees and complex shirts.",
    ],
  },
  {
    slug: "swiggy-instamart-dark-stores-city",
    shape: "guesstimate",
    title: "How many dark stores does a quick-commerce player need to cover Bengaluru?",
    type: "Network sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Swiggy",
    answer: "Roughly 60 to 80 stores to promise 10-minute delivery across the served area.",
    hints: ["The delivery-time promise fixes the radius; the radius fixes the store count."],
    moves: [
      { label: "Move 1", text: "Fix the radius: 10-minute delivery means about 6 minutes of riding, or a 2 to 2.5 km radius in city traffic." },
      { label: "Move 2", text: "Store coverage: a 2 km radius covers roughly 12 to 15 square km." },
      { label: "Move 3", text: "Serviceable area: Bengaluru's dense, order-generating area is perhaps 800 square km, not the full metro." },
      { label: "Move 4", text: "Divide with overlap: 800 over 13, plus 20% overlap for load sharing, gives about 70 stores." },
      { label: "Check", text: "Order density decides viability per store: a store below 800 orders a day rarely pays back." },
    ],
    pitfalls: [
      "Covering the entire municipal area including low-demand fringes.",
      "Using straight-line radius where traffic makes it road-time radius.",
      "Ignoring that stores also need minimum order density, not just coverage.",
    ],
  },
  {
    slug: "bus-depot-fleet-city-route",
    shape: "guesstimate",
    title: "Estimate the buses BEST needs for one high-frequency Mumbai route.",
    type: "Fleet sizing",
    difficulty: 1,
    minutes: 15,
    answer: "About 18 to 22 buses for a 20 km route at 5-minute peak headway.",
    hints: ["Round-trip time divided by headway gives buses in service."],
    moves: [
      { label: "Move 1", text: "Round trip: 20 km each way at 12 kmph city speed is about 3.5 hours including terminal layover." },
      { label: "Move 2", text: "Peak headway: a bus every 5 minutes." },
      { label: "Move 3", text: "Divide: 210 minutes over 5 gives 42 buses at peak... check direction: that count already covers both directions of the loop." },
      { label: "Move 4", text: "Correct and buffer: 210 over 5 is 42 slots but each bus occupies one slot across the loop; add 10% maintenance spare." },
      { label: "Check", text: "If 42 sounds high, revisit speed: raising average speed to 15 kmph cuts the fleet by a fifth. Fleet is hostage to traffic." },
    ],
    pitfalls: [
      "Forgetting layover time at each terminal.",
      "Using free-flow speeds for Mumbai traffic.",
      "Skipping the maintenance spare ratio.",
    ],
  },
  {
    slug: "print-newspaper-mumbai-logistics",
    shape: "guesstimate",
    title: "Estimate the delivery agents needed to distribute a newspaper across Mumbai.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 8,000 to 12,000 agents for a leading daily's Mumbai circulation.",
    hints: ["Circulation divided by copies one agent can deliver before offices open."],
    moves: [
      { label: "Move 1", text: "Circulation: a leading daily prints 8 to 10 lakh Mumbai copies." },
      { label: "Move 2", text: "Delivery window: papers land at depots by 4:30 am and must be delivered by 7:30, a 3-hour window." },
      { label: "Move 3", text: "Agent productivity: a cycling agent drops 80 to 120 copies in that window in a dense building cluster." },
      { label: "Move 4", text: "Divide: 9 lakh over 100 gives about 9,000 agents." },
      { label: "Check", text: "The same agent often carries 3 to 4 titles; the industry shares this workforce rather than each paper hiring its own." },
    ],
    pitfalls: [
      "Ignoring the hard morning deadline that caps copies per agent.",
      "Assuming exclusive agents per newspaper.",
      "Using suburban house density for tower-block delivery rates.",
    ],
  },
  {
    slug: "call-center-agents-telecom",
    shape: "guesstimate",
    title: "Size the call-centre team for a telco with 30 crore subscribers.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Airtel",
    answer: "Roughly 15,000 to 25,000 agents after IVR and app deflection.",
    hints: ["Calls per subscriber per month, minus self-serve deflection, divided by agent capacity."],
    moves: [
      { label: "Move 1", text: "Contact rate: subscribers call about once every 2 months, so 15 crore calls a month." },
      { label: "Move 2", text: "Deflection: IVR and the app resolve 60 to 70%, leaving about 5 crore agent calls." },
      { label: "Move 3", text: "Agent capacity: 6 minutes per call at 80% occupancy is about 60 calls a shift, 1,300 a month." },
      { label: "Move 4", text: "Divide: 5 crore over 1,300 gives about 38,000... sanity-check contact rate: prepaid users call far less; halving brings it toward 20,000." },
      { label: "Check", text: "The prepaid/postpaid mix is the single biggest swing; state your assumption explicitly." },
    ],
    pitfalls: [
      "Using postpaid contact rates for a mostly prepaid base.",
      "Forgetting IVR deflection entirely.",
      "Sizing to average volume with no shrinkage for breaks, training and attrition.",
    ],
  },
  {
    slug: "ola-cabs-airport-queue",
    shape: "guesstimate",
    title: "How many cabs should aggregators stage at Bengaluru airport at midnight?",
    type: "Queue sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 400 to 600 cabs across aggregators for the late-night arrival bank.",
    hints: ["Arriving passengers in the peak hour times cab-share, minus other modes."],
    moves: [
      { label: "Move 1", text: "Arrival bank: 15 to 20 flights land between 11 pm and 1 am, about 2,500 to 3,000 passengers an hour." },
      { label: "Move 2", text: "Mode share at midnight: buses thin out, so cabs take perhaps 50 to 60% of arrivals, in groups of 1.8 per cab." },
      { label: "Move 3", text: "Demand: 2,800 times 0.55 over 1.8 is about 850 cab trips an hour." },
      { label: "Move 4", text: "Staging: with a 45-minute round trip to the city unavailable, the queue must hold most of an hour's demand; stage 500+." },
      { label: "Check", text: "Surge pricing is the system admitting the queue was sized short; a stable queue means staging matched the bank." },
    ],
    pitfalls: [
      "Using daily-average arrivals instead of the midnight bank.",
      "Forgetting passengers share cabs.",
      "Assuming cabs can cycle back within the same hour.",
    ],
  },
  {
    slug: "steel-plant-rakes-daily",
    shape: "guesstimate",
    title: "How many railway rakes does a 10 MTPA steel plant need daily?",
    type: "Throughput estimation",
    difficulty: 3,
    minutes: 25,
    askedAt: "Tata Steel",
    answer: "Roughly 12 to 16 rakes a day inbound and outbound combined.",
    hints: ["Steel out is only part of it; iron ore and coal in weigh more than the steel out."],
    moves: [
      { label: "Move 1", text: "Outbound: 10 million tonnes a year is about 28,000 tonnes a day of finished steel." },
      { label: "Move 2", text: "Inbound: each tonne of steel needs roughly 1.6 tonnes of ore and 0.8 of coal, so about 65,000 tonnes a day of raw material." },
      { label: "Move 3", text: "Rake size: a loaded rake carries about 4,000 tonnes." },
      { label: "Move 4", text: "Divide: 28,000 out is 7 rakes; 65,000 in is 16 rakes, though captive mines and conveyors replace some." },
      { label: "Check", text: "If plant sidings can turn a rake in 6 hours, siding capacity, not rake count, becomes the real constraint." },
    ],
    pitfalls: [
      "Counting only finished steel and forgetting the heavier inbound flow.",
      "Ignoring captive sources that bypass rail.",
      "Treating rake availability as unconstrained.",
    ],
  },
  {
    slug: "cinema-concession-popcorn-day",
    shape: "guesstimate",
    title: "Estimate daily popcorn tubs sold by a 6-screen multiplex.",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 700 to 1,000 tubs on a decent day.",
    hints: ["Admissions times attach rate."],
    moves: [
      { label: "Move 1", text: "Admissions: 6 screens, 250 seats, 4 shows, 35% occupancy gives about 2,100 admissions." },
      { label: "Move 2", text: "Attach rate: roughly 35 to 45% of admissions buy popcorn, often shared between two." },
      { label: "Move 3", text: "Multiply: 2,100 times 0.4 gives about 850 tubs." },
      { label: "Move 4", text: "Adjust mix: weekends triple weekdays; a blockbuster weekend can double the attach rate's base." },
      { label: "Check", text: "Kitchen capacity rarely binds; the queue at the counter during the interval does." },
    ],
    pitfalls: [
      "Using peak occupancy for all shows.",
      "Counting per-person consumption when tubs are shared.",
      "Ignoring the weekday/weekend split.",
    ],
  },
  {
    slug: "warehouse-space-festive-inventory",
    shape: "guesstimate",
    title: "Estimate warehouse space an e-commerce firm adds for festive season.",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 30 to 50% over base capacity, several million square feet for a market leader.",
    hints: ["Festive daily volume versus normal, times days of inventory cover."],
    moves: [
      { label: "Move 1", text: "Volume jump: sale-period daily orders run 3x normal for about 6 weeks." },
      { label: "Move 2", text: "Inventory cover: firms pre-position 3 to 4 weeks of festive demand before the event." },
      { label: "Move 3", text: "Space math: 3x volume for a month against normal 1x cover needs roughly 2 to 3x normal inventory on hand at peak." },
      { label: "Move 4", text: "Temper with flow-through: cross-docks and seller-fulfilled stock mean added space is 30 to 50%, not 200%." },
      { label: "Check", text: "Short-term leases and temporary structures carry the peak; permanent space is sized to the base, not the spike." },
    ],
    pitfalls: [
      "Sizing permanent capacity to a six-week spike.",
      "Ignoring seller-owned inventory that never enters your warehouse.",
      "Confusing throughput capacity with storage capacity.",
    ],
  },
  {
    slug: "railway-linen-wash-capacity",
    shape: "guesstimate",
    title: "Estimate bedsheets Indian Railways washes daily for AC coaches.",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 8 to 10 lakh linen pieces a day across mechanised laundries.",
    hints: ["AC berths occupied per night times linen pieces per berth."],
    moves: [
      { label: "Move 1", text: "Count AC berths: about 1,200 long-distance trains with 5 AC coaches of 60 berths gives roughly 3.6 lakh berths a night." },
      { label: "Move 2", text: "Occupancy: AC classes run near 90%, so about 3.2 lakh sets used." },
      { label: "Move 3", text: "Pieces per set: 2 sheets plus a pillow cover, about 3 pieces, giving nearly 10 lakh pieces." },
      { label: "Move 4", text: "Convert to laundry capacity: a mechanised laundry does 10 to 20 tonnes a day; at 200 g a piece the network needs about 200 tonnes." },
      { label: "Check", text: "Blankets wash monthly, not daily; including them inflates the number falsely." },
    ],
    pitfalls: [
      "Counting non-AC coaches, which get no linen.",
      "Washing blankets daily in your math.",
      "Ignoring multi-night journeys that reuse the same set.",
    ],
  },
  {
    slug: "pds-ration-shop-throughput",
    shape: "guesstimate",
    title: "How many families can one ration shop serve in the first week of the month?",
    type: "Queue sizing",
    difficulty: 2,
    minutes: 18,
    answer: "About 1,200 to 1,800 families, which is why queues form when 2,500 are assigned.",
    hints: ["Service time per family times operating hours across 7 days."],
    moves: [
      { label: "Move 1", text: "Service time: weighing, biometric auth and payment take 4 to 6 minutes per family." },
      { label: "Move 2", text: "Daily window: 8 working hours gives about 90 to 100 families a day." },
      { label: "Move 3", text: "First week: 7 days times 95 is roughly 650; many shops add a second counter in rush week, doubling it." },
      { label: "Move 4", text: "Total: about 1,300 with a second counter, against 2,000 or more assigned cards." },
      { label: "Check", text: "Biometric failures add a retry loop for a tenth of customers; that alone eats an hour a day." },
    ],
    pitfalls: [
      "Ignoring biometric failure retries.",
      "Assuming demand spreads evenly across the month.",
      "Forgetting the shop also unloads and stacks stock in the same hours.",
    ],
  },
  {
    slug: "highway-truck-driver-count",
    shape: "guesstimate",
    title: "Estimate the long-haul truck drivers active in India.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 40 to 50 lakh drivers for long-haul, within a larger total driver pool.",
    hints: ["Start from the truck fleet, not the population."],
    moves: [
      { label: "Move 1", text: "Fleet: India has about 1.2 crore registered goods vehicles; long-haul heavy trucks are roughly 40 lakh." },
      { label: "Move 2", text: "Utilisation: perhaps 80% of trucks are on the road in a month." },
      { label: "Move 3", text: "Drivers per truck: long-haul runs 1.2 to 1.5 drivers per truck given rest rules and attrition." },
      { label: "Move 4", text: "Multiply: 32 lakh active trucks times 1.3 gives about 42 lakh drivers." },
      { label: "Check", text: "The industry reports chronic driver shortage; a ratio below 1.2 is the shortage showing up in your math." },
    ],
    pitfalls: [
      "Counting all goods vehicles including small city tempos as long-haul.",
      "Assuming one driver per truck exactly.",
      "Ignoring parked fleet share.",
    ],
  },
  {
    slug: "cement-bags-truck-loading",
    shape: "guesstimate",
    title: "How many trucks leave a 5 MTPA cement plant daily?",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 15,
    askedAt: "UltraTech",
    answer: "Roughly 500 to 700 trucks a day, after rail takes its share.",
    hints: ["Daily tonnage split rail versus road, divided by truck payload."],
    moves: [
      { label: "Move 1", text: "Daily output: 5 million tonnes over 350 days is about 14,000 tonnes." },
      { label: "Move 2", text: "Mode split: rail moves 30 to 40% for long distances, leaving about 9,000 tonnes by road." },
      { label: "Move 3", text: "Truck payload: 15 to 25 tonnes; take 18 average with bagged loads." },
      { label: "Move 4", text: "Divide: 9,000 over 18 gives about 500 trucks." },
      { label: "Check", text: "Loading bays turn a truck in 30 to 45 minutes; 500 trucks needs about 15 bays running two shifts, which matches real plants." },
    ],
    pitfalls: [
      "Sending all output by road.",
      "Using rated truck capacity when overloading rules changed real payloads.",
      "Forgetting the plant also receives inbound fuel and gypsum trucks.",
    ],
  },
  {
    slug: "quick-commerce-rider-batch",
    shape: "guesstimate",
    title: "How many riders does one dark store need through the day?",
    type: "Fleet sizing",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 25 to 40 riders across shifts for a 1,000-order store.",
    hints: ["Orders per hour at peak divided by deliveries per rider-hour."],
    moves: [
      { label: "Move 1", text: "Daily orders: a healthy dark store does about 1,000, with 15% of the day's orders in the dinner hour." },
      { label: "Move 2", text: "Peak load: about 150 orders in the peak hour." },
      { label: "Move 3", text: "Rider rate: a 10-minute-radius round trip means 3 to 4 deliveries an hour." },
      { label: "Move 4", text: "Divide: 150 over 3.5 gives about 43 riders at peak; off-peak needs a third of that." },
      { label: "Check", text: "Rider idle time off-peak is the cost problem; batching two orders per trip at peak cuts the fleet by a quarter." },
    ],
    pitfalls: [
      "Staffing the whole day at peak levels.",
      "Ignoring order batching.",
      "Forgetting pick-and-pack time happens in parallel, not on the rider's clock.",
    ],
  },
  {
    slug: "airline-turnaround-ground-crew",
    shape: "guesstimate",
    title: "Estimate ground staff IndiGo needs at a metro airport.",
    type: "Workforce sizing",
    difficulty: 3,
    minutes: 25,
    askedAt: "IndiGo",
    answer: "Roughly 2,500 to 4,000 people at a hub handling 200+ daily departures.",
    hints: ["Staff per turnaround times simultaneous turnarounds, plus fixed functions."],
    moves: [
      { label: "Move 1", text: "Departures: a metro hub runs 200 to 250 IndiGo departures a day." },
      { label: "Move 2", text: "Per-turnaround crew: loaders, ramp, cabin cleaning, ops and gate staff total 15 to 20 people touching each aircraft." },
      { label: "Move 3", text: "Concurrency: at peak, 12 to 15 aircraft turn simultaneously, needing about 250 people on the ramp at once." },
      { label: "Move 4", text: "Convert to headcount: three shifts, weekly offs and leave roughly multiply on-duty peak by 5, then add check-in, baggage and back office." },
      { label: "Check", text: "Multiply staff-per-flight by daily flights and you overcount badly; the same crew works many flights." },
    ],
    pitfalls: [
      "Multiplying per-flight crew by total flights.",
      "Ignoring shift and leave multipliers in the other direction.",
      "Forgetting outsourced functions may not sit on the airline's own rolls.",
    ],
  },
  {
    slug: "ev-charging-stations-highway",
    shape: "guesstimate",
    title: "How many fast chargers does the Mumbai-Pune expressway need by 2030?",
    type: "Network sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 150 to 250 fast-charging points across plazas on the corridor.",
    hints: ["EVs passing daily times share needing a charge, divided by sessions per charger."],
    moves: [
      { label: "Move 1", text: "Traffic: about 60,000 vehicles a day; assume 15% are EVs by 2030, so 9,000 EVs." },
      { label: "Move 2", text: "Charge need: the 95 km run is within most ranges; only 20 to 25% top up mid-way, about 2,000 sessions." },
      { label: "Move 3", text: "Charger throughput: a 30-minute fast session plus shuffle time gives one charger 15 to 18 sessions a day." },
      { label: "Move 4", text: "Divide: 2,000 over 16 gives about 125 chargers, sized up for weekend peaks toward 200." },
      { label: "Check", text: "Peak Saturday demand is twice the average day; queue tolerance, not average math, sets the final count." },
    ],
    pitfalls: [
      "Assuming every passing EV charges on this short corridor.",
      "Using average daily traffic when weekends drive sizing.",
      "Ignoring grid connection limits at plazas.",
    ],
  },
  {
    slug: "hotel-housekeeping-staff",
    shape: "guesstimate",
    title: "Size the housekeeping team for a 300-room business hotel.",
    type: "Workforce sizing",
    difficulty: 1,
    minutes: 15,
    askedAt: "Taj Hotels",
    answer: "About 45 to 60 housekeeping staff across shifts and functions.",
    hints: ["Rooms per attendant per shift is the industry anchor."],
    moves: [
      { label: "Move 1", text: "Occupied rooms: 300 rooms at 75% occupancy means about 225 rooms to service daily." },
      { label: "Move 2", text: "Attendant productivity: 12 to 14 rooms per 8-hour shift at business-hotel standards." },
      { label: "Move 3", text: "Divide: 225 over 13 gives about 17 attendants on the morning shift." },
      { label: "Move 4", text: "Add the rest: evening turndown, public areas, laundry, supervisors and weekly offs roughly triple the total roster." },
      { label: "Check", text: "Luxury standards halve rooms-per-attendant; grade of hotel moves this more than size does." },
    ],
    pitfalls: [
      "Rostering only for room cleaning and forgetting public areas and laundry.",
      "Ignoring weekly offs when converting shift need to headcount.",
      "Using budget-hotel productivity for a five-star product.",
    ],
  },
  {
    slug: "mandi-arrivals-onion-lasalgaon",
    shape: "guesstimate",
    title: "Estimate daily onion arrivals at Lasalgaon mandi in season.",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 1,500 to 2,500 tonnes a day in peak arrival season.",
    hints: ["Count tractor-trolleys through the gate, then convert to tonnes."],
    moves: [
      { label: "Move 1", text: "Vehicle flow: in season the yard receives 400 to 600 tractor-trolleys and small trucks a day." },
      { label: "Move 2", text: "Load size: a trolley carries 3 to 5 tonnes." },
      { label: "Move 3", text: "Multiply: 500 vehicles times 4 tonnes gives about 2,000 tonnes." },
      { label: "Move 4", text: "Check the other side: auctions, weighment and dispatch must clear the same tonnage or the yard chokes by noon." },
      { label: "Check", text: "Arrivals halve off-season; a single annual average misleads on infrastructure sizing." },
    ],
    pitfalls: [
      "Averaging peak and lean seasons into one number.",
      "Forgetting outbound dispatch capacity must match inbound.",
      "Using truck sizes for what are mostly tractor-trolleys.",
    ],
  },
  {
    slug: "security-guards-it-park",
    shape: "guesstimate",
    title: "How many security guards does a large IT park deploy?",
    type: "Workforce sizing",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 250 to 400 guards on the rolls for a 50,000-person park.",
    hints: ["Count posts, then multiply by the shift-and-off factor."],
    moves: [
      { label: "Move 1", text: "Count posts: gates, tower lobbies, basements, patrols and control rooms give a 10-tower park 60 to 80 posts." },
      { label: "Move 2", text: "Coverage: most posts run 24x7, needing 3 shifts." },
      { label: "Move 3", text: "Multiply: 70 posts times 3 shifts is 210 on duty per day." },
      { label: "Move 4", text: "Add reliever factor: weekly offs and leave need about 1.5 bodies per seat, giving 300 or more." },
      { label: "Check", text: "The reliever multiplier, not the post count, is where most sizing goes wrong." },
    ],
    pitfalls: [
      "Forgetting the reliever factor above raw shift math.",
      "Counting only gate guards and missing patrols and basements.",
      "Assuming day-only posts run round the clock.",
    ],
  },
  {
    slug: "courier-hub-sorting-capacity",
    shape: "guesstimate",
    title: "Estimate parcels a Delhivery mega-hub sorts nightly.",
    type: "Throughput estimation",
    difficulty: 2,
    minutes: 20,
    askedAt: "Delhivery",
    answer: "Roughly 10 to 15 lakh parcels in the overnight sort window.",
    hints: ["Sorter belt rate times hours, plus manual lines."],
    moves: [
      { label: "Move 1", text: "The window: line-haul trucks land between 8 pm and midnight; sorted loads must leave by 4 am, a 6 to 8 hour sort." },
      { label: "Move 2", text: "Automated rate: a cross-belt sorter does 20,000 to 30,000 parcels an hour." },
      { label: "Move 3", text: "Multiply: 25,000 times 7 hours gives about 1.75 lakh per sorter line; a mega-hub runs several lines plus manual bulk." },
      { label: "Move 4", text: "Sum: 4 to 6 effective lines lands between 8 and 12 lakh, more in festive season." },
      { label: "Check", text: "Truck dock capacity often binds before sorter capacity; parcels cannot be sorted faster than they are unloaded." },
    ],
    pitfalls: [
      "Running sorters 24 hours when the network gives them a 7-hour window.",
      "Ignoring unloading as the upstream bottleneck.",
      "Counting design speed rather than sustained speed with jams.",
    ],
  },
  {
    slug: "power-plant-coal-stock",
    shape: "guesstimate",
    title: "How much coal must a 2,000 MW plant hold for 15 days of cover?",
    type: "Inventory estimation",
    difficulty: 2,
    minutes: 18,
    askedAt: "NTPC",
    answer: "Roughly 3 to 4 lakh tonnes for 15 days at healthy load.",
    hints: ["MW to units to coal: about 0.6 to 0.7 kg per unit generated."],
    moves: [
      { label: "Move 1", text: "Daily generation: 2,000 MW at 80% load factor gives about 38 million units a day." },
      { label: "Move 2", text: "Coal intensity: Indian coal at moderate quality burns about 0.65 kg per unit." },
      { label: "Move 3", text: "Daily burn: 38 million times 0.65 kg is about 25,000 tonnes a day." },
      { label: "Move 4", text: "Multiply: 15 days of cover means roughly 3.7 lakh tonnes in the yard." },
      { label: "Check", text: "That is about 90 rakes of coal; yard space and rake unloading rate decide if the cover is achievable, not just the arithmetic." },
    ],
    pitfalls: [
      "Using imported-coal heat rates for domestic coal.",
      "Computing at 100% plant load factor.",
      "Ignoring monsoon, when both demand and supply chains shift.",
    ],
  },
  {
    slug: "metro-station-gates-peak",
    shape: "guesstimate",
    title: "How many AFC gates does a busy metro station need?",
    type: "Capacity estimation",
    difficulty: 1,
    minutes: 15,
    answer: "About 20 to 30 gates for a station moving 8,000 to 10,000 people in the peak hour direction.",
    hints: ["Gate throughput is 25 to 30 persons a minute; size to the peak 15 minutes."],
    moves: [
      { label: "Move 1", text: "Peak flow: a busy interchange sees 8,000 to 10,000 entries an hour in the morning peak." },
      { label: "Move 2", text: "Gate rate: a working gate passes 25 to 30 people a minute, about 1,600 an hour." },
      { label: "Move 3", text: "Divide: 9,000 over 1,600 gives 6 entry gates at even flow." },
      { label: "Move 4", text: "Size to surges: train arrivals dump 1,000 people at once at exits; peak-15-minute flow doubles the requirement, and exits need their own set." },
      { label: "Check", text: "Gates fail and reverse-flow arguments happen; real stations install twice the smooth-flow math." },
    ],
    pitfalls: [
      "Sizing entry and forgetting exit surges when trains arrive.",
      "Using hourly averages when 15-minute peaks bind.",
      "Assuming all gates work all the time.",
    ],
  },
  {
    slug: "restaurant-cloud-kitchen-orders",
    shape: "guesstimate",
    title: "How many orders can one cloud kitchen execute in the dinner peak?",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 15,
    askedAt: "Rebel Foods",
    answer: "Roughly 60 to 100 orders an hour across brands from one kitchen.",
    hints: ["Stations in parallel, not the kitchen as one queue."],
    moves: [
      { label: "Move 1", text: "Map stations: fryer, tandoor, wok, assembly; each is its own capacity lane." },
      { label: "Move 2", text: "Station rates: a wok station plates a dish every 4 to 5 minutes; 4 parallel stations give about 50 dishes an hour." },
      { label: "Move 3", text: "Orders versus dishes: an average order holds 2 dishes, so wok output alone is about 25 orders; the fryer and tandoor lanes lift the kitchen past 70." },
      { label: "Move 4", text: "Cap at packaging: one packer seals 60 to 80 orders an hour; two packers keep pace at peak." },
      { label: "Check", text: "Menu breadth kills throughput; the same kitchen does 100 orders of 20 SKUs or 50 orders of 80 SKUs." },
    ],
    pitfalls: [
      "Modelling the kitchen as one serial queue.",
      "Forgetting packaging as a station.",
      "Ignoring menu complexity's effect on station speed.",
    ],
  },
  {
    slug: "garbage-trucks-pune",
    shape: "guesstimate",
    title: "Estimate the garbage collection vehicles Pune city runs.",
    type: "Fleet sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 800 to 1,200 vehicles from small ghanta gadis to compactors.",
    hints: ["Waste tonnage divided by vehicle payload times trips."],
    moves: [
      { label: "Move 1", text: "Waste generated: 7 million people at 450 g per head gives about 3,200 tonnes a day." },
      { label: "Move 2", text: "Fleet mix: small door-to-door vehicles carry 1 to 2 tonnes; compactors carry 8 to 10 for the transfer leg." },
      { label: "Move 3", text: "Door-to-door: 2,500 tonnes via small vehicles doing 2 trips of 1.5 tonnes needs about 800 vehicles." },
      { label: "Move 4", text: "Transfer: moving 3,200 tonnes to processing in 9-tonne compactors doing 3 trips needs about 120 more." },
      { label: "Check", text: "Route time, not payload, limits small vehicles; narrow lanes mean a trip is 4 hours regardless of load." },
    ],
    pitfalls: [
      "Sizing everything with compactor payloads.",
      "Ignoring the two-tier collection and transfer structure.",
      "Using per-capita waste figures from richer cities.",
    ],
  },
  {
    slug: "bank-branch-tellers-rural",
    shape: "guesstimate",
    title: "How many counters does a district-town bank branch need on pension day?",
    type: "Queue sizing",
    difficulty: 1,
    minutes: 15,
    askedAt: "SBI",
    answer: "About 5 to 7 active counters against 2 to 3 on a normal day.",
    hints: ["Pension-day footfall versus minutes per transaction."],
    moves: [
      { label: "Move 1", text: "Footfall: pension day brings 500 to 700 customers versus 150 normally." },
      { label: "Move 2", text: "Transaction time: passbook update plus withdrawal takes 4 to 5 minutes for elderly customers." },
      { label: "Move 3", text: "Counter capacity: about 12 customers an hour, or 85 in a full day." },
      { label: "Move 4", text: "Divide: 600 over 85 gives 7 counters to clear the day without a spillover queue." },
      { label: "Check", text: "Customers arrive front-loaded before noon; clearing by 2 pm needs more counters than the full-day average suggests." },
    ],
    pitfalls: [
      "Using average-day staffing math for a known spike day.",
      "Ignoring front-loaded arrival patterns.",
      "Forgetting business correspondents now absorb part of this load.",
    ],
  },
  {
    slug: "movie-shoot-crew-bollywood",
    shape: "guesstimate",
    title: "Estimate the crew on a mid-budget Bollywood film set on a shoot day.",
    type: "Workforce sizing",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 150 to 250 people on a typical shoot day.",
    hints: ["Sum departments rather than guessing one number."],
    moves: [
      { label: "Move 1", text: "Camera, light and grip: about 40 to 60 people including riggers." },
      { label: "Move 2", text: "Production, direction and AD teams: 30 to 40 across departments." },
      { label: "Move 3", text: "Art, costume, makeup, sound and stunts: 40 to 60 depending on the scene." },
      { label: "Move 4", text: "Support: catering, transport, security and spot staff add another 40, plus junior artists per scene." },
      { label: "Check", text: "Crowd scenes double the count through junior artists; quote a base and a spike." },
    ],
    pitfalls: [
      "Quoting one flat number for both intimate and crowd scenes.",
      "Forgetting support functions like catering and transport.",
      "Confusing total credited crew with people present on a given day.",
    ],
  },
  {
    slug: "solar-park-cleaning-crew",
    shape: "guesstimate",
    title: "Size the panel-cleaning operation for a 2 GW solar park.",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 18,
    askedAt: "Adani Green",
    answer: "Roughly 300 to 500 workers, or far fewer with robotic cleaning.",
    hints: ["Panels divided by panels-per-worker-per-day, against a cleaning cycle."],
    moves: [
      { label: "Move 1", text: "Panel count: 2 GW at 550 W per panel is about 36 lakh panels." },
      { label: "Move 2", text: "Cycle: desert dust needs every panel cleaned every 15 to 20 days, so about 2 lakh panels a day." },
      { label: "Move 3", text: "Manual rate: a worker with a water wand cleans 400 to 600 panels a shift." },
      { label: "Move 4", text: "Divide: 2 lakh over 500 gives about 400 workers, halved where semi-automated brushes run." },
      { label: "Check", text: "Water scarcity is the real constraint in desert parks; robotic dry cleaning changes this math entirely." },
    ],
    pitfalls: [
      "Cleaning every panel daily in your assumptions.",
      "Ignoring water logistics as part of the operation.",
      "Using rooftop cleaning rates for utility-scale rows.",
    ],
  },
  {
    slug: "exam-centers-jee-national",
    shape: "guesstimate",
    title: "How many exam centres does JEE Main need across India?",
    type: "Network sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 500 to 700 computer-based centres per session.",
    hints: ["Candidates per session divided by centre capacity across shifts and days."],
    moves: [
      { label: "Move 1", text: "Candidates: about 10 lakh registrations per session." },
      { label: "Move 2", text: "Centre capacity: a computer lab centre seats 250 to 400 per shift." },
      { label: "Move 3", text: "Shifts and days: 2 shifts a day across 5 to 6 days gives one centre 10 to 12 slots, about 3,500 candidates." },
      { label: "Move 4", text: "Divide: 10 lakh over 3,500 gives about 300 centres; geographic spread forces near-double so no student travels overnight." },
      { label: "Check", text: "Coverage, not capacity, sets the final count: a district with 400 candidates still needs its own centre." },
    ],
    pitfalls: [
      "Optimising pure capacity and ignoring travel-distance coverage.",
      "Forgetting multi-day, multi-shift scheduling.",
      "Assuming all centres have equal computer counts.",
    ],
  },
  {
    slug: "milk-booth-mother-dairy-delhi",
    shape: "guesstimate",
    title: "Estimate litres one Mother Dairy booth sells daily.",
    type: "Throughput estimation",
    difficulty: 1,
    minutes: 12,
    answer: "Roughly 800 to 1,500 litres a day per busy booth.",
    hints: ["Morning queue length times purchase size, plus evening trickle."],
    moves: [
      { label: "Move 1", text: "Morning window: 2 peak hours serving a customer every 30 to 40 seconds gives about 200 customers." },
      { label: "Move 2", text: "Purchase size: households buy 1.5 to 2 litres of token milk." },
      { label: "Move 3", text: "Morning volume: 200 times 1.8 is about 360 litres; evening adds half of morning." },
      { label: "Move 4", text: "Add packaged sales through the day: pouches and curd roughly double token volume at good booths." },
      { label: "Check", text: "Booth economics run on volume; below 500 litres a day, a location is usually rationalised." },
    ],
    pitfalls: [
      "Ignoring the token-versus-pouch split.",
      "Extending peak-rate sales across all open hours.",
      "Using one booth's number for all booths regardless of catchment.",
    ],
  },
  {
    slug: "traffic-police-junctions-hyderabad",
    shape: "guesstimate",
    title: "How many traffic constables does Hyderabad deploy on a working morning?",
    type: "Workforce sizing",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 1,500 to 2,500 personnel across junctions and patrols.",
    hints: ["Manned junctions times staff per junction per shift."],
    moves: [
      { label: "Move 1", text: "Junctions: the city has about 600 signalised junctions; perhaps 400 get morning manning." },
      { label: "Move 2", text: "Staff per junction: 2 to 4 constables at big junctions, 1 at small ones; average 2.5." },
      { label: "Move 3", text: "Multiply: 400 times 2.5 gives about 1,000 at junctions." },
      { label: "Move 4", text: "Add patrols, challan teams, escort and reserve: roughly another 60 to 80% over junction strength." },
      { label: "Check", text: "Sanctioned strength always exceeds street presence; leave, courts and training absorb a quarter of the roster." },
    ],
    pitfalls: [
      "Manning every signalised junction in your math.",
      "Forgetting non-junction duties like escorts and challans.",
      "Equating sanctioned strength with deployed strength.",
    ],
  },
  {
    slug: "oxygen-cylinders-hospital-surge",
    shape: "guesstimate",
    title: "Estimate oxygen a 500-bed hospital consumes daily in a respiratory surge.",
    type: "Inventory estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 8 to 12 tonnes a day, versus 1 to 2 tonnes normally.",
    hints: ["Beds on oxygen times flow rate times minutes; ICU flows dwarf ward flows."],
    moves: [
      { label: "Move 1", text: "Split beds: in a surge, 300 ward beds on oxygen, 100 ICU, 100 off oxygen." },
      { label: "Move 2", text: "Flow rates: ward patients need 5 to 10 litres a minute; ICU with high-flow devices need 40 to 60." },
      { label: "Move 3", text: "Daily volume: wards give 300 times 7 LPM, ICU gives 100 times 50 LPM; together about 10,300 litres a minute." },
      { label: "Move 4", text: "Convert: about 15 million litres a day, roughly 20 tonnes gas weight; apply diversity since not all run max flow, landing near 10 tonnes." },
      { label: "Check", text: "A 20-kilolitre liquid oxygen tank holds about 23 tonnes; surge burn empties it in two days, which is why refill frequency became the crisis metric." },
    ],
    pitfalls: [
      "Using ward flow rates for high-flow ICU devices.",
      "Running every bed at maximum flow with no diversity factor.",
      "Confusing liquid litres with gas litres, which differ 800-fold.",
    ],
  },
  {
    slug: "festival-crowd-management-ujjain",
    shape: "guesstimate",
    title: "Estimate holding-area capacity needed for a big temple's festival day.",
    type: "Queue sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Holding for 30,000 to 50,000 people if darshan throughput is 10,000 an hour against 15,000 arrivals.",
    hints: ["Holding absorbs the gap between arrival rate and darshan throughput."],
    moves: [
      { label: "Move 1", text: "Arrival profile: 2 lakh visitors on the day, half arriving in the 6 peak morning hours, about 15,000 an hour." },
      { label: "Move 2", text: "Darshan throughput: lanes moving 2 to 3 people a second at the sanctum give about 10,000 an hour." },
      { label: "Move 3", text: "Gap: 5,000 people an hour accumulate; over a 6-hour peak the queue grows toward 30,000." },
      { label: "Move 4", text: "Size holding: 30,000 people at 2 to 3 square feet each needs about 8 acres of shaded, watered queueing." },
      { label: "Check", text: "Crowd density above 4 per square metre is the danger line; capacity planning here is a safety calculation, not comfort." },
    ],
    pitfalls: [
      "Sizing to average arrivals instead of the peak profile.",
      "Ignoring dwell time inside the sanctum as the true bottleneck.",
      "Packing density assumptions that cross safety limits.",
    ],
  },
  {
    slug: "tyre-plant-output-daily",
    shape: "guesstimate",
    title: "How many tyres does a large two-wheeler tyre plant make daily?",
    type: "Capacity estimation",
    difficulty: 2,
    minutes: 18,
    askedAt: "MRF",
    answer: "Roughly 40,000 to 60,000 two-wheeler tyres a day at a flagship plant.",
    hints: ["Work back from India's two-wheeler tyre demand and plant shares, or forward from curing presses."],
    moves: [
      { label: "Move 1", text: "Demand anchor: 2 crore new two-wheelers plus replacement on a 12 crore fleet needs roughly 12 to 15 crore tyres a year." },
      { label: "Move 2", text: "A leading maker holds about 25% share, produced across 8 to 10 plants." },
      { label: "Move 3", text: "Per-plant: 3.5 crore tyres over 10 plants is 35 lakh a year on average; a flagship does double." },
      { label: "Move 4", text: "Daily: 70 lakh over 350 days gives about 20,000; reconcile with press math, where 200 curing presses at 4 minutes a cure run near 50,000. Flagship plants sit between." },
      { label: "Check", text: "Curing time is the hard cycle: presses times cures per day caps output regardless of demand." },
    ],
    pitfalls: [
      "Mixing two-wheeler and truck tyre economics; they differ 20x in weight.",
      "Ignoring replacement demand, which exceeds OEM demand.",
      "Averaging away the flagship-versus-small-plant spread.",
    ],
  },
];
