import type { Question } from "./types";

// Operations cases. Bottlenecks, networks, quality and cost: the situations
// an operations interview walks you into and expects a structured way out of.
export const OPERATIONS_CASES: Question[] = [
  {
    slug: "qsr-delivery-time-worsening",
    shape: "case",
    title: "A burger chain's average delivery time rose from 28 to 39 minutes. Diagnose it.",
    type: "Bottleneck diagnosis",
    difficulty: 2,
    minutes: 25,
    askedAt: "McDonald's",
    answer: "Split the clock into kitchen time, wait-for-rider time and ride time before touching anything. Most such cases hide in wait-for-rider, and the recommendation is rider supply or dispatch logic, not a faster kitchen.",
    hints: ["Decompose the 39 minutes into stages before proposing any fix."],
    moves: [
      { label: "Move 1", text: "Break the journey: order accept, kitchen prep, waiting for pickup, riding, handover. Get minutes for each, then compare against the old 28-minute baseline stage by stage." },
      { label: "Move 2", text: "Locate the growth: if kitchen time held at 12 minutes and ride time at 11, the extra 11 minutes sits in rider wait, pointing at fleet supply or dispatch." },
      { label: "Move 3", text: "Ask what changed: order volume up, rider incentives cut, delivery radius widened, or a new stacking algorithm are the usual suspects." },
      { label: "Move 4", text: "Match fix to cause: radius creep needs zone redrawing; rider churn needs incentive repair; stacking needs a cap on orders per trip." },
      { label: "Close", text: "Recommend the one change aimed at the stage that grew, with the minutes you expect back and a two-week measurement plan." },
    ],
    pitfalls: [
      "Proposing kitchen automation before splitting the clock.",
      "Treating average delay as uniform when it may be a tail of terrible orders.",
      "Ignoring that a wider delivery radius mechanically adds minutes.",
    ],
  },
  {
    slug: "warehouse-pick-errors-rising",
    shape: "case",
    title: "Mispicks at a grocery warehouse doubled in two months. Find the cause and fix it.",
    type: "Quality diagnosis",
    difficulty: 2,
    minutes: 25,
    askedAt: "BigBasket",
    answer: "Segment errors by picker cohort, SKU type and zone. A doubling in two months usually tracks a specific change: new temp hires, a slotting reshuffle, or lookalike SKUs shelved adjacently. Fix the change, not the picker.",
    hints: ["Errors that double suddenly have a cause with a start date. Find what changed then."],
    moves: [
      { label: "Move 1", text: "Cut the data three ways: by picker tenure, by SKU category, by warehouse zone. See where the doubling concentrates." },
      { label: "Move 2", text: "Overlay the timeline: hiring batches, slotting changes, new SKUs, app updates. The error curve usually bends at one of these dates." },
      { label: "Move 3", text: "Test the leading suspect: if new hires err 4x, it is training and buddy-shift design; if one aisle errs, it is lookalike adjacency." },
      { label: "Move 4", text: "Fix structurally: separate lookalikes, add barcode-scan confirmation on error-prone SKUs, gate new hires behind an accuracy threshold." },
      { label: "Close", text: "Commit to an error-rate target and a weekly review until the rate returns to baseline." },
    ],
    pitfalls: [
      "Blaming workers before checking what management changed.",
      "Averaging error rates instead of segmenting them.",
      "Adding blanket double-checks that tax every pick to fix a concentrated problem.",
    ],
  },
  {
    slug: "factory-oee-improvement",
    shape: "case",
    title: "A packaging line runs at 55% OEE. The plant head wants 75%. Build the path.",
    type: "Process improvement",
    difficulty: 3,
    minutes: 30,
    answer: "Decompose OEE into availability, performance and quality; attack the largest loss first. Typical path: cut changeover time with SMED, then fix minor stops, then speed. The gap from 55 to 75 usually lives in changeovers and unlogged small stops.",
    hints: ["OEE is availability times performance times quality. Get the three numbers before anything."],
    moves: [
      { label: "Move 1", text: "Split 55% into its three factors. Say availability 70%, performance 85%, quality 92%: availability is the wound." },
      { label: "Move 2", text: "Break availability loss: planned changeovers, breakdowns, waiting for material, unlogged micro-stops. Time-study a week." },
      { label: "Move 3", text: "Attack in order of size: SMED a 90-minute changeover toward 30; preventive maintenance on the top 3 breakdown causes; fix the feed system behind micro-stops." },
      { label: "Move 4", text: "Recompute: availability 85% with same performance and quality lifts OEE to 66%; the last stretch comes from performance tuning." },
      { label: "Close", text: "Phase the roadmap over two quarters with an OEE bridge chart from 55 to 75 and owners per loss bucket." },
    ],
    pitfalls: [
      "Chasing machine speed while changeovers eat the calendar.",
      "Trusting logged downtime and missing micro-stops.",
      "Promising 75% without a loss-by-loss bridge.",
    ],
  },
  {
    slug: "dark-store-stockouts-evening",
    shape: "case",
    title: "A quick-commerce store shows 15% stockouts every evening. Fix availability.",
    type: "Inventory management",
    difficulty: 2,
    minutes: 25,
    askedAt: "Blinkit",
    answer: "Evening stockouts with morning replenishment mean the store gets one fill against a demand curve that peaks late. Either add an afternoon top-up run for fast movers or re-weight morning quantities toward evening-peaking SKUs.",
    hints: ["When the stockout has a time-of-day pattern, the answer is in replenishment timing, not total quantity."],
    moves: [
      { label: "Move 1", text: "Confirm the pattern: stockouts by hour and by SKU. Evening-only stockouts on milk, bread and snacks tell a timing story, not a forecasting one." },
      { label: "Move 2", text: "Map replenishment: one 6 am truck against demand that is 60% post-5pm means fast movers sell out by design." },
      { label: "Move 3", text: "Options: a 3 pm mini-replenishment for the top 100 SKUs; deeper morning fill accepting spoilage risk; or inter-store transfers from slow stores." },
      { label: "Move 4", text: "Cost it: the afternoon van costs a few thousand rupees a day against recovered sales of the entire stocked-out demand, usually a clear yes in high-volume stores." },
      { label: "Close", text: "Pilot the top-up run in the five worst stores for two weeks, tracking availability at 8 pm and spoilage." },
    ],
    pitfalls: [
      "Raising order quantities across the board and creating spoilage.",
      "Treating it as a forecasting problem when the daily total forecast is fine.",
      "Ignoring the cost asymmetry between a stockout and an extra van run.",
    ],
  },
  {
    slug: "port-congestion-vessel-wait",
    shape: "case",
    title: "Vessels wait 3 days to berth at a container port. Advise the operator.",
    type: "Capacity expansion",
    difficulty: 3,
    minutes: 30,
    answer: "Separate berth capacity from yard and gate capacity; ports often queue vessels because the yard is full, not the quay. Quick wins come from yard density and evacuation speed; a new berth is the slow, expensive answer and often the wrong first one.",
    hints: ["Ask whether the constraint is the berth, the yard, or the gate before recommending concrete."],
    moves: [
      { label: "Move 1", text: "Diagnose the chain: berth occupancy, crane rate, yard utilisation, rail and gate evacuation. A yard above 85% full slows everything upstream." },
      { label: "Move 2", text: "If yard-bound: containers dwell 6 days when they should dwell 3. Attack dwell with higher storage tariffs after day 3 and faster customs clearance." },
      { label: "Move 3", text: "If berth-bound: raise crane intensity per vessel and shift to larger call sizes rather than more calls." },
      { label: "Move 4", text: "Sequence: pricing and process changes deliver in months; a berth delivers in years. Do both if traffic growth persists." },
      { label: "Close", text: "Target vessel wait under 12 hours via dwell-time reduction first, and gate a berth investment on sustained occupancy above 70%." },
    ],
    pitfalls: [
      "Recommending berth construction for what is a yard-dwell problem.",
      "Ignoring pricing as an operations lever.",
      "Measuring berth occupancy alone and calling it the constraint.",
    ],
  },
  {
    slug: "airline-on-time-performance",
    shape: "case",
    title: "An airline's on-time performance fell from 85% to 68%. Recover it.",
    type: "Root cause",
    difficulty: 3,
    minutes: 30,
    askedAt: "IndiGo",
    answer: "Delays cascade: one late morning departure infects the aircraft's whole day. Find whether first-departure delays, turnaround slippage, or airspace congestion grew, then rebuild schedule buffers where the data says, not uniformly.",
    hints: ["Split delays into first-flight-of-day and knock-on. The cascade usually dominates."],
    moves: [
      { label: "Move 1", text: "Decompose: what share of delays are first departures versus knock-on from a late inbound aircraft? Cascades typically explain 60%+." },
      { label: "Move 2", text: "Trace first-delay causes: crew reporting, overnight maintenance handover, early-morning fog at hubs, or over-tight 25-minute turnarounds." },
      { label: "Move 3", text: "Check schedule design: if block times were cut to squeeze an extra rotation, the timetable itself manufactures lateness." },
      { label: "Move 4", text: "Fix asymmetrically: add buffer only to the 20 worst rotations, protect the first wave with spare aircraft at hubs, pre-position crew." },
      { label: "Close", text: "Commit to a morning-wave OTP target above 90%, since protecting the first departure protects the day." },
    ],
    pitfalls: [
      "Adding buffer uniformly and destroying fleet utilisation.",
      "Blaming weather for a structural schedule problem.",
      "Ignoring that one spare aircraft at a hub absorbs an entire cascade.",
    ],
  },
  {
    slug: "milk-procurement-spoilage",
    shape: "case",
    title: "A dairy loses 4% of collected milk to spoilage before processing. Cut it.",
    type: "Supply chain",
    difficulty: 2,
    minutes: 25,
    askedAt: "Amul",
    answer: "Map the cold chain from village society to plant; spoilage concentrates where milk waits warm. The usual fix is bulk milk coolers at collection points and tighter tanker routing, prioritised by each route's spoilage contribution.",
    hints: ["Spoilage is a time-and-temperature integral. Find where milk sits warm longest."],
    moves: [
      { label: "Move 1", text: "Trace the journey: farmer to society (30 min warm), society holding (2 to 4 hours, the danger zone), tanker leg, plant reception." },
      { label: "Move 2", text: "Quantify by stage: societies without bulk coolers explain most spoilage; long afternoon tanker routes explain the rest." },
      { label: "Move 3", text: "Prioritise: rank societies by volume times hours-warm. The top decile usually causes half the loss." },
      { label: "Move 4", text: "Invest: a bulk cooler at the top 50 societies, twice-daily tanker runs on the 10 worst routes, and reject-at-source testing to stop bad milk mixing into good tankers." },
      { label: "Close", text: "Target spoilage below 1.5% in two flush seasons, with cooler payback computed from saved milk alone." },
    ],
    pitfalls: [
      "Blaming farmers when the wait at the society is the killer.",
      "Averaging spoilage across routes instead of ranking them.",
      "Ignoring that one sour can contaminates a full tanker.",
    ],
  },
  {
    slug: "garment-factory-defect-rate",
    shape: "case",
    title: "A garment exporter's defect rate is costing a big buyer. Save the account.",
    type: "Quality management",
    difficulty: 2,
    minutes: 25,
    answer: "Move inspection upstream: end-of-line checking finds defects after value is added. Instal in-line checks at cutting and stitching, trace defects to operations, and fix the top three operations. Most factories find 60% of defects come from a handful of operations.",
    hints: ["Ask where defects are found versus where they are made."],
    moves: [
      { label: "Move 1", text: "Get the Pareto: defects by type and by operation. Stitching skips, measurement variance and stains usually top it." },
      { label: "Move 2", text: "Find detection lag: a defect made at operation 5 and caught at final inspection has ridden through 30 operations of wasted work." },
      { label: "Move 3", text: "Instal in-line gates: check after cutting and after the 3 highest-defect operations; empower line stops." },
      { label: "Move 4", text: "Fix root causes: machine maintenance for skips, pattern recalibration for measurement, handling discipline for stains." },
      { label: "Close", text: "Offer the buyer a corrective plan with weekly defect data sharing; transparency retains accounts that promises do not." },
    ],
    pitfalls: [
      "Adding more final inspectors instead of moving checks upstream.",
      "Treating all defect types with one generic fix.",
      "Hiding the data from the buyer while fixing quietly.",
    ],
  },
  {
    slug: "ecommerce-lastmile-cost-cut",
    shape: "case",
    title: "Last-mile cost per package is 1.4x industry benchmark. Close the gap.",
    type: "Cost reduction",
    difficulty: 2,
    minutes: 25,
    askedAt: "Ekart",
    answer: "Decompose cost per package into deliveries per rider-day and cost per rider-day. The gap usually sits in route density and failed deliveries, so the fixes are batching, address quality and first-attempt success, not rider pay cuts.",
    hints: ["Cost per package = rider cost per day over packages per day. Which term is off?"],
    moves: [
      { label: "Move 1", text: "Benchmark the two terms: if riders cost the same but deliver 60 packages versus the benchmark 85, it is a productivity problem." },
      { label: "Move 2", text: "Break productivity: stops per hour, packages per stop, failed-attempt rate, time at hub before departure." },
      { label: "Move 3", text: "Usual suspects: 15% failed deliveries from bad addresses and closed doors; low packages-per-stop from poor batching; late hub sorts eating route hours." },
      { label: "Move 4", text: "Fix: address verification at order, delivery-time preferences, tighter beat design, and earlier sort completion to lengthen the route day." },
      { label: "Close", text: "Path to benchmark: first-attempt success from 85 to 93% and stops per hour up 15% closes the 1.4x without touching wages." },
    ],
    pitfalls: [
      "Cutting rider pay and paying it back in attrition and failed deliveries.",
      "Ignoring failed attempts, each of which doubles that package's cost.",
      "Comparing against benchmarks with different terrain and order density.",
    ],
  },
  {
    slug: "hospital-discharge-delay",
    shape: "case",
    title: "Patients wait 6 hours between being declared fit and leaving. Free the beds.",
    type: "Process improvement",
    difficulty: 2,
    minutes: 25,
    askedAt: "Apollo Hospitals",
    answer: "Map the discharge chain: doctor sign-off, pharmacy return, billing, insurance clearance, bed cleaning. Insurance pre-authorisation and billing consolidation are the usual multi-hour steps; start discharge processing the evening before, not at morning rounds.",
    hints: ["Discharge is a process with parallel steps being run in series. Which steps can start earlier?"],
    moves: [
      { label: "Move 1", text: "Time-stamp the chain for 50 discharges: sign-off to pharmacy, to bill, to insurance, to physical exit. Find the fat steps." },
      { label: "Move 2", text: "Typical finding: insurance clearance takes 3 hours and starts only after the final bill, which waits for morning rounds." },
      { label: "Move 3", text: "Parallelise: flag probable discharges the night before, pre-fill insurance paperwork, run provisional billing, schedule pharmacy returns early." },
      { label: "Move 4", text: "Add a discharge lounge: move waiting patients out of beds so the bed turns even while paperwork finishes." },
      { label: "Check", text: "Each hour of discharge delay times beds times occupancy is admissions turned away; convert the 6 hours into revenue to size the prize." },
    ],
    pitfalls: [
      "Blaming insurers while your own billing starts late.",
      "Running sequential steps that have no true dependency.",
      "Measuring bed occupancy but not bed turn time.",
    ],
  },
  {
    slug: "fmcg-distributor-fill-rate",
    shape: "case",
    title: "Retailer fill rate for a snacks brand fell to 78%. Trace and repair it.",
    type: "Supply chain",
    difficulty: 2,
    minutes: 25,
    askedAt: "PepsiCo",
    answer: "Walk the chain backward: retailer order to distributor stock to depot to plant. Fill-rate drops usually concentrate in specific SKUs and specific distributors; the common causes are distributor working-capital limits and a long-tail SKU explosion, not plant capacity.",
    hints: ["Fill rate fails SKU by SKU and distributor by distributor. Never average it."],
    moves: [
      { label: "Move 1", text: "Cut fill rate by SKU and geography: is it 95% on the top 20 SKUs and 40% on the tail, or broad-based?" },
      { label: "Move 2", text: "Check distributor stock: thin inventories signal credit stress; distributors under-order to manage working capital, and the gap shows up as retailer stockouts." },
      { label: "Move 3", text: "Check upstream: depot stock-outs on the same SKUs point at production planning or a demand forecast that missed a regional spike." },
      { label: "Move 4", text: "Repair: rationalise the SKU tail, extend selective credit to stressed distributors, and re-plan production toward chronic short SKUs." },
      { label: "Close", text: "Set fill-rate recovery to 92% in eight weeks, tracked weekly by SKU-distributor cell rather than one national number." },
    ],
    pitfalls: [
      "Averaging fill rate into one national figure.",
      "Adding plant capacity when the constraint is distributor credit.",
      "Ignoring the cost of the SKU long tail on availability.",
    ],
  },
  {
    slug: "cash-van-route-optimisation",
    shape: "case",
    title: "A cash logistics firm wants 20% more ATM stops per van. Design the change.",
    type: "Route optimisation",
    difficulty: 2,
    minutes: 22,
    answer: "The stop count is dominated by dwell time, not driving. Cut per-stop protocol time with pre-staged cassettes and dynamic routing by machine cash-level telemetry, so vans skip machines that don't need visits.",
    hints: ["When dwell dominates driving, routing software alone moves little."],
    moves: [
      { label: "Move 1", text: "Split the shift: 8 stops of 35 minutes dwell plus 25 minutes driving. Dwell is 60% of the day." },
      { label: "Move 2", text: "Attack dwell: cassette-swap instead of note counting at the machine cuts a stop toward 15 minutes." },
      { label: "Move 3", text: "Attack the route list: telemetry-based scheduling drops machines above 40% cash, removing empty visits." },
      { label: "Move 4", text: "Re-sequence with a solver only after the two structural changes, adding the final 5 to 10%." },
      { label: "Close", text: "Cassette swap plus telemetry routing delivers the 20% with the same fleet; pilot on one city vault first." },
    ],
    pitfalls: [
      "Buying routing software while 35-minute dwells stand untouched.",
      "Ignoring RBI security protocol as a hard constraint on some steps.",
      "Assuming every ATM needs its scheduled visit.",
    ],
  },
  {
    slug: "restaurant-table-turn-weekend",
    shape: "case",
    title: "A full-service restaurant loses weekend walk-ins to 45-minute waits. Fix throughput.",
    type: "Capacity management",
    difficulty: 1,
    minutes: 20,
    answer: "Raise table turns rather than adding tables: tighten the order-to-kitchen and bill-drop steps, which stretch occupied-but-idle time. A turn of 75 minutes can usually shrink to 60 without rushing diners.",
    hints: ["A table's occupied time includes long stretches where nobody is eating. Find them."],
    moves: [
      { label: "Move 1", text: "Time a turn: seating to order 12 minutes, food arrival 20, dining 30, bill request to exit 13. Nearly half is not dining." },
      { label: "Move 2", text: "Compress the edges: QR ordering or faster captain coverage on seating; proactive bill drop with dessert; pre-set payment." },
      { label: "Move 3", text: "Fix the kitchen's Friday spike: pre-prep the weekend top 10 dishes so ticket times hold under load." },
      { label: "Move 4", text: "Manage the queue as revenue: waitlist SMS, bar seating for waiters, and a walk-in-friendly table mix of twos rather than sixes." },
      { label: "Close", text: "A 15-minute turn reduction on 20 tables over a 4-hour peak adds roughly one full extra seating." },
    ],
    pitfalls: [
      "Rushing diners visibly and paying for it in reviews.",
      "Adding tables in a space where the kitchen is the real cap.",
      "Ignoring table-size mix against party-size mix.",
    ],
  },
  {
    slug: "pharma-cold-chain-excursions",
    shape: "case",
    title: "2% of a vaccine distributor's shipments have temperature excursions. Eliminate them.",
    type: "Supply chain risk",
    difficulty: 3,
    minutes: 28,
    answer: "Instrument first: put loggers on every shipment and locate excursions by lane and leg. They typically cluster at handoffs, especially airport tarmac dwell and last-mile transfer. Fix the top lanes with better packouts and handoff SLAs before buying reefer capacity.",
    hints: ["Excursions cluster at handoffs. Which leg of which lane?"],
    moves: [
      { label: "Move 1", text: "Data first: logger every shipment, map excursions to lane, leg and time of day." },
      { label: "Move 2", text: "Typical cluster: tarmac dwell in summer afternoons and the unrefrigerated last hop to small towns." },
      { label: "Move 3", text: "Engineering fixes: upgraded packouts rated for 96 hours on hot lanes, afternoon-flight avoidance, and PCM bricks for the last mile." },
      { label: "Move 4", text: "Process fixes: handoff SLAs with airlines, excursion alerts in transit rather than discovery at delivery." },
      { label: "Close", text: "Target excursions below 0.3% in two quarters; every avoided excursion saves the product value plus the replacement logistics." },
    ],
    pitfalls: [
      "Buying reefer trucks when the excursions happen on tarmac.",
      "Treating all lanes as equally risky.",
      "Discovering excursions at delivery instead of alerting mid-transit.",
    ],
  },
  {
    slug: "two-wheeler-plant-shift-addition",
    shape: "case",
    title: "Demand exceeds a scooter plant's two-shift output by 30%. Add a third shift or expand?",
    type: "Capacity decision",
    difficulty: 3,
    minutes: 30,
    askedAt: "TVS",
    answer: "A third shift adds capacity fastest and cheapest if maintenance windows and supervision hold, but it caps at about 25 to 30% more and squeezes maintenance. Take the third shift now as the bridge, and trigger a line expansion only if demand holds two more quarters.",
    hints: ["Compare speed, cost and reversibility of each option, not just capacity added."],
    moves: [
      { label: "Move 1", text: "Size the options: third shift adds about 30% in weeks; line debottlenecking adds 10 to 15% in a quarter; a new line adds 50% in 18 months." },
      { label: "Move 2", text: "Cost them: the shift is almost pure variable cost; the line is heavy capex needing sustained demand." },
      { label: "Move 3", text: "Check the risks: night-shift quality dip, maintenance compression to weekends, supervisor thinness. Mitigate with staggered maintenance and senior anchors at night." },
      { label: "Move 4", text: "Test demand durability: is the 30% a festive spike, a competitor's stumble, or structural? The answer gates the capex, not the shift." },
      { label: "Close", text: "Start the third shift within a month, hold capex until two more quarters confirm demand, and pre-order long-lead equipment as a hedge." },
    ],
    pitfalls: [
      "Committing capex to a demand spike.",
      "Ignoring maintenance windows when the calendar fills with shifts.",
      "Treating shift three as free of quality and supervision costs.",
    ],
  },
  {
    slug: "grocery-chain-shrinkage",
    shape: "case",
    title: "A supermarket chain's shrinkage hit 2.8% of sales. Bring it under 1.5%.",
    type: "Loss prevention",
    difficulty: 2,
    minutes: 25,
    askedAt: "DMart",
    answer: "Split shrinkage into theft, damage, expiry and paperwork error; each has a different owner and fix. Fresh-category expiry and receiving-dock paperwork usually beat customer theft; attack with markdown discipline, receiving audits and camera coverage at the top 10 loss stores.",
    hints: ["Shrinkage is four different problems wearing one number."],
    moves: [
      { label: "Move 1", text: "Decompose by category and cause: fresh expiry, damage in handling, theft internal and external, vendor short-shipping booked as received." },
      { label: "Move 2", text: "Rank stores: shrinkage concentrates; the worst decile of stores usually runs 3x the best." },
      { label: "Move 3", text: "Category fixes: dynamic markdowns before expiry, better cold-chain handling for damage, blind receiving counts against invoices." },
      { label: "Move 4", text: "People fixes: POS exception reports for sweethearting, high-value SKU placement, and store-level shrinkage ownership in manager scorecards." },
      { label: "Close", text: "The path to 1.5% is roughly half process and half accountability; set store-wise targets, not one chain number." },
    ],
    pitfalls: [
      "Assuming shrinkage means customer theft.",
      "Chain-average targets that let the worst stores hide.",
      "Anti-theft spending that exceeds the theft it prevents.",
    ],
  },
  {
    slug: "construction-project-delay-recovery",
    shape: "case",
    title: "A metro construction package is 8 months late at 60% completion. Recover the schedule.",
    type: "Project recovery",
    difficulty: 3,
    minutes: 30,
    askedAt: "L&T",
    answer: "Re-baseline honestly, find the critical path, and crash only activities on it. Late projects usually suffer from land or utility handover gaps and slow decision loops more than site productivity; recover with parallel working fronts and a decision SLA with the client.",
    hints: ["Only the critical path matters for the date. Where does it run now?"],
    moves: [
      { label: "Move 1", text: "Re-baseline: strip optimism, rebuild the network, and identify today's true critical path, which has usually moved." },
      { label: "Move 2", text: "Classify the 8 months: land handover delays, design changes, contractor mobilisation, monsoon. Each has a different recovery lever." },
      { label: "Move 3", text: "Crash selectively: extra shifts and formwork only on critical activities; opening additional work fronts where access exists buys more than overtime everywhere." },
      { label: "Move 4", text: "Fix the decision loop: a weekly client-contractor board with 7-day decision SLAs on drawings and change orders often recovers more than site measures." },
      { label: "Close", text: "Present a recovered date with confidence bands, the crash cost, and the client decisions on which it is conditional." },
    ],
    pitfalls: [
      "Crashing non-critical activities and burning money for zero days.",
      "Hiding the true completion date to buy time.",
      "Ignoring client-side decision delays as a schedule input.",
    ],
  },
  {
    slug: "telecom-tower-fuel-theft",
    shape: "case",
    title: "Diesel consumption at rural telecom towers runs 25% above modelled need. Investigate.",
    type: "Cost diagnosis",
    difficulty: 2,
    minutes: 22,
    askedAt: "Indus Towers",
    answer: "The gap is some mix of theft, generator inefficiency and grid outages worse than modelled. Meter reality first: IoT fuel sensors and grid-outage logs on a sample of towers separate the three, and the fixes differ completely.",
    hints: ["Three explanations, three different fixes. Instrument before accusing."],
    moves: [
      { label: "Move 1", text: "Model the gap per tower: expected diesel from outage hours times generator burn rate versus actual fills." },
      { label: "Move 2", text: "Instrument a sample: fuel-level telemetry catches sudden drops (theft) versus steady over-burn (ageing generators) versus long grid outages (bad model)." },
      { label: "Move 3", text: "Act by cause: locked and sensored tanks plus fill-verification for theft; generator overhaul or right-sizing for burn; solar-battery hybrids where the grid is the problem." },
      { label: "Move 4", text: "Prioritise: rank towers by absolute excess litres; the top 10% of towers usually explain half the leak." },
      { label: "Close", text: "Telemetry pays for itself in months; make it standard fit and tie vendor fuel contracts to metered consumption." },
    ],
    pitfalls: [
      "Assuming the whole gap is theft.",
      "Fleet-wide fixes when excess concentrates in a tower decile.",
      "Modelling grid outages from old data.",
    ],
  },
  {
    slug: "festive-surge-fulfilment-plan",
    shape: "case",
    title: "Design the fulfilment plan for a 4x order surge in Diwali week.",
    type: "Surge planning",
    difficulty: 3,
    minutes: 30,
    askedAt: "Amazon",
    answer: "Pre-position inventory forward, pre-hire and train surge labour a month early, lock carrier capacity contracts, and defend the promise by widening delivery windows on low-priority pin codes rather than failing everywhere equally.",
    hints: ["You cannot scale everything 4x; decide what degrades gracefully."],
    moves: [
      { label: "Move 1", text: "Forecast by node: the 4x is not uniform; metros spike harder in electronics, tier-2 in fashion. Push inventory to forward nodes before the event." },
      { label: "Move 2", text: "Labour: temp hires at half productivity mean hiring 2.5x the throughput gap, onboarded two weeks early on simplified single-role tasks." },
      { label: "Move 3", text: "Transport: contract line-haul and last-mile surge capacity in advance; spot-market trucks in Diwali week cost double." },
      { label: "Move 4", text: "Protect the promise selectively: hold next-day only for top pin codes and prime customers, stretch others to 3 or 4 days upfront rather than breaking promises." },
      { label: "Close", text: "War-room the week with hourly node health metrics and pre-agreed degradation triggers instead of improvised firefighting." },
    ],
    pitfalls: [
      "Planning labour at trained-worker productivity.",
      "Promising normal delivery speed everywhere and failing publicly.",
      "Leaving carrier capacity to the spot market.",
    ],
  },
  {
    slug: "bus-fleet-breakdown-rate",
    shape: "case",
    title: "A state bus corporation's breakdowns per 10,000 km doubled in three years. Reverse it.",
    type: "Maintenance strategy",
    difficulty: 2,
    minutes: 25,
    answer: "An ageing fleet run on breakdown-maintenance is the usual story. Shift the top failure systems to preventive schedules, fix spares availability, and retire the worst decile of buses whose repair cost exceeds replacement economics.",
    hints: ["Ask what the fleet age curve and the maintenance regime look like before anything else."],
    moves: [
      { label: "Move 1", text: "Profile failures: by system (engine, gearbox, electrical, tyres), by bus age, by depot. Age and a few systems usually dominate." },
      { label: "Move 2", text: "Audit the regime: if buses see a mechanic only when they fail, breakdowns are the maintenance schedule." },
      { label: "Move 3", text: "Preventive shift: kilometre-based service triggers for the top 4 failure systems; depot-level spares kits for the 20 highest-use parts." },
      { label: "Move 4", text: "Fleet action: the oldest 10% of buses often cause 30% of breakdowns; ground or cannibalise them for spares." },
      { label: "Close", text: "Track breakdowns per 10,000 km monthly by depot, and publish it; depot competition moves this metric faster than circulars." },
    ],
    pitfalls: [
      "Buying new buses while the maintenance regime stays reactive.",
      "Central spares warehouses that leave depots waiting days.",
      "Averaging breakdown rates across a bimodal fleet age profile.",
    ],
  },
  {
    slug: "steel-inventory-working-capital",
    shape: "case",
    title: "A steel processor holds 70 days of inventory; peers hold 45. Release the cash.",
    type: "Inventory management",
    difficulty: 2,
    minutes: 25,
    answer: "Split inventory into raw, WIP and finished; the excess usually sits in raw material bought on price speculation and finished goods made to a stale forecast. Move to consumption-linked raw procurement and order-backed finishing, category by category.",
    hints: ["The 25 extra days are not spread evenly. Which stage and which grades?"],
    moves: [
      { label: "Move 1", text: "Cut the 70 days by stage: say 35 raw, 10 WIP, 25 finished against peer 20/10/15." },
      { label: "Move 2", text: "Raw excess: bulk buys on price dips. Impose a hedging policy separate from physical stock so speculation happens in futures, not the yard." },
      { label: "Move 3", text: "Finished excess: fast grades sold in weeks, slow grades sitting quarters. Make slow grades to order only, accept longer quoted lead times." },
      { label: "Move 4", text: "Systemise: reorder points from actual consumption, monthly S&OP with sales, and ageing alerts on anything past 60 days." },
      { label: "Close", text: "25 days released on the inventory value, at working-capital interest rates, is the annual saving; state it in crores to land the point." },
    ],
    pitfalls: [
      "Cutting safety stock on fast movers and creating stockouts to fix a slow-mover problem.",
      "Letting procurement speculate with physical inventory.",
      "One inventory target across grades with 10x different velocities.",
    ],
  },
  {
    slug: "railway-freight-share-loss",
    shape: "case",
    title: "Railways keeps losing freight share to road. Advise where rail can win it back.",
    type: "Network strategy",
    difficulty: 3,
    minutes: 30,
    answer: "Rail cannot beat road on door-to-door flexibility, so compete where rail's physics win: long-haul bulk and containerised lanes above 700 km, time-tabled freight trains, and terminal investments that cut the first and last mile pain that pushes shippers to trucks.",
    hints: ["Ask why shippers leave: it is rarely the line-haul price."],
    moves: [
      { label: "Move 1", text: "Segment freight: bulk (coal, cement, ore) is loyal; the loss is in piecemeal, time-sensitive and containerisable cargo." },
      { label: "Move 2", text: "Diagnose the leak: unpredictable transit times, rake availability, and costly terminal handling beat price as reasons shippers quote." },
      { label: "Move 3", text: "Compete selectively: scheduled freight services with guaranteed transit on 20 dense lanes, smaller train-load offers, and private terminal partnerships." },
      { label: "Move 4", text: "Price with the service: shippers pay rail-plus for truck-like reliability; discounting an unreliable service wins nothing." },
      { label: "Close", text: "Pick 10 lanes over 700 km with bulk-adjacent cargo, run time-tabled trains for a year, and measure share shift lane by lane." },
    ],
    pitfalls: [
      "Fighting road on short-haul flexibility where trucks structurally win.",
      "Assuming price is the reason for share loss.",
      "Network-wide promises instead of lane-level proof.",
    ],
  },
  {
    slug: "atm-network-uptime",
    shape: "case",
    title: "A bank's ATM uptime is 91% against a 97% regulatory expectation. Close the gap.",
    type: "Service operations",
    difficulty: 2,
    minutes: 22,
    answer: "Decompose downtime: cash-outs, technical faults, power and connectivity. Cash-out hours usually dominate and are a forecasting and routing failure; technical faults concentrate in old machines. Fix cash forecasting first, then targeted machine replacement.",
    hints: ["Downtime is not one disease. Split the 9% by cause before prescribing."],
    moves: [
      { label: "Move 1", text: "Attribute the 9%: say 4% cash-out, 3% technical, 1% power, 1% network. Each has a different owner." },
      { label: "Move 2", text: "Cash-outs: replenishment runs on fixed schedules while withdrawals spike at salary week; move to consumption-forecast routing with the cash agency." },
      { label: "Move 3", text: "Technical: fault rates by machine age and model; the oldest quintile usually drives half the faults. Replace or de-commission." },
      { label: "Move 4", text: "Power and network: batteries and dual-SIM routers at chronic sites, identified from incident logs." },
      { label: "Close", text: "Contract the cash agency on uptime, not trips; incentives aligned to the outcome finish what analysis starts." },
    ],
    pitfalls: [
      "Buying UPSs everywhere when power is 1 point of the 9.",
      "Fixed replenishment schedules against spiky withdrawal patterns.",
      "Vendor contracts that pay for visits rather than uptime.",
    ],
  },
  {
    slug: "kitchen-equipment-make-vs-buy",
    shape: "case",
    title: "A cloud kitchen chain debates making its own sauces versus buying. Decide.",
    type: "Make versus buy",
    difficulty: 2,
    minutes: 22,
    answer: "Buy the commodity sauces and make only the signature ones that define taste and are supply-risky. The decision hinges on volume threshold, taste differentiation and vendor dependence, not unit cost alone.",
    hints: ["Split the SKUs: commodity versus signature. The answer differs by half."],
    moves: [
      { label: "Move 1", text: "Cost honestly: in-house unit cost must carry equipment, quality staff, compliance and wastage, not just ingredients." },
      { label: "Move 2", text: "Volume test: a central sauce unit breaks even only above a threshold; below it, contract manufacturing wins on cost." },
      { label: "Move 3", text: "Strategic test: signature sauces carry the brand's taste and leak recipes through vendors; commodity ketchup does not." },
      { label: "Move 4", text: "Risk test: single-vendor dependence on a taste-critical input is a hidden cost; dual-source or make." },
      { label: "Close", text: "Make the 5 signature sauces centrally once volume crosses threshold, buy the rest on annual contracts with two vendors each." },
    ],
    pitfalls: [
      "Comparing vendor price with an in-house cost that omits overheads.",
      "One blanket decision across taste-critical and commodity SKUs.",
      "Ignoring recipe confidentiality as a real economic factor.",
    ],
  },
  {
    slug: "warehouse-automation-roi",
    shape: "case",
    title: "Should a 3PL install a goods-to-person robotics system in its Bhiwandi warehouse?",
    type: "Automation decision",
    difficulty: 3,
    minutes: 30,
    answer: "Automate if the maths clears at realistic Indian labour costs, which is a higher bar than in the West: the payback usually needs throughput density, multi-year client contracts and land constraints, not just wage savings. Often the right answer is partial automation of the fastest zone.",
    hints: ["Cheap labour raises the automation bar. What else must justify it?"],
    moves: [
      { label: "Move 1", text: "Baseline: current cost per pick with labour, error rates, and the peak-season hiring struggle." },
      { label: "Move 2", text: "Model automation: capex, maintenance, integration, plus throughput gain and error reduction. At Indian wages, wage savings alone rarely clear 5-year payback." },
      { label: "Move 3", text: "Add the non-wage cases: land constraint (robots densify storage 3x), labour volatility at peak, night-shift throughput, client SLA premiums." },
      { label: "Move 4", text: "De-risk: automate the fast-moving 20% of SKUs in one zone; keep the long tail manual. Verify client contract tenure covers payback." },
      { label: "Close", text: "Recommend partial goods-to-person for the fast zone if contracted volumes cover 70% of payback; full automation only with land constraint or 7-year contracts." },
    ],
    pitfalls: [
      "Copying Western payback math into Indian wage reality.",
      "All-or-nothing framing when zonal automation exists.",
      "Ignoring client contract tenure against a 5-year payback.",
    ],
  },
  {
    slug: "vendor-consolidation-auto-parts",
    shape: "case",
    title: "An auto maker has 600 suppliers; quality and logistics suffer. Rationalise the base.",
    type: "Vendor management",
    difficulty: 3,
    minutes: 28,
    askedAt: "Maruti Suzuki",
    answer: "Segment suppliers by criticality and performance, consolidate the commodity tail toward the best performers, but keep dual sourcing on single-point-of-failure parts. The goal is fewer, deeper relationships without concentration risk.",
    hints: ["Rationalisation is not minimisation; safety-critical parts need redundancy."],
    moves: [
      { label: "Move 1", text: "Segment the 600: strategic (engine, electronics), bottleneck (single-source castings), leverage (commodity fasteners), routine. Different rules per quadrant." },
      { label: "Move 2", text: "Score performance: PPM defects, delivery adherence, cost trajectory, financial health. The bottom quartile of commodity vendors is the exit list." },
      { label: "Move 3", text: "Consolidate leverage items: moving 200 fastener-type vendors to 60 lifts volumes per vendor, buying price and priority." },
      { label: "Move 4", text: "Protect against concentration: dual-source anything that stops the line, cap any vendor at a share ceiling, and audit financial fragility annually." },
      { label: "Close", text: "Target 350 vendors in 24 months with a published exit path, so departing vendors wind down without supply shocks." },
    ],
    pitfalls: [
      "Cutting vendor count on cost alone and creating single points of failure.",
      "Exiting vendors abruptly and triggering end-of-relationship quality collapse.",
      "Treating strategic and commodity suppliers with the same playbook.",
    ],
  },
  {
    slug: "solar-epc-material-planning",
    shape: "case",
    title: "A solar EPC keeps idling crews waiting for modules. Fix material-site synchronisation.",
    type: "Scheduling",
    difficulty: 2,
    minutes: 22,
    answer: "The mismatch is between long, uncertain module lead times and rigid crew schedules. Buffer at the project level with a rolling 3-week material-confirmed lookahead: crews mobilise only against material physically in the regional yard, not against promised ship dates.",
    hints: ["Which is cheaper to buffer: crew time or material inventory?"],
    moves: [
      { label: "Move 1", text: "Quantify the pain: crew-days idled per project and the daily cost of an idle installation crew versus holding modules two extra weeks." },
      { label: "Move 2", text: "Trace variability: module deliveries slip on imports, port clearance and trucking; crew schedules assume none of it." },
      { label: "Move 3", text: "Re-sequence the trigger: mobilise crews on material-in-yard, not material-promised. Hold a regional buffer stock sized to two weeks of installation." },
      { label: "Move 4", text: "Attack lead-time variance: customs broker SLAs, pre-cleared documentation, and penalty clauses on supplier delivery windows." },
      { label: "Close", text: "Idle crew cost usually exceeds buffer inventory carrying cost several times over; state the trade and change the mobilisation rule." },
    ],
    pitfalls: [
      "Scheduling crews against promise dates with known 30% slippage.",
      "Refusing buffer stock while paying for idle crews.",
      "Fixing one project when the rule causes it fleet-wide.",
    ],
  },
  {
    slug: "airport-security-queue-redesign",
    shape: "case",
    title: "Morning security queues at a metro airport cross 25 minutes. Redesign the flow.",
    type: "Queue management",
    difficulty: 2,
    minutes: 25,
    answer: "Throughput per lane is capped by the divest-and-scan cycle, so add pre-lane preparation, parallel divest stations and a dedicated light-bag lane. Matching lane opening to the flight bank profile matters more than adding machines.",
    hints: ["Watch where the seconds go at one lane before adding lanes."],
    moves: [
      { label: "Move 1", text: "Time the cycle: divest 40 seconds, scan 15, walkthrough 8, reclaim 30. The machine is idle while people fumble with trays." },
      { label: "Move 2", text: "Decouple stages: 3 parallel divest positions per scanner keep the belt fed continuously, lifting lane throughput 40%." },
      { label: "Move 3", text: "Segment passengers: a cabin-baggage-only lane runs nearly twice the rate; families and heavy-baggage flows get their own lane." },
      { label: "Move 4", text: "Roster to the banks: the 5 to 8 am departure bank needs all lanes; midday needs half. Staffing to the average manufactures the morning queue." },
      { label: "Close", text: "Target a 10-minute P90 wait using existing machines; buy new lanes only after cycle decoupling is exhausted." },
    ],
    pitfalls: [
      "Adding scanners while divest time caps the existing ones.",
      "Staffing lanes flat across a spiky departure profile.",
      "Measuring average wait when the P90 drives missed flights and complaints.",
    ],
  },
  {
    slug: "tractor-dealer-service-capacity",
    shape: "case",
    title: "A tractor dealer loses service business in harvest season. Capture it.",
    type: "Service operations",
    difficulty: 1,
    minutes: 20,
    askedAt: "Mahindra",
    answer: "Harvest is when tractors work hardest and can least afford workshop visits, so take service to the field: mobile service vans, pre-harvest maintenance camps, and stocked fast-moving parts. The workshop model loses precisely when demand peaks.",
    hints: ["In harvest, the tractor cannot come to you. Invert the model."],
    moves: [
      { label: "Move 1", text: "Understand the loss: farmers defer service or use village mechanics because a workshop day costs a harvest day." },
      { label: "Move 2", text: "Pre-empt: run pre-harvest check camps in villages a month before season, converting breakdowns into scheduled work." },
      { label: "Move 3", text: "Go mobile: two vans with a mechanic, common parts and oils handle 6 to 8 field jobs a day at premium pricing farmers gladly pay in season." },
      { label: "Move 4", text: "Stock for season: the 30 parts that fail in harvest need depth; a stockout sends the customer to the local mechanic for good." },
      { label: "Close", text: "Measure captured service revenue per season and van utilisation; two vans typically pay back within one harvest." },
    ],
    pitfalls: [
      "Discounting workshop visits when the barrier is time, not price.",
      "Vans without the right parts, which burn trust faster than no van.",
      "Ignoring the village mechanic as the real competitor.",
    ],
  },
  {
    slug: "ecom-packaging-cost-sustainability",
    shape: "case",
    title: "Cut packaging cost 20% while meeting a plastic-reduction commitment.",
    type: "Cost reduction",
    difficulty: 2,
    minutes: 22,
    answer: "Right-size before you re-material: box-size optimisation and void-fill elimination cut both cost and material, funding the costlier paper-based switches. The two goals conflict only if you leave right-sizing on the table.",
    hints: ["Shipping air is the biggest cost; attack size before material."],
    moves: [
      { label: "Move 1", text: "Audit the flow: cube utilisation per shipment; most e-commerce boxes ship 40% air with paid void fill." },
      { label: "Move 2", text: "Right-size: add 4 box sizes and algorithmic carton selection; smaller boxes cut corrugate, void fill and freight simultaneously." },
      { label: "Move 3", text: "Re-material where it pays: paper tape for plastic tape and mailers for boxes on soft goods, funded by the right-sizing savings." },
      { label: "Move 4", text: "Test protectiveness: damage rates must hold; a 1% damage rise erases packaging savings." },
      { label: "Close", text: "Sequence: right-size first (12 to 15% cost out), then material swaps (plastic out, cost neutral), landing the 20% with the commitment intact." },
    ],
    pitfalls: [
      "Swapping materials first and finding sustainability raised costs.",
      "Ignoring freight savings from smaller cube.",
      "Letting damage rates drift as packaging lightens.",
    ],
  },
  {
    slug: "hospital-or-utilisation",
    shape: "case",
    title: "Operating theatres run at 55% utilisation yet surgeons complain of no slots. Resolve it.",
    type: "Capacity management",
    difficulty: 3,
    minutes: 28,
    answer: "Both facts are true: block scheduling gives surgeons fixed slots they underuse, while others cannot book the idle time. Move to a rule where unused blocks release 72 hours ahead, protect emergency capacity explicitly, and start first cases on time.",
    hints: ["Utilisation and access can both be broken when capacity is owned, not shared."],
    moves: [
      { label: "Move 1", text: "Audit block usage: which surgeons use what share of their blocks; typical finding is a wide spread from 30% to 90%." },
      { label: "Move 2", text: "Find the leaks: late first-case starts, gaps between cases, and blocks held but not booked." },
      { label: "Move 3", text: "Change the rules: unused block time auto-releases 72 hours out to a waitlist; block allocation reviews quarterly against actual usage." },
      { label: "Move 4", text: "Fix the morning: first-case on-time starts drive the whole day; pre-op readiness the evening before moves this most." },
      { label: "Close", text: "Target 75% utilisation with released-time booking, and show surgeons the data that their access improves when idle blocks circulate." },
    ],
    pitfalls: [
      "Treating utilisation as a scheduling software problem when it is a block-ownership politics problem.",
      "Squeezing emergency buffer capacity to lift the number.",
      "Ignoring late first starts that cascade through every subsequent case.",
    ],
  },
  {
    slug: "fmcg-rural-distribution-cost",
    shape: "case",
    title: "Serving villages below 2,000 population loses money for an FMCG firm. Make it viable.",
    type: "Network design",
    difficulty: 3,
    minutes: 28,
    askedAt: "HUL",
    answer: "Direct distribution cannot pay below a density threshold; switch to hub-and-spoke with rural super-stockists, wholesale feeding, telecaller ordering and shared last-mile. Coverage stays, cost structure changes.",
    hints: ["The van route economics fail on density. What replaces the van?"],
    moves: [
      { label: "Move 1", text: "Confirm the economics: a van covering 15 small villages books orders that don't cover fuel and salesman cost." },
      { label: "Move 2", text: "Re-tier the network: appoint sub-stockists in feeder towns; small-village shops buy from them or from weekly haats." },
      { label: "Move 3", text: "Replace visits with calls: telecaller order-taking plus delivery by shared rural logistics or the sub-stockist's own trips." },
      { label: "Move 4", text: "Rationalise range: villages get the 40-SKU rural pack list, not the full catalogue, cutting handling and returns." },
      { label: "Close", text: "Measure cost-to-serve per village tier quarterly; direct service resumes only where density crosses the threshold." },
    ],
    pitfalls: [
      "Abandoning coverage instead of re-architecting cost.",
      "Pushing the full SKU range where 40 SKUs do the volume.",
      "Ignoring wholesale and haats as legitimate channels.",
    ],
  },
  {
    slug: "print-plant-consolidation",
    shape: "case",
    title: "A newspaper group runs 12 print plants at falling volumes. Consolidate the network.",
    type: "Network optimisation",
    difficulty: 3,
    minutes: 28,
    answer: "Close plants where trucking from a neighbour still meets the edition deadline; the binding constraint is print-to-doorstep time, not print cost. Typically 12 plants become 7 with deadline-feasible trucking, saving fixed costs while protecting morning delivery.",
    hints: ["The constraint is the 6:30 am doorstep, not the printing press."],
    moves: [
      { label: "Move 1", text: "Model the deadline chain backward: doorstep 6:30 am, depot 4:30, plant dispatch 2:30, print start 11 pm. Each plant serves a trucking radius defined by these hours." },
      { label: "Move 2", text: "Map volumes: which plants run below 40% capacity; falling circulation means several." },
      { label: "Move 3", text: "Test closures: can plant B's radius absorb plant A's editions within the dispatch window, including edition-change time on the presses?" },
      { label: "Move 4", text: "Account the trade: closed plant fixed costs against added trucking and any later news deadline for far editions." },
      { label: "Close", text: "Recommend the 5 closures that clear the deadline test, phased over 18 months with union settlements costed in." },
    ],
    pitfalls: [
      "Optimising print cost while breaking the morning deadline.",
      "Ignoring edition-change setup time when loading a surviving plant.",
      "Leaving labour transition costs out of the business case.",
    ],
  },
  {
    slug: "quick-service-franchise-consistency",
    shape: "case",
    title: "Mystery audits show franchise outlets score 30% below company stores. Standardise.",
    type: "Quality management",
    difficulty: 2,
    minutes: 22,
    answer: "Franchisees fail where the system lets them: cost pressure meets weak enforcement. Fix the economics that tempt corner-cutting, simplify the standards to the vital few, audit with consequences, and support before punishing.",
    hints: ["Ask why a rational franchisee cuts the corner before policing the corner."],
    moves: [
      { label: "Move 1", text: "Locate the gap: which audit lines fail? Usually staffing levels, ingredient substitution and cleaning frequency, which are the cost lines." },
      { label: "Move 2", text: "Check the economics: if company stores run 65% gross margin and franchisees 55% after royalties, corner-cutting is a survival response." },
      { label: "Move 3", text: "Simplify and support: cut the 200-point manual to the 30 points customers notice; central supply of pre-portioned ingredients removes the substitution temptation." },
      { label: "Move 4", text: "Enforce with teeth and help: quarterly audits tied to renewal, but failing stores get an improvement visit before a notice." },
      { label: "Close", text: "Track the audit gap quarterly; if economics were the cause, margin repair moves scores faster than inspection ever will." },
    ],
    pitfalls: [
      "Pure enforcement against an economic root cause.",
      "A 200-point standard nobody can hold in their head.",
      "Letting ingredient supply stay local and substitutable.",
    ],
  },
  {
    slug: "coal-mine-truck-cycle-time",
    shape: "case",
    title: "An open-cast mine's dumper cycle time rose 20%, cutting output. Restore it.",
    type: "Bottleneck diagnosis",
    difficulty: 2,
    minutes: 22,
    askedAt: "Coal India",
    answer: "Decompose the cycle: load, haul, dump, return, queue. Rising cycle time with the same route usually means queueing at the shovel or the dump, from a shovel down or haul-road deterioration. Fix the constraint stage; buying more dumpers makes queues longer.",
    hints: ["More trucks against a slow shovel just grows the queue."],
    moves: [
      { label: "Move 1", text: "Split the cycle with GPS data: where did the extra minutes appear? Queue-at-shovel time is the usual growth." },
      { label: "Move 2", text: "If shovel-bound: check shovel availability and bucket cycle; one shovel on breakdown pushes its trucks onto others, queuing everything." },
      { label: "Move 3", text: "If road-bound: monsoon-damaged haul roads slow laden speeds; grader deployment restores more capacity than any purchase." },
      { label: "Move 4", text: "Rebalance the fleet: match truck count to shovel loading rate; surplus trucks go to the other bench rather than the queue." },
      { label: "Close", text: "Restore cycle time to baseline and institute daily cycle-time dashboards by stage, so the next 20% creep gets caught in a week." },
    ],
    pitfalls: [
      "Adding trucks to a shovel-constrained circuit.",
      "Ignoring haul-road condition as an operations variable.",
      "Tracking only tonnage, which hides where the cycle grew.",
    ],
  },
  {
    slug: "apparel-ecom-size-returns",
    shape: "case",
    title: "40% of a fashion site's returns say wrong size. Halve size-related returns.",
    type: "Returns reduction",
    difficulty: 2,
    minutes: 22,
    askedAt: "Myntra",
    answer: "Size returns come from inconsistent brand sizing and buyer guesswork. Attack with per-brand fit data ('this brand runs small'), a size recommender trained on the buyer's kept-versus-returned history, and standardised size charts enforced on sellers.",
    hints: ["The same customer keeps M in one brand and returns M in another. That is data."],
    moves: [
      { label: "Move 1", text: "Mine the returns: by brand, by SKU, by customer cohort. Sizing chaos concentrates in specific brands and categories." },
      { label: "Move 2", text: "Deploy fit intelligence: 'runs small, order a size up' badges from return-reason data, per brand and SKU." },
      { label: "Move 3", text: "Personalise: recommend sizes from the customer's own keep history across brands; cold-start with height-weight prompts." },
      { label: "Move 4", text: "Fix the source: mandate measured garment specs from sellers, audit against physical samples, and penalise chronic offenders." },
      { label: "Close", text: "A drop from 40% to 20% size-returns pays for itself in reverse logistics alone; track return rate per SKU as a seller-facing metric." },
    ],
    pitfalls: [
      "Building one universal size chart when brands genuinely differ.",
      "Ignoring the goldmine in return-reason plus keep-history data.",
      "Treating returns purely as logistics cost instead of an information source.",
    ],
  },
  {
    slug: "gas-cylinder-delivery-network",
    shape: "case",
    title: "LPG delivery in a city averages 4 days from booking. Bring it to 1.",
    type: "Service operations",
    difficulty: 2,
    minutes: 22,
    askedAt: "Indian Oil",
    answer: "The lag sits in batching: distributors accumulate bookings until a truck fills. Break it with smaller daily runs, demand-zone routing, and forecast-led pre-positioning, since refill demand is highly predictable per household.",
    hints: ["Refill demand is predictable: every household cycles every 25 to 40 days."],
    moves: [
      { label: "Move 1", text: "Trace the 4 days: booking to distributor batch (2.5 days), truck loading and route (1 day), doorstep attempt (0.5). Batching is the fat." },
      { label: "Move 2", text: "Exploit predictability: households refill on a stable cycle; forecast area demand and pre-position stock at the distributor daily." },
      { label: "Move 3", text: "Re-route: fixed daily beats per zone rather than fill-the-truck batching; a booking joins tomorrow's beat, not next week's batch." },
      { label: "Move 4", text: "Handle exceptions: same-day premium delivery absorbs urgency and funds the extra runs." },
      { label: "Close", text: "Pilot in two distributorships: daily beats plus forecasting should hit next-day for 85% of bookings without fleet addition." },
    ],
    pitfalls: [
      "Adding trucks when batching policy is the delay.",
      "Ignoring how predictable per-household refill cycles are.",
      "One citywide fix when distributor practices vary wildly.",
    ],
  },
  {
    slug: "it-hardware-refresh-logistics",
    shape: "case",
    title: "A bank must refresh 40,000 branch computers in 12 months. Plan the rollout.",
    type: "Rollout planning",
    difficulty: 2,
    minutes: 25,
    answer: "This is a wave-planning problem: pilot, standardise the runbook, then industrialise at roughly 800 machines a week through regional staging hubs, with old-asset reverse logistics and data-wiping compliance built into the same visit.",
    hints: ["The constraint is coordinated on-site hours, not hardware supply."],
    moves: [
      { label: "Move 1", text: "Size the drumbeat: 40,000 over 45 working weeks is about 900 a week, or 180 branch visits a week at 5 machines each." },
      { label: "Move 2", text: "Pilot 20 branches: build the per-branch runbook, timing (half a day per branch), and the failure list (network configs, legacy peripherals)." },
      { label: "Move 3", text: "Industrialise: regional staging hubs pre-image machines so branch time is swap-and-verify, not install; 25 two-person crews cover the drumbeat." },
      { label: "Move 4", text: "Close the loop: old machines leave the same day, wiped-certificate issued, refurbished or scrapped under audit trail." },
      { label: "Close", text: "Schedule branch waves around month-end freezes and audit weeks; the calendar's blackout days, not crew capacity, are what threaten 12 months." },
    ],
    pitfalls: [
      "Imaging machines at the branch instead of a staging hub.",
      "Forgetting reverse logistics and data-destruction compliance.",
      "Planning without banking blackout windows.",
    ],
  },
  {
    slug: "cement-freight-mode-mix",
    shape: "case",
    title: "A cement firm's freight cost per tonne beats rivals by 8% the wrong way. Rebalance the mode mix.",
    type: "Logistics strategy",
    difficulty: 3,
    minutes: 28,
    askedAt: "UltraTech",
    answer: "Freight disadvantage usually traces to mode mix and lead distance: too much long-haul road and depots placed by history, not by demand. Shift lanes above 300 km to rail where sidings allow, re-site depots against the current demand map, and load trucks fuller with bulkers.",
    hints: ["Compare mode shares and average lead distance before rate negotiations."],
    moves: [
      { label: "Move 1", text: "Decompose the 8%: mode mix (rail versus road share), lead distance, vehicle utilisation, and rates. Rate negotiation is usually the smallest lever." },
      { label: "Move 2", text: "Rail shift: lanes over 300 km with siding access move at 60 to 70% of road cost; every 5-point mix shift moves total freight 2 to 3%." },
      { label: "Move 3", text: "Depot audit: demand has moved since depots were sited; re-mapping cuts average secondary lead distance." },
      { label: "Move 4", text: "Utilisation: bulk tankers and higher-capacity trucks on dense corridors raise tonnes per trip." },
      { label: "Close", text: "A 3-part programme (mode, network, utilisation) closes the 8% in 18 months; pure rate squeezing would recover 2 at the cost of carrier quality." },
    ],
    pitfalls: [
      "Leading with rate negotiations on a structural problem.",
      "Rail commitments on lanes without siding or rake availability.",
      "Depot network treated as fixed history.",
    ],
  },
  {
    slug: "ott-live-event-capacity",
    shape: "case",
    title: "Prepare a streaming platform's operations for a cricket final with 5x normal load.",
    type: "Surge planning",
    difficulty: 3,
    minutes: 28,
    askedAt: "JioHotstar",
    answer: "Plan for the worst minute, not the average hour: pre-scale infrastructure ahead of the toss, degrade gracefully by dropping bitrate before dropping streams, and war-room with kill-switch authority. The operational insight is that failures cluster at moments of maximum shared attention.",
    hints: ["The last over is the load test. What spikes at wickets?"],
    moves: [
      { label: "Move 1", text: "Model the curve: load spikes at toss, wickets and the final overs; concurrency can double in 5 minutes at a wicket." },
      { label: "Move 2", text: "Pre-scale: auto-scaling reacts too slowly for a wicket spike; pre-provision to forecast peak plus 30% before play starts." },
      { label: "Move 3", text: "Degrade by design: bitrate laddering sheds load invisibly; feature shedding (stats overlays off) comes next; stream drops are the last resort." },
      { label: "Move 4", text: "Rehearse failure: game-day war room, chaos drills the week before, and pre-agreed authority to trigger degradations without meetings." },
      { label: "Close", text: "Success metric is rebuffering rate at the worst minute, not average; report the final over as its own SLA." },
    ],
    pitfalls: [
      "Scaling to average concurrency and dying at the first wicket.",
      "Binary thinking: full quality or outage, with no degradation ladder.",
      "Deciding degradation steps during the incident instead of before.",
    ],
  },
  {
    slug: "bank-branch-network-rationalisation",
    shape: "case",
    title: "Digital adoption halved branch footfall. Redesign the branch network.",
    type: "Network optimisation",
    difficulty: 3,
    minutes: 28,
    askedAt: "HDFC Bank",
    answer: "Do not close by footfall alone: branches anchor deposits, senior customers and small-business relationships that outlive their transaction counts. Convert oversized branches to smaller advisory formats, merge overlapping pairs, and close only where a nearby branch absorbs relationships measurably.",
    hints: ["A branch's value is its book, not its queue length."],
    moves: [
      { label: "Move 1", text: "Score branches on two axes: transaction load (falling) and relationship value (deposits, loans, senior customer density)." },
      { label: "Move 2", text: "Segment actions: high-value low-footfall branches shrink into advisory formats; low-value branches within 2 km of another merge; genuinely redundant ones close." },
      { label: "Move 3", text: "Model attrition honestly: closures lose 5 to 15% of the book depending on the nearest alternative; that loss belongs in the closure math." },
      { label: "Move 4", text: "Repurpose capacity: freed staff move from teller lines to sales and service roles that digital cannot do." },
      { label: "Close", text: "Rationalise 20% of square footage rather than 20% of branches; format change beats closure in most Indian micro-markets." },
    ],
    pitfalls: [
      "Closing on footfall while the deposit book quietly walks to a rival.",
      "Ignoring regulatory expectations on banking access.",
      "Treating every branch as the same format problem.",
    ],
  },
  {
    slug: "spare-parts-inventory-service-level",
    shape: "case",
    title: "An elevator firm promises 4-hour repairs but hits 60%. Fix spare-parts availability.",
    type: "Inventory management",
    difficulty: 2,
    minutes: 25,
    askedAt: "Otis",
    answer: "A 4-hour promise is an inventory-positioning problem: the failing 40% are stockouts of mid-tail parts held only centrally. Stratify parts by criticality and failure rate, push the vital-and-frequent tier to technician vans and city depots, and pool the slow tail regionally.",
    hints: ["Where must a part physically sit for a 4-hour fix to be possible?"],
    moves: [
      { label: "Move 1", text: "Autopsy the misses: which parts caused the failed 40%, and where was the nearest unit sitting?" },
      { label: "Move 2", text: "Stratify: A-parts (frequent, cheap) belong in every van; B-parts in city depots; C-parts (rare, costly) pooled regionally with courier SLAs." },
      { label: "Move 3", text: "Position by installed base: van and depot stock lists follow the local elevator models, not a national average list." },
      { label: "Move 4", text: "Close the loop: every 4-hour miss gets a part-position root cause, feeding monthly stock-list revisions." },
      { label: "Close", text: "Target 92% within-4-hour at a costed inventory increase; the premium contracts funding the promise justify the working capital." },
    ],
    pitfalls: [
      "One national stock list against locally different installed bases.",
      "Holding everything centrally to minimise inventory while breaking the SLA.",
      "Not autopsying each miss to a part and location.",
    ],
  },
  {
    slug: "food-delivery-rain-surge",
    shape: "case",
    title: "Rain doubles food-delivery demand while rider supply drops 30%. Manage the imbalance.",
    type: "Demand-supply balancing",
    difficulty: 2,
    minutes: 22,
    askedAt: "Swiggy",
    answer: "You cannot conjure riders in rain; manage both sides: surge incentives and rain gear raise effective supply somewhat, while honest longer ETAs, batching and a temporarily trimmed restaurant radius manage demand. Protect rider safety as a hard constraint.",
    hints: ["Both sides of the marketplace are levers; neither alone closes the gap."],
    moves: [
      { label: "Move 1", text: "Quantify the gap: demand 2x, supply 0.7x means effective capacity shortfall of 65% against demand at normal service levels." },
      { label: "Move 2", text: "Lift supply: rain surge pay, gear provision, and shift guarantees recover perhaps 10 of the 30 lost points; safety caps the rest." },
      { label: "Move 3", text: "Shape demand: show honest 60-minute ETAs upfront, batch aggressively, shrink delivery radius, and let price surge where allowed." },
      { label: "Move 4", text: "Protect the experience: proactive delay notifications and easy cancellation refunds hurt less than silent lateness." },
      { label: "Close", text: "Optimise for completed-orders-with-honest-promises, not order volume; declined orders cost less than broken ones." },
    ],
    pitfalls: [
      "Accepting every order at normal ETAs and failing half.",
      "Pushing riders into unsafe conditions with incentives.",
      "Treating demand as untouchable when ETA honesty shapes it naturally.",
    ],
  },
  {
    slug: "textile-export-lead-time",
    shape: "case",
    title: "A textile exporter quotes 90-day lead times; Bangladesh quotes 60. Compete.",
    type: "Lead time reduction",
    difficulty: 3,
    minutes: 28,
    answer: "Map the 90 days: fabric sourcing and approval loops usually eat more than stitching. Compress with fabric platforming (pre-approved greige stock), parallelised sampling and approvals, and booking logistics at order rather than at completion.",
    hints: ["The stitching is 2 weeks. Where do the other 10 go?"],
    moves: [
      { label: "Move 1", text: "Value-stream map: fabric procurement 35 days, sampling and buyer approval 20, cutting and stitching 15, finishing 8, shipping booking and transit 12." },
      { label: "Move 2", text: "Fabric platform: hold pre-approved greige for the top fabric bases and dye to order, cutting 35 days toward 12." },
      { label: "Move 3", text: "Parallelise approvals: digital sampling and pre-agreed tolerance bands turn a 20-day sequential loop into 8 days running alongside fabric prep." },
      { label: "Move 4", text: "Book freight at order confirmation, not ex-factory; vessel space uncertainty is a silent week." },
      { label: "Close", text: "A credible 65-day quote with reliability beats a fake 60; sell the buyer on adherence data, and price the remaining gap against your compliance record." },
    ],
    pitfalls: [
      "Squeezing the stitching stage that is already the smallest slice.",
      "Holding finished-fabric inventory in fashion colours that die each season.",
      "Quoting matched lead times you then miss, which loses buyers permanently.",
    ],
  },
  {
    slug: "municipal-water-nonrevenue",
    shape: "case",
    title: "A city loses 38% of pumped water as non-revenue water. Build the reduction plan.",
    type: "Loss reduction",
    difficulty: 3,
    minutes: 28,
    answer: "Split the 38% into physical leaks, theft and metering error; each needs a different attack. District metering to localise, pressure management and leak repair for physical losses, regularisation drives for theft, and meter replacement for under-registration.",
    hints: ["Non-revenue water is three problems: leaks, theft, and meters that lie."],
    moves: [
      { label: "Move 1", text: "Establish the split with a water balance: say 20 points physical leakage, 12 theft and unbilled use, 6 meter under-registration." },
      { label: "Move 2", text: "Zone the network: district metered areas with bulk meters localise losses to neighbourhoods, turning a city problem into 40 measurable ones." },
      { label: "Move 3", text: "Physical: fix the top leaking zones first; night-flow analysis finds them. Pressure management cuts burst rates network-wide." },
      { label: "Move 4", text: "Commercial: amnesty-then-enforcement for illegal connections, and replace the oldest meter cohort that under-reads 15%." },
      { label: "Close", text: "Target 24% in five years zone by zone; every recovered point is water sold without a drop of new supply built." },
    ],
    pitfalls: [
      "City-wide averages instead of zone-level measurement.",
      "Chasing pipes when a third of the loss is commercial.",
      "Building new supply capacity while losing 38% of the old.",
    ],
  },
  {
    slug: "auto-service-workshop-throughput",
    shape: "case",
    title: "A car service centre turns away bookings; bays sit idle by 4 pm. Diagnose and expand throughput.",
    type: "Scheduling",
    difficulty: 1,
    minutes: 20,
    askedAt: "Maruti Suzuki",
    answer: "Everyone drops cars at 9 am, so mornings choke while afternoons idle: it is a scheduling shape problem. Slotted drop-offs, pick-up services, an express lane for small jobs, and evening bays convert idle afternoon capacity into served demand.",
    hints: ["Idle bays and refused customers together mean a time-of-day mismatch."],
    moves: [
      { label: "Move 1", text: "Plot arrivals versus bay occupancy by hour: a 9 am wall of drop-offs, technicians overloaded till 2, idle after 4." },
      { label: "Move 2", text: "Slot the intake: booked drop windows across the day, priced nudges for afternoon slots, and doorstep pick-up that lets the workshop pace its own intake." },
      { label: "Move 3", text: "Segment jobs: 40% are under 90 minutes; an express lane keeps small jobs out of full-service bays." },
      { label: "Move 4", text: "Stretch the day: an evening shift for drop-offs after office hours serves exactly the customers being refused." },
      { label: "Close", text: "Same bays, reshaped schedule: 25 to 30% more cars a day, measured as bay-hours utilised across the full day." },
    ],
    pitfalls: [
      "Building bays when afternoon bays already sit idle.",
      "Letting customer habit dictate the intake curve.",
      "Mixing 45-minute jobs into 4-hour bays.",
    ],
  },
  {
    slug: "pharma-plant-changeover-capacity",
    shape: "case",
    title: "A generics plant loses a fifth of capacity to line changeovers. Recover half of it.",
    type: "Process improvement",
    difficulty: 2,
    minutes: 25,
    askedAt: "Sun Pharma",
    answer: "Attack sequence first, then speed: campaign scheduling that groups compatible products cuts the number of major cleanings, and SMED-style externalisation cuts each changeover's length. Both together recover 8 to 10 points of the 20 without touching compliance.",
    hints: ["Two levers: fewer changeovers, and faster ones. Sequence enables the first."],
    moves: [
      { label: "Move 1", text: "Classify changeovers: minor (same molecule, size change) versus major (molecule change, full cleaning validation). Majors cost 10x." },
      { label: "Move 2", text: "Re-sequence: campaign compatible products together; a smarter monthly wheel cuts major changeovers by a third." },
      { label: "Move 3", text: "Compress each: externalise prep (staged tooling, pre-mixed cleaning agents, documents ready) so the line stops only for what truly needs it stopped." },
      { label: "Move 4", text: "Protect compliance: every shortcut stays inside validated cleaning procedures; the win is organisation, not corner-cutting." },
      { label: "Close", text: "Recovered capacity delays capex: 10 points of a plant is a fraction of a new line's cost, delivered in two quarters." },
    ],
    pitfalls: [
      "Treating cleaning validation time as compressible; it is not.",
      "Optimising changeover speed while the sequence forces needless majors.",
      "Chasing OEE while regulatory batch records lag.",
    ],
  },
  {
    slug: "ev-fleet-charging-depot",
    shape: "case",
    title: "An e-bus depot with 100 buses keeps missing morning pull-out. Fix overnight charging.",
    type: "Scheduling",
    difficulty: 2,
    minutes: 25,
    answer: "The depot has enough energy but not enough coordinated power: unmanaged charging peaks past the grid connection, tripping and delaying. Smart-charging that staggers buses against departure times, plus a few fast chargers for late arrivals, clears pull-out without a grid upgrade.",
    hints: ["Energy over the night is enough; simultaneous power is the constraint."],
    moves: [
      { label: "Move 1", text: "Do the math: 100 buses times 250 kWh nightly over 8 hours is about 3 MW average, but unmanaged plug-in-on-arrival peaks at 6 MW against a 4 MW connection." },
      { label: "Move 2", text: "Sequence by need: buses charge in departure order, not arrival order; a bus leaving at 9 am can wait while the 5:30 pull-out charges first." },
      { label: "Move 3", text: "Manage the peak: staggered charging holds load under the connection limit; a small battery buffer shaves the morning top-up spike." },
      { label: "Move 4", text: "Handle exceptions: 2 or 3 fast chargers rescue late-returning or low-state buses without disturbing the schedule." },
      { label: "Close", text: "Charge-management software costs a fraction of a grid connection upgrade; measure success as on-time pull-out rate, not average charge level." },
    ],
    pitfalls: [
      "Buying a grid upgrade for a scheduling problem.",
      "Charging in arrival order instead of departure order.",
      "Sizing chargers for average rather than the morning readiness deadline.",
    ],
  },
  {
    slug: "cold-storage-utilisation-seasonal",
    shape: "case",
    title: "A potato cold storage runs full 5 months, near-empty 7. Improve annual economics.",
    type: "Asset utilisation",
    difficulty: 2,
    minutes: 22,
    answer: "The asset is seasonal by design, so fill the trough with compatible counter-seasonal produce, monetise services beyond storage (grading, financing against stored stock), and price the peak properly rather than chasing off-season volume at any rate.",
    hints: ["What else needs cold in the months potatoes don't?"],
    moves: [
      { label: "Move 1", text: "Baseline the economics: fixed costs run all year; five full months must currently carry twelve months of cost." },
      { label: "Move 2", text: "Fill the trough: apples, seed storage, pulses and processed food need overlapping but offset seasons; multi-commodity chambers with separate temperature zones widen the catch." },
      { label: "Move 3", text: "Sell services, not just space: grading, sorting, and warehouse-receipt financing against stored potatoes earn margin on the same stock." },
      { label: "Move 4", text: "Reprice the peak: peak-season storage is scarce and underpriced; farmers pay for guaranteed space booked pre-harvest." },
      { label: "Close", text: "Model the mix: even 40% trough utilisation plus service income typically doubles asset-level profit." },
    ],
    pitfalls: [
      "Chasing incompatible commodities into potato-tuned chambers.",
      "Leaving warehouse-receipt financing to banks entirely.",
      "Underpricing peak scarcity while overbuilding for it.",
    ],
  },
  {
    slug: "airline-cargo-belly-utilisation",
    shape: "case",
    title: "A passenger airline's belly cargo flies 45% full. Lift cargo revenue.",
    type: "Asset utilisation",
    difficulty: 2,
    minutes: 22,
    answer: "Belly space is a perishable by-product: sell it like one. Dynamic pricing by route and day, forwarder commitments on dense lanes, faster acceptance cut-offs, and e-commerce partnerships convert empty kilos into near-pure margin.",
    hints: ["The marginal cost of flying a filled kilo is tiny. What stops the filling?"],
    moves: [
      { label: "Move 1", text: "Map utilisation by lane and day: metros midweek fly full, leisure routes weekends fly empty. The average hides sellable pockets." },
      { label: "Move 2", text: "Fix acceptance friction: late cut-offs, slow quotes and paper processes push forwarders to dedicated freighters; digital booking with instant rates recovers them." },
      { label: "Move 3", text: "Commit and spot: block-space agreements with forwarders on dense lanes, dynamic spot pricing on the rest." },
      { label: "Move 4", text: "Court e-commerce: predictable daily volumes at negotiated rates fill the trough lanes that spot demand never will." },
      { label: "Close", text: "Cargo yield management mirrors seat yield management; target 65% utilisation with a revenue-per-flight metric owned by one team." },
    ],
    pitfalls: [
      "Averaging utilisation across lanes with opposite problems.",
      "Pricing statically while demand swings daily.",
      "Ignoring ground handling cut-off friction as the real barrier.",
    ],
  },
];
