import type { Question } from "./types";

// Product guesstimates. Estimation at system scale, where the interesting answer
// is usually the constraint rather than the total.
export const PRODUCT_GUESSTIMATES: Question[] = [
  {
    slug: "whatsapp-photos-india-daily",
    shape: "guesstimate",
    title: "How many photos are sent on WhatsApp in India in a single day?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 15,
    askedAt: "Google",
    answer: "Roughly 2 billion photo sends a day, about four per active user.",
    hints: ["Users times messages per user is too blunt. Split users into heavy, regular and light."],
    moves: [
      { label: "Move 1", text: "Set the user base. Around 500 million WhatsApp users in India, of whom roughly 80% are active on a given day." },
      { label: "Move 2", text: "Segment by intensity rather than averaging. Say 20% heavy, 50% regular, 30% light." },
      { label: "Move 3", text: "Assign photo sends per segment, roughly 15, 4 and 1 a day, and sum." },
      { label: "Move 4", text: "Total near 2 billion, then note that group forwards multiply one image across many recipients." },
      { label: "Check", text: "That is about four photos per active user. Plausible where WhatsApp carries most social sharing." },
    ],
    pitfalls: [
      "Averaging across all users, which buries the heavy segment that drives the total.",
      "Not defining whether a group send counts once or once per recipient.",
      "Producing a number with no per-user check, which is the fastest way to catch an error.",
    ],
  },
  {
    slug: "swiggy-order-history-storage",
    shape: "guesstimate",
    title: "Estimate the storage Swiggy needs for one year of order history.",
    type: "Scale estimation",
    difficulty: 3,
    minutes: 20,
    askedAt: "Swiggy",
    answer: "About 6 TB of primary order data, and 30 to 60 TB once replicas, backups and logs are counted.",
    hints: ["Storage equals rows times bytes per row. Get the row count before worrying about bytes."],
    moves: [
      { label: "Move 1", text: "Size daily orders at roughly 2 million, so about 730 million orders a year." },
      { label: "Move 2", text: "Size one record. Header, items, addresses, payment and status history come to roughly 5 to 10 KB." },
      { label: "Move 3", text: "Multiply out. 730 million at 8 KB is about 6 TB of primary data, which is small by modern standards." },
      { label: "Move 4", text: "Add replicas, backups, search indexes and event logs at several times the primary size." },
      { label: "Check", text: "The interesting answer is that orders are cheap and derived data is not. Saying that separates a product answer from arithmetic." },
    ],
    pitfalls: [
      "Answering only the primary table and missing that replicas and logs dominate.",
      "Assuming images sit inside the order record rather than in object storage.",
      "Forgetting retention policy, which is the lever that actually controls the number.",
    ],
  },
  {
    slug: "upi-friday-evening-concurrency",
    shape: "guesstimate",
    title: "How many people are on UPI between 8pm and 10pm on a Friday?",
    type: "Concurrency",
    difficulty: 2,
    minutes: 20,
    askedAt: "PhonePe",
    answer: "Roughly 40 to 70 million transactions in the window, with peak concurrency in the low hundreds of thousands per second.",
    hints: ["Transactions in a window and concurrent users are different numbers. Say which you are answering."],
    moves: [
      { label: "Move 1", text: "Start from daily UPI volume, in the region of 600 to 700 million transactions." },
      { label: "Move 2", text: "Apply the time distribution. Evening hours carry disproportionate volume, perhaps 10% in this two-hour window." },
      { label: "Move 3", text: "Convert to a per-second rate by dividing across 7,200 seconds." },
      { label: "Move 4", text: "Convert transactions to people using transactions per active user in the window, typically one or two." },
      { label: "Check", text: "Peak load, not average, is what sizes infrastructure. Say that explicitly since it is the point of the question." },
    ],
    pitfalls: [
      "Dividing daily volume evenly across 24 hours.",
      "Conflating transactions with unique users.",
      "Answering average throughput when the useful number is peak.",
    ],
  },
  {
    slug: "news-app-daily-server-cost",
    shape: "guesstimate",
    title: "Estimate the daily server cost of a 10 million user Indian news app.",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 1.5 to 4 lakh rupees a day, with image and video bandwidth the dominant line rather than compute.",
    hints: ["Bandwidth, not compute, usually dominates media-heavy consumer apps."],
    moves: [
      { label: "Move 1", text: "Size sessions. Ten million registered users might give 2 to 3 million daily actives at several sessions each." },
      { label: "Move 2", text: "Size payload. A news session pulls text, thumbnails and sometimes video, perhaps 5 to 15 MB." },
      { label: "Move 3", text: "Multiply to daily egress in the tens of terabytes, then price it at CDN rates." },
      { label: "Move 4", text: "Add compute and database, which for a read-heavy app with good caching is a minority of the bill." },
      { label: "Check", text: "Compare against likely ad revenue per user. If infrastructure exceeds it, the business does not work, which is the real finding." },
    ],
    pitfalls: [
      "Sizing compute carefully and ignoring bandwidth, which is the larger cost.",
      "Forgetting caching, which removes most repeat load.",
      "Giving a cost with no revenue comparison, which makes the number meaningless.",
    ],
  },
  {
    slug: "uber-rides-bengaluru-rainy-tuesday",
    shape: "guesstimate",
    title: "How many rides does a ride-hailing app complete in Bengaluru on a rainy Tuesday?",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    askedAt: "Uber",
    answer: "Roughly 250,000 to 400,000 completed rides, with demand spiking and supply falling at the same time.",
    hints: ["Rain raises demand and lowers driver supply simultaneously. Completed rides are capped by supply."],
    moves: [
      { label: "Move 1", text: "Establish a baseline. A city of 13 million might see 300,000 to 400,000 app rides on a normal weekday." },
      { label: "Move 2", text: "Apply the rain effect on demand, which rises sharply as people avoid two-wheelers and walking." },
      { label: "Move 3", text: "Apply the rain effect on supply, which falls as drivers avoid flooded roads and longer trip times." },
      { label: "Move 4", text: "Recognise the binding constraint. Completed rides follow supply, so the number may fall even as demand rises." },
      { label: "Check", text: "Requests and completions diverge on rainy days, which is precisely why surge pricing exists. Say that." },
    ],
    pitfalls: [
      "Assuming higher demand means more completed rides.",
      "Ignoring that trip times lengthen, so each driver completes fewer rides.",
      "Not distinguishing requests from completions.",
    ],
  },
  {
    slug: "support-bot-messages-large-bank",
    shape: "guesstimate",
    title: "How many messages does a support bot handle for a large Indian bank daily?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 2 to 5 million messages a day, concentrated in a handful of intents like balance and card status.",
    hints: ["Conversations and messages differ by a factor of five or more. Decide which you are counting."],
    moves: [
      { label: "Move 1", text: "Size the customer base, perhaps 50 million accounts with 15 to 20 million digitally active." },
      { label: "Move 2", text: "Apply support contact rate, perhaps 2 to 4% of active users needing help in a given month." },
      { label: "Move 3", text: "Convert to daily conversations, then multiply by messages per conversation, typically five to eight." },
      { label: "Move 4", text: "Note the concentration. A few intents carry most volume, which is what makes automation viable." },
      { label: "Check", text: "Add month-end and salary-day spikes, which can double volume on specific dates." },
    ],
    pitfalls: [
      "Reporting conversations as messages or the reverse.",
      "Assuming uniform daily volume in a business with strong monthly cycles.",
      "Ignoring that intent concentration is the actual product insight.",
    ],
  },
  {
    slug: "fintech-dau-after-six-months",
    shape: "guesstimate",
    title: "Estimate the daily active users of a new fintech app six months after launch.",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 5 to 15% of installs, and the honest answer depends far more on retention than on install count.",
    hints: ["Installs are easy to buy. Work forward from retention curves, not from download numbers."],
    moves: [
      { label: "Move 1", text: "Start from installs driven by marketing spend, perhaps 2 to 5 million in six months with real budget." },
      { label: "Move 2", text: "Apply activation. A large share never complete onboarding, particularly with KYC in the flow." },
      { label: "Move 3", text: "Apply the retention curve. Day 30 retention for consumer fintech typically sits in the teens." },
      { label: "Move 4", text: "Convert monthly actives to daily using engagement frequency, which for payments is high and for investing is low." },
      { label: "Check", text: "State which product type you assumed. A payments app and an investing app differ by an order of magnitude here." },
    ],
    pitfalls: [
      "Treating installs as users.",
      "Ignoring KYC drop-off, which is the largest single leak in Indian fintech onboarding.",
      "Using one engagement frequency across very different fintech products.",
    ],
  },
  {
    slug: "youtube-video-uploaded-india-daily",
    shape: "guesstimate",
    title: "How much video is uploaded to YouTube from India in a day?",
    type: "Scale estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 100,000 to 200,000 hours a day, dominated by short-form and mobile uploads.",
    hints: ["Creators are a tiny fraction of viewers. Size creators first, then output per creator."],
    moves: [
      { label: "Move 1", text: "Size viewers at roughly 500 million Indian users, then apply the creator ratio, well under 1%." },
      { label: "Move 2", text: "Split creators by intensity. Daily uploaders are rare, occasional uploaders far more common." },
      { label: "Move 3", text: "Apply length. Short-form dominates count while long-form dominates hours, so both matter." },
      { label: "Move 4", text: "Multiply and sum, converting everything into hours for a consistent answer." },
      { label: "Check", text: "Convert to storage using bitrate. The result should be large but not absurd against global infrastructure." },
    ],
    pitfalls: [
      "Applying a creator rate anywhere near the viewer count.",
      "Answering in videos when the question asked about volume of video.",
      "Ignoring that short and long form need separate treatment.",
    ],
  },
  {
    slug: "push-notifications-shopping-app",
    shape: "guesstimate",
    title: "Estimate the number of push notifications a shopping app sends daily.",
    type: "Usage estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 30 to 80 million sends for a large Indian app, of which only a small fraction are actually delivered and seen.",
    hints: ["Sent, delivered and opened are three very different numbers. Track all three."],
    moves: [
      { label: "Move 1", text: "Size the installed base at perhaps 100 million, of which maybe half have notifications enabled." },
      { label: "Move 2", text: "Apply frequency, typically one to three pushes a day per eligible user across campaigns." },
      { label: "Move 3", text: "Apply delivery rate, since dormant devices and uninstalls silently absorb a large share." },
      { label: "Move 4", text: "Apply open rate, typically low single digits for promotional pushes in India." },
      { label: "Check", text: "Note the cost of over-sending: disabled notifications are permanent, which is the real product constraint." },
    ],
    pitfalls: [
      "Reporting sends as if they were impressions.",
      "Assuming every install can receive a push.",
      "Ignoring that frequency and opt-out rate are directly linked.",
    ],
  },
  {
    slug: "ecommerce-searches-per-second-peak",
    shape: "guesstimate",
    title: "How many searches does an e-commerce app handle per second at peak?",
    type: "Concurrency",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 20,000 to 60,000 searches a second at a sale peak, against a few thousand on a normal day.",
    hints: ["Sale peaks are an order of magnitude above normal. The peak is the whole question."],
    moves: [
      { label: "Move 1", text: "Size normal load. Daily sessions in the tens of millions, each with several searches, spread unevenly." },
      { label: "Move 2", text: "Convert to a normal peak-hour rate, which is several times the daily average." },
      { label: "Move 3", text: "Apply the sale multiplier. Festive sale opening minutes can be ten to twenty times normal peak." },
      { label: "Move 4", text: "Note that traffic bunches into the first minutes of a sale, which is the actual engineering problem." },
      { label: "Check", text: "Infrastructure is sized for the worst minute of the year, not the average second. Say that." },
    ],
    pitfalls: [
      "Dividing daily searches by 86,400.",
      "Ignoring the sale-opening spike, which defines capacity planning.",
      "Confusing page views with search queries.",
    ],
  },
  {
    slug: "live-cricket-stream-bandwidth-india",
    shape: "guesstimate",
    title: "Estimate the bandwidth a live cricket stream consumes in India.",
    type: "Scale estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 5 to 20 terabits per second at peak concurrency for a major match.",
    hints: ["Multiply concurrent viewers by per-stream bitrate. Both numbers need care."],
    moves: [
      { label: "Move 1", text: "Size peak concurrency, which for a major Indian match can reach tens of millions of simultaneous viewers." },
      { label: "Move 2", text: "Apply bitrate. Mobile streams may run 0.5 to 2 Mbps, higher-quality streams several times that." },
      { label: "Move 3", text: "Weight the mix, since most Indian viewing is mobile at lower bitrates." },
      { label: "Move 4", text: "Multiply out to total throughput, and note this is served through CDN edges rather than from origin." },
      { label: "Check", text: "Compare against India's total internet capacity. A single match consuming a visible share of it is the correct and striking answer." },
    ],
    pitfalls: [
      "Using desktop-quality bitrate for a mobile-first audience.",
      "Ignoring adaptive bitrate, which lowers quality under congestion.",
      "Treating total viewers as concurrent viewers.",
    ],
  },
  {
    slug: "otps-sent-india-daily",
    shape: "guesstimate",
    title: "How many OTPs are sent in India in a day?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 300 to 600 million, driven by payments, logins and delivery confirmations.",
    hints: ["Enumerate the use cases first. Payments alone will not get you there."],
    moves: [
      { label: "Move 1", text: "List the sources: card payments, net banking, app logins, delivery confirmations, and account changes." },
      { label: "Move 2", text: "Size the largest. Card and net banking transactions alone run into the hundreds of millions daily." },
      { label: "Move 3", text: "Add logins and re-verifications, which are frequent given short session lifetimes in Indian apps." },
      { label: "Move 4", text: "Add retries, since a meaningful share of OTPs are resent after delivery failure or timeout." },
      { label: "Check", text: "Note that UPI PIN transactions do not use OTP, which is a large volume correctly excluded." },
    ],
    pitfalls: [
      "Including UPI transactions, which authenticate differently.",
      "Forgetting resends, which are a large share of total sends.",
      "Missing non-payment use cases entirely.",
    ],
  },
  {
    slug: "food-delivery-mumbai-rainy-evening",
    shape: "guesstimate",
    title: "Estimate food delivery orders in Mumbai on a rainy evening.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 250,000 to 400,000 orders, with demand well above what rider supply can actually serve.",
    hints: ["Rain lifts demand and cuts rider availability. The completed number is supply-limited."],
    moves: [
      { label: "Move 1", text: "Set a baseline evening. Mumbai might see 200,000 to 300,000 dinner orders on a normal day." },
      { label: "Move 2", text: "Apply the rain uplift on demand, which can be 30 to 50% as people stop going out." },
      { label: "Move 3", text: "Apply the rider constraint. Fewer riders work, and each takes longer per delivery in flooded traffic." },
      { label: "Move 4", text: "Conclude that fulfilled orders rise less than demand, with delivery times stretching and cancellations rising." },
      { label: "Check", text: "The interesting metric is unserved demand, which is what surge pricing and longer ETAs are managing." },
    ],
    pitfalls: [
      "Applying a demand uplift with no supply constraint.",
      "Ignoring longer delivery times, which reduce orders per rider.",
      "Missing cancellations, which spike in exactly these conditions.",
    ],
  },
  {
    slug: "cloud-backup-photos-indian-users",
    shape: "guesstimate",
    title: "How many photos does a cloud backup service store for Indian users?",
    type: "Scale estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Tens of billions of photos, translating to single-digit exabytes of storage.",
    hints: ["Free tier limits shape this heavily. Most users never exceed them."],
    moves: [
      { label: "Move 1", text: "Size users with backup enabled, perhaps 200 to 300 million Indian smartphone users." },
      { label: "Move 2", text: "Estimate photos per user. Phone galleries commonly hold a few thousand images accumulated over years." },
      { label: "Move 3", text: "Apply the backed-up share, constrained by free tier limits that most users hit and stop at." },
      { label: "Move 4", text: "Convert to storage using 2 to 4 MB per photo, after compression applied by the service." },
      { label: "Check", text: "Note that the free tier cap, not user behaviour, is what actually bounds this number." },
    ],
    pitfalls: [
      "Ignoring free tier limits, which cap most users' contribution.",
      "Using uncompressed file sizes.",
      "Assuming every smartphone user has cloud backup enabled.",
    ],
  },
  {
    slug: "payment-gateway-transactions-sale-day",
    shape: "guesstimate",
    title: "Estimate daily transactions on a payments gateway during a sale.",
    type: "Concurrency",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 20 to 50 million transactions on the day, with the first hour carrying a disproportionate share.",
    hints: ["The daily total matters less than the worst minute. Size both."],
    moves: [
      { label: "Move 1", text: "Size normal daily volume for a large gateway, in the low millions of transactions." },
      { label: "Move 2", text: "Apply the sale multiplier, since festive sale days can be five to ten times normal." },
      { label: "Move 3", text: "Model the intraday shape. Sale openings and midnight deals create extreme, short spikes." },
      { label: "Move 4", text: "Convert the peak minute into transactions per second, which is the number capacity is built for." },
      { label: "Check", text: "Add failure and retry traffic, which rises exactly when the system is most loaded and compounds the problem." },
    ],
    pitfalls: [
      "Reporting only the daily total, which hides the real engineering challenge.",
      "Ignoring retries, which amplify load during degradation.",
      "Assuming a smooth intraday curve on a sale day.",
    ],
  },
  {
    slug: "bike-taxi-rides-hyderabad-daily",
    shape: "guesstimate",
    title: "How many rides does a bike-taxi app complete in Hyderabad daily?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 150,000 to 300,000 rides, mostly short commute trips priced well below cabs.",
    hints: ["Bike taxis serve short trips. Size the trip length band they compete in."],
    moves: [
      { label: "Move 1", text: "Size the city's daily motorised trips at several million for a population near 10 million." },
      { label: "Move 2", text: "Isolate the addressable band, short solo trips of 2 to 7 kilometres." },
      { label: "Move 3", text: "Apply app penetration in that band, competing against autos, buses and personal two-wheelers." },
      { label: "Move 4", text: "Check supply. Rider count multiplied by trips per rider per day gives an independent estimate to compare." },
      { label: "Check", text: "Note regulatory risk. Bike taxis are restricted in several Indian states, which caps the market abruptly." },
    ],
    pitfalls: [
      "Sizing against all city trips rather than the short-trip band.",
      "Ignoring the personal two-wheeler, which is the real competitor.",
      "Missing the regulatory constraint entirely.",
    ],
  },
  {
    slug: "dating-app-users-india",
    shape: "guesstimate",
    title: "Estimate the number of Indian users on a dating app.",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 15 to 30 million installs but far fewer monthly actives, with a heavily skewed gender ratio.",
    hints: ["The gender ratio is the defining feature of this market and changes the usable number substantially."],
    moves: [
      { label: "Move 1", text: "Size the addressable population: urban, English-comfortable, smartphone-owning adults aged 18 to 35." },
      { label: "Move 2", text: "Apply cultural adoption, which is far lower than Western penetration rates." },
      { label: "Move 3", text: "Split by gender. Indian dating apps run heavily male-skewed, often three or four to one." },
      { label: "Move 4", text: "Convert installs to monthly actives, applying high churn since successful users leave and unsuccessful ones give up." },
      { label: "Check", text: "The usable market size is set by the smaller side of the marketplace, which is the real constraint." },
    ],
    pitfalls: [
      "Applying Western penetration rates.",
      "Ignoring the gender ratio, which caps effective liquidity.",
      "Treating installs as active users in a category with extreme churn.",
    ],
  },
  {
    slug: "job-portal-resumes-per-day",
    shape: "guesstimate",
    title: "How many resumes does a job portal receive per day in India?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 50,000 to 150,000 new or updated profiles a day, plus millions of applications against existing ones.",
    hints: ["New resumes and job applications are different events. Say which you are counting."],
    moves: [
      { label: "Move 1", text: "Size the annual entrant pool: graduates and job changers, together tens of millions a year." },
      { label: "Move 2", text: "Apply portal usage, higher for white-collar and IT roles than for blue-collar work." },
      { label: "Move 3", text: "Convert to daily new profile creation, then add updates from existing users who are job hunting." },
      { label: "Move 4", text: "Separately size applications, which are far more numerous since one candidate applies to many roles." },
      { label: "Check", text: "Note seasonality around campus placement and appraisal cycles, which create large predictable spikes." },
    ],
    pitfalls: [
      "Confusing profile creation with application volume.",
      "Ignoring that a single candidate submits many applications.",
      "Assuming flat volume in a strongly seasonal market.",
    ],
  },
  {
    slug: "real-estate-portal-listings",
    shape: "guesstimate",
    title: "Estimate the number of live listings on an Indian real estate portal.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 3 million live listings, with heavy duplication across brokers inflating the raw count.",
    hints: ["Duplicate listings are endemic here. Distinguish listings from actual properties."],
    moves: [
      { label: "Move 1", text: "Size annual transactions across rent and sale in major cities, in the millions." },
      { label: "Move 2", text: "Convert to live inventory using time on market, typically one to three months." },
      { label: "Move 3", text: "Apply portal share, which is high in metros and much lower in smaller towns." },
      { label: "Move 4", text: "Inflate for duplication. The same flat is often listed by several brokers under different entries." },
      { label: "Check", text: "Note that stale listings persist long after the property is gone, which inflates the number further." },
    ],
    pitfalls: [
      "Reporting listings as unique properties.",
      "Ignoring stale inventory that was never removed.",
      "Treating rent and sale markets as one, when their turnover rates differ hugely.",
    ],
  },
  {
    slug: "songs-streamed-india-daily",
    shape: "guesstimate",
    title: "How many songs are streamed in India per day?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 1.5 to 3 billion streams a day, overwhelmingly on ad-funded free tiers.",
    hints: ["Free listeners dominate volume. Paid subscribers dominate revenue. Do not mix them up."],
    moves: [
      { label: "Move 1", text: "Size music app users at roughly 200 to 250 million monthly actives across platforms." },
      { label: "Move 2", text: "Apply daily active share, perhaps 40%, giving under 100 million daily listeners." },
      { label: "Move 3", text: "Apply listening time, perhaps 45 to 90 minutes, and convert to tracks at roughly four minutes each." },
      { label: "Move 4", text: "Adjust for skips, which count as streams only past a threshold, typically 30 seconds." },
      { label: "Check", text: "Note the revenue inversion. Enormous stream volume against very low per-stream payout is the defining economics." },
    ],
    pitfalls: [
      "Ignoring the skip threshold that defines a counted stream.",
      "Applying Western per-user listening time.",
      "Conflating volume share with revenue share.",
    ],
  },
  {
    slug: "photo-app-india-annual-storage",
    shape: "guesstimate",
    title: "Estimate the storage a photo-sharing app needs for one year of Indian uploads.",
    type: "Scale estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Several petabytes of original uploads, multiplied a few times over by the derived sizes served to devices.",
    hints: ["Every upload is stored several times over at different resolutions. That multiplier is the answer."],
    moves: [
      { label: "Move 1", text: "Size uploaders. Of hundreds of millions of users, only a fraction post, and posting frequency is skewed." },
      { label: "Move 2", text: "Estimate uploads per year, weighting heavy creators separately from occasional posters." },
      { label: "Move 3", text: "Apply original file size after client-side compression, typically 1 to 3 MB." },
      { label: "Move 4", text: "Multiply for derivatives. Thumbnails, feed sizes and full-screen versions add several times the original." },
      { label: "Check", text: "Add video, which even at low posting rates dominates storage because per-item size is enormously larger." },
    ],
    pitfalls: [
      "Storing one copy per upload in your model when services store many.",
      "Ignoring video, which dominates bytes even at low volumes.",
      "Applying a uniform posting rate across a heavily skewed user base.",
    ],
  },
  {
    slug: "telecom-app-support-tickets",
    shape: "guesstimate",
    title: "How many support tickets does a telecom app generate daily?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 100,000 to 300,000 tickets a day, spiking sharply around billing dates and network incidents.",
    hints: ["Contact rate per subscriber is small but the subscriber base is enormous. Both matter."],
    moves: [
      { label: "Move 1", text: "Size the base at perhaps 300 to 400 million subscribers for a large Indian operator." },
      { label: "Move 2", text: "Apply digital engagement, since only a portion use the app rather than calling or visiting a store." },
      { label: "Move 3", text: "Apply monthly contact rate, typically low single digit percent, then convert to daily." },
      { label: "Move 4", text: "Add event-driven spikes. A network outage can multiply volume within minutes." },
      { label: "Check", text: "Note the intent mix. Recharge and plan queries dominate, which is what makes self-service deflection effective." },
    ],
    pitfalls: [
      "Applying a contact rate suited to a premium service to a mass-market telecom base.",
      "Ignoring outage spikes, which drive staffing decisions.",
      "Not separating app tickets from total contacts across all channels.",
    ],
  },
  {
    slug: "shared-scooter-unlocks-daily",
    shape: "guesstimate",
    title: "Estimate the daily unlocks a shared scooter service sees in an Indian city.",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 3 to 8 rides per vehicle per day in a well-run operation, giving tens of thousands of unlocks citywide.",
    hints: ["Rides per vehicle per day is the metric the whole business turns on. Start there."],
    moves: [
      { label: "Move 1", text: "Size the fleet, perhaps 5,000 to 15,000 vehicles in a major city deployment." },
      { label: "Move 2", text: "Apply availability. Battery swaps, damage and redistribution keep a share of the fleet off the road." },
      { label: "Move 3", text: "Apply rides per available vehicle per day, which is the industry's central productivity metric." },
      { label: "Move 4", text: "Weight by location. Vehicles near metro stations and offices turn far more than those in residential areas." },
      { label: "Check", text: "Note the break-even. Below roughly three rides per vehicle per day, most shared mobility unit economics fail." },
    ],
    pitfalls: [
      "Assuming the whole fleet is available every day.",
      "Ignoring redistribution cost, which grows with usage.",
      "Reporting unlocks without the per-vehicle figure, which is the only one that matters commercially.",
    ],
  },
  {
    slug: "quick-commerce-peak-orders-per-second",
    shape: "guesstimate",
    title: "How many orders per second does a quick commerce app peak at?",
    type: "Concurrency",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 200 to 600 orders a second at an evening peak, far higher during festival hours.",
    hints: ["Quick commerce demand is extraordinarily peaked. The evening window is the whole story."],
    moves: [
      { label: "Move 1", text: "Size daily orders nationally, in the low millions for a leading platform." },
      { label: "Move 2", text: "Apply the intraday curve. Evening hours may carry 40% of the day in a three-hour window." },
      { label: "Move 3", text: "Convert to a per-second rate across that window, then apply a within-peak multiplier." },
      { label: "Move 4", text: "Note the physical constraint. Dark store picking capacity binds before software does." },
      { label: "Check", text: "The bottleneck is pickers and riders, not servers. Recognising that is the product insight here." },
    ],
    pitfalls: [
      "Treating this as purely a software scaling question.",
      "Averaging orders across the full day.",
      "Ignoring that each dark store has a hard hourly throughput ceiling.",
    ],
  },
  {
    slug: "short-video-daily-users-india",
    shape: "guesstimate",
    title: "Estimate the number of Indians watching short video daily.",
    type: "Usage estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 250 to 350 million daily viewers, averaging well over an hour each.",
    hints: ["This is now close to the whole smartphone base. Start there and subtract."],
    moves: [
      { label: "Move 1", text: "Size smartphone users at roughly 700 million with regular internet access." },
      { label: "Move 2", text: "Apply short video reach, which across all platforms is now the majority of internet users." },
      { label: "Move 3", text: "Convert monthly reach to daily using stickiness, which for short video is unusually high." },
      { label: "Move 4", text: "Note overlap. The same person uses several short video products, so platform figures cannot be summed." },
      { label: "Check", text: "Multiply by time per user to get total attention hours, which is the number advertisers actually buy." },
    ],
    pitfalls: [
      "Summing user counts across platforms, which double counts heavily.",
      "Ignoring that short video reaches beyond the English-speaking internet.",
      "Reporting reach without time spent, which is the commercially meaningful measure.",
    ],
  },
  {
    slug: "weather-app-api-calls-daily",
    shape: "guesstimate",
    title: "How many API calls does a weather app make per day?",
    type: "Scale estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Far fewer than users times opens, because caching by location collapses most of the demand.",
    hints: ["Weather is identical for everyone in a location. Caching is the entire answer."],
    moves: [
      { label: "Move 1", text: "Size naive demand: daily active users multiplied by app opens and background refreshes." },
      { label: "Move 2", text: "Recognise the collapse. All users in one city share one forecast, so cache by location, not by user." },
      { label: "Move 3", text: "Size the real upstream calls: number of distinct locations multiplied by refresh frequency." },
      { label: "Move 4", text: "Add widget and notification refreshes, which run on schedules rather than on user action." },
      { label: "Check", text: "The gap between naive and cached demand is often three orders of magnitude, which is the point of the question." },
    ],
    pitfalls: [
      "Multiplying users by opens and stopping there.",
      "Ignoring background refresh, which can exceed foreground usage.",
      "Missing that cache granularity is a product decision with a large cost consequence.",
    ],
  },
  {
    slug: "recommendation-model-training-data",
    shape: "guesstimate",
    title: "Estimate the training data volume for an Indian retailer's recommendation model.",
    type: "Scale estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Tens of terabytes of raw events, reducing to a far smaller feature set after sampling and aggregation.",
    hints: ["Raw event volume and useful training data differ enormously. Both numbers are worth stating."],
    moves: [
      { label: "Move 1", text: "Size the events: views, clicks, add-to-cart and purchases, with views dominating by orders of magnitude." },
      { label: "Move 2", text: "Apply per-event size, which is small, a few hundred bytes, but multiplied by billions of events." },
      { label: "Move 3", text: "Apply the retention window. Most recommendation models train on recent behaviour, not on all history." },
      { label: "Move 4", text: "Reduce to features. Aggregated user and item features are far smaller than the raw event log." },
      { label: "Check", text: "Note the class imbalance. Purchases are rare relative to views, which shapes sampling more than raw volume does." },
    ],
    pitfalls: [
      "Assuming all historical data is used for training.",
      "Ignoring that raw logs and training features are different artefacts.",
      "Missing the imbalance between views and purchases.",
    ],
  },
  {
    slug: "stadium-wifi-devices-during-match",
    shape: "guesstimate",
    title: "How many devices connect to a stadium's wifi during a match?",
    type: "Concurrency",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 30 to 50% of attendees connect, but usage spikes into a few specific moments rather than spreading evenly.",
    hints: ["Everyone uploads at the same instant. Simultaneity, not total connections, is the problem."],
    moves: [
      { label: "Move 1", text: "Size attendance at 40,000 to 60,000 for a large Indian stadium." },
      { label: "Move 2", text: "Apply connection rate, limited by people who already have adequate mobile data." },
      { label: "Move 3", text: "Model usage bursts. Wickets, sixes and innings breaks trigger simultaneous uploads by tens of thousands." },
      { label: "Move 4", text: "Convert to bandwidth. Upload is the constraint, since video shares are far heavier than browsing." },
      { label: "Check", text: "Note that stadium wifi is designed for the worst 30 seconds of the match, not the average over three hours." },
    ],
    pitfalls: [
      "Sizing for average load rather than the burst.",
      "Assuming download dominates, when it is upload that saturates.",
      "Ignoring that mobile networks in the stadium compete for the same users.",
    ],
  },
  {
    slug: "failed-payment-transactions-india-daily",
    shape: "guesstimate",
    title: "Estimate the daily volume of failed payment transactions in India.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 5 to 20 million failures a day, with a small percentage failure rate applied to an enormous base.",
    hints: ["A tiny failure rate on a billion transactions is still a very large number."],
    moves: [
      { label: "Move 1", text: "Size total daily digital transactions, including UPI, cards and net banking, at roughly a billion." },
      { label: "Move 2", text: "Apply failure rates by rail. UPI failure rates are low single digit percent, cards somewhat higher." },
      { label: "Move 3", text: "Split by cause: bank downtime, insufficient funds, technical decline and user abandonment." },
      { label: "Move 4", text: "Add retries, since a failed payment is usually attempted again within minutes." },
      { label: "Check", text: "Note the cost. Each failure has a support and abandonment cost, which is why small rate improvements matter enormously." },
    ],
    pitfalls: [
      "Treating all payment rails as having the same failure rate.",
      "Counting retries as separate failures without saying so.",
      "Reporting the rate without the absolute number, which is what makes the point.",
    ],
  },
  {
    slug: "banking-app-month-end-usage",
    shape: "guesstimate",
    title: "How many people use a banking app in the last three days of a month?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Two to three times the normal daily rate, driven by salary credit, bill payment and rent transfers.",
    hints: ["Banking usage is not smooth. Month end is a genuine, predictable spike."],
    moves: [
      { label: "Move 1", text: "Establish the baseline. A large bank's app might see 10 to 15% of digitally active customers on a normal day." },
      { label: "Move 2", text: "Identify month-end drivers: salary credits, rent, EMI, card bills and utility payments clustering together." },
      { label: "Move 3", text: "Apply the multiplier, roughly doubling or tripling daily actives across those three days." },
      { label: "Move 4", text: "Note the within-day peak, since salary credits arrive in a narrow window and everyone checks at once." },
      { label: "Check", text: "This is why banks schedule maintenance mid-month. The pattern is predictable enough to plan around." },
    ],
    pitfalls: [
      "Assuming smooth daily usage in a business with a strong monthly cycle.",
      "Ignoring that the spike is also intraday, not just across days.",
      "Confusing logins with transactions.",
    ],
  },
  {
    slug: "ecommerce-returns-processed-daily",
    shape: "guesstimate",
    title: "Estimate the number of returns an e-commerce platform processes daily.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 15 to 25% of orders in apparel and under 5% in electronics, so the mix decides the total.",
    hints: ["Return rates vary enormously by category. An overall average will mislead you."],
    moves: [
      { label: "Move 1", text: "Size daily orders for a large Indian platform, in the low millions." },
      { label: "Move 2", text: "Split by category, since apparel and footwear return at multiples of the rate for electronics or groceries." },
      { label: "Move 3", text: "Apply category return rates and weight by order mix." },
      { label: "Move 4", text: "Add cash-on-delivery refusals, which behave like returns and are a large Indian-specific factor." },
      { label: "Check", text: "Note the cost. Reverse logistics plus unsellable inventory makes returns a major profitability driver, not an operational footnote." },
    ],
    pitfalls: [
      "Applying one blended return rate across all categories.",
      "Ignoring delivery refusal on cash-on-delivery orders.",
      "Counting returns without their cost, which is the point of the question.",
    ],
  },
  {
    slug: "airline-customer-call-hours-daily",
    shape: "guesstimate",
    title: "How many hours of customer calls does an airline handle daily?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1,500 to 4,000 agent hours a day, dominated by disruption rather than routine booking.",
    hints: ["Routine bookings moved online years ago. What is left is disruption, which takes far longer per call."],
    moves: [
      { label: "Move 1", text: "Size daily passengers, perhaps 100,000 to 200,000 for a large Indian carrier." },
      { label: "Move 2", text: "Apply the contact rate, low for normal travel since most bookings and check-ins are self-service." },
      { label: "Move 3", text: "Apply handling time, longer for changes, refunds and disruption than for simple queries." },
      { label: "Move 4", text: "Add disruption events. One cancelled flight generates hundreds of long, emotionally difficult calls." },
      { label: "Check", text: "Staffing is driven by disruption variance, not by the average day, which is why call centres feel overwhelmed when weather turns." },
    ],
    pitfalls: [
      "Using a uniform handling time across query types.",
      "Sizing for the average day when staffing is a peak problem.",
      "Ignoring that self-service has already removed the easy volume.",
    ],
  },
  {
    slug: "kyc-verifications-india-daily",
    shape: "guesstimate",
    title: "Estimate the number of KYC verifications done in India per day.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 3 to 8 million verifications a day across banking, telecom, fintech and gig platforms.",
    hints: ["Enumerate the sectors that legally require it. The list is longer than it first appears."],
    moves: [
      { label: "Move 1", text: "List the sectors: bank accounts, mobile connections, demat accounts, wallets, lending and gig worker onboarding." },
      { label: "Move 2", text: "Size the largest. New mobile connections and bank accounts alone run into millions monthly." },
      { label: "Move 3", text: "Add re-verification, since periodic KYC refresh is mandated and adds a steady baseline." },
      { label: "Move 4", text: "Add failed and repeated attempts, which are common given document quality and name mismatches." },
      { label: "Check", text: "Note the drop-off. A large share of started verifications are never completed, which is a major product problem." },
    ],
    pitfalls: [
      "Counting only new customer onboarding and missing periodic re-verification.",
      "Ignoring repeat attempts after failure.",
      "Missing entire sectors such as gig platform onboarding.",
    ],
  },
  {
    slug: "school-communication-app-messages",
    shape: "guesstimate",
    title: "How many messages does a school communication app send per day?",
    type: "Usage estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 5 to 15 messages per student per school day, heavily concentrated at two times of day.",
    hints: ["One teacher action fans out to an entire class. That multiplier defines the volume."],
    moves: [
      { label: "Move 1", text: "Size the base: students on the platform, each with one or two parent accounts attached." },
      { label: "Move 2", text: "Identify message types: attendance, homework, circulars, fee reminders and emergency alerts." },
      { label: "Move 3", text: "Apply fan-out. A single teacher post reaches 40 students, which is 40 to 80 deliveries." },
      { label: "Move 4", text: "Apply the school calendar, since volume falls to near zero on holidays and spikes at term boundaries." },
      { label: "Check", text: "Note the two daily peaks, morning attendance and end-of-day homework, which is what capacity must handle." },
    ],
    pitfalls: [
      "Counting teacher actions rather than delivered messages.",
      "Ignoring that each student may have multiple parent recipients.",
      "Assuming uniform volume across the calendar year.",
    ],
  },
  {
    slug: "top-ten-app-daily-downloads-india",
    shape: "guesstimate",
    title: "Estimate the daily downloads of a top-ten Indian app.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 100,000 to 500,000 installs a day, with a large share being reinstalls rather than new users.",
    hints: ["Reinstalls and device changes are a big share of installs. Gross downloads overstate user growth."],
    moves: [
      { label: "Move 1", text: "Size the addressable base at several hundred million smartphone users." },
      { label: "Move 2", text: "Note saturation. A top-ten app already has most of its addressable users, so growth is incremental." },
      { label: "Move 3", text: "Add device replacement. Millions of new phones each month trigger reinstalls of the same apps." },
      { label: "Move 4", text: "Add uninstall-reinstall cycles, common where storage is tight on entry-level devices." },
      { label: "Check", text: "Downloads and net user growth are barely related for a mature app. Saying that is the answer the question wants." },
    ],
    pitfalls: [
      "Treating downloads as new users.",
      "Ignoring device replacement as an install driver.",
      "Missing that storage pressure causes churn on low-end phones.",
    ],
  },
  {
    slug: "checkout-abandonment-india-daily",
    shape: "guesstimate",
    title: "How many people abandon checkout on an Indian e-commerce site daily?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 60 to 75% of carts are abandoned, so abandonment volume far exceeds completed order volume.",
    hints: ["Abandonment happens at several distinct steps. Locating which one matters more than the total."],
    moves: [
      { label: "Move 1", text: "Size sessions and cart creation, since only a fraction of visitors add anything to a cart." },
      { label: "Move 2", text: "Apply stage-wise drop: cart to address, address to payment, payment to success." },
      { label: "Move 3", text: "Note the Indian specifics. Payment failure and cash-on-delivery preference create drop points unique to this market." },
      { label: "Move 4", text: "Separate genuine abandonment from technical failure, which look identical in funnel data but need opposite fixes." },
      { label: "Check", text: "Recovering one point at the payment step is worth more than large gains earlier, since intent is highest there." },
    ],
    pitfalls: [
      "Reporting one abandonment number with no stage breakdown.",
      "Confusing payment failure with user abandonment.",
      "Applying Western funnel benchmarks to an Indian checkout.",
    ],
  },
  {
    slug: "wallet-topups-during-ipl-match",
    shape: "guesstimate",
    title: "How many wallet top-ups happen during an IPL match?",
    type: "Concurrency",
    difficulty: 2,
    minutes: 20,
    answer: "Hundreds of thousands within the match window, with extreme spikes at innings break and in the final overs.",
    hints: ["The spike shape follows the game, not the clock. Model the match, not the hours."],
    moves: [
      { label: "Move 1", text: "Size the audience engaging with fantasy and gaming platforms during a match, in the tens of millions." },
      { label: "Move 2", text: "Apply the paying share, a small fraction, but a fraction of a very large number." },
      { label: "Move 3", text: "Model the timing. Deadlines before toss and the innings break create sharp, predictable surges." },
      { label: "Move 4", text: "Add in-play spikes when the match turns, driving late top-ups within a few minutes." },
      { label: "Check", text: "Payment failure at exactly these moments is the worst possible outcome, which is why this load pattern gets so much engineering attention." },
    ],
    pitfalls: [
      "Spreading volume evenly across the match duration.",
      "Ignoring the contest deadline, which is the single largest spike.",
      "Treating this as a payments question rather than a peak-load question.",
    ],
  },
  {
    slug: "digital-insurance-claims-india-daily",
    shape: "guesstimate",
    title: "Estimate the number of insurance claims filed digitally in India per day.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 100,000 to 250,000 a day, dominated by health and motor rather than life.",
    hints: ["Claim frequency varies enormously by line. Size health and motor separately from life."],
    moves: [
      { label: "Move 1", text: "Size policies in force by line: motor is compulsory and huge, health growing fast, life large but rarely claimed." },
      { label: "Move 2", text: "Apply claim frequency. Motor runs a few percent a year, health somewhat higher, life a fraction of a percent." },
      { label: "Move 3", text: "Convert annual claims to daily, then apply the digital share, which is rising but incomplete." },
      { label: "Move 4", text: "Add cashless hospital authorisations, which behave like claims operationally and are high volume." },
      { label: "Check", text: "Note seasonality. Monsoon drives motor claims and seasonal illness drives health claims, so volume is not flat." },
    ],
    pitfalls: [
      "Applying one claim frequency across all insurance lines.",
      "Forgetting cashless authorisations, which dominate health operations.",
      "Assuming the digital share is complete when much is still paper.",
    ],
  },
  {
    slug: "logistics-pin-codes-to-serve",
    shape: "guesstimate",
    title: "How many pin codes does a logistics app need to serve?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "India has roughly 19,000 pin codes, but the top 10% carry the large majority of e-commerce volume.",
    hints: ["Coverage and volume are different goals. The tail costs far more per parcel than it earns."],
    moves: [
      { label: "Move 1", text: "Establish the total, roughly 19,000 pin codes nationally." },
      { label: "Move 2", text: "Apply the volume distribution. Urban pin codes carry a hugely disproportionate share of parcels." },
      { label: "Move 3", text: "Cost the tail. Remote pin codes may see a handful of parcels a week, making dedicated coverage uneconomic." },
      { label: "Move 4", text: "Consider partnership. Postal and franchise networks serve the tail more cheaply than owned operations can." },
      { label: "Check", text: "The real answer is that near-full coverage is a marketing claim, delivered through partners rather than owned capacity." },
    ],
    pitfalls: [
      "Treating all pin codes as equally worth serving.",
      "Ignoring the partner model that makes tail coverage possible.",
      "Confusing serviceable pin codes with pin codes served daily.",
    ],
  },
  {
    slug: "ads-served-indian-news-site-daily",
    shape: "guesstimate",
    title: "Estimate the number of ads served on an Indian news site daily.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 50 to 200 million impressions a day for a large publisher, though viewable impressions are far fewer.",
    hints: ["Served and viewable are different. The gap between them is the whole revenue story."],
    moves: [
      { label: "Move 1", text: "Size daily sessions, in the tens of millions for a large Indian news property." },
      { label: "Move 2", text: "Apply pages per session, typically low for news since much traffic is single-article from social." },
      { label: "Move 3", text: "Apply ad slots per page, commonly four to eight including sticky and in-article units." },
      { label: "Move 4", text: "Apply viewability. A large share of served impressions are never actually seen, and only viewable ones are paid for at full rate." },
      { label: "Check", text: "Multiply by realistic CPM to reach revenue, and note how low Indian display rates are compared with global ones." },
    ],
    pitfalls: [
      "Reporting served impressions as though all were monetised.",
      "Assuming multiple pages per session for social-referred news traffic.",
      "Applying Western CPM rates to Indian inventory.",
    ],
  },
  {
    slug: "bank-two-factor-sms-monthly",
    shape: "guesstimate",
    title: "How many authentication SMS does a large bank send per month?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 200 to 500 million messages a month, a material and often overlooked cost line.",
    hints: ["Multiply by the per-SMS cost at the end. The rupee number is what makes this interesting."],
    moves: [
      { label: "Move 1", text: "Size digitally active customers, perhaps 20 to 30 million for a large Indian bank." },
      { label: "Move 2", text: "Apply transaction frequency requiring an OTP, several times a month per active customer." },
      { label: "Move 3", text: "Add non-transactional messages: login alerts, balance notifications and mandatory intimations." },
      { label: "Move 4", text: "Add failures and resends, which are common with network delays and add a meaningful percentage." },
      { label: "Check", text: "Multiply by cost per SMS. The annual figure runs into hundreds of crores, which is why banks push app-based authentication." },
    ],
    pitfalls: [
      "Counting only OTPs and ignoring alert messages, which are often larger in volume.",
      "Forgetting resends.",
      "Giving the volume without the cost, which is the actual insight.",
    ],
  },
  {
    slug: "ride-hailing-active-drivers-delhi",
    shape: "guesstimate",
    title: "Estimate the daily active drivers on a ride-hailing app in Delhi.",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 50,000 to 90,000 drivers active on a given day, far fewer than the number registered.",
    hints: ["Registered and active differ by a factor of two or three. Say which you mean."],
    moves: [
      { label: "Move 1", text: "Size daily rides in the city, perhaps 600,000 to 900,000 across platforms." },
      { label: "Move 2", text: "Apply rides per driver per day, typically 12 to 18 for a full shift in heavy traffic." },
      { label: "Move 3", text: "Divide to get drivers required, then gross up for partial shifts and multi-app drivers." },
      { label: "Move 4", text: "Note that supply is highly elastic. Incentives move driver hours far more than driver count does." },
      { label: "Check", text: "The peak-hour supply gap is the operationally important number, not the daily total." },
    ],
    pitfalls: [
      "Using registered drivers as active drivers.",
      "Ignoring drivers who run several apps simultaneously.",
      "Sizing on daily totals when supply shortfalls happen at specific hours.",
    ],
  },
  {
    slug: "irctc-tatkal-window-tickets",
    shape: "guesstimate",
    title: "How many tickets are sold in the IRCTC Tatkal window?",
    type: "Concurrency",
    difficulty: 3,
    minutes: 20,
    answer: "A few lakh tickets against many times that in simultaneous attempts, compressed into the opening minutes.",
    hints: ["Inventory is fixed and tiny. The interesting number is attempts, not sales."],
    moves: [
      { label: "Move 1", text: "Size the inventory. Tatkal quota is a small fixed share of seats on each train." },
      { label: "Move 2", text: "Multiply across trains running the next day to get total tickets available in the window." },
      { label: "Move 3", text: "Size the demand side. Attempts vastly exceed inventory, especially on festival routes." },
      { label: "Move 4", text: "Model the concurrency. Nearly all attempts arrive within the first two minutes of opening." },
      { label: "Check", text: "This is a fixed-inventory flash sale, not a normal booking system. That framing is what the question is testing." },
    ],
    pitfalls: [
      "Sizing demand without recognising inventory is hard-capped.",
      "Spreading attempts across the hour rather than the opening minutes.",
      "Ignoring bots and agents, which are a large share of attempts.",
    ],
  },
  {
    slug: "food-app-ratings-collected-daily",
    shape: "guesstimate",
    title: "Estimate the number of ratings a food delivery app collects per day.",
    type: "Usage estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 20 to 35% of orders get rated, so several hundred thousand ratings a day, skewed toward extremes.",
    hints: ["Response rate is the whole answer. And the people who respond are not representative."],
    moves: [
      { label: "Move 1", text: "Size daily orders at roughly 2 million for a large platform." },
      { label: "Move 2", text: "Apply response rate, which is decent when prompted immediately in-app but far from universal." },
      { label: "Move 3", text: "Split by prompt type. A one-tap star prompt gets far more responses than a written review request." },
      { label: "Move 4", text: "Note the bias. Very good and very bad experiences are rated far more often than adequate ones." },
      { label: "Check", text: "The distribution shape matters more than the count for any decision built on this data." },
    ],
    pitfalls: [
      "Assuming ratings represent the average experience.",
      "Treating star ratings and written reviews as the same response rate.",
      "Reporting volume with no view on selection bias.",
    ],
  },
  {
    slug: "upi-app-users-to-break-even",
    shape: "guesstimate",
    title: "How many users would a new UPI app need to break even?",
    type: "Cost estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Tens of millions of engaged users, because UPI itself earns nothing and the money must come from adjacent products.",
    hints: ["UPI transactions carry no merchant discount rate. The revenue has to come from somewhere else."],
    moves: [
      { label: "Move 1", text: "Establish the revenue problem. Person-to-person UPI is free by regulation, so payments alone earn nothing." },
      { label: "Move 2", text: "Identify the actual revenue: lending, insurance, mutual funds, bill payments and merchant services." },
      { label: "Move 3", text: "Size the cost base: technology, transaction infrastructure, customer acquisition and support." },
      { label: "Move 4", text: "Compute revenue per user from cross-sell conversion, which is low single digit percent." },
      { label: "Check", text: "The answer is that UPI is a customer acquisition channel, not a business. Saying that is the point." },
    ],
    pitfalls: [
      "Assuming payment volume translates into payment revenue.",
      "Ignoring acquisition cost, which for Indian fintech has been enormous.",
      "Missing that the whole model depends on cross-sell conversion.",
    ],
  },
  {
    slug: "lending-app-documents-monthly",
    shape: "guesstimate",
    title: "Estimate the documents processed by a digital lending app monthly.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Several million document uploads a month, most from applications that are never approved.",
    hints: ["Most applications are rejected, but every one of them uploads documents first."],
    moves: [
      { label: "Move 1", text: "Size applications, perhaps several hundred thousand a month for a mid-size lender." },
      { label: "Move 2", text: "Apply documents per application: identity, address, income proof and bank statements, typically five to eight files." },
      { label: "Move 3", text: "Add re-uploads, which are frequent because of poor image quality and rejected formats." },
      { label: "Move 4", text: "Note that approval rate is low, so most processing effort produces no loan at all." },
      { label: "Check", text: "That rejection ratio is the real cost driver. Cheap early screening is worth more than better document processing." },
    ],
    pitfalls: [
      "Sizing from approved loans rather than from applications.",
      "Ignoring re-uploads, which can double the volume.",
      "Missing that processing cost is incurred regardless of approval.",
    ],
  },
  {
    slug: "notifications-before-users-disable",
    shape: "guesstimate",
    title: "How many notifications can an app send before users disable them?",
    type: "Usage estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly two to three promotional pushes a day is the practical ceiling, and the damage is permanent once crossed.",
    hints: ["Opt-out is irreversible in practice. That asymmetry should shape the whole answer."],
    moves: [
      { label: "Move 1", text: "Establish the baseline. Most users tolerate transactional notifications indefinitely but promotional ones far less." },
      { label: "Move 2", text: "Model the decay. Each additional daily push lifts opt-out rate non-linearly." },
      { label: "Move 3", text: "Value the loss. A disabled user is unreachable forever, so opt-out cost is the full lifetime of future messaging." },
      { label: "Move 4", text: "Compare against the gain. Each extra push has a low open rate, so incremental revenue is small." },
      { label: "Check", text: "The maths usually favours sending less. Growth teams routinely get this wrong because opt-out cost is deferred and invisible." },
    ],
    pitfalls: [
      "Optimising per-campaign opens without costing opt-outs.",
      "Treating transactional and promotional notifications as one category.",
      "Ignoring that the loss is permanent while the gain is one-off.",
    ],
  },
  {
    slug: "streaming-premiere-peak-concurrency",
    shape: "guesstimate",
    title: "Estimate peak concurrent viewers for an Indian streaming premiere.",
    type: "Concurrency",
    difficulty: 3,
    minutes: 20,
    answer: "A few million for a major film release, and tens of millions for a live cricket final.",
    hints: ["Live and on-demand behave completely differently. Say which you are sizing."],
    moves: [
      { label: "Move 1", text: "Distinguish the two. Live events force simultaneity, on-demand releases spread across hours and days." },
      { label: "Move 2", text: "For an on-demand premiere, size subscribers, the share watching on day one, and the spread across the evening." },
      { label: "Move 3", text: "For live, note that concurrency approaches the full interested audience at the climactic moment." },
      { label: "Move 4", text: "Add the free tier, which in India carries a large share of live sports viewership." },
      { label: "Check", text: "Infrastructure is built for the live peak. An on-demand premiere is a far easier engineering problem, which is worth saying." },
    ],
    pitfalls: [
      "Treating an on-demand release as if viewing were simultaneous.",
      "Ignoring the free tier in a market where it dominates live viewing.",
      "Reporting total viewers when the question asked for concurrency.",
    ],
  },
  {
    slug: "warehouses-needed-next-day-delivery",
    shape: "guesstimate",
    title: "How many warehouses does an e-commerce player need for next-day delivery?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 25 to 60 fulfilment centres to cover the demand that matters, sized by drive time rather than by geography.",
    hints: ["Next-day delivery is a drive-time problem. Draw radii around demand, not around the map."],
    moves: [
      { label: "Move 1", text: "Establish the constraint. Next-day requires the parcel to be within a few hours of drive time from a facility." },
      { label: "Move 2", text: "Map demand, which is heavily concentrated in the top 30 or so cities." },
      { label: "Move 3", text: "Place facilities to cover those clusters, accepting that remote regions will not get next-day service." },
      { label: "Move 4", text: "Split by facility type. Large fulfilment centres hold inventory, smaller sortation hubs handle the last leg." },
      { label: "Check", text: "The honest answer covers most orders, not most geography. Saying that distinction is what the question rewards." },
    ],
    pitfalls: [
      "Trying to cover the map rather than the demand.",
      "Treating all warehouses as the same type of facility.",
      "Ignoring that inventory placement, not warehouse count, decides whether next-day is actually achievable.",
    ],
  },
  {
    slug: "estimate-support-cost-per-user",
    shape: "guesstimate",
    title: "Estimate the annual customer support cost per user for a consumer app.",
    type: "Cost estimation",
    difficulty: 2,
    minutes: 20,
    answer: "A few rupees per user per year, since only a small fraction ever contact support, but the per-contact cost is high.",
    hints: ["Contact rate is tiny. Cost per contact is not. Both numbers matter."],
    moves: [
      { label: "Move 1", text: "Size the contact rate, typically low single digit percent of monthly active users." },
      { label: "Move 2", text: "Split by channel. Self-service costs almost nothing, chat costs more, voice costs most." },
      { label: "Move 3", text: "Apply cost per contact using agent salary divided by contacts handled per shift." },
      { label: "Move 4", text: "Divide total support cost by total users to reach the per-user figure." },
      { label: "Check", text: "Compare against revenue per user. In low-revenue consumer apps a small rise in contact rate erases the margin." },
    ],
    pitfalls: [
      "Applying a contact rate suited to a financial product to a casual app.",
      "Using one cost per contact across channels.",
      "Not comparing against revenue per user, which is what makes the number meaningful.",
    ],
  },
];
