import type { Question } from "./types";

// Product cases. Four shapes recur: diagnose, design, measure, prioritise.
export const PRODUCT_CASES: Question[] = [
  {
    slug: "reels-watch-time-drop",
    shape: "case",
    title: "Reels watch time in India dropped 8% week on week. Diagnose it.",
    type: "Root cause",
    difficulty: 3,
    minutes: 30,
    askedAt: "Meta",
    answer: "Most likely instrumentation or seasonality rather than product. Confirm by cutting the drop by app version and geography before acting.",
    hints: ["Before diagnosing, confirm the metric is real. Instrumentation breaks more often than behaviour changes."],
    moves: [
      { label: "Move 1", text: "Verify the data. Check whether a logging change, app release or pipeline failure lines up with the drop." },
      { label: "Move 2", text: "Decompose the metric. Watch time equals users times sessions times time per session. Only one usually moved." },
      { label: "Move 3", text: "Cut by dimension: platform, city tier, app version, network quality. A drop in one slice is a bug." },
      { label: "Move 4", text: "Check external causes, which in India means exams, festivals, cricket or a competitor launch." },
      { label: "Close", text: "Name the most likely cause, say what would confirm it, and say what you would do meanwhile." },
    ],
    pitfalls: [
      "Jumping to a product explanation before ruling out instrumentation.",
      "Listing every possible cause without committing to one.",
      "Failing to ask whether 8% is even outside normal weekly variance.",
    ],
  },
  {
    slug: "savings-product-gig-workers",
    shape: "case",
    title: "Design a savings product for gig workers inside a payments app.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    askedAt: "Razorpay",
    answer: "A percentage-of-payout auto-save with a short cooling period on withdrawal, judged on balance retained at 90 days.",
    hints: ["Start with the user's cash flow, not with the product. Gig income is daily and irregular."],
    moves: [
      { label: "Move 1", text: "Characterise the user. Income arrives daily, varies widely, and has no employer deduction to hook into." },
      { label: "Move 2", text: "Name the real job: a buffer for a bad week or a vehicle repair, not long-horizon wealth." },
      { label: "Move 3", text: "Design for the cash flow. Round-ups and a share of each payout beat a fixed monthly debit." },
      { label: "Move 4", text: "Solve withdrawal. Instant access destroys the buffer, a hard lock destroys trust." },
      { label: "Close", text: "Pick the metric. Balance retained after 90 days tells you far more than accounts opened." },
    ],
    pitfalls: [
      "Designing a wealth product for someone whose problem is next week's rent.",
      "Assuming a monthly cadence for someone paid daily.",
      "Measuring sign-ups rather than balance retained.",
    ],
  },
  {
    slug: "instamart-north-star-metric",
    shape: "case",
    title: "What is the North Star metric for a quick commerce app, and why that one?",
    type: "Metrics",
    difficulty: 2,
    minutes: 20,
    askedAt: "Swiggy",
    answer: "Weekly orders per retained user, guard-railed by on-time delivery rate.",
    hints: ["Test any candidate by asking what breaks if the team optimises it ruthlessly."],
    moves: [
      { label: "Move 1", text: "State what the product is for: replacing a small unplanned shop, which means habit and reliability." },
      { label: "Move 2", text: "Generate candidates: orders per week, gross merchandise value, monthly actives, retained weekly orderers." },
      { label: "Move 3", text: "Break each. GMV rewards discount-driven bulk buying. Monthly actives hide churn. Raw orders ignore reliability." },
      { label: "Move 4", text: "Land on weekly orders per retained user with an on-time guard rail that stops the team buying frequency with broken promises." },
      { label: "Close", text: "Say what you would watch alongside it. A single number with no counter-metric is how teams optimise into trouble." },
    ],
    pitfalls: [
      "Choosing revenue, which is an outcome rather than a lever.",
      "Picking a metric with no counter-metric.",
      "Confusing a company goal with a product North Star.",
    ],
  },
  {
    slug: "ab-test-clicks-up-retention-down",
    shape: "case",
    title: "An A/B test shows 4% more clicks and 2% less retention. Ship it?",
    type: "Experiment read",
    difficulty: 3,
    minutes: 25,
    askedAt: "Google",
    answer: "Do not ship. Retention compounds and clicks do not, and the test almost certainly ran too short to read retention.",
    hints: ["Check whether either result is significant before debating the trade-off."],
    moves: [
      { label: "Move 1", text: "Establish significance and duration. A retention reading from a one-week test is usually too early." },
      { label: "Move 2", text: "Convert both to the same currency. A click lift is worth something now, a retention loss compounds over a lifetime." },
      { label: "Move 3", text: "Look for the mechanism. A click gain with a retention loss usually means something got more prominent, not more useful." },
      { label: "Move 4", text: "Segment. If the loss is in new users and the gain in existing ones, this is a targeting decision." },
      { label: "Close", text: "Do not ship, and name the next test you would run instead." },
    ],
    pitfalls: [
      "Comparing percentages across metrics with different time horizons.",
      "Ignoring statistical power and treating both numbers as facts.",
      "Shipping because the primary metric moved up.",
    ],
  },
  {
    slug: "onboarding-first-time-internet-users",
    shape: "case",
    title: "Improve onboarding for first-time internet users on a shopping app.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    askedAt: "Meesho",
    answer: "Remove text dependence and defer every step that is not needed to see value. Language and literacy, not interface polish, are the barriers.",
    hints: ["Ask what this user cannot do, not what they might prefer. The constraints are literacy and trust."],
    moves: [
      { label: "Move 1", text: "Characterise the user. Possibly low literacy, unfamiliar with app conventions, and cautious about entering personal data." },
      { label: "Move 2", text: "Audit the current flow for text dependence, English defaults and steps demanded before any value is shown." },
      { label: "Move 3", text: "Redesign around images, voice and vernacular, with icons that mean something outside app convention." },
      { label: "Move 4", text: "Defer friction. Let them browse before registering, and ask for details only at the point they are needed." },
      { label: "Close", text: "Measure first-session product views rather than registration completion, since the goal is understanding, not signup." },
    ],
    pitfalls: [
      "Designing for a smartphone-literate user who is not the target.",
      "Front-loading registration before any value is demonstrated.",
      "Treating language as a translation problem rather than a comprehension one.",
    ],
  },
  {
    slug: "notification-opt-out-rising",
    shape: "case",
    title: "Notification opt-outs are rising sharply. What would you do?",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Cut promotional frequency and separate transactional from marketing channels. Opt-out is permanent, so the cost of over-sending is far larger than it appears.",
    hints: ["Ask whether the increase came from more messages or from worse ones."],
    moves: [
      { label: "Move 1", text: "Segment opt-outs by user tenure and by what message immediately preceded them." },
      { label: "Move 2", text: "Check frequency. A growth push that raised daily sends is the most common cause." },
      { label: "Move 3", text: "Check relevance. Poorly targeted campaigns drive opt-out faster than volume alone." },
      { label: "Move 4", text: "Value the loss properly. A disabled user is unreachable for their whole remaining lifetime." },
      { label: "Close", text: "Recommend a frequency cap with per-user relevance scoring, and name the campaign you would stop first." },
    ],
    pitfalls: [
      "Optimising campaign-level opens while ignoring cumulative opt-out.",
      "Treating transactional and promotional messaging as one stream.",
      "Not costing the permanent loss of a reachable user.",
    ],
  },
  {
    slug: "search-relevance-marketplace",
    shape: "case",
    title: "Sellers complain that marketplace search favours large brands. Respond.",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Check whether the ranking is genuinely biased or simply reflecting conversion. If it reflects conversion, the fix is seller tooling, not ranking changes.",
    hints: ["A complaint about fairness may be an accurate description of a ranking that is working correctly."],
    moves: [
      { label: "Move 1", text: "Establish what the ranking optimises. If it maximises conversion, popular listings naturally win." },
      { label: "Move 2", text: "Test for genuine bias by comparing conversion at equal exposure, which separates quality from position effects." },
      { label: "Move 3", text: "Weigh the marketplace health argument. If small sellers never gain exposure, supply diversity erodes over time." },
      { label: "Move 4", text: "Consider an exploration budget: a small share of impressions given to unproven listings to gather data." },
      { label: "Close", text: "Recommend measured exploration with a cap on the conversion cost you are willing to accept." },
    ],
    pitfalls: [
      "Changing ranking weights in response to complaints without measuring bias.",
      "Ignoring long-term supply health for short-term conversion.",
      "Treating exploration as free when it has a measurable revenue cost.",
    ],
  },
  {
    slug: "payment-failure-rate-rising",
    shape: "case",
    title: "Payment success rate fell from 94% to 88%. Find out why.",
    type: "Root cause",
    difficulty: 3,
    minutes: 30,
    answer: "Almost always a specific bank, rail or gateway degrading rather than a broad product change. Segment before hypothesising.",
    hints: ["Segment by rail, bank and gateway first. A blended rate hides the failure."],
    moves: [
      { label: "Move 1", text: "Split by payment method. UPI, cards, net banking and wallets fail for entirely different reasons." },
      { label: "Move 2", text: "Split by issuing bank. One large bank degrading can move the blended rate several points on its own." },
      { label: "Move 3", text: "Check timing. A step change points at a deployment or a partner incident, a gradual slide at mix shift." },
      { label: "Move 4", text: "Separate technical decline from business decline, since insufficient funds is not a system failure." },
      { label: "Close", text: "Recommend routing changes and retry logic for the failing path, and name what monitoring would have caught it sooner." },
    ],
    pitfalls: [
      "Working from a blended success rate.",
      "Treating all declines as technical failures.",
      "Missing that a mix shift toward a weaker rail can move the rate with nothing broken.",
    ],
  },
  {
    slug: "feature-adoption-low-after-launch",
    shape: "case",
    title: "A new feature launched to 5% adoption. Is that a failure?",
    type: "Metrics",
    difficulty: 2,
    minutes: 25,
    answer: "Not necessarily. Judge against the addressable audience and the depth of use, not against the total user base.",
    hints: ["Adoption over the whole base is usually the wrong denominator. Find the right one."],
    moves: [
      { label: "Move 1", text: "Fix the denominator. Adoption should be measured against users who could plausibly need the feature." },
      { label: "Move 2", text: "Check discovery. Low adoption may mean nobody found it, which is a placement problem not a value problem." },
      { label: "Move 3", text: "Look at depth. Five percent using it constantly is a very different result from five percent trying it once." },
      { label: "Move 4", text: "Check the counterfactual. If it displaced a worse workflow, the value may not show in adoption at all." },
      { label: "Close", text: "Give a verdict with the denominator stated, and say what number would make you kill it." },
    ],
    pitfalls: [
      "Measuring adoption against the entire user base by default.",
      "Ignoring discovery as a cause of low usage.",
      "Judging on breadth without looking at depth.",
    ],
  },
  {
    slug: "prioritise-three-features-next-quarter",
    shape: "case",
    title: "You can ship one of three features next quarter. Choose and defend.",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    askedAt: "Flipkart",
    answer: "Choose against a stated objective with a stated cost of delay, and be explicit about what you are giving up.",
    hints: ["State the objective first. Prioritisation without a goal is just preference."],
    moves: [
      { label: "Move 1", text: "Establish the objective for the quarter: growth, retention, monetisation or reliability." },
      { label: "Move 2", text: "Size each feature's impact against that objective, with the assumption behind each estimate stated." },
      { label: "Move 3", text: "Weigh effort and risk honestly, including dependencies that could slip the whole quarter." },
      { label: "Move 4", text: "Consider cost of delay. Some features lose value if shipped late, others do not." },
      { label: "Close", text: "Pick one, say what you are sacrificing, and name the signal that would make you switch." },
    ],
    pitfalls: [
      "Scoring on a framework without ever stating the objective.",
      "Proposing to do all three in reduced form, which dodges the question.",
      "Ignoring cost of delay, which often decides genuinely close calls.",
    ],
  },
  {
    slug: "app-crash-rate-spike-after-release",
    shape: "case",
    title: "Crash rate tripled after a release. Walk through your response.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Stop the rollout first, then diagnose. Containing exposure precedes understanding the cause.",
    hints: ["The first move is containment, not investigation. Say that before anything else."],
    moves: [
      { label: "Move 1", text: "Halt the rollout immediately to cap the affected population." },
      { label: "Move 2", text: "Segment crashes by device, OS version and app version to locate the affected slice." },
      { label: "Move 3", text: "Decide roll back or fix forward, based on severity and how quickly a fix can ship through app review." },
      { label: "Move 4", text: "Assess user impact, since crashes at a critical step like checkout matter far more than crashes on a settings page." },
      { label: "Close", text: "Recommend the containment action, then the process change, since a tripled crash rate reaching production is a testing failure." },
    ],
    pitfalls: [
      "Investigating root cause while exposure keeps growing.",
      "Treating all crashes as equally severe regardless of where they occur.",
      "Fixing the bug without addressing how it shipped.",
    ],
  },
  {
    slug: "design-for-low-end-android",
    shape: "case",
    title: "Half your users are on entry-level Android devices. Redesign for them.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    answer: "Cut app size, reduce memory pressure and make everything work offline-first. Storage and data cost drive uninstalls more than any feature does.",
    hints: ["On these devices the app competes for storage. Uninstall is the failure mode, not disengagement."],
    moves: [
      { label: "Move 1", text: "Name the constraints: limited storage, low RAM, older processors, and expensive or intermittent data." },
      { label: "Move 2", text: "Attack app size, since large apps are the first uninstalled when storage runs out." },
      { label: "Move 3", text: "Reduce runtime cost: fewer animations, smaller images, aggressive caching and offline-first flows." },
      { label: "Move 4", text: "Consider a lite variant, which several Indian-scale apps have shipped for exactly this segment." },
      { label: "Close", text: "Measure uninstall rate by device tier, since that is the metric this work is actually trying to move." },
    ],
    pitfalls: [
      "Treating this as a visual design problem rather than a resource constraint.",
      "Optimising load time while ignoring app size.",
      "Assuming users have unlimited data.",
    ],
  },
  {
    slug: "two-sided-marketplace-supply-shortage",
    shape: "case",
    title: "A marketplace has plenty of demand and not enough supply. What do you do?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Stop spending on demand and fix supply economics and onboarding friction. Adding demand to a supply-constrained marketplace makes the experience worse.",
    hints: ["Adding more demand to a supply shortage actively harms the product. Say that early."],
    moves: [
      { label: "Move 1", text: "Confirm the imbalance with unfulfilled request rate and wait times, not with intuition." },
      { label: "Move 2", text: "Diagnose the supply side: is it earnings, onboarding friction, or an unattractive experience once onboarded?" },
      { label: "Move 3", text: "Fix economics first. Supply follows earnings more reliably than it follows marketing." },
      { label: "Move 4", text: "Consider throttling demand in undersupplied areas, which protects the experience while supply builds." },
      { label: "Close", text: "Recommend pausing demand spend, and say what supply level would let you resume." },
    ],
    pitfalls: [
      "Continuing demand acquisition into a supply shortage.",
      "Assuming supply is a marketing problem rather than an economics problem.",
      "Ignoring geographic imbalance by looking only at aggregate ratios.",
    ],
  },
  {
    slug: "subscription-churn-rising-month-four",
    shape: "case",
    title: "Subscription churn spikes in month four. Investigate.",
    type: "Root cause",
    difficulty: 3,
    minutes: 30,
    answer: "Look for an event at month four: a trial discount ending, a card expiring, or the content that drew them running out.",
    hints: ["A spike at a specific month means a specific event, not a gradual loss of interest."],
    moves: [
      { label: "Move 1", text: "Check for a pricing event. Introductory discounts ending at month three cause exactly this pattern." },
      { label: "Move 2", text: "Check involuntary churn. Failed renewals from expired cards are a large and fixable share." },
      { label: "Move 3", text: "Check content or value exhaustion. Users may have consumed what they joined for." },
      { label: "Move 4", text: "Cohort by acquisition channel, since discount-acquired users churn differently from organic ones." },
      { label: "Close", text: "Separate voluntary from involuntary churn in the recommendation. They need completely different fixes." },
    ],
    pitfalls: [
      "Treating involuntary churn as a satisfaction problem.",
      "Averaging across acquisition channels with very different retention.",
      "Reaching for engagement features before checking for a billing event.",
    ],
  },
  {
    slug: "define-success-for-referral-programme",
    shape: "case",
    title: "How would you measure success for a referral programme?",
    type: "Metrics",
    difficulty: 2,
    minutes: 20,
    answer: "Retained referred users per rupee of incentive, not referrals sent. Volume metrics reward gaming.",
    hints: ["Ask what someone would do to game each candidate metric. That eliminates most of them."],
    moves: [
      { label: "Move 1", text: "Reject referrals sent, which costs the referrer nothing and measures nothing." },
      { label: "Move 2", text: "Reject signups too, since incentives reliably produce fake or dormant accounts." },
      { label: "Move 3", text: "Move to activated referrals: users who complete a meaningful first action." },
      { label: "Move 4", text: "Divide by incentive cost, so the metric captures efficiency rather than raw volume." },
      { label: "Close", text: "Add a fraud guard rail, because any referral programme with real money attached will be attacked." },
    ],
    pitfalls: [
      "Choosing a metric that rewards volume over quality.",
      "Ignoring incentive cost entirely.",
      "Not planning for fraud, which is guaranteed rather than possible.",
    ],
  },
  {
    slug: "design-grocery-list-feature",
    shape: "case",
    title: "Design a recurring grocery list feature for a delivery app.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    answer: "Build it from purchase history rather than asking users to create a list, and make editing before checkout effortless.",
    hints: ["Asking users to build a list is friction. You already know what they buy."],
    moves: [
      { label: "Move 1", text: "Name the job: reduce the effort of a repeat shop that is largely identical each time." },
      { label: "Move 2", text: "Reject manual list building, which is work the user must do before getting any benefit." },
      { label: "Move 3", text: "Generate from history, inferring cadence per item since milk and rice repeat at different intervals." },
      { label: "Move 4", text: "Make correction cheap. The list will be wrong sometimes, and editing must be faster than starting over." },
      { label: "Close", text: "Measure repeat order frequency and basket completeness, not feature usage on its own." },
    ],
    pitfalls: [
      "Requiring setup effort before any value is delivered.",
      "Assuming one cadence across all grocery items.",
      "Measuring feature engagement rather than the behaviour it was meant to change.",
    ],
  },
  {
    slug: "dau-flat-but-sessions-rising",
    shape: "case",
    title: "Daily actives are flat but sessions per user are rising. Good or bad?",
    type: "Metrics",
    difficulty: 2,
    minutes: 20,
    answer: "Depends on why. More sessions can mean deeper engagement or it can mean users failing and retrying. Find out which.",
    hints: ["More sessions is not automatically good. Ask what a session now represents."],
    moves: [
      { label: "Move 1", text: "Check session length. Rising count with falling length often means people cannot complete a task." },
      { label: "Move 2", text: "Check task completion. If sessions rise while completions stay flat, something is broken." },
      { label: "Move 3", text: "Check for a definitional change. A shorter session timeout will split one session into several." },
      { label: "Move 4", text: "Check the segment. Rising sessions among power users differs entirely from rising sessions among new ones." },
      { label: "Close", text: "Give a verdict tied to task completion, and name the instrumentation you would add." },
    ],
    pitfalls: [
      "Treating any engagement increase as positive.",
      "Missing a session definition change, which is a common cause.",
      "Not looking at completion rates alongside session counts.",
    ],
  },
  {
    slug: "competitor-launched-same-feature",
    shape: "case",
    title: "A competitor shipped your roadmap feature first. What now?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Watch whether it works for them before reacting. Their launch is a free experiment you did not have to pay for.",
    hints: ["A competitor's launch is data, not a deadline. Treat it that way."],
    moves: [
      { label: "Move 1", text: "Resist the reflex to accelerate. Speed to match rarely produces a better product." },
      { label: "Move 2", text: "Watch their adoption signals: reviews, app store commentary, and whether they keep promoting it." },
      { label: "Move 3", text: "Ask whether it fits your users. Different user bases make the same feature succeed and fail." },
      { label: "Move 4", text: "If you still build it, build it better on a specific named dimension rather than shipping parity." },
      { label: "Close", text: "Recommend a decision date and the signal you will use, rather than an immediate yes or no." },
    ],
    pitfalls: [
      "Reprioritising the roadmap on competitor news alone.",
      "Assuming their user base and yours behave identically.",
      "Shipping parity, which gives users no reason to switch or stay.",
    ],
  },
  {
    slug: "should-we-build-in-app-chat",
    shape: "case",
    title: "Should a services marketplace build in-app chat?",
    type: "Product design",
    difficulty: 2,
    minutes: 25,
    answer: "Yes, primarily to keep transactions on-platform and to have a record when disputes arise. Communication quality is the secondary benefit.",
    hints: ["Ask what problem chat solves for the business, not just for the user."],
    moves: [
      { label: "Move 1", text: "Establish the leakage problem. Once phone numbers are exchanged, the next transaction happens off-platform." },
      { label: "Move 2", text: "Value the dispute record. Without a log, the platform cannot adjudicate anything." },
      { label: "Move 3", text: "Weigh the cost. Chat needs moderation, abuse handling and notification infrastructure." },
      { label: "Move 4", text: "Consider masked calling as a cheaper alternative that achieves much of the same." },
      { label: "Close", text: "Recommend with the leakage metric named, since that is what justifies the investment." },
    ],
    pitfalls: [
      "Justifying chat on user convenience alone.",
      "Underestimating moderation cost.",
      "Missing masked calling, which solves much of the problem more cheaply.",
    ],
  },
  {
    slug: "personalisation-hurting-discovery",
    shape: "case",
    title: "Personalisation raised engagement but narrowed what users see. Act?",
    type: "Experiment read",
    difficulty: 3,
    minutes: 30,
    answer: "Yes, add exploration. Short-term engagement gains from narrowing come at the cost of long-term catalogue value and user boredom.",
    hints: ["Optimising engagement today can shrink the space of things a user ever discovers."],
    moves: [
      { label: "Move 1", text: "Quantify the narrowing with catalogue coverage and per-user content diversity, not just engagement." },
      { label: "Move 2", text: "Model the long-term risk. A narrowing feed eventually exhausts the user's interest." },
      { label: "Move 3", text: "Consider supply health. Creators or sellers who never get exposure leave the platform." },
      { label: "Move 4", text: "Introduce a measured exploration share, tuned against an accepted short-term engagement cost." },
      { label: "Close", text: "Recommend the exploration budget with the diversity metric you would track alongside engagement." },
    ],
    pitfalls: [
      "Optimising engagement with no diversity counter-metric.",
      "Ignoring the supply side, which depends on exposure.",
      "Treating exploration as free.",
    ],
  },
  {
    slug: "free-tier-cannibalising-paid",
    shape: "case",
    title: "The free tier is cannibalising paid subscriptions. Fix it.",
    type: "Metrics",
    difficulty: 3,
    minutes: 30,
    answer: "Check whether free users would ever have paid. If not, this is not cannibalisation, it is reach, and the fix is a better paid trigger.",
    hints: ["Establish whether free users are lost revenue or people who were never going to pay."],
    moves: [
      { label: "Move 1", text: "Test the counterfactual. Would the free user have subscribed if the free tier did not exist?" },
      { label: "Move 2", text: "Examine the boundary. Cannibalisation usually means the free tier includes the feature people would pay for." },
      { label: "Move 3", text: "Value the free tier properly through ad revenue, network effects and conversion over time." },
      { label: "Move 4", text: "Redraw the line so the paid trigger sits at a moment of high intent rather than at an arbitrary usage cap." },
      { label: "Close", text: "Recommend the boundary change, and state the conversion rate that would confirm it worked." },
    ],
    pitfalls: [
      "Assuming every free user is a lost paying customer.",
      "Ignoring the value the free tier creates independently.",
      "Moving the paywall without identifying the moment of highest intent.",
    ],
  },
  {
    slug: "user-research-contradicts-data",
    shape: "case",
    title: "User interviews say one thing, the data says the opposite. Which do you follow?",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Neither alone. Interviews explain why, data describes what. A contradiction usually means you are measuring a different population than you interviewed.",
    hints: ["Check whether the interviewed users and the measured users are actually the same group."],
    moves: [
      { label: "Move 1", text: "Compare the populations. Interview participants are usually more engaged than the average user." },
      { label: "Move 2", text: "Check what each measures. People report intentions and remembered behaviour, data records actual behaviour." },
      { label: "Move 3", text: "Look for the reconciling explanation, which usually exists and is more interesting than either source alone." },
      { label: "Move 4", text: "Design a targeted test that would distinguish the two accounts." },
      { label: "Close", text: "Recommend the test rather than picking a side, and say what each outcome would mean." },
    ],
    pitfalls: [
      "Dismissing qualitative research as unreliable.",
      "Treating interview participants as representative.",
      "Choosing a side rather than finding what reconciles both.",
    ],
  },
  {
    slug: "reduce-time-to-first-value",
    shape: "case",
    title: "New users take too long to reach their first useful moment. Fix it.",
    type: "Product design",
    difficulty: 2,
    minutes: 25,
    answer: "Find the moment that predicts retention, then remove every step between opening the app and reaching it.",
    hints: ["Define the first useful moment precisely before trying to shorten the path to it."],
    moves: [
      { label: "Move 1", text: "Identify the activation moment empirically by finding the action most correlated with week-four retention." },
      { label: "Move 2", text: "Map the current path and count the steps and time to reach it." },
      { label: "Move 3", text: "Remove or defer steps. Anything not required to reach that moment should come later." },
      { label: "Move 4", text: "Pre-fill and infer where possible, using device signals rather than asking." },
      { label: "Close", text: "Measure time to activation and activation rate, not onboarding completion, which measures the wrong thing." },
    ],
    pitfalls: [
      "Guessing the activation moment instead of finding it in data.",
      "Optimising onboarding completion, which rewards asking less rather than delivering value sooner.",
      "Removing steps that turn out to be load-bearing for later retention.",
    ],
  },
  {
    slug: "sunset-a-feature-with-loyal-users",
    shape: "case",
    title: "You need to sunset a feature that a small group loves. How?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Confirm the maintenance cost is real, give a long notice period with a migration path, and accept that some of those users will leave.",
    hints: ["The decision is about cost, not popularity. But the execution is entirely about trust."],
    moves: [
      { label: "Move 1", text: "Quantify the cost: engineering maintenance, support load and the constraint it places on other work." },
      { label: "Move 2", text: "Quantify the users properly, including whether they are disproportionately valuable or vocal." },
      { label: "Move 3", text: "Look for a migration path. Sunsetting with an alternative is a completely different conversation." },
      { label: "Move 4", text: "Communicate early and once, with a firm date. Repeated delays destroy credibility for the next sunset." },
      { label: "Close", text: "Recommend the timeline and be explicit about the churn you expect to accept." },
    ],
    pitfalls: [
      "Deciding on user count without measuring the cost of keeping it.",
      "Sunsetting with no migration path.",
      "Announcing a date and then moving it, which poisons future communications.",
    ],
  },
  {
    slug: "growth-team-versus-core-product",
    shape: "case",
    title: "The growth team's experiments are degrading the core experience. Resolve it.",
    type: "Metrics",
    difficulty: 3,
    minutes: 30,
    answer: "Install shared guard-rail metrics that both teams are accountable to. The conflict is structural, not personal.",
    hints: ["This is an incentive design problem. Look at what each team is measured on."],
    moves: [
      { label: "Move 1", text: "Diagnose the incentive. Growth is measured on acquisition and conversion, product on retention and satisfaction." },
      { label: "Move 2", text: "Quantify the damage with retention and complaint data attributable to growth experiments." },
      { label: "Move 3", text: "Define guard rails: metrics no experiment may degrade regardless of its primary win." },
      { label: "Move 4", text: "Extend measurement windows, since short tests systematically miss retention harm." },
      { label: "Close", text: "Recommend shared accountability rather than a veto, since a veto just moves the conflict." },
    ],
    pitfalls: [
      "Framing this as a personality conflict.",
      "Giving one team veto power over the other.",
      "Keeping test windows too short to detect the harm being argued about.",
    ],
  },
  {
    slug: "should-we-support-regional-languages",
    shape: "case",
    title: "Should the app support ten Indian languages?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Start with two or three where the addressable user base is largest, and treat it as an ongoing content cost rather than a one-time translation project.",
    hints: ["Translation is not the cost. Keeping ten languages current, forever, is the cost."],
    moves: [
      { label: "Move 1", text: "Size the opportunity per language using internet users by language, not by state population." },
      { label: "Move 2", text: "Cost it honestly. Every future feature, error message and support article multiplies by ten." },
      { label: "Move 3", text: "Test with a partial rollout in one or two languages to measure the actual conversion lift." },
      { label: "Move 4", text: "Distinguish interface translation from content translation, since user-generated content cannot be translated at all." },
      { label: "Close", text: "Recommend a staged rollout with a lift threshold that must be met before adding the next language." },
    ],
    pitfalls: [
      "Treating localisation as a one-time translation project.",
      "Sizing by state population rather than by internet users in that language.",
      "Ignoring that user-generated content stays in whatever language it was written in.",
    ],
  },
  {
    slug: "fraud-rising-on-refunds",
    shape: "case",
    title: "Refund fraud is rising. Tighten the policy?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Target the abusers rather than tightening for everyone. A blanket policy change costs more in lost honest customers than the fraud does.",
    hints: ["Estimate the cost of friction on honest users before changing anything for everyone."],
    moves: [
      { label: "Move 1", text: "Size the fraud precisely, separating genuine abuse from legitimate dissatisfaction." },
      { label: "Move 2", text: "Check concentration. Fraud is usually concentrated in a small number of accounts and locations." },
      { label: "Move 3", text: "Model the cost of tightening: honest customers refused, complaints, and reduced purchase confidence." },
      { label: "Move 4", text: "Design targeted intervention: risk scoring, per-account limits and verification only for flagged cases." },
      { label: "Close", text: "Recommend the targeted approach, and state the fraud level at which a blanket change becomes justified." },
    ],
    pitfalls: [
      "Applying a blanket policy to solve a concentrated problem.",
      "Not costing the friction imposed on honest customers.",
      "Treating every refund request as potential fraud.",
    ],
  },
  {
    slug: "design-offline-mode",
    shape: "case",
    title: "Design offline mode for a learning app used on patchy networks.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    answer: "Pre-download the next lesson automatically on wifi, queue progress for sync, and never lose a user's work when connectivity drops.",
    hints: ["The failure to avoid is losing work someone already did. Design around that first."],
    moves: [
      { label: "Move 1", text: "Characterise the network. Intermittent rather than absent, so the app must handle transitions gracefully." },
      { label: "Move 2", text: "Decide what to pre-fetch. The next lesson is predictable, so download it automatically on wifi." },
      { label: "Move 3", text: "Queue writes locally. Quiz answers and progress must survive a dropout and sync later." },
      { label: "Move 4", text: "Handle conflicts. The same account used on two devices offline will produce divergent state." },
      { label: "Close", text: "Measure lesson completion on poor connections, which is the outcome this work exists to improve." },
    ],
    pitfalls: [
      "Designing for fully offline when the real condition is intermittent.",
      "Ignoring sync conflicts.",
      "Pre-downloading aggressively on mobile data, which costs the user money.",
    ],
  },
  {
    slug: "conversion-up-but-margin-down",
    shape: "case",
    title: "Conversion improved but contribution margin fell. Explain.",
    type: "Metrics",
    difficulty: 3,
    minutes: 25,
    answer: "You converted more of the wrong orders. Discount-led conversion and a mix shift into low-margin categories both produce exactly this.",
    hints: ["More conversion is not better if what converted was unprofitable."],
    moves: [
      { label: "Move 1", text: "Check discount depth. If conversion was bought with promotions, margin loss is the direct cost." },
      { label: "Move 2", text: "Check category mix. More orders in low-margin categories drags blended margin even at constant discounting." },
      { label: "Move 3", text: "Check basket size. Conversion improvements sometimes bring smaller orders that carry fixed fulfilment cost." },
      { label: "Move 4", text: "Check returns, since a converted order that comes back costs more than one never placed." },
      { label: "Close", text: "Recommend margin-aware optimisation targets, since conversion alone is an incomplete objective." },
    ],
    pitfalls: [
      "Celebrating conversion without a margin counter-metric.",
      "Ignoring fulfilment cost on small baskets.",
      "Forgetting returns, which reverse the revenue but not the cost.",
    ],
  },
  {
    slug: "measure-quality-of-support",
    shape: "case",
    title: "How would you measure the quality of customer support?",
    type: "Metrics",
    difficulty: 2,
    minutes: 20,
    answer: "First contact resolution and repeat contact rate, not handling time. Speed metrics reward closing tickets rather than solving problems.",
    hints: ["Ask what each candidate metric would push an agent to do under pressure."],
    moves: [
      { label: "Move 1", text: "Reject handling time as a primary metric, since it rewards closing conversations quickly." },
      { label: "Move 2", text: "Use first contact resolution, which captures whether the problem was actually solved." },
      { label: "Move 3", text: "Add repeat contact rate within a window, which catches issues closed prematurely." },
      { label: "Move 4", text: "Add a satisfaction measure, while noting response bias toward extreme experiences." },
      { label: "Close", text: "Track deflection too, since the best support outcome is a product fix that removes the need to contact anyone." },
    ],
    pitfalls: [
      "Optimising handling time, which reliably degrades resolution quality.",
      "Relying on satisfaction surveys with low and biased response rates.",
      "Never asking why the contact happened in the first place.",
    ],
  },
  {
    slug: "should-we-launch-a-loyalty-programme",
    shape: "case",
    title: "Should the app launch a paid loyalty programme?",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    answer: "Only if it changes behaviour rather than rewarding what already happens. Most loyalty programmes discount your best customers for buying what they would have bought anyway.",
    hints: ["Ask whether the reward changes behaviour or subsidises existing behaviour."],
    moves: [
      { label: "Move 1", text: "Identify the intended change: higher frequency, larger baskets, or category expansion." },
      { label: "Move 2", text: "Model the subsidy. Existing frequent buyers will join first and consume rewards without changing anything." },
      { label: "Move 3", text: "Design for the marginal user, whose behaviour would actually change, rather than for the loyal one." },
      { label: "Move 4", text: "Consider a paid model, where the fee itself filters for genuine intent and funds the benefit." },
      { label: "Close", text: "Recommend with an incremental behaviour target, not a membership number." },
    ],
    pitfalls: [
      "Measuring success by sign-ups rather than incremental behaviour.",
      "Subsidising customers who were already loyal.",
      "Ignoring the accounting liability that unredeemed points create.",
    ],
  },
  {
    slug: "app-store-rating-falling",
    shape: "case",
    title: "The app store rating fell from 4.4 to 3.9. Investigate.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Read the recent reviews before touching any dashboard. A rating fall is almost always one specific, nameable complaint.",
    hints: ["The reviews say why. Read them before opening any analytics."],
    moves: [
      { label: "Move 1", text: "Read the recent one and two star reviews and cluster them by theme." },
      { label: "Move 2", text: "Correlate with release timing, since a bad update usually shows up within days." },
      { label: "Move 3", text: "Check whether a review prompt change altered who is being asked to rate." },
      { label: "Move 4", text: "Segment by device and region, since a crash confined to one Android version can dominate reviews." },
      { label: "Close", text: "Recommend the specific fix, then re-prompting satisfied users, since ratings recover slowly on their own." },
    ],
    pitfalls: [
      "Analysing metrics without reading what people actually wrote.",
      "Missing that a prompt change altered the sampled population.",
      "Fixing the issue but never re-prompting, so the average stays depressed.",
    ],
  },
  {
    slug: "trade-off-speed-versus-accuracy-search",
    shape: "case",
    title: "Search results could be more accurate but 300ms slower. Ship it?",
    type: "Experiment read",
    difficulty: 3,
    minutes: 25,
    answer: "Probably not at 300ms. Latency harms conversion measurably and immediately, while relevance gains have to be large to offset it.",
    hints: ["Latency has a well-documented conversion cost. Quantify both sides in the same units."],
    moves: [
      { label: "Move 1", text: "Quantify the latency cost using known conversion sensitivity, which is significant at hundreds of milliseconds." },
      { label: "Move 2", text: "Quantify the relevance gain in the same currency: clicks, conversions or orders." },
      { label: "Move 3", text: "Segment by connection. On slow Indian networks 300ms of server time compounds with network delay." },
      { label: "Move 4", text: "Look for a middle path: serve fast results first and refine asynchronously." },
      { label: "Close", text: "Recommend against the straight trade, and propose the progressive approach with a target latency budget." },
    ],
    pitfalls: [
      "Treating relevance as automatically worth any latency cost.",
      "Testing only on fast office networks.",
      "Accepting the binary framing rather than looking for a hybrid.",
    ],
  },
  {
    slug: "design-for-shared-devices",
    shape: "case",
    title: "Many users share one phone with family. Design for that.",
    type: "Product design",
    difficulty: 2,
    minutes: 30,
    answer: "Support fast profile switching without full re-authentication, and never assume the person holding the phone is the account owner.",
    hints: ["Personalisation built on device identity breaks completely when the device is shared."],
    moves: [
      { label: "Move 1", text: "Recognise the pattern. Device sharing is common in Indian households, particularly across generations." },
      { label: "Move 2", text: "Identify what breaks: recommendations, watch history, saved payment details and privacy of personal content." },
      { label: "Move 3", text: "Design lightweight profiles that switch in one tap without a full login each time." },
      { label: "Move 4", text: "Protect sensitive actions. Payment and personal data should require verification even within a switched profile." },
      { label: "Close", text: "Measure recommendation quality after the change, since a shared-device account produces incoherent signals." },
    ],
    pitfalls: [
      "Assuming one device equals one user.",
      "Making profile switching as heavy as logging in.",
      "Leaving payment methods accessible to whoever picks up the phone.",
    ],
  },
  {
    slug: "onboarding-drop-at-kyc",
    shape: "case",
    title: "Half your signups drop off at the KYC step. Fix it.",
    type: "Root cause",
    difficulty: 2,
    minutes: 25,
    answer: "Move KYC later, after the user has seen value, and reduce the failure modes in the step itself.",
    hints: ["Ask whether KYC needs to happen before value is delivered, or merely before money moves."],
    moves: [
      { label: "Move 1", text: "Break the step down. Document capture, OCR failure, name mismatch and OTP failure are separate problems." },
      { label: "Move 2", text: "Check whether the regulation actually requires KYC at this point, or only before transacting." },
      { label: "Move 3", text: "Defer it. Let users explore and only verify at the point of first transaction." },
      { label: "Move 4", text: "Improve the step: better capture guidance, retry handling and clear error messages for common mismatches." },
      { label: "Close", text: "Measure completion by sub-step, since one failure mode usually dominates the aggregate number." },
    ],
    pitfalls: [
      "Treating KYC drop-off as one number rather than several distinct failures.",
      "Assuming regulation requires verification earlier than it does.",
      "Improving the UI without fixing the OCR and matching failures underneath.",
    ],
  },
  {
    slug: "which-users-to-save",
    shape: "case",
    title: "You can win back one churned segment. Which one?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "The segment that churned for a fixable reason and had high value. Recency and reason matter more than segment size.",
    hints: ["Not all churn is winnable. Segment by reason before segmenting by value."],
    moves: [
      { label: "Move 1", text: "Segment by churn reason: price, a bad experience, a competitor, or a life change that ends the need entirely." },
      { label: "Move 2", text: "Discard the unwinnable. A user who no longer has the need will not return regardless of offer." },
      { label: "Move 3", text: "Score the rest on prior value and recency, since recently churned users are far cheaper to win back." },
      { label: "Move 4", text: "Match the intervention to the reason. A service failure needs an apology and a fix, not a discount." },
      { label: "Close", text: "Pick the segment and name the win-back mechanism, with the payback period you would accept." },
    ],
    pitfalls: [
      "Targeting the largest churned segment regardless of winnability.",
      "Sending the same discount to everyone regardless of why they left.",
      "Ignoring recency, which is the strongest predictor of win-back success.",
    ],
  },
  {
    slug: "dark-patterns-boost-conversion",
    shape: "case",
    title: "A pre-ticked checkbox lifts conversion 6%. Keep it?",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 20,
    answer: "No. The gain is real and so is the downstream cost in refunds, complaints and trust, and increasingly in regulatory exposure.",
    hints: ["Follow the 6% forward. Where do those conversions end up three months later?"],
    moves: [
      { label: "Move 1", text: "Trace the cohort. Users who converted this way should be tracked for refunds, complaints and cancellations." },
      { label: "Move 2", text: "Cost the support load, since unintended purchases generate expensive contacts." },
      { label: "Move 3", text: "Consider regulation. Consumer protection rules increasingly treat pre-ticked consent as a violation." },
      { label: "Move 4", text: "Test the honest alternative. A clear opt-in with a good value proposition often recovers much of the gain." },
      { label: "Close", text: "Recommend removal, and propose the honest variant as the replacement test." },
    ],
    pitfalls: [
      "Judging on the conversion number alone.",
      "Ignoring the support and refund cost that follows.",
      "Treating regulatory risk as a legal problem rather than a product decision.",
    ],
  },
  {
    slug: "define-mvp-for-new-market",
    shape: "case",
    title: "Define the minimum product for launching in a new country.",
    type: "Product design",
    difficulty: 3,
    minutes: 30,
    answer: "Whatever is required to complete one full transaction legally and reliably. Everything else waits for evidence that the market works.",
    hints: ["The minimum is defined by the transaction, not by feature parity with your home market."],
    moves: [
      { label: "Move 1", text: "Identify the core transaction and work backwards to what is strictly needed to complete it." },
      { label: "Move 2", text: "Add the non-negotiables: local payment methods, language, and regulatory compliance." },
      { label: "Move 3", text: "Cut everything built for home-market maturity, which was earned over years and is not needed on day one." },
      { label: "Move 4", text: "Decide what you will learn from launch and what evidence would justify further investment." },
      { label: "Close", text: "Define success as validated learning about demand, not as revenue in the first quarter." },
    ],
    pitfalls: [
      "Porting the full home-market product.",
      "Treating local payment methods as an optimisation rather than a requirement.",
      "Launching with no defined learning goal.",
    ],
  },
  {
    slug: "engagement-up-nps-down",
    shape: "case",
    title: "Engagement is up but customer satisfaction is down. Explain.",
    type: "Metrics",
    difficulty: 3,
    minutes: 25,
    answer: "Users may be spending more time because something got harder, not better. Or you added engaging features while degrading the core job.",
    hints: ["Time spent is ambiguous. Establish whether it reflects value or friction."],
    moves: [
      { label: "Move 1", text: "Separate engagement types. Time completing tasks is different from time struggling with them." },
      { label: "Move 2", text: "Check task success rates alongside time spent." },
      { label: "Move 3", text: "Check who moved. Satisfaction may have fallen among a specific segment while engagement rose among another." },
      { label: "Move 4", text: "Read verbatim feedback, which usually names the cause directly." },
      { label: "Close", text: "Give a hypothesis with the segment identified, and the instrumentation that would confirm it." },
    ],
    pitfalls: [
      "Treating time spent as an unambiguous positive.",
      "Comparing aggregate metrics without segmenting.",
      "Ignoring open-text feedback that already explains it.",
    ],
  },
  {
    slug: "should-we-open-the-api",
    shape: "case",
    title: "Should the platform open a public API?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Only with a clear view on what you want built and what you are giving away. An open API is a permanent commitment, not a feature.",
    hints: ["Once external developers depend on it, you can never change it freely again."],
    moves: [
      { label: "Move 1", text: "Define the goal: ecosystem growth, enterprise integration, or reducing your own build burden." },
      { label: "Move 2", text: "Assess the risk. An API can let competitors extract your data or disintermediate your interface." },
      { label: "Move 3", text: "Cost the commitment: versioning, documentation, support and the loss of freedom to change internals." },
      { label: "Move 4", text: "Consider a narrower option: partner APIs under contract rather than a fully public one." },
      { label: "Close", text: "Recommend the narrowest scope that achieves the stated goal, and name the rate limits and terms." },
    ],
    pitfalls: [
      "Opening an API without a clear goal for it.",
      "Underestimating the permanence of the commitment.",
      "Ignoring competitive data extraction risk.",
    ],
  },
  {
    slug: "instrumentation-gap-found",
    shape: "case",
    title: "You discover a key funnel step was never instrumented. What now?",
    type: "Root cause",
    difficulty: 2,
    minutes: 20,
    answer: "Instrument it, then re-examine every past decision that assumed a number for that step. Some of them were probably wrong.",
    hints: ["The bigger problem is not the missing data. It is the decisions already made without it."],
    moves: [
      { label: "Move 1", text: "Add the instrumentation and let it run long enough to be reliable." },
      { label: "Move 2", text: "Find proxies. Server logs or downstream counts may allow partial reconstruction of history." },
      { label: "Move 3", text: "Re-examine decisions that assumed a value for this step, since some conclusions may not survive." },
      { label: "Move 4", text: "Audit for other gaps, since one missing event usually indicates a process problem rather than an isolated oversight." },
      { label: "Close", text: "Recommend an instrumentation review as part of the launch checklist, which is the durable fix." },
    ],
    pitfalls: [
      "Adding the event and moving on without revisiting past conclusions.",
      "Assuming this is the only gap.",
      "Waiting for perfect data before acting at all.",
    ],
  },
  {
    slug: "seasonal-product-off-season",
    shape: "case",
    title: "Your product is used heavily for three months and ignored for nine. Fix it.",
    type: "Product design",
    difficulty: 2,
    minutes: 25,
    answer: "Either find an adjacent off-season job for the same user, or accept the seasonality and build the cost base around it.",
    hints: ["Fighting seasonality is often more expensive than designing for it."],
    moves: [
      { label: "Move 1", text: "Understand the driver. Exam cycles, festivals, weather and tax dates each behave differently." },
      { label: "Move 2", text: "Look for an adjacent job. The same user may have a different need in the off season." },
      { label: "Move 3", text: "Consider the honest alternative: accept seasonality and make the cost base variable." },
      { label: "Move 4", text: "Use the off season deliberately for building and for retention rather than acquisition." },
      { label: "Close", text: "Recommend one path clearly, since trying both usually produces a product that serves neither well." },
    ],
    pitfalls: [
      "Bolting on unrelated features to fill the off season.",
      "Maintaining peak-season cost year round.",
      "Measuring off-season engagement against peak-season benchmarks.",
    ],
  },
  {
    slug: "one-large-customer-drives-roadmap",
    shape: "case",
    title: "One large customer is dictating your roadmap. Handle it.",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Separate what is genuinely generalisable from what is bespoke, and price the bespoke work so the decision becomes economic rather than political.",
    hints: ["Ask whether other customers would use the same thing. That question resolves most of it."],
    moves: [
      { label: "Move 1", text: "Size the dependency honestly. If they are a large share of revenue, the constraint is real." },
      { label: "Move 2", text: "Test generalisability. Some requests genuinely represent the market, and those should be built." },
      { label: "Move 3", text: "Price the rest as custom work, which makes the trade-off explicit and funds the engineering time." },
      { label: "Move 4", text: "Reduce the dependency over time, since the underlying problem is revenue concentration." },
      { label: "Close", text: "Recommend the split and the pricing model, and name the concentration target you would work toward." },
    ],
    pitfalls: [
      "Building every request to protect the relationship.",
      "Refusing on principle without weighing the revenue risk.",
      "Treating this as a product problem when it is a concentration problem.",
    ],
  },
  {
    slug: "ai-feature-hallucinating",
    shape: "case",
    title: "Your AI assistant gives wrong answers 5% of the time. Ship it?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Depends entirely on the cost of a wrong answer. Five percent is fine for suggestions and unacceptable for anything financial or medical.",
    hints: ["The error rate means nothing without knowing what a single error costs."],
    moves: [
      { label: "Move 1", text: "Characterise the errors. Confidently wrong is far more dangerous than visibly uncertain." },
      { label: "Move 2", text: "Cost a single failure in the actual use case, from mild annoyance to real financial harm." },
      { label: "Move 3", text: "Design the containment: confidence thresholds, human review, and clear scoping of what it will not answer." },
      { label: "Move 4", text: "Set expectations in the interface, since a tool presented as a draft assistant is judged differently from an authority." },
      { label: "Close", text: "Recommend conditional shipping with the scope limits named, and the monitoring that would catch drift." },
    ],
    pitfalls: [
      "Judging on the aggregate error rate without weighting severity.",
      "Shipping without a fallback for low-confidence cases.",
      "Presenting probabilistic output with the confidence of a database lookup.",
    ],
  },
  {
    slug: "internal-tool-nobody-uses",
    shape: "case",
    title: "An internal tool you built is barely used. Investigate.",
    type: "Root cause",
    difficulty: 2,
    minutes: 20,
    answer: "Usually the tool solved a problem the team did not have, or it is slower than the spreadsheet it replaced.",
    hints: ["Ask what people are doing instead. That reveals what the tool failed to beat."],
    moves: [
      { label: "Move 1", text: "Find the alternative. If they are still using a spreadsheet, the spreadsheet is winning on something." },
      { label: "Move 2", text: "Check whether the problem was real. Internal tools are often built on assumed rather than observed need." },
      { label: "Move 3", text: "Compare the workflow end to end, including the steps around the tool, not just the tool itself." },
      { label: "Move 4", text: "Test switching cost. A better tool that requires relearning may still lose." },
      { label: "Close", text: "Recommend fixing the specific gap or retiring the tool, since a half-used internal tool costs more than no tool." },
    ],
    pitfalls: [
      "Assuming low usage means poor training rather than poor fit.",
      "Comparing the tool to the ideal rather than to the spreadsheet it competes with.",
      "Keeping it alive out of sunk cost.",
    ],
  },
  {
    slug: "roadmap-for-a-declining-product",
    shape: "case",
    title: "Your product's category is shrinking. What is the roadmap?",
    type: "Prioritisation",
    difficulty: 3,
    minutes: 30,
    answer: "Stop investing in growth and optimise for profitability and retention, unless there is a genuine adjacent market the assets transfer into.",
    hints: ["Growth investment in a shrinking category rarely pays back. Be honest about that first."],
    moves: [
      { label: "Move 1", text: "Confirm the decline is structural rather than competitive, since those need opposite responses." },
      { label: "Move 2", text: "Segment the remaining base. A shrinking category often leaves a profitable, loyal core." },
      { label: "Move 3", text: "Shift the objective from growth to margin and retention, which changes what belongs on the roadmap." },
      { label: "Move 4", text: "Test adjacency honestly. Assets sometimes transfer, and often they do not." },
      { label: "Close", text: "Recommend the harvest strategy explicitly, and name what evidence would justify investing again." },
    ],
    pitfalls: [
      "Confusing losing share with a shrinking category.",
      "Continuing growth investment out of institutional optimism.",
      "Claiming adjacency without evidence that the assets transfer.",
    ],
  },
  {
    slug: "two-teams-same-feature",
    shape: "case",
    title: "Two teams have independently built the same feature. Resolve it.",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 20,
    answer: "Pick one on merit, migrate the other's users, and fix the visibility failure that let it happen twice.",
    hints: ["The duplicate is the symptom. The process gap is the actual problem."],
    moves: [
      { label: "Move 1", text: "Compare the two on user outcomes and maintainability, not on which team is more senior." },
      { label: "Move 2", text: "Check whether they genuinely serve the same need, since two similar features sometimes serve different segments." },
      { label: "Move 3", text: "Plan the migration, since users of the retired version must be moved with care." },
      { label: "Move 4", text: "Fix the cause. Duplicate work means roadmaps are not visible across teams." },
      { label: "Close", text: "Recommend the merge and the process change, and handle the team whose work is retired deliberately." },
    ],
    pitfalls: [
      "Deciding on organisational politics rather than merit.",
      "Retiring one without a migration plan.",
      "Fixing the duplicate without fixing the visibility gap.",
    ],
  },
  {
    slug: "loud-power-users-demand-feature",
    shape: "case",
    title: "Your loudest power users demand a feature the data says few will use. Decide.",
    type: "Prioritisation",
    difficulty: 2,
    minutes: 25,
    answer: "Neither obey the voices nor worship the dashboard: check whether the loud minority is disproportionately valuable (revenue, retention, word of mouth) before ruling. Often the right move is a scoped version for that segment, explicitly framed as such, rather than a roadmap slot or a flat no.",
    hints: ["Ask who is asking before asking how many are asking."],
    moves: [
      { label: "Move 1", text: "Profile the requesters: what share of revenue, referrals and retention do these users represent? A 2% cohort driving 30% of value changes the calculus entirely." },
      { label: "Move 2", text: "Interrogate the data silence: usage prediction for unbuilt features is unreliable; low predicted use may mean the need is real but your instrumentation cannot see it." },
      { label: "Move 3", text: "Find the need under the ask: power users prescribe solutions; interview five of them for the underlying job, which is often servable far more cheaply." },
      { label: "Move 4", text: "Consider the scoped middle: a power-user setting, an API hook or a paid tier serves the vocal segment without taxing the mainstream product surface." },
      { label: "Close", text: "Decide with the segment value on the table, communicate the reasoning to the requesters either way, and log the request pattern; three unrelated loud asks pointing at one gap is a roadmap signal." },
    ],
    pitfalls: [
      "Counting voices instead of weighing them.",
      "Treating predicted-usage data for an unbuilt feature as settled fact.",
      "Building the literal request instead of the underlying need.",
    ],
  },
  {
    slug: "should-we-copy-the-market-leader",
    shape: "case",
    title: "Should a smaller app copy the market leader's interface?",
    type: "Product design",
    difficulty: 2,
    minutes: 25,
    answer: "Copy the conventions users have already learned, differentiate on the job you do better. Copying wholesale gives nobody a reason to switch.",
    hints: ["Familiarity reduces learning cost. Differentiation gives a reason to switch. You need both."],
    moves: [
      { label: "Move 1", text: "Separate conventions from differentiators. Where a control sits is a convention, not an advantage." },
      { label: "Move 2", text: "Adopt conventions freely, since fighting learned behaviour costs users for no benefit." },
      { label: "Move 3", text: "Identify the switching reason. A smaller app needs one dimension where it is clearly better." },
      { label: "Move 4", text: "Invest disproportionately in that dimension rather than spreading effort across parity features." },
      { label: "Close", text: "Recommend convention plus one sharp differentiator, and name what that differentiator should be." },
    ],
    pitfalls: [
      "Being different for its own sake on standard interactions.",
      "Copying wholesale and offering no reason to switch.",
      "Spreading effort across parity instead of concentrating on one advantage.",
    ],
  },
  {
    slug: "metric-improved-after-outage",
    shape: "case",
    title: "A key metric improved right after an outage. What do you conclude?",
    type: "Metrics",
    difficulty: 3,
    minutes: 20,
    answer: "Almost certainly nothing causal. Survivorship and composition effects explain most post-outage metric improvements.",
    hints: ["Ask who is left in the denominator after an outage. That usually explains it."],
    moves: [
      { label: "Move 1", text: "Check composition. If casual users dropped off, the remaining base is more engaged by definition." },
      { label: "Move 2", text: "Check the denominator. Rates improve when the base shrinks even with no behaviour change." },
      { label: "Move 3", text: "Check for a backlog effect. Suppressed demand released after recovery inflates the following period." },
      { label: "Move 4", text: "Compare absolute counts alongside rates, which usually shows the improvement is illusory." },
      { label: "Close", text: "Conclude no causal improvement, and note the lesson about rate metrics during disruption." },
    ],
    pitfalls: [
      "Treating a post-outage rate improvement as a real gain.",
      "Looking only at rates and never at absolute volumes.",
      "Ignoring the backlog surge in the recovery window.",
    ],
  },
  {
    slug: "design-for-users-who-cannot-read",
    shape: "case",
    title: "Design a payments flow for users who cannot read.",
    type: "Product design",
    difficulty: 3,
    minutes: 30,
    answer: "Voice-first with strong visual confirmation, and irreversible actions must be confirmable without reading anything.",
    hints: ["Icons are not universal either. Test comprehension rather than assuming it."],
    moves: [
      { label: "Move 1", text: "Identify what must be communicated: amount, recipient and confirmation. Everything else can be removed." },
      { label: "Move 2", text: "Use voice for input and readback, in the user's own language, for the amount and recipient." },
      { label: "Move 3", text: "Use faces and photos rather than names, since visual recognition of a person is reliable where text is not." },
      { label: "Move 4", text: "Design error states carefully. A failed payment must be understandable without any text at all." },
      { label: "Close", text: "Test with the actual population, since designers systematically overestimate icon comprehension." },
    ],
    pitfalls: [
      "Assuming icons are self-explanatory.",
      "Handling the happy path with voice and leaving errors in text.",
      "Testing with literate users and inferring the rest.",
    ],
  },
  {
    slug: "growth-slowed-after-hitting-scale",
    shape: "case",
    title: "Growth slowed sharply after reaching 50 million users. Why?",
    type: "Root cause",
    difficulty: 3,
    minutes: 30,
    answer: "You are probably approaching the boundary of the addressable market as originally defined. The next users are structurally different from the first fifty million.",
    hints: ["Ask who is left. The remaining non-users differ from your existing base in some specific way."],
    moves: [
      { label: "Move 1", text: "Size the addressable market honestly and check what share you already hold." },
      { label: "Move 2", text: "Characterise the remaining non-users. Language, income, device or need usually separates them." },
      { label: "Move 3", text: "Check whether acquisition channels saturated, since the same channels reach the same kind of people." },
      { label: "Move 4", text: "Decide between deepening monetisation of existing users or expanding the definition of the market." },
      { label: "Close", text: "Recommend one path with the required product change named, since expansion is rarely just a marketing exercise." },
    ],
    pitfalls: [
      "Treating a market boundary as a marketing failure.",
      "Assuming the next users behave like the last ones.",
      "Pushing harder on saturated channels.",
    ],
  },
];
