import type { Question } from "./types";

// Strategy and consulting cases. The answer is a recommendation with a stated
// condition, never a framework recited out loud.
export const STRATEGY_CASES: Question[] = [
  {
    slug: "paint-manufacturer-profit-decline",
    shape: "case",
    title: "A paint manufacturer's profit fell 18% while revenue grew. Find out why.",
    type: "Profitability",
    difficulty: 3,
    minutes: 30,
    askedAt: "McKinsey",
    answer: "Mix and input cost, not volume. Growth came from lower-margin industrial paint while a raw material rise could not be passed through.",
    hints: ["Revenue grew, so the answer is on the cost side or in the mix. Rule out volume first."],
    moves: [
      { label: "Move 1", text: "Split revenue into price and volume. Volume growth with flat price points straight at mix." },
      { label: "Move 2", text: "Break revenue by segment. Decorative and industrial paint carry very different margins." },
      { label: "Move 3", text: "Work the cost side. Titanium dioxide and crude derivatives dominate paint input cost." },
      { label: "Move 4", text: "Test pass-through. Most commodity profitability cases resolve as an input rise the company could not push to customers." },
      { label: "Close", text: "State the driver, size it roughly, and give one recommendation that follows, such as segment-level repricing." },
    ],
    pitfalls: [
      "Naming framework buckets out loud instead of using them.",
      "Jumping to cost cutting before establishing whether the problem is mix.",
      "Ending on diagnosis with no recommendation attached.",
    ],
  },
  {
    slug: "korean-beauty-brand-india-entry",
    shape: "case",
    title: "A Korean beauty brand wants to enter India. Should it?",
    type: "Market entry",
    difficulty: 2,
    minutes: 30,
    askedAt: "Bain",
    answer: "Yes, online-first through marketplaces and quick commerce, provided the landed price after duty still holds the target price point.",
    hints: ["Do not size the whole beauty market. Size the segment this brand could realistically own."],
    moves: [
      { label: "Move 1", text: "Size the addressable slice: urban women with the income to buy imported skincare, a small fraction of the headline market." },
      { label: "Move 2", text: "Assess the right to win. Strong trend advantage and social proof, but no distribution and no local skin-type credibility." },
      { label: "Move 3", text: "Choose the entry mode. Online-first avoids physical distribution cost and is how recent beauty entrants have done it." },
      { label: "Move 4", text: "Test the economics. Import duty, cold chain for actives and marketplace commission decide whether the price point survives." },
      { label: "Close", text: "Give a clear yes or no with a condition attached. A hedge with no threshold reads as unwillingness to decide." },
    ],
    pitfalls: [
      "Sizing the entire Indian cosmetics market, which flatters the case and answers nothing.",
      "Treating demand as the risk when distribution and duty are what kill entrants.",
      "Recommending entry without naming what would reverse the call.",
    ],
  },
  {
    slug: "hospital-chain-diagnostics-acquisition",
    shape: "case",
    title: "A hospital chain is weighing the purchase of a diagnostics lab network.",
    type: "M&A",
    difficulty: 3,
    minutes: 35,
    askedAt: "BCG",
    answer: "Buy only if referral capture and asset utilisation are quantified. Otherwise this is paying a premium for volume the chain already sends elsewhere.",
    hints: ["The value is in captured referrals, not in the labs themselves. Size that first."],
    moves: [
      { label: "Move 1", text: "Establish the strategic logic. A hospital already generates diagnostic demand it currently gives away." },
      { label: "Move 2", text: "Size the captured volume. How much of the labs' revenue would come from the chain's own patients." },
      { label: "Move 3", text: "Check utilisation. Diagnostics is a fixed-asset business, so incremental volume on existing machines is nearly pure margin." },
      { label: "Move 4", text: "Compare against building. Setting up in-house labs may be cheaper than paying an acquisition premium." },
      { label: "Close", text: "Recommend with a price ceiling, not just a yes. The answer to an M&A case is always conditional on the number." },
    ],
    pitfalls: [
      "Ignoring the build alternative, which is often the better answer.",
      "Assuming synergies without sizing them.",
      "Giving an unconditional yes with no view on valuation.",
    ],
  },
  {
    slug: "multiplex-weekday-footfall",
    shape: "case",
    title: "A multiplex chain wants to lift weekday footfall by 20%.",
    type: "Growth",
    difficulty: 2,
    minutes: 25,
    answer: "Segment-priced weekday tickets funded out of contribution, with food and beverage carrying the profit.",
    hints: ["The screen runs whether it is full or not, so the marginal seat is nearly pure margin."],
    moves: [
      { label: "Move 1", text: "Separate fixed from variable cost. A screening costs almost the same empty or full." },
      { label: "Move 2", text: "Segment by who is actually free on a weekday: students, retirees, shift workers, corporate groups." },
      { label: "Move 3", text: "Price by segment without breaking the weekend. Time-of-day pricing and student ID protect premium slots." },
      { label: "Move 4", text: "Work the food and beverage line, which is where a discounted weekday seat becomes profitable." },
      { label: "Close", text: "Value the extra seat at contribution, not revenue. That tells you what the discount budget can be." },
    ],
    pitfalls: [
      "Discounting across the board and cannibalising the weekend.",
      "Valuing the extra seat at ticket price rather than contribution.",
      "Proposing marketing spend with no view on what a weekday customer is worth.",
    ],
  },
  {
    slug: "steel-producer-cost-reduction",
    shape: "case",
    title: "A steel producer must cut costs 12% without touching headcount.",
    type: "Cost reduction",
    difficulty: 3,
    minutes: 30,
    askedAt: "Kearney",
    answer: "Energy, raw material yield and logistics, in that order. Labour is a small share of steel cost anyway, which is why the constraint costs less than it sounds.",
    hints: ["Break total cost into its actual components before choosing where to cut."],
    moves: [
      { label: "Move 1", text: "Build the cost stack. Iron ore, coking coal, energy and logistics dominate. Labour is often under 10%." },
      { label: "Move 2", text: "Attack energy first, the largest controllable line, through waste heat recovery and load scheduling." },
      { label: "Move 3", text: "Work yield. A one point improvement in metallic yield drops straight to the bottom line at this scale." },
      { label: "Move 4", text: "Rework logistics. Rake planning, port handling and inventory carrying are frequently mispriced." },
      { label: "Close", text: "Note that the no-headcount constraint barely binds, since labour was never the lever. Saying that shows you read the cost stack." },
    ],
    pitfalls: [
      "Reaching for procurement discounts on commodities priced by global markets.",
      "Treating a 12% total cost cut as needing 12% off every line.",
      "Ignoring yield, which is the highest-leverage lever in metals.",
    ],
  },
  {
    slug: "telco-cheaper-new-entrant",
    shape: "case",
    title: "A telco is losing subscribers to a cheaper new entrant. Respond.",
    type: "Competitive response",
    difficulty: 2,
    minutes: 30,
    answer: "Do not match on price. Segment-defend the high-value base and let the price-sensitive tail go, since matching destroys more value than it saves.",
    hints: ["Work out which subscribers are actually leaving before designing any response."],
    moves: [
      { label: "Move 1", text: "Segment the churn. Losing low-ARPU prepaid users is a different problem from losing postpaid families." },
      { label: "Move 2", text: "Value the lost subscribers. If departing users were barely contribution positive, the churn number overstates the damage." },
      { label: "Move 3", text: "Test the entrant's economics. A price they cannot sustain is a waiting game, not a war." },
      { label: "Move 4", text: "Defend selectively. Bundles, family plans and network quality hold high-value users without a general price cut." },
      { label: "Close", text: "Say explicitly what you are willing to lose. A defence that tries to keep everyone keeps nobody profitably." },
    ],
    pitfalls: [
      "Matching price across the board and destroying industry economics.",
      "Treating all churned subscribers as equally valuable.",
      "Ignoring whether the entrant can actually sustain its pricing.",
    ],
  },
  {
    slug: "airline-profit-falling-record-loads",
    shape: "case",
    title: "An airline's profit is falling despite record load factors. Explain.",
    type: "Profitability",
    difficulty: 3,
    minutes: 30,
    answer: "Full aircraft sold at the wrong price. Yield fell faster than loads rose, most likely from over-discounting or a worsening fuel and lease cost base.",
    hints: ["Load factor says seats are full. It says nothing about what those seats sold for."],
    moves: [
      { label: "Move 1", text: "Separate load factor from yield. Revenue per available seat kilometre is the metric that matters." },
      { label: "Move 2", text: "Test whether discounting drove the loads. Filling aircraft cheaply is easy and often unprofitable." },
      { label: "Move 3", text: "Work the cost side. Fuel, lease rentals and airport charges move independently of how full the aircraft is." },
      { label: "Move 4", text: "Check the route mix. Adding thin new routes can lift network loads while diluting overall profitability." },
      { label: "Close", text: "Recommend on yield management and route rationalisation, and name the routes you would cut first." },
    ],
    pitfalls: [
      "Treating high load factor as evidence of a healthy business.",
      "Ignoring currency, since fuel and leases are dollar-denominated for Indian carriers.",
      "Recommending cost cuts before establishing whether the problem is revenue.",
    ],
  },
  {
    slug: "dairy-cooperative-premium-brand",
    shape: "case",
    title: "Should a dairy cooperative launch a premium brand?",
    type: "New product",
    difficulty: 2,
    minutes: 30,
    answer: "Yes, but under a separate brand name. The cooperative's mass-market equity is an asset for milk and a liability for premium.",
    hints: ["Ask what the existing brand actually stands for before extending it."],
    moves: [
      { label: "Move 1", text: "Define the premium opportunity: high-margin categories like cheese, yoghurt and speciality butter." },
      { label: "Move 2", text: "Test brand permission. A trusted mass brand may not carry authority in premium, and can dilute if stretched." },
      { label: "Move 3", text: "Check the supply chain. Premium dairy needs cold chain and consistency the cooperative may not have." },
      { label: "Move 4", text: "Assess cannibalisation, which for a cooperative is less damaging since it captures both sides." },
      { label: "Close", text: "Recommend a separate brand, and name the one capability gap that would stop you." },
    ],
    pitfalls: [
      "Assuming brand trust transfers upward into premium.",
      "Ignoring cold chain, which is the binding constraint in Indian premium dairy.",
      "Treating cannibalisation as automatically bad.",
    ],
  },
  {
    slug: "hotel-chain-own-versus-franchise",
    shape: "case",
    title: "A hotel chain is deciding between owning and franchising its next 50 hotels.",
    type: "Business model",
    difficulty: 2,
    minutes: 30,
    answer: "Franchise for speed and capital efficiency, own in a few flagship locations where brand control genuinely matters.",
    hints: ["Owning is a real estate business. Franchising is a brand business. They have different returns entirely."],
    moves: [
      { label: "Move 1", text: "Separate the two economics. Owning captures property appreciation and full margin but consumes capital." },
      { label: "Move 2", text: "Franchising trades margin for speed. Fee income is smaller per hotel but scales without balance sheet strain." },
      { label: "Move 3", text: "Weigh brand risk. A poorly run franchise damages the brand across all properties." },
      { label: "Move 4", text: "Consider a hybrid: own flagships in top cities, franchise the long tail." },
      { label: "Close", text: "Give the split and name the standards regime that makes franchising safe. Without that the recommendation is incomplete." },
    ],
    pitfalls: [
      "Comparing absolute profit per hotel while ignoring capital employed.",
      "Ignoring brand risk from inconsistent franchisee operations.",
      "Forcing a binary when a hybrid is the standard industry answer.",
    ],
  },
  {
    slug: "cement-company-state-expansion",
    shape: "case",
    title: "A cement company must choose which state to expand into.",
    type: "Market entry",
    difficulty: 3,
    minutes: 30,
    answer: "Whichever state is within economical freight distance of a viable limestone source and is short of local capacity. Demand alone does not decide it.",
    hints: ["Cement cannot travel far economically. Geography constrains this more than market size does."],
    moves: [
      { label: "Move 1", text: "Establish the freight constraint. Cement is low value per tonne, so economics decay sharply beyond a few hundred kilometres." },
      { label: "Move 2", text: "Map limestone availability, since a plant must sit near its raw material, not near its customers." },
      { label: "Move 3", text: "Assess regional supply and demand balance. A high-demand state already oversupplied is worse than a smaller undersupplied one." },
      { label: "Move 4", text: "Check regulatory and mining lease timelines, which frequently decide feasibility." },
      { label: "Close", text: "Recommend on the supply gap within the freight radius, and name the mining lease as the key risk." },
    ],
    pitfalls: [
      "Choosing on demand size alone and ignoring freight economics.",
      "Forgetting that limestone location, not customer location, anchors the plant.",
      "Ignoring existing regional capacity already under construction.",
    ],
  },
  {
    slug: "fmcg-quick-commerce-entry",
    shape: "case",
    title: "An FMCG firm is deciding whether to sell through quick commerce.",
    type: "Channel",
    difficulty: 2,
    minutes: 25,
    answer: "Yes, but with pack sizes and pricing built for the channel, and with an explicit view on how much it cannibalises general trade.",
    hints: ["The question is not whether to be there. It is what it does to your existing distributors."],
    moves: [
      { label: "Move 1", text: "Size the channel. Quick commerce is small nationally but large among urban high-value consumers." },
      { label: "Move 2", text: "Work the economics. Platform commissions, listing fees and higher return rates compress margin materially." },
      { label: "Move 3", text: "Assess channel conflict. General trade distributors react badly to being undercut on price." },
      { label: "Move 4", text: "Design channel-specific packs. Different sizes reduce direct price comparison and protect the distributor relationship." },
      { label: "Close", text: "Recommend entry with a pack architecture, and state the margin floor below which you would not list." },
    ],
    pitfalls: [
      "Ignoring channel conflict with distributors who carry the rest of the business.",
      "Listing identical packs at different prices across channels.",
      "Treating platform commission as the only incremental cost.",
    ],
  },
  {
    slug: "pharma-patent-expiry",
    shape: "case",
    title: "A pharma company faces patent expiry on its top-selling drug.",
    type: "Competitive response",
    difficulty: 3,
    minutes: 30,
    answer: "Accept the price collapse, defend volume through an authorised generic, and redeploy the cash into the pipeline. Fighting the erosion directly does not work.",
    hints: ["Patent cliffs are not survivable through pricing. Plan around the loss rather than against it."],
    moves: [
      { label: "Move 1", text: "Size the exposure. What share of revenue and, more importantly, of profit comes from this molecule." },
      { label: "Move 2", text: "Model the erosion. Generic entry typically takes most of the volume and collapses price within months." },
      { label: "Move 3", text: "Consider an authorised generic, which cannibalises deliberately but keeps some of the volume in-house." },
      { label: "Move 4", text: "Look at lifecycle options: new formulations, combinations or indications, while being honest that these rarely hold much." },
      { label: "Close", text: "Recommend on capital redeployment. The real decision is what the freed cash funds next." },
    ],
    pitfalls: [
      "Assuming brand loyalty protects a molecule after generic entry.",
      "Overstating what reformulation can defend.",
      "Sizing the revenue exposure but not the profit exposure, which is far larger.",
    ],
  },
  {
    slug: "bank-closing-half-its-branches",
    shape: "case",
    title: "A bank is deciding whether to close half its branches.",
    type: "Cost reduction",
    difficulty: 3,
    minutes: 30,
    answer: "Close selectively, not by half. Branches acquire deposits and serve older customers, so the ones to keep are defined by deposit franchise, not by transaction count.",
    hints: ["A branch does two different jobs. Transactions have moved online. Deposit gathering has not."],
    moves: [
      { label: "Move 1", text: "Separate the branch's functions: transactions, sales and deposit gathering. Only the first has genuinely migrated." },
      { label: "Move 2", text: "Segment customers. Older and rural customers still transact in person, and often hold the stickiest deposits." },
      { label: "Move 3", text: "Value each branch on deposits sourced, not footfall. Low-traffic branches can be highly valuable." },
      { label: "Move 4", text: "Model the deposit runoff risk of closure, which can cost more than the branch ever did." },
      { label: "Close", text: "Recommend a targeted closure list with a deposit retention plan attached, and name what you would do before closing any." },
    ],
    pitfalls: [
      "Ranking branches by transaction volume, which measures the wrong job.",
      "Ignoring deposit flight when a branch closes.",
      "Applying a uniform percentage target to a decision that must be branch by branch.",
    ],
  },
  {
    slug: "apparel-retailer-rising-inventory",
    shape: "case",
    title: "An apparel retailer has rising inventory and flat sales. Diagnose it.",
    type: "Operations",
    difficulty: 2,
    minutes: 30,
    answer: "A buying and planning failure, not a demand failure. Assortment was bought against a forecast the market did not deliver, and markdowns were taken too late.",
    hints: ["Inventory rising against flat sales is almost always a buying problem, not a selling problem."],
    moves: [
      { label: "Move 1", text: "Split inventory by age and category. Fresh stock rising is different from ageing stock accumulating." },
      { label: "Move 2", text: "Check sell-through by collection. A few bad buys can distort the whole position." },
      { label: "Move 3", text: "Examine markdown timing. Apparel loses value fast, so late markdowns compound the problem." },
      { label: "Move 4", text: "Test the forecasting process, including how much was bought on last year's numbers versus current signal." },
      { label: "Close", text: "Recommend both a clearance plan for the existing position and a change to the buying process, since one without the other repeats the problem." },
    ],
    pitfalls: [
      "Treating it as a demand problem and reaching for marketing spend.",
      "Looking at total inventory without ageing it.",
      "Clearing the stock without fixing the buying process that created it.",
    ],
  },
  {
    slug: "logistics-own-fleet-versus-aggregator",
    shape: "case",
    title: "A logistics firm is choosing between its own fleet and aggregators.",
    type: "Make or buy",
    difficulty: 2,
    minutes: 25,
    answer: "Own the base load, buy the peak. Owning everything strands capital in idle trucks and buying everything surrenders reliability.",
    hints: ["Demand is not flat. Split it into base and peak before deciding anything."],
    moves: [
      { label: "Move 1", text: "Profile demand. Almost all freight businesses have a stable base and a volatile peak." },
      { label: "Move 2", text: "Compare cost per trip. Owned trucks are cheaper when utilised and expensive when idle." },
      { label: "Move 3", text: "Weigh service quality. Own drivers give control over reliability and handling, which matters for some cargo." },
      { label: "Move 4", text: "Test the balance sheet effect. Owning consumes capital that could fund network expansion instead." },
      { label: "Close", text: "Recommend the split explicitly, naming the utilisation threshold above which owning wins." },
    ],
    pitfalls: [
      "Comparing cost per trip at full utilisation, which never happens.",
      "Ignoring the capital cost of ownership.",
      "Treating this as binary when the industry answer is a mix.",
    ],
  },
  {
    slug: "pe-fund-hospital-chain",
    shape: "case",
    title: "A private equity fund is evaluating a regional hospital chain.",
    type: "Due diligence",
    difficulty: 3,
    minutes: 35,
    answer: "Invest only if the chain's performance survives without its founding doctors. Hospital value that walks out of the building is not value you can buy.",
    hints: ["In healthcare, the asset is often the clinician, not the building. Test whether that is the case here."],
    moves: [
      { label: "Move 1", text: "Test revenue concentration by doctor. If a few consultants drive most admissions, the business is those individuals." },
      { label: "Move 2", text: "Check occupancy and case mix. High-margin specialities behave very differently from general beds." },
      { label: "Move 3", text: "Examine payer mix. Government scheme patients pay far less than cash or insured ones, and shift margin sharply." },
      { label: "Move 4", text: "Assess expansion headroom. Growth in healthcare needs clinicians as much as capital, and they are scarce." },
      { label: "Close", text: "Recommend conditional on doctor retention terms, and say what valuation you would pay without them." },
    ],
    pitfalls: [
      "Valuing beds and equipment while ignoring clinician dependence.",
      "Averaging across specialities with completely different margins.",
      "Assuming capital alone unlocks growth in a supply-constrained profession.",
    ],
  },
  {
    slug: "sugar-mill-ethanol-investment",
    shape: "case",
    title: "A sugar mill is deciding whether to invest in ethanol capacity.",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 30,
    answer: "Yes if the blending mandate and procurement price hold, but the entire return depends on policy, which makes this a regulatory bet dressed as a capex decision.",
    hints: ["Work out what fraction of the return depends on a government decision that could change."],
    moves: [
      { label: "Move 1", text: "Establish the economics. Diverting cane juice to ethanol trades sugar revenue for fuel revenue." },
      { label: "Move 2", text: "Model both price paths. Sugar prices are cyclical and ethanol prices are administered, so the risk profiles differ completely." },
      { label: "Move 3", text: "Value the flexibility. A dual-feed plant can switch between outputs, which is worth paying for." },
      { label: "Move 4", text: "Size the policy risk. Blending targets and procurement prices are set by government and have changed before." },
      { label: "Close", text: "Recommend the flexible configuration, and state the ethanol price below which the investment fails." },
    ],
    pitfalls: [
      "Treating administered prices as if they were market prices.",
      "Ignoring the value of being able to switch outputs.",
      "Building a case on current policy with no downside scenario.",
    ],
  },
  {
    slug: "it-services-losing-to-ai-natives",
    shape: "case",
    title: "An IT services firm is losing deals to AI-native competitors.",
    type: "Competitive response",
    difficulty: 3,
    minutes: 30,
    answer: "The threat is to the pricing model, not the client relationship. Move from billing hours to billing outcomes before clients force the change.",
    hints: ["Ask what the competitor is actually undercutting: the work, or the way the work is priced."],
    moves: [
      { label: "Move 1", text: "Diagnose the loss. Losing on price, on capability, or on the client's belief that fewer people are now needed." },
      { label: "Move 2", text: "Recognise the structural issue. A headcount-based model is threatened by anything that reduces headcount per outcome." },
      { label: "Move 3", text: "Test the relationship moat. Deep domain knowledge and integration depth are harder to displace than the coding itself." },
      { label: "Move 4", text: "Reprice deliberately. Outcome-based contracts let productivity gains be captured rather than passed through." },
      { label: "Close", text: "Recommend the pricing shift with a pilot account named, since a wholesale change is unrealistic." },
    ],
    pitfalls: [
      "Responding with rate cuts, which accelerates the collapse of the model.",
      "Assuming client relationships alone will hold once value is questioned.",
      "Treating this as a technology problem rather than a business model problem.",
    ],
  },
  {
    slug: "carmaker-electric-platform-decision",
    shape: "case",
    title: "A car maker is deciding whether to build a dedicated electric platform.",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 35,
    answer: "Build it if volumes over the platform's life clear the fixed cost. Converted petrol platforms are cheaper now and uncompetitive later.",
    hints: ["Compare against the alternative of adapting an existing platform, including what that costs in product quality."],
    moves: [
      { label: "Move 1", text: "Size the investment. A dedicated platform is a multi-year, multi-thousand-crore commitment." },
      { label: "Move 2", text: "Compare the converted alternative. Cheaper, faster, but compromised on range, packaging and cost per unit." },
      { label: "Move 3", text: "Forecast volumes over the platform life, not just next year, since amortisation depends on the whole run." },
      { label: "Move 4", text: "Consider partnering or licensing a platform, which several manufacturers have chosen instead of building." },
      { label: "Close", text: "Recommend with a volume threshold. Below it, partner. Above it, build." },
    ],
    pitfalls: [
      "Deciding on current-year electric volumes rather than lifetime volumes.",
      "Ignoring the partnering option entirely.",
      "Underweighting the product compromises of a converted platform.",
    ],
  },
  {
    slug: "chemical-plant-sixty-percent-capacity",
    shape: "case",
    title: "A chemical plant is running at 60% capacity. What would you do?",
    type: "Operations",
    difficulty: 3,
    minutes: 30,
    answer: "Find out whether the constraint is demand, feedstock or a bottleneck step. Each has a completely different answer, and only one of them is solved by selling harder.",
    hints: ["Sixty percent could mean three entirely different problems. Establish which before proposing anything."],
    moves: [
      { label: "Move 1", text: "Test demand. If the order book is thin, this is a commercial problem and capacity is a symptom." },
      { label: "Move 2", text: "Test feedstock. Chemical plants often run below capacity because an input is constrained or uneconomic." },
      { label: "Move 3", text: "Test the process. A single bottleneck step can cap the whole line regardless of demand." },
      { label: "Move 4", text: "Consider toll manufacturing for third parties, which fills capacity without needing new customers." },
      { label: "Close", text: "Recommend against the specific constraint found, and say what data would confirm it." },
    ],
    pitfalls: [
      "Assuming low utilisation always means weak demand.",
      "Proposing a sales push before checking whether the plant could even serve it.",
      "Missing toll manufacturing, which is standard practice in the industry.",
    ],
  },
  {
    slug: "jewellery-chain-franchise-decision",
    shape: "case",
    title: "A jewellery chain is deciding between franchised and owned stores.",
    type: "Business model",
    difficulty: 2,
    minutes: 30,
    answer: "Own in the top markets, franchise in smaller towns, because the inventory funding requirement is what makes jewellery franchising attractive at all.",
    hints: ["Jewellery inventory is enormously expensive. Ask who funds it in each model."],
    moves: [
      { label: "Move 1", text: "Recognise the inventory problem. A jewellery store carries crores of rupees of stock before selling anything." },
      { label: "Move 2", text: "Note that franchising shifts that funding burden, which is the real reason the model exists here." },
      { label: "Move 3", text: "Weigh the trust risk. Jewellery is a purity and authenticity purchase, so a bad franchisee is catastrophic." },
      { label: "Move 4", text: "Consider hallmarking, buyback policies and audit as the controls that make franchising survivable." },
      { label: "Close", text: "Recommend the geography split, and name the control regime without which you would not franchise at all." },
    ],
    pitfalls: [
      "Treating this as a standard retail franchising question and missing the inventory funding issue.",
      "Underestimating brand damage from a purity scandal at one franchise.",
      "Ignoring gold price risk, which sits with whoever holds the stock.",
    ],
  },
  {
    slug: "media-company-streaming-launch",
    shape: "case",
    title: "A media company is deciding whether to launch its own streaming service.",
    type: "Market entry",
    difficulty: 3,
    minutes: 30,
    answer: "Probably not alone. Unless the content library is genuinely differentiated, licensing to existing platforms earns more than subsidising subscriber acquisition against global players.",
    hints: ["Compare the value of licensing content out against the cost of acquiring subscribers yourself."],
    moves: [
      { label: "Move 1", text: "Value the library. Streaming economics rest on content people cannot get elsewhere." },
      { label: "Move 2", text: "Size the subscriber cost. Acquisition is expensive and churn in India is high at any meaningful price point." },
      { label: "Move 3", text: "Compare the licensing alternative, which is certain revenue with no technology or marketing spend." },
      { label: "Move 4", text: "Consider the hybrid: an ad-funded free tier that monetises reach rather than subscriptions." },
      { label: "Close", text: "Recommend licensing unless a named piece of content justifies going alone, and say what that content would need to be." },
    ],
    pitfalls: [
      "Assuming a content library automatically converts to subscribers.",
      "Ignoring technology and marketing costs, which dwarf content spend early on.",
      "Applying Western subscription pricing to the Indian market.",
    ],
  },
  {
    slug: "university-second-campus",
    shape: "case",
    title: "A university is deciding whether to open a second campus.",
    type: "Growth",
    difficulty: 2,
    minutes: 30,
    answer: "Only if faculty can be recruited at the same standard. Capital is available, reputation is not transferable, and a weak second campus damages the first.",
    hints: ["Ask what the university is actually selling. It is usually reputation, and reputation does not copy across easily."],
    moves: [
      { label: "Move 1", text: "Establish what drives demand: placement outcomes, faculty quality and brand, in roughly that order." },
      { label: "Move 2", text: "Test whether those transfer. A new campus starts with the brand but none of the placement track record." },
      { label: "Move 3", text: "Size the faculty constraint. Recruiting a full faculty at the same standard is usually harder than funding the buildings." },
      { label: "Move 4", text: "Consider alternatives: expanding the existing campus, or online programmes that use existing faculty." },
      { label: "Close", text: "Recommend against unless faculty recruitment is solved first, and state that dilution risk is the reason." },
    ],
    pitfalls: [
      "Treating this as a real estate and capital question.",
      "Assuming brand transfers fully to a campus with no outcomes history.",
      "Ignoring the risk that a weak second campus damages the original.",
    ],
  },
  {
    slug: "tyre-maker-raw-material-shock",
    shape: "case",
    title: "A tyre maker faces a sudden rubber price shock. What now?",
    type: "Pricing",
    difficulty: 2,
    minutes: 25,
    answer: "Pass through in the replacement market where pricing power exists, absorb temporarily in original equipment where contracts bind, and hedge the exposure going forward.",
    hints: ["The two customer channels have completely different pricing power. Treat them separately."],
    moves: [
      { label: "Move 1", text: "Split the business. Original equipment sales to car makers are contracted, replacement sales to consumers are not." },
      { label: "Move 2", text: "Test pass-through in replacement, where brand and availability give real pricing power." },
      { label: "Move 3", text: "Examine the OEM contracts for raw material escalation clauses, which often exist but lag." },
      { label: "Move 4", text: "Look at substitution and mix. Synthetic rubber content and product mix shift can absorb part of the shock." },
      { label: "Close", text: "Recommend differential pricing by channel plus a hedging policy, and note that competitors face the same shock." },
    ],
    pitfalls: [
      "Applying one pricing response across both channels.",
      "Ignoring escalation clauses already in OEM contracts.",
      "Forgetting that competitors are equally affected, which changes what the market will bear.",
    ],
  },
  {
    slug: "cooperative-bank-merger",
    shape: "case",
    title: "A cooperative bank is deciding whether to merge with a larger peer.",
    type: "M&A",
    difficulty: 3,
    minutes: 30,
    answer: "Merge if the capital position genuinely constrains growth. Independence is worth little if the bank cannot lend, but the local relationship advantage is real and easily destroyed.",
    hints: ["Establish whether the bank is merging from strength or from weakness. The answer differs completely."],
    moves: [
      { label: "Move 1", text: "Diagnose the motivation. Capital adequacy pressure, technology cost, or regulatory burden each imply different terms." },
      { label: "Move 2", text: "Value the local franchise. Cooperative banks lend on relationships larger banks cannot replicate." },
      { label: "Move 3", text: "Test whether that advantage survives the merger, since centralised credit processes usually erode it." },
      { label: "Move 4", text: "Examine alternatives: a technology partnership or capital raise that solves the constraint without losing independence." },
      { label: "Close", text: "Recommend based on whether the binding constraint is capital or capability, and say which you found." },
    ],
    pitfalls: [
      "Treating this as a pure financial transaction and ignoring the relationship franchise.",
      "Not distinguishing merging from strength versus distress.",
      "Missing the alternatives that solve the constraint without a merger.",
    ],
  },
  {
    slug: "airline-routes-versus-frequency",
    shape: "case",
    title: "An airline must choose between adding routes and adding frequency.",
    type: "Growth",
    difficulty: 2,
    minutes: 25,
    answer: "Frequency on proven routes first. It attracts the business traveller who pays the fare that makes the network profitable, and carries far less risk than a new destination.",
    hints: ["Ask which choice serves the higher-yielding passenger."],
    moves: [
      { label: "Move 1", text: "Understand who pays. Business travellers pay premium fares and value schedule choice above almost everything." },
      { label: "Move 2", text: "Note that frequency compounds. More departures make a route materially more attractive to that traveller." },
      { label: "Move 3", text: "Weigh new route risk. An unproven destination takes seasons to mature and may never do so." },
      { label: "Move 4", text: "Check the constraint. Slots at congested airports may make the choice for you." },
      { label: "Close", text: "Recommend frequency on the highest-yield existing routes, with new routes funded only from surplus aircraft." },
    ],
    pitfalls: [
      "Treating all passengers as equally valuable.",
      "Ignoring slot availability, which often decides this in practice.",
      "Underestimating how long a new route takes to mature.",
    ],
  },
  {
    slug: "snack-brand-failed-launch",
    shape: "case",
    title: "A snack brand's new product failed at launch. Why?",
    type: "Root cause",
    difficulty: 2,
    minutes: 30,
    answer: "Establish whether people did not buy it or could not find it. Distribution failure and product failure look identical in the sales data and have opposite fixes.",
    hints: ["Trial and repeat are different failures. Separate them before doing anything else."],
    moves: [
      { label: "Move 1", text: "Check distribution first. If the product never reached shelves, nothing about the product is proven." },
      { label: "Move 2", text: "Split trial from repeat. Low trial is an awareness or availability problem, low repeat is a product problem." },
      { label: "Move 3", text: "Examine price and pack. In Indian snacking, the price point often matters more than the taste." },
      { label: "Move 4", text: "Review the competitive shelf. A crowded category may have left no visible space for a new entrant." },
      { label: "Close", text: "Recommend against the specific failure found, and say what you would test before relaunching." },
    ],
    pitfalls: [
      "Concluding the product failed when it was never properly distributed.",
      "Looking at total sales without splitting trial and repeat.",
      "Recommending a relaunch without changing what caused the failure.",
    ],
  },
  {
    slug: "pesticide-firm-regulatory-ban",
    shape: "case",
    title: "A pesticide firm faces a regulatory ban on its main product.",
    type: "Regulatory",
    difficulty: 3,
    minutes: 30,
    answer: "Assume the ban holds and move. Reformulate where possible, redirect to unaffected export markets in the interim, and accept a smaller business.",
    hints: ["Do not build the recommendation on the ban being reversed. Plan for it holding."],
    moves: [
      { label: "Move 1", text: "Size the exposure by revenue, profit and manufacturing asset specificity, since a dedicated plant is stranded." },
      { label: "Move 2", text: "Check the export option. Some markets may still permit the product, buying transition time." },
      { label: "Move 3", text: "Assess reformulation. A related molecule may serve the same crop problem within the rules." },
      { label: "Move 4", text: "Examine the customer relationship. Farmers and dealers buy a portfolio, so the risk is losing the whole basket." },
      { label: "Close", text: "Recommend a transition plan with a timeline, and be explicit that the business ends up smaller." },
    ],
    pitfalls: [
      "Building the plan around lobbying the ban away.",
      "Ignoring stranded manufacturing assets.",
      "Missing that losing one product can cost the whole dealer relationship.",
    ],
  },
  {
    slug: "steel-trader-backward-integration",
    shape: "case",
    title: "A steel trader is deciding whether to integrate backwards into production.",
    type: "Make or buy",
    difficulty: 3,
    minutes: 30,
    answer: "Almost certainly not. Trading and manufacturing are different businesses with different capital intensity and cycles, and the trader's advantage is relationships, not assets.",
    hints: ["Ask what the trader is actually good at, and whether that skill helps at all in manufacturing."],
    moves: [
      { label: "Move 1", text: "Define the current advantage. Traders win on relationships, working capital and market timing." },
      { label: "Move 2", text: "Test whether that transfers. Manufacturing rewards operational discipline and scale, which are unrelated skills." },
      { label: "Move 3", text: "Size the capital gap. A steel plant costs orders of magnitude more than a trading book." },
      { label: "Move 4", text: "Note the cycle risk. A trader can shrink in a downturn, a plant cannot, so integration removes the flexibility that protects them." },
      { label: "Close", text: "Recommend against, and offer the alternative of long-term supply agreements that capture some benefit without the capital." },
    ],
    pitfalls: [
      "Assuming margin capture justifies the move without asking about capability.",
      "Ignoring how differently the two businesses behave in a downturn.",
      "Missing the contractual alternatives to full integration.",
    ],
  },
  {
    slug: "tower-company-portfolio-sale",
    shape: "case",
    title: "A telecom tower company is deciding whether to sell its portfolio.",
    type: "Divestiture",
    difficulty: 3,
    minutes: 30,
    answer: "Sell if the buyer values the contracted cash flows more highly than the market values them inside the parent, which is usually the case for infrastructure assets.",
    hints: ["Ask whether these assets are worth more to someone else than to the current owner, and why."],
    moves: [
      { label: "Move 1", text: "Characterise the asset. Towers are long-dated, contracted, inflation-linked cash flows, which is what infrastructure funds want." },
      { label: "Move 2", text: "Test the valuation gap. Such assets often trade at higher multiples standalone than inside a telecom operator." },
      { label: "Move 3", text: "Assess the strategic cost. Selling means renting back capacity and losing control over a critical input." },
      { label: "Move 4", text: "Check tenancy ratios. Towers with multiple operators are worth far more than single-tenant ones." },
      { label: "Close", text: "Recommend on the multiple gap, with the leaseback terms named as the condition that makes or breaks it." },
    ],
    pitfalls: [
      "Valuing the towers on cost rather than on contracted cash flow.",
      "Ignoring leaseback obligations, which reverse much of the benefit.",
      "Missing tenancy ratio, which is the single biggest driver of tower value.",
    ],
  },
  {
    slug: "hospital-cardiac-unit-decision",
    shape: "case",
    title: "A hospital is deciding whether to add a cardiac unit.",
    type: "Capital allocation",
    difficulty: 2,
    minutes: 30,
    answer: "Yes if the cardiologist can be recruited and the catchment supports the case volume. Equipment is the easy part, and the least of the risk.",
    hints: ["Cardiac care is high margin and high fixed cost. Volume is what decides it."],
    moves: [
      { label: "Move 1", text: "Size the catchment. Cardiac procedures per lakh population, applied to the realistic draw area." },
      { label: "Move 2", text: "Check competition. Patients travel for cardiac care, so a strong nearby centre takes the volume regardless of proximity." },
      { label: "Move 3", text: "Model the economics. High fixed cost in equipment and staff means the unit needs minimum volume to break even." },
      { label: "Move 4", text: "Confront the clinician constraint. Without a reputed cardiologist the unit will not attract referrals at all." },
      { label: "Close", text: "Recommend conditional on recruitment, and state the monthly case volume needed to justify it." },
    ],
    pitfalls: [
      "Treating this as an equipment purchase decision.",
      "Assuming patients choose the nearest hospital for major procedures.",
      "Not calculating the break-even case volume.",
    ],
  },
  {
    slug: "cab-aggregator-owning-vehicles",
    shape: "case",
    title: "A cab aggregator is deciding whether to own its vehicles.",
    type: "Business model",
    difficulty: 3,
    minutes: 30,
    answer: "Own a limited fleet for supply reliability at peak and for premium categories, but not broadly. Ownership converts an asset-light platform into a fleet operator.",
    hints: ["The aggregator's valuation rests on being asset-light. Ask what owning does to that."],
    moves: [
      { label: "Move 1", text: "Define the problem being solved. Owning is usually about supply reliability and service consistency, not about margin." },
      { label: "Move 2", text: "Size the economics. Owned vehicles carry depreciation, maintenance, insurance and driver employment costs." },
      { label: "Move 3", text: "Test the alternative. Better driver incentives may fix supply more cheaply than buying cars." },
      { label: "Move 4", text: "Consider the electric angle, where high vehicle cost and low running cost can justify ownership that petrol cannot." },
      { label: "Close", text: "Recommend a limited owned fleet with a named purpose, and reject broad ownership explicitly." },
    ],
    pitfalls: [
      "Ignoring what asset ownership does to the platform's capital requirements.",
      "Missing driver incentives as the cheaper solution to the same problem.",
      "Treating utilisation as guaranteed when demand is peaked.",
    ],
  },
  {
    slug: "textile-exporter-currency-swing",
    shape: "case",
    title: "A textile exporter is hit by a sharp currency move. How should it respond?",
    type: "Risk",
    difficulty: 2,
    minutes: 25,
    answer: "Establish the net exposure first. Exporters with imported inputs are far less exposed than the revenue line suggests, and hedging the gross number is a common and expensive error.",
    hints: ["Exports earn foreign currency but inputs may cost it too. Net the two before doing anything."],
    moves: [
      { label: "Move 1", text: "Calculate net exposure. Foreign currency revenue minus foreign currency costs, not revenue alone." },
      { label: "Move 2", text: "Check competitor exposure. If rivals in other countries face the same move, relative position may be unchanged." },
      { label: "Move 3", text: "Test pricing. Contracts may be fixed in the short term, so the pass-through timing matters." },
      { label: "Move 4", text: "Review hedging policy, since the real failure is usually the absence of a policy rather than this particular move." },
      { label: "Close", text: "Recommend a hedging framework on net exposure, and note that a favourable move is equally a matter of luck." },
    ],
    pitfalls: [
      "Hedging gross revenue rather than net exposure.",
      "Ignoring that competitors in other countries face their own currency moves.",
      "Treating a windfall as performance rather than as an unhedged bet that happened to pay.",
    ],
  },
  {
    slug: "conglomerate-which-business-to-divest",
    shape: "case",
    title: "A conglomerate must divest one business. Which one?",
    type: "Divestiture",
    difficulty: 3,
    minutes: 35,
    answer: "The one worth more to someone else than to the group. That is usually the business with no shared capability, not simply the weakest performer.",
    hints: ["The worst-performing business is not automatically the right one to sell. Ask who the natural owner is."],
    moves: [
      { label: "Move 1", text: "Assess each business on returns above cost of capital, not on absolute profit." },
      { label: "Move 2", text: "Test the parenting advantage. Does the group add anything to this business, or merely own it?" },
      { label: "Move 3", text: "Identify the natural owner. A buyer with genuine synergies will pay more than the asset is worth standalone." },
      { label: "Move 4", text: "Check entanglement. Shared brand, plants or people can make a business hard to separate cleanly." },
      { label: "Close", text: "Recommend the business with the widest gap between buyer value and group value, and say what the proceeds fund." },
    ],
    pitfalls: [
      "Selling the weakest performer without asking who would pay most.",
      "Ignoring separation complexity, which can destroy the value of the deal.",
      "Not saying what the freed capital is for.",
    ],
  },
  {
    slug: "fertiliser-subsidy-reform",
    shape: "case",
    title: "A fertiliser company faces reform of the subsidy regime.",
    type: "Regulatory",
    difficulty: 3,
    minutes: 30,
    answer: "Shift the mix toward products less dependent on subsidy and build direct farmer relationships, since a business whose margin is set by policy has no pricing power to defend.",
    hints: ["Work out how much of current margin is administered rather than earned."],
    moves: [
      { label: "Move 1", text: "Decompose margin. Separate what comes from subsidy from what comes from genuine market pricing." },
      { label: "Move 2", text: "Model the reform scenarios, including direct benefit transfer, which changes who the customer effectively is." },
      { label: "Move 3", text: "Assess the product mix. Speciality and micronutrient products sit outside the main subsidy regime." },
      { label: "Move 4", text: "Consider the working capital effect, since subsidy receivables from government tie up enormous cash." },
      { label: "Close", text: "Recommend a mix shift with a timeline, and note that reform may improve cash flow even as it compresses margin." },
    ],
    pitfalls: [
      "Assuming subsidy-driven margin is defensible margin.",
      "Ignoring the working capital implications, which are often the bigger effect.",
      "Planning around one scenario when policy outcomes are genuinely uncertain.",
    ],
  },
  {
    slug: "bakery-central-versus-instore",
    shape: "case",
    title: "A bakery chain is choosing between central and in-store production.",
    type: "Operations",
    difficulty: 2,
    minutes: 25,
    answer: "Central production for shelf-stable lines, in-store for anything sold on freshness. The split follows the product, not the cost curve.",
    hints: ["Not all bakery products have the same shelf life. That difference decides the answer."],
    moves: [
      { label: "Move 1", text: "Segment the range by shelf life. Bread and cakes behave very differently from cookies and packaged items." },
      { label: "Move 2", text: "Compare cost. Central production is cheaper per unit through scale but adds distribution cost and time." },
      { label: "Move 3", text: "Value freshness. In-store baking is a customer proposition, including the smell, not just a production choice." },
      { label: "Move 4", text: "Consider the hybrid: centrally prepared frozen dough, baked in store, which most chains actually use." },
      { label: "Close", text: "Recommend the hybrid with the product split named, and state the wastage assumption it depends on." },
    ],
    pitfalls: [
      "Optimising purely on production cost per unit.",
      "Ignoring wastage, which is high in fresh bakery and changes the comparison.",
      "Missing the par-baked hybrid that resolves most of the tension.",
    ],
  },
  {
    slug: "shipping-line-charter-versus-buy",
    shape: "case",
    title: "A shipping line is deciding whether to charter or buy vessels.",
    type: "Make or buy",
    difficulty: 3,
    minutes: 30,
    answer: "Own the core capacity, charter the swing. Shipping is violently cyclical and owning through a downturn is what has historically destroyed shipping companies.",
    hints: ["Ask what happens to each option when freight rates collapse. That is the real test."],
    moves: [
      { label: "Move 1", text: "Establish the cycle. Freight rates swing enormously, and vessel prices move with them." },
      { label: "Move 2", text: "Compare commitments. Owning is a decades-long bet, chartering can be as short as a single voyage." },
      { label: "Move 3", text: "Note the timing trap. Vessels are cheapest exactly when nobody has the money or nerve to buy." },
      { label: "Move 4", text: "Model the downturn. An owned fleet with debt against it is the standard failure mode in shipping." },
      { label: "Close", text: "Recommend a core-plus-swing structure, and name the freight rate level at which you would buy." },
    ],
    pitfalls: [
      "Deciding on current freight rates rather than through-cycle economics.",
      "Ignoring the debt service obligation that survives a downturn.",
      "Missing that vessel asset value moves with rates, so both sides fall together.",
    ],
  },
  {
    slug: "power-producer-early-coal-shutdown",
    shape: "case",
    title: "A power producer is deciding whether to shut a coal plant early.",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 30,
    answer: "Depends almost entirely on the power purchase agreement. A contracted plant earns capacity payments regardless of dispatch, which changes the arithmetic completely.",
    hints: ["Find out how the plant earns money before assessing whether to close it."],
    moves: [
      { label: "Move 1", text: "Read the contract. Many Indian plants earn fixed capacity charges whether or not they generate." },
      { label: "Move 2", text: "Compare marginal economics. If variable cost exceeds the merit order clearing price, the plant rarely runs anyway." },
      { label: "Move 3", text: "Size the closure cost, including decommissioning, land remediation and workforce obligations." },
      { label: "Move 4", text: "Consider repurposing. The grid connection and land may be more valuable for renewables plus storage." },
      { label: "Close", text: "Recommend on contract structure first, and name repurposing as the option that preserves the connection asset." },
    ],
    pitfalls: [
      "Assessing on generation economics while ignoring capacity payments.",
      "Forgetting decommissioning liabilities.",
      "Missing that the grid connection is often the most valuable remaining asset.",
    ],
  },
  {
    slug: "retailer-own-delivery-fleet",
    shape: "case",
    title: "A retailer is deciding whether to build its own delivery fleet.",
    type: "Make or buy",
    difficulty: 2,
    minutes: 25,
    answer: "Only in the densest zones where volume supports it. Elsewhere third-party logistics is cheaper, and density, not total volume, is what decides.",
    hints: ["Delivery economics are driven by drops per kilometre. Ask where that number is high enough."],
    moves: [
      { label: "Move 1", text: "Establish the cost driver. Cost per delivery falls sharply with drop density, not with total order count." },
      { label: "Move 2", text: "Map order density by area. A few zones will be far denser than the average." },
      { label: "Move 3", text: "Compare against third-party pricing, which is effectively a fixed rate regardless of your density." },
      { label: "Move 4", text: "Weigh service control. Owning delivery controls the last customer touchpoint, which matters for returns and complaints." },
      { label: "Close", text: "Recommend own fleet in named high-density zones and third party elsewhere, with a density threshold stated." },
    ],
    pitfalls: [
      "Comparing average cost per delivery across a whole city.",
      "Ignoring the fixed cost of fleet management overhead.",
      "Treating the choice as all or nothing.",
    ],
  },
  {
    slug: "two-wheeler-maker-export-entry",
    shape: "case",
    title: "A two-wheeler maker is entering an African export market.",
    type: "Market entry",
    difficulty: 2,
    minutes: 30,
    answer: "Enter through a local distributor with a service network committed upfront. Product fit is rarely the problem, after-sales is.",
    hints: ["Selling the first bike is easy. Ask what happens when it needs a spare part."],
    moves: [
      { label: "Move 1", text: "Size the market. Motorcycle demand is largely commercial, since two-wheeler taxis dominate many African cities." },
      { label: "Move 2", text: "Test the product fit. Commercial use means load, road condition and durability matter more than styling." },
      { label: "Move 3", text: "Solve after-sales. Spare parts availability and trained mechanics determine repeat purchase and brand reputation." },
      { label: "Move 4", text: "Choose the model. Distributor, joint venture or assembly, weighing local content rules and import duty." },
      { label: "Close", text: "Recommend the entry mode with the service network commitment as an explicit precondition." },
    ],
    pitfalls: [
      "Assuming an Indian product specification transfers unchanged.",
      "Treating after-sales as a later phase rather than an entry requirement.",
      "Ignoring local assembly rules that materially change landed cost.",
    ],
  },
  {
    slug: "hospital-doctor-attrition",
    shape: "case",
    title: "A hospital chain has rising doctor attrition. Fix it.",
    type: "Organisation",
    difficulty: 2,
    minutes: 30,
    answer: "Find out where they are going. Doctors leaving for their own practice need a different answer entirely from doctors leaving for a competitor.",
    hints: ["Segment the leavers before designing anything. Their destinations tell you the cause."],
    moves: [
      { label: "Move 1", text: "Segment by destination. Competitor hospitals, independent practice, or abroad each imply a different problem." },
      { label: "Move 2", text: "Segment by seniority. Losing senior consultants who bring patient volume is far costlier than losing juniors." },
      { label: "Move 3", text: "Test the economics of leaving. If independent practice pays more, revenue-sharing rather than salary is the lever." },
      { label: "Move 4", text: "Examine non-financial factors: theatre time, equipment access, administrative load and clinical autonomy." },
      { label: "Close", text: "Recommend differentiated retention for the segment that actually drives revenue, and quantify what one departure costs." },
    ],
    pitfalls: [
      "Treating all attrition as one problem with one salary answer.",
      "Not costing a departure, including the patient volume that leaves with them.",
      "Assuming compensation is the driver without testing autonomy and workload.",
    ],
  },
  {
    slug: "packaged-food-acquiring-d2c",
    shape: "case",
    title: "A packaged food firm is considering acquiring a D2C brand.",
    type: "M&A",
    difficulty: 3,
    minutes: 30,
    answer: "Buy for the brand and consumer insight, not the revenue. Pay a distribution-synergy price only if you can put the product into general trade without breaking what made it work.",
    hints: ["Ask what the acquirer actually gets that it could not build. Usually it is brand equity and speed."],
    moves: [
      { label: "Move 1", text: "Value the target honestly. Most D2C brands are small in revenue and unprofitable at the point of sale." },
      { label: "Move 2", text: "Identify the real asset: a young brand with genuine consumer connection and product innovation speed." },
      { label: "Move 3", text: "Size the distribution synergy. Putting the product into a million outlets is the acquirer's actual contribution." },
      { label: "Move 4", text: "Assess integration risk. Corporate processes routinely destroy the agility that made the target attractive." },
      { label: "Close", text: "Recommend with an integration model, typically keeping the brand at arm's length, and name the price ceiling." },
    ],
    pitfalls: [
      "Valuing on revenue multiples when the asset is brand equity.",
      "Assuming distribution synergy is automatic rather than a channel-fit question.",
      "Integrating fully and destroying the culture that created the value.",
    ],
  },
  {
    slug: "airport-second-terminal",
    shape: "case",
    title: "An airport is deciding whether to build a second terminal.",
    type: "Capital allocation",
    difficulty: 3,
    minutes: 30,
    answer: "Check whether the terminal is even the constraint. Runway slots and airspace frequently bind first, and a new terminal then adds capacity that cannot be used.",
    hints: ["An airport has several constraints. Find which one actually binds before building anything."],
    moves: [
      { label: "Move 1", text: "Identify the binding constraint among runway movements, terminal floor area, apron stands and airspace." },
      { label: "Move 2", text: "If terminal area binds, size the shortfall against passenger forecasts, allowing for peak-hour rather than annual flow." },
      { label: "Move 3", text: "Consider cheaper alternatives: reconfiguring existing space, off-peak incentives, or remote stands with bussing." },
      { label: "Move 4", text: "Model the revenue upside, since retail and food per passenger is a large share of airport economics." },
      { label: "Close", text: "Recommend conditional on the constraint identified, and state the passenger threshold that triggers construction." },
    ],
    pitfalls: [
      "Assuming the terminal is the constraint because it is the visible one.",
      "Sizing on annual passengers rather than peak hour flow.",
      "Ignoring non-aeronautical revenue, which often justifies the investment.",
    ],
  },
  {
    slug: "dairy-pricing-milk-glut",
    shape: "case",
    title: "A dairy must decide how to price during a milk glut.",
    type: "Pricing",
    difficulty: 2,
    minutes: 25,
    answer: "Hold consumer prices and convert the surplus into powder and butter. Cutting the farmer procurement price solves this season and destroys next season's supply.",
    hints: ["A dairy has two prices to set. The one paid to farmers matters more over time than the one charged to consumers."],
    moves: [
      { label: "Move 1", text: "Separate the two decisions: procurement price to farmers and retail price to consumers." },
      { label: "Move 2", text: "Note that liquid milk demand is inelastic. Cutting retail price adds little volume and gives up margin." },
      { label: "Move 3", text: "Use conversion. Surplus milk becomes powder, butter and cheese, which store and carry the glut forward." },
      { label: "Move 4", text: "Protect the farmer relationship, since a procurement cut pushes suppliers to competitors and reduces future supply." },
      { label: "Close", text: "Recommend holding both prices and expanding conversion capacity, naming storage as the constraint." },
    ],
    pitfalls: [
      "Cutting the retail price into inelastic demand.",
      "Cutting procurement price and damaging long-term supply.",
      "Ignoring conversion and storage, which is the standard industry answer.",
    ],
  },
  {
    slug: "luxury-hotel-budget-brand",
    shape: "case",
    title: "A luxury hotel group is considering launching a budget brand.",
    type: "New product",
    difficulty: 2,
    minutes: 30,
    answer: "Yes, under a clearly separate name with separate service standards. The volume opportunity is real and the dilution risk is entirely a branding decision.",
    hints: ["Downward brand extension is the risky direction. Ask what protects the parent brand."],
    moves: [
      { label: "Move 1", text: "Size the opportunity. Mid-market and budget travel is far larger than luxury in room-nights." },
      { label: "Move 2", text: "Test capability transfer. Operating discipline and distribution transfer, but the cost base does not." },
      { label: "Move 3", text: "Assess dilution risk. A visible parent name on a budget property damages luxury pricing power." },
      { label: "Move 4", text: "Design the architecture. A distinct name with a quiet endorsement is how most groups have handled this." },
      { label: "Close", text: "Recommend the separate brand, and name the operating cost structure that must differ for the economics to work." },
    ],
    pitfalls: [
      "Extending the luxury name downward for short-term recognition.",
      "Assuming the luxury cost base can serve a budget price point.",
      "Ignoring that budget hotels are a distribution and occupancy game, not a service game.",
    ],
  },
  {
    slug: "edtech-post-pandemic-collapse",
    shape: "case",
    title: "An edtech company's revenue collapsed after schools reopened. What now?",
    type: "Turnaround",
    difficulty: 3,
    minutes: 35,
    answer: "Shrink to a defensible core: the segment that chose the product on merit rather than because schools were shut. Everything built on lockdown demand should be cut.",
    hints: ["Separate customers who were forced online from those who genuinely preferred it."],
    moves: [
      { label: "Move 1", text: "Segment the base. Test cohorts by whether retention held after reopening, which reveals genuine demand." },
      { label: "Move 2", text: "Confront the cost base, built for a growth rate that no longer exists and burning cash." },
      { label: "Move 3", text: "Find the defensible niche: exam preparation and supplementary learning have survived where general tutoring has not." },
      { label: "Move 4", text: "Consider the hybrid or offline model, which several Indian edtech firms moved to for exactly this reason." },
      { label: "Close", text: "Recommend a smaller, focused business with a named segment, and be explicit that most of the revenue is not coming back." },
    ],
    pitfalls: [
      "Treating the collapse as a marketing problem.",
      "Cutting costs proportionally rather than exiting segments entirely.",
      "Assuming the pandemic-era customer base will return.",
    ],
  },
  {
    slug: "mining-firm-downstream-processing",
    shape: "case",
    title: "A mining firm is deciding whether to move into downstream processing.",
    type: "Make or buy",
    difficulty: 3,
    minutes: 30,
    answer: "Only where the processing sits close to the mine and the product is expensive to transport. Otherwise this is a different business with different skills and worse returns.",
    hints: ["Ask whether integration is driven by real economics or by the appeal of a higher headline margin."],
    moves: [
      { label: "Move 1", text: "Test the transport logic. Processing near the mine makes sense when ore is bulky and the product is not." },
      { label: "Move 2", text: "Compare returns properly. Mining margins are often higher than processing margins, so integration can dilute." },
      { label: "Move 3", text: "Assess capability. Processing needs continuous operations discipline that mining organisations often lack." },
      { label: "Move 4", text: "Consider the cycle. Integration reduces exposure to commodity price swings, which cuts both ways." },
      { label: "Close", text: "Recommend narrowly, only where transport economics justify it, and reject the general case for integration." },
    ],
    pitfalls: [
      "Assuming capturing more of the value chain always improves returns.",
      "Ignoring the capability gap between extraction and processing.",
      "Missing that reduced cyclicality also caps the upside.",
    ],
  },
  {
    slug: "retailer-sunday-opening-new-market",
    shape: "case",
    title: "A retailer must decide whether to trade on Sundays in a new market.",
    type: "Operations",
    difficulty: 1,
    minutes: 20,
    answer: "Open if Sunday sales exceed the incremental cost of staffing it, but check first whether Sunday trade is genuinely new or simply shifted from Saturday.",
    hints: ["The question is whether Sunday sales are incremental or moved from another day."],
    moves: [
      { label: "Move 1", text: "Size expected Sunday sales from comparable stores in similar markets." },
      { label: "Move 2", text: "Test for cannibalisation. If customers merely shift from Saturday, the extra revenue is illusory." },
      { label: "Move 3", text: "Cost the day. Staffing, utilities and premium wages are real, and staff retention costs matter too." },
      { label: "Move 4", text: "Check local norms and regulation, since some markets have restrictions or simply low Sunday footfall." },
      { label: "Close", text: "Recommend on incremental contribution, and suggest testing in a few stores before committing the chain." },
    ],
    pitfalls: [
      "Counting all Sunday sales as incremental.",
      "Ignoring staff cost and morale effects.",
      "Rolling out chain-wide without a pilot.",
    ],
  },
  {
    slug: "cinema-chain-food-delivery",
    shape: "case",
    title: "A cinema chain is considering entering food delivery.",
    type: "Growth",
    difficulty: 2,
    minutes: 25,
    answer: "No. The kitchen capacity is real but it is idle at exactly the wrong hours, and the chain has no delivery capability or customer relationship outside the cinema.",
    hints: ["Check when the spare capacity exists and when delivery demand peaks. If they do not overlap, the idea fails."],
    moves: [
      { label: "Move 1", text: "Identify the supposed asset: kitchen capacity and prime locations sitting idle much of the day." },
      { label: "Move 2", text: "Compare timing. Cinema kitchens are busiest at evening show times, which is exactly when food delivery peaks." },
      { label: "Move 3", text: "Test the capability gap. Delivery needs packaging, dispatch and a completely different service standard." },
      { label: "Move 4", text: "Consider the smaller version: listing existing snacks on aggregators, which tests demand with almost no investment." },
      { label: "Close", text: "Recommend against the full entry, propose the cheap test, and name what result would change your mind." },
    ],
    pitfalls: [
      "Assuming idle capacity is free capacity.",
      "Not checking whether the peaks collide.",
      "Recommending a large entry when a cheap test would answer the question.",
    ],
  },
  {
    slug: "should-we-outsource-manufacturing",
    shape: "case",
    title: "Should a consumer brand outsource its manufacturing?",
    type: "Make or buy",
    difficulty: 2,
    minutes: 30,
    answer: "Outsource unless manufacturing is genuinely a source of advantage. For most consumer brands the advantage is brand and distribution, not the factory.",
    hints: ["Ask whether the factory is a source of differentiation or simply a cost centre."],
    moves: [
      { label: "Move 1", text: "Test whether manufacturing differentiates. A proprietary process is worth owning, a standard one is not." },
      { label: "Move 2", text: "Compare cost. Contract manufacturers running at scale across several brands often beat an owned plant per unit." },
      { label: "Move 3", text: "Assess the risks: quality control, capacity priority in peak season, and formulation confidentiality." },
      { label: "Move 4", text: "Consider flexibility, since outsourcing converts fixed cost to variable and makes new formats far cheaper to launch." },
      { label: "Close", text: "Recommend outsourcing with the quality regime named, or keep one plant for the differentiated line." },
    ],
    pitfalls: [
      "Owning a factory for control without asking what it costs.",
      "Ignoring capacity priority risk during peak season.",
      "Outsourcing a genuinely proprietary process.",
    ],
  },
];
