import type { Question } from "./types";

// Strategy and consulting guesstimates. Every answer is a band plus a structure,
// never a single figure presented as fact.
export const STRATEGY_GUESSTIMATES: Question[] = [
  {
    slug: "electric-two-wheelers-india-2030",
    shape: "guesstimate",
    title: "How many electric two-wheelers will be sold in India in 2030?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "BCG",
    answer: "Roughly 7 to 9 million electric units, out of a total two-wheeler market near 22 to 24 million.",
    hints: ["Size the total two-wheeler market first. Electric share is the last step, not the first."],
    moves: [
      { label: "Move 1", text: "Start from households, not people. India runs roughly 300 million households by 2030, with two-wheeler ownership near 50% nationally." },
      { label: "Move 2", text: "Convert the installed base into annual sales through the replacement cycle. At an eight year life, replacement alone drives about 19 million units a year." },
      { label: "Move 3", text: "Add new-household demand and subtract drift to four-wheelers. Land the total market near 22 to 24 million units." },
      { label: "Move 4", text: "Apply an electric share. Penetration was low single digits in 2024, so 30 to 40% gives roughly 7 to 9 million units." },
      { label: "Check", text: "At 8 million units India would be the largest electric two-wheeler market on earth, consistent with it already being the largest two-wheeler market." },
    ],
    pitfalls: [
      "Guessing an electric percentage at the start, which turns every later number into decoration on a guess.",
      "Sizing the installed base and calling it annual sales. The replacement cycle is the step interviewers listen for.",
      "Skipping the sanity check, which is where judgement shows rather than arithmetic.",
    ],
  },
  {
    slug: "starbucks-bandra-daily-revenue",
    shape: "guesstimate",
    title: "Estimate the daily revenue of a Starbucks outlet in Bandra, Mumbai.",
    type: "Revenue estimation",
    difficulty: 1,
    minutes: 15,
    askedAt: "Bain",
    answer: "Around 2.2 to 2.7 lakh rupees a day, which is close to 8 crore rupees a year.",
    hints: ["Build it as seats times turns times spend, not as footfall guessed in one go."],
    moves: [
      { label: "Move 1", text: "Fix the physical constraint. A Bandra outlet seats roughly 40 people and trades about 13 hours a day." },
      { label: "Move 2", text: "Split the day. Roughly 4 peak hours near full with two turns an hour, and 9 off-peak hours at about 30% occupancy." },
      { label: "Move 3", text: "Count customers. Peak gives about 320, off-peak about 110, then add takeaway at roughly a quarter of the total." },
      { label: "Move 4", text: "Apply the bill. Around 540 customers at 400 to 500 rupees lands near 2.2 to 2.7 lakh rupees a day." },
      { label: "Check", text: "That is about 8 crore rupees a year for one outlet. High for a cafe, plausible for premium coffee in Bandra." },
    ],
    pitfalls: [
      "Treating seats as customers. A seat turns several times a day and that multiplier is the whole answer.",
      "Using one flat occupancy across 13 hours, which understates peak and overstates the rest.",
      "Forgetting takeaway, which is large in coffee and nearly free of seating limits.",
    ],
  },
  {
    slug: "petrol-pumps-mumbai-pune-expressway",
    shape: "guesstimate",
    title: "How many petrol pumps does the Mumbai to Pune expressway need?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    askedAt: "McKinsey",
    answer: "Eight to fourteen fuel stations, with capacity per station doing more of the work than the count.",
    hints: ["This is demand-driven supply, not road length divided by a spacing assumption."],
    moves: [
      { label: "Move 1", text: "Size traffic. The expressway carries roughly 150,000 vehicles a day, about 70% cars and 30% commercial." },
      { label: "Move 2", text: "Work out how many refuel en route. At 95 km most cars do not need to, so assume 10% of cars and 30% of trucks stop." },
      { label: "Move 3", text: "Convert to litres. Roughly 10,500 cars at 25 litres and 13,500 trucks at 100 litres gives about 1.6 million litres a day." },
      { label: "Move 4", text: "Divide by capacity. At 4,000 litres per pump per day, sense-check the stop rate downward and land at 8 to 14 stations." },
      { label: "Check", text: "The real expressway has a handful of fuel stops. A number in the hundreds means the stop-rate assumption is wrong, and saying so is the point." },
    ],
    pitfalls: [
      "Dividing road length by assumed spacing, which answers a different question and shows no reasoning.",
      "Assuming every vehicle refuels on a 95 km road.",
      "Refusing to revise an assumption after the sanity check fails.",
    ],
  },
  {
    slug: "air-conditioners-delhi-ncr-summer",
    shape: "guesstimate",
    title: "How many air conditioners are sold across Delhi NCR each summer?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    askedAt: "Kearney",
    answer: "Roughly 1.5 to 2.5 million units in a season, split between first-time buyers and replacements.",
    hints: ["Separate first-time purchase from replacement. They grow at completely different rates."],
    moves: [
      { label: "Move 1", text: "Size households. Delhi NCR holds roughly 30 million people, or about 6.5 million households." },
      { label: "Move 2", text: "Split by income. Perhaps 45% can afford an air conditioner, and owners average more than a single unit." },
      { label: "Move 3", text: "Estimate penetration growth. If ownership rises a few points a year, first-time buying is several hundred thousand units." },
      { label: "Move 4", text: "Add replacement. At a ten year life on a base of several million units, replacement adds a similar volume again." },
      { label: "Check", text: "Delhi NCR is one of the most air-conditioned markets in India, so a number above its population share of national sales is expected." },
    ],
    pitfalls: [
      "Assuming one unit per household, which understates the affluent segment badly.",
      "Ignoring replacement demand, which is most of a mature category's volume.",
      "Treating annual sales as evenly spread when the category is violently seasonal.",
    ],
  },
  {
    slug: "weddings-in-india-per-year",
    shape: "guesstimate",
    title: "Estimate the number of weddings held in India in a year.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 8 to 11 million weddings a year.",
    hints: ["Work from the cohort reaching marriage age, not from the whole population."],
    moves: [
      { label: "Move 1", text: "Take the population near 1.45 billion and find the annual birth cohort, roughly 23 to 25 million." },
      { label: "Move 2", text: "That cohort reaches marriage age together. Each wedding consumes two people, so divide by two." },
      { label: "Move 3", text: "Adjust for those who never marry or marry much later. Applying roughly 80% gives around 9 to 10 million." },
      { label: "Move 4", text: "Sanity-check against the wedding industry, often cited in the low lakhs of crores of rupees, which implies a similar count." },
      { label: "Check", text: "State the seasonality. Weddings cluster into a few auspicious months, which matters for anyone serving the market." },
    ],
    pitfalls: [
      "Multiplying the whole population by a marriage rate, which double counts both partners.",
      "Ignoring that marriage age is rising, which shifts the cohort.",
      "Giving a single number when the honest answer is a band.",
    ],
  },
  {
    slug: "cement-metro-line-thirty-stations",
    shape: "guesstimate",
    title: "How much cement will a metro line of 30 stations consume?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    askedAt: "BCG",
    answer: "Roughly 1.5 to 3 million tonnes, dominated by viaduct and tunnel work rather than the stations themselves.",
    hints: ["Split the line into stations, elevated viaduct and tunnel. They consume very different volumes per kilometre."],
    moves: [
      { label: "Move 1", text: "Fix the geometry. Thirty stations at roughly 1.2 km spacing gives a line near 35 km." },
      { label: "Move 2", text: "Split the alignment between elevated and underground, since tunnelling consumes far more material per kilometre." },
      { label: "Move 3", text: "Apply per-kilometre concrete volumes, then convert to cement at roughly 350 kg per cubic metre of concrete." },
      { label: "Move 4", text: "Add the stations, which are large structures but a minority of total volume." },
      { label: "Check", text: "Compare against annual Indian cement output. A single metro line should be a rounding error nationally, and it is." },
    ],
    pitfalls: [
      "Sizing the stations and forgetting the line between them, which is most of the material.",
      "Quoting concrete volume when the question asked for cement.",
      "Treating elevated and underground sections as equivalent.",
    ],
  },
  {
    slug: "hotel-rooms-needed-goa-peak",
    shape: "guesstimate",
    title: "How many hotel rooms does Goa need at peak season?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 50,000 to 80,000 formal rooms, with informal stays carrying a large share on top.",
    hints: ["Build from visitor arrivals and length of stay, then divide by nights available."],
    moves: [
      { label: "Move 1", text: "Size annual visitors, roughly 8 million, and note arrivals concentrate into the December to February window." },
      { label: "Move 2", text: "Convert arrivals to room-nights using average stay near 3 nights and about 2.5 people per room." },
      { label: "Move 3", text: "Concentrate demand. If a quarter of the year carries half the arrivals, peak nightly demand is several times the average." },
      { label: "Move 4", text: "Divide peak room-nights by nights in the period, then by realistic peak occupancy of 80 to 90%." },
      { label: "Check", text: "The answer is deliberately about peak. Building for peak leaves capacity idle most of the year, which is the strategic point." },
    ],
    pitfalls: [
      "Averaging demand across the year and badly undersizing the peak.",
      "Assuming one person per room.",
      "Ignoring homestays and informal rentals, which absorb a large share of Goa demand.",
    ],
  },
  {
    slug: "school-buses-bengaluru",
    shape: "guesstimate",
    title: "How many school buses operate in Bengaluru?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 8,000 to 15,000 buses, driven by how many children use school transport rather than by school count.",
    hints: ["Start from the number of school-going children, not from the number of schools."],
    moves: [
      { label: "Move 1", text: "Size the child population. Bengaluru holds roughly 13 million people, with school-age children around 15% of that." },
      { label: "Move 2", text: "Estimate the share in private schools using bus transport, perhaps a third of all school children." },
      { label: "Move 3", text: "Divide by capacity. At 45 seats and two trips a morning, one bus moves around 80 to 90 children." },
      { label: "Move 4", text: "Adjust for route efficiency, since buses rarely fill completely across a spread-out city." },
      { label: "Check", text: "Compare against total registered buses in the city. School transport should be meaningful but a minority share." },
    ],
    pitfalls: [
      "Working from schools rather than children, which ignores wildly different school sizes.",
      "Assuming one trip per bus per morning.",
      "Forgetting that many children walk, cycle or are dropped by parents.",
    ],
  },
  {
    slug: "atms-needed-tier-two-city",
    shape: "guesstimate",
    title: "How many ATMs does a tier-two Indian city of 2 million need?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 700 to 1,200 machines, and falling as digital payments displace cash withdrawals.",
    hints: ["Size total withdrawal transactions per month, then divide by what one machine can serve."],
    moves: [
      { label: "Move 1", text: "Size banked adults. Of 2 million people, perhaps 1.3 million adults, most holding an account." },
      { label: "Move 2", text: "Estimate withdrawal frequency, perhaps two or three cash withdrawals a month, far lower than a decade ago." },
      { label: "Move 3", text: "Divide by machine capacity. An ATM handles a few hundred transactions a day at reasonable queue lengths." },
      { label: "Move 4", text: "Adjust for placement. Machines cluster in commercial areas, so utilisation is uneven and the count exceeds pure demand maths." },
      { label: "Check", text: "Say the direction of travel. This number is shrinking in India, which is the strategically interesting part." },
    ],
    pitfalls: [
      "Using pre-UPI withdrawal behaviour, which overstates demand substantially.",
      "Assuming perfectly even utilisation across a city.",
      "Answering the count without noting the category is in decline.",
    ],
  },
  {
    slug: "coffee-cups-office-tower",
    shape: "guesstimate",
    title: "How many cups of coffee are drunk in a 30-floor office tower each day?",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 4,000 to 7,000 cups a day across all sources.",
    hints: ["Get occupancy right first. Everything else is a multiplier on that number."],
    moves: [
      { label: "Move 1", text: "Size occupancy. Thirty floors at roughly 100 to 150 desks each gives 3,000 to 4,500 workers before hybrid attendance." },
      { label: "Move 2", text: "Apply attendance. With hybrid working, perhaps 65% are in on a given day." },
      { label: "Move 3", text: "Apply consumption. Coffee drinkers are perhaps 70% of staff, averaging two cups on a working day." },
      { label: "Move 4", text: "Split by source between pantry machines, the ground floor cafe and outside purchase, since only some is addressable." },
      { label: "Check", text: "Note the peak. Most volume lands in two short windows, which is what actually sizes equipment." },
    ],
    pitfalls: [
      "Assuming full attendance in a post-hybrid office.",
      "Treating every worker as a coffee drinker.",
      "Giving total daily volume when the useful number for a cafe is peak-hour demand.",
    ],
  },
  {
    slug: "gold-jewellery-kerala-annual",
    shape: "guesstimate",
    title: "How many kilograms of gold jewellery are sold in Kerala in a year?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 60 to 100 tonnes, a share of national demand far above Kerala's population share.",
    hints: ["Weddings drive most of this. Start from wedding count, then add festival and investment buying."],
    moves: [
      { label: "Move 1", text: "Size weddings. Kerala holds roughly 35 million people, giving perhaps 200,000 to 250,000 weddings a year." },
      { label: "Move 2", text: "Apply gold per wedding. Kerala buying is unusually heavy, plausibly 200 to 300 grams per wedding across both families." },
      { label: "Move 3", text: "Add non-wedding demand: festivals, births, and gold as savings, which together can match wedding volume." },
      { label: "Move 4", text: "Subtract nothing for recycling at this stage, but flag that old gold exchanged for new inflates gross sales figures." },
      { label: "Check", text: "Kerala is roughly 2.5% of India's population but a far larger share of gold demand, so an outsized number is the correct answer." },
    ],
    pitfalls: [
      "Applying a national average gold-per-person figure to a state that behaves nothing like the average.",
      "Ignoring exchange of old jewellery, which double counts metal.",
      "Forgetting investment buying, which is a large part of Kerala demand.",
    ],
  },
  {
    slug: "delhi-metro-annual-revenue",
    shape: "guesstimate",
    title: "Estimate the annual revenue of the Delhi Metro.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 5,000 to 8,000 crore rupees, with fares the majority and property plus advertising the rest.",
    hints: ["Fares are not the only line. Property and advertising matter enough to change the answer."],
    moves: [
      { label: "Move 1", text: "Size ridership. Roughly 5 to 6 million journeys a day on a normal weekday, lower at weekends." },
      { label: "Move 2", text: "Apply average fare. Distance-based pricing across a large network averages perhaps 25 to 35 rupees a journey." },
      { label: "Move 3", text: "Multiply out to roughly 5,000 crore rupees a year in fare revenue, adjusting weekdays against weekends." },
      { label: "Move 4", text: "Add non-fare revenue. Station retail, advertising and property development add a meaningful further share." },
      { label: "Check", text: "Note that revenue and profitability are different questions. Metro systems rarely cover capital cost from fares." },
    ],
    pitfalls: [
      "Using a peak-day ridership figure as the annual average.",
      "Applying the maximum fare rather than an average across trip lengths.",
      "Ignoring non-fare revenue, which is deliberately built into the business model.",
    ],
  },
  {
    slug: "taxis-mumbai-airport-midnight",
    shape: "guesstimate",
    title: "How many taxis does Mumbai airport need at midnight?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 300 to 600 vehicles waiting, driven by arrival bunching rather than by total daily passengers.",
    hints: ["This is a peak-load question. Daily passenger totals tell you almost nothing about midnight."],
    moves: [
      { label: "Move 1", text: "Size arrivals in the window. Late-night slots carry long-haul international arrivals, so several wide-body aircraft may land within an hour." },
      { label: "Move 2", text: "Convert aircraft to passengers, perhaps 250 to 300 each, then apply the share that takes a taxi rather than a private pickup." },
      { label: "Move 3", text: "Convert passengers to vehicles using group size, since families arriving together take one car." },
      { label: "Move 4", text: "Account for turnaround. A taxi that departs is gone for an hour, so the stand needs the full peak simultaneously." },
      { label: "Check", text: "The answer is about simultaneity, not throughput. Saying that out loud is what distinguishes a good answer here." },
    ],
    pitfalls: [
      "Dividing daily passengers by 24, which completely misses the bunching that defines the problem.",
      "Assuming one passenger per taxi.",
      "Forgetting that a dispatched taxi is unavailable for the rest of the peak.",
    ],
  },
  {
    slug: "laptops-sold-india-annually",
    shape: "guesstimate",
    title: "Estimate the number of laptops sold in India each year.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 14 to 18 million units, with enterprise and education buying a large share of it.",
    hints: ["Split consumer from institutional buying. They behave completely differently."],
    moves: [
      { label: "Move 1", text: "Size the consumer base. Perhaps 80 to 100 million households can afford a laptop, with ownership well under full penetration." },
      { label: "Move 2", text: "Apply a replacement cycle near five years on the installed base to get replacement demand." },
      { label: "Move 3", text: "Add first-time buying, driven by students and newly affording households." },
      { label: "Move 4", text: "Add institutional purchase. Corporate refresh cycles and government education programmes are a large, lumpy block." },
      { label: "Check", text: "Compare with smartphone sales, an order of magnitude higher. Laptops being far smaller is the expected relationship." },
    ],
    pitfalls: [
      "Treating laptops as a per-person product when they are largely per-household or per-employee.",
      "Ignoring institutional and government buying, which can move the total sharply.",
      "Using a replacement cycle borrowed from phones.",
    ],
  },
  {
    slug: "kirana-stores-in-india",
    shape: "guesstimate",
    title: "How many kirana stores are there in India?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 10 to 13 million outlets, the large majority rural and very small.",
    hints: ["Build from catchment. Each store serves a small, fairly predictable number of households."],
    moves: [
      { label: "Move 1", text: "Take roughly 300 million households, split about two-thirds rural and one-third urban." },
      { label: "Move 2", text: "Apply catchment. A rural store may serve 50 to 100 households, an urban one somewhat more but with more competition." },
      { label: "Move 3", text: "Divide households by catchment separately for each, then add the two." },
      { label: "Move 4", text: "Adjust for overlap in dense urban areas where several stores share the same street." },
      { label: "Check", text: "The commonly cited figure is around 12 million. Landing in that band from first principles is the goal." },
    ],
    pitfalls: [
      "Applying an urban catchment nationally, which badly undercounts rural India.",
      "Confusing kirana stores with all retail outlets including pharmacies and apparel.",
      "Ignoring that many stores are tiny and part-time.",
    ],
  },
  {
    slug: "indian-tea-market-volume",
    shape: "guesstimate",
    title: "Estimate the size of the Indian tea market by volume.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 1.2 million tonnes of domestic consumption a year.",
    hints: ["Consumption per person per day is small and easy to estimate. Scale it up carefully."],
    moves: [
      { label: "Move 1", text: "Estimate drinkers. Tea is close to universal in India, so assume around 1 billion regular consumers." },
      { label: "Move 2", text: "Estimate cups per day, perhaps two on average across all drinkers, higher in the north and east." },
      { label: "Move 3", text: "Convert cups to leaf. Roughly 2 grams of tea per cup gives about 4 grams per person per day." },
      { label: "Move 4", text: "Scale up and convert to tonnes, then separate domestic consumption from the export share of national production." },
      { label: "Check", text: "India produces roughly 1.3 million tonnes and exports a modest fraction, so domestic consumption near 1 million tonnes holds." },
    ],
    pitfalls: [
      "Forgetting to convert cups into weight of leaf, which is the whole arithmetic.",
      "Confusing production with domestic consumption.",
      "Using a Western per-person tea figure.",
    ],
  },
  {
    slug: "hotel-rooms-india-branded",
    shape: "guesstimate",
    title: "Estimate the number of branded hotel rooms in India.",
    type: "Supply estimation",
    difficulty: 2,
    minutes: 18,
    answer: "Roughly 1.8 to 2.2 lakh branded rooms, a thin formal layer over a much larger unbranded stock.",
    hints: ["Count chains and average property sizes; branded supply is concentrated and countable."],
    moves: [
      { label: "Move 1", text: "List the chains: 8 to 10 major domestic and international groups operate meaningful Indian portfolios." },
      { label: "Move 2", text: "Portfolio math: the largest chains run 150 to 300 hotels each; the full branded universe is perhaps 1,500 to 2,000 properties." },
      { label: "Move 3", text: "Rooms per property: business hotels average 100 to 150 rooms; resorts and budget brands pull the average down toward 110." },
      { label: "Move 4", text: "Multiply: 1,800 properties times 110 rooms gives about 2 lakh branded rooms." },
      { label: "Check", text: "Contrast with the total: guesthouses, lodges and unbranded hotels hold perhaps 15 to 20 lakh rooms; the branded share near 10 to 15% is the strategic story." },
    ],
    pitfalls: [
      "Confusing branded supply with total room supply.",
      "Using flagship 300-room properties as the average.",
      "Forgetting management-contract properties that carry a brand without its ownership.",
    ],
  },
  {
    slug: "indian-railways-diesel-annual",
    shape: "guesstimate",
    title: "Estimate the annual diesel consumption of Indian Railways.",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 2 to 3 billion litres a year, and falling as electrification advances.",
    hints: ["Only the non-electrified share matters, and that share is shrinking fast."],
    moves: [
      { label: "Move 1", text: "Size the network activity. Indian Railways runs roughly 13,000 passenger trains and a large freight operation daily." },
      { label: "Move 2", text: "Apply the diesel share. With most route kilometres now electrified, only a minority of traction is diesel." },
      { label: "Move 3", text: "Estimate consumption per locomotive-hour, then multiply by diesel locomotive hours worked." },
      { label: "Move 4", text: "Add shunting and departmental use, which is small per unit but constant." },
      { label: "Check", text: "Note the trend explicitly. A number that would have been far higher a decade ago is the interesting observation." },
    ],
    pitfalls: [
      "Assuming the whole network runs on diesel.",
      "Estimating per train rather than per locomotive hour, which is how fuel is actually burned.",
      "Giving a static answer for a number that is structurally declining.",
    ],
  },
  {
    slug: "bicycles-sold-india-annually",
    shape: "guesstimate",
    title: "How many bicycles are sold in India each year?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 12 to 16 million units, mostly utility bicycles rather than leisure models.",
    hints: ["Utility and leisure are two different markets. Size the larger one first."],
    moves: [
      { label: "Move 1", text: "Segment demand. The bulk is rural and semi-urban utility transport, with children's and leisure bikes far smaller." },
      { label: "Move 2", text: "For utility, work from households without motorised transport and a replacement cycle near seven years." },
      { label: "Move 3", text: "Add children's bicycles, driven by the child population and a shorter effective life as children outgrow them." },
      { label: "Move 4", text: "Add premium leisure, which is growing quickly but from a very small base." },
      { label: "Check", text: "Note the direction. Rising two-wheeler affordability pushes utility cycling down while urban leisure rises." },
    ],
    pitfalls: [
      "Sizing from urban leisure cycling, which is a rounding error in this market.",
      "Ignoring the child segment, which is a large share of unit volume.",
      "Assuming one bicycle per household forever, with no replacement.",
    ],
  },
  {
    slug: "gyms-in-hyderabad",
    shape: "guesstimate",
    title: "Estimate the number of gyms in Hyderabad.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 1,500 to 2,500 facilities, most of them small neighbourhood gyms rather than chains.",
    hints: ["Work from paying members, then divide by what one gym can sustain."],
    moves: [
      { label: "Move 1", text: "Size the addressable population. Of roughly 10 million people, perhaps 3 million are urban adults with disposable income." },
      { label: "Move 2", text: "Apply membership penetration, plausibly 5 to 8%, giving 150,000 to 250,000 members." },
      { label: "Move 3", text: "Divide by gym size. A neighbourhood gym sustains perhaps 100 to 200 members, a chain branch several times that." },
      { label: "Move 4", text: "Weight the mix. Most facilities are small, so the average is closer to the neighbourhood figure than the chain one." },
      { label: "Check", text: "Note seasonality and churn. January memberships inflate counts that lapse by March, so active members differ from sold ones." },
    ],
    pitfalls: [
      "Applying a Western penetration rate to an Indian city.",
      "Assuming every gym is a large chain branch.",
      "Confusing memberships sold with members actually attending.",
    ],
  },
  {
    slug: "chennai-daily-water-consumption",
    shape: "guesstimate",
    title: "How much water does Chennai consume in a day?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1,000 to 1,400 million litres a day, with domestic use the largest block.",
    hints: ["Per person per day is the anchor. Everything else is an addition on top of it."],
    moves: [
      { label: "Move 1", text: "Size population near 11 million in the metropolitan area." },
      { label: "Move 2", text: "Apply domestic use. Indian urban norms sit near 100 to 135 litres per person per day where supply allows." },
      { label: "Move 3", text: "Add commercial, industrial and institutional demand, typically a further quarter to a third on top of domestic." },
      { label: "Move 4", text: "Add distribution losses, which in Indian cities can be 20% or more of water put into the system." },
      { label: "Check", text: "Note that supply and demand differ sharply in Chennai. What the city consumes and what it needs are not the same number." },
    ],
    pitfalls: [
      "Forgetting distribution losses, which are a large share of water actually pumped.",
      "Using a per-person figure from a city with reliable round-the-clock supply.",
      "Answering consumption when the interesting question is the shortfall.",
    ],
  },
  {
    slug: "highway-toll-plaza-revenue",
    shape: "guesstimate",
    title: "Estimate the annual revenue of a highway toll plaza.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 40 to 90 crore rupees a year on a busy national corridor.",
    hints: ["Commercial vehicles pay several times what cars pay, so the mix matters more than the count."],
    moves: [
      { label: "Move 1", text: "Size traffic. A busy national highway plaza handles perhaps 25,000 to 40,000 vehicles a day." },
      { label: "Move 2", text: "Split the mix. Roughly 60% cars, 30% commercial, 10% exempt or local pass holders." },
      { label: "Move 3", text: "Apply rates. Cars might pay 100 rupees, trucks three to five times that, so commercial traffic carries most of the revenue." },
      { label: "Move 4", text: "Multiply out daily revenue and annualise, adjusting for seasonal and weekly variation." },
      { label: "Check", text: "Note exemptions and monthly passes for local residents, which reduce effective collection meaningfully." },
    ],
    pitfalls: [
      "Applying the car rate to all vehicles, which understates revenue badly.",
      "Ignoring exempt categories and local passes.",
      "Assuming uniform traffic across the year on a corridor with strong seasonality.",
    ],
  },
  {
    slug: "mobile-towers-india-needed",
    shape: "guesstimate",
    title: "How many mobile towers does India need?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 700,000 to 800,000 tower sites, carrying far more individual antennas than that.",
    hints: ["Urban towers are capacity-limited and rural ones are coverage-limited. Size them separately."],
    moves: [
      { label: "Move 1", text: "Split the problem. Rural sites exist to cover area, urban sites exist to carry traffic in a small area." },
      { label: "Move 2", text: "For rural, divide land area by the coverage radius of a tower, which is several kilometres in open terrain." },
      { label: "Move 3", text: "For urban, work from subscribers per cell, since a dense city needs many small cells regardless of area." },
      { label: "Move 4", text: "Separate towers from antennas. Multiple operators and multiple bands share one physical structure." },
      { label: "Check", text: "Note that the number rises with data demand, not with subscriber count, which is the strategically relevant driver." },
    ],
    pitfalls: [
      "Using one coverage radius for the whole country.",
      "Confusing tower count with base station count, which is several times higher.",
      "Sizing from subscribers alone and ignoring data traffic growth.",
    ],
  },
  {
    slug: "milk-packets-delhi-morning",
    shape: "guesstimate",
    title: "Estimate the number of milk packets delivered in Delhi each morning.",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 6 to 9 million half-litre packets a day through formal channels.",
    hints: ["Convert litres to packets at the end. Estimating packets directly hides the assumption."],
    moves: [
      { label: "Move 1", text: "Size households at roughly 4.5 million for a population near 20 million." },
      { label: "Move 2", text: "Apply consumption. An Indian urban household uses perhaps 1 to 1.5 litres of milk a day." },
      { label: "Move 3", text: "Split the channel. A meaningful share still comes from loose milk vendors rather than packets." },
      { label: "Move 4", text: "Convert litres to packets, since the standard pack is half a litre, roughly doubling the packet count." },
      { label: "Check", text: "Add institutional demand from cafes, sweet shops and hotels, which is a substantial addition in a city like Delhi." },
    ],
    pitfalls: [
      "Answering in litres when the question asked for packets.",
      "Assuming the entire market is packaged milk.",
      "Forgetting commercial and institutional buyers.",
    ],
  },
  {
    slug: "second-hand-car-market-india",
    shape: "guesstimate",
    title: "How large is the Indian second-hand car market?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 25,
    answer: "Roughly 4.5 to 6 million units a year, comfortably larger than new car sales by volume.",
    hints: ["Every used sale starts as a new car sold years earlier. Work from that installed base."],
    moves: [
      { label: "Move 1", text: "Size the installed base. Years of new car sales in the 3 to 4 million range build a base of tens of millions of vehicles." },
      { label: "Move 2", text: "Apply a turnover rate. A car may change hands once every five to seven years within its life." },
      { label: "Move 3", text: "That gives annual used transactions above new sales, which is the structurally correct relationship." },
      { label: "Move 4", text: "Split organised from unorganised. Most transactions still happen informally, which matters for anyone entering the market." },
      { label: "Check", text: "In mature markets used sales run two to three times new. India sitting near 1.4 times suggests room to grow." },
    ],
    pitfalls: [
      "Sizing used sales below new sales, which gets the basic relationship backwards.",
      "Ignoring informal transactions, which are most of the market.",
      "Confusing transaction value with transaction volume.",
    ],
  },
  {
    slug: "hospital-beds-needed-pune",
    shape: "guesstimate",
    title: "Estimate the number of hospital beds needed in Pune.",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 20,000 to 30,000 beds for a population near 7 million.",
    hints: ["Build from admissions per year and average length of stay, not from a beds-per-thousand rule."],
    moves: [
      { label: "Move 1", text: "Size population near 7 million in the urban agglomeration." },
      { label: "Move 2", text: "Estimate admissions. Perhaps 5 to 8% of people are admitted at least once a year." },
      { label: "Move 3", text: "Apply length of stay near four days to get total bed-days demanded across the year." },
      { label: "Move 4", text: "Divide by 365 and by realistic occupancy of 70 to 80%, since a hospital cannot run full." },
      { label: "Check", text: "Cross-check against the beds-per-thousand benchmark. Landing near 3 to 4 per thousand is plausible for a well-served Indian city." },
    ],
    pitfalls: [
      "Quoting a beds-per-thousand ratio with no derivation, which shows no reasoning.",
      "Assuming 100% occupancy, which leaves no headroom for surges.",
      "Ignoring that Pune draws patients from a much wider region than its own population.",
    ],
  },
  {
    slug: "dominos-pizzas-india-daily",
    shape: "guesstimate",
    title: "How many pizzas does Domino's sell in India in a day?",
    type: "Volume estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 500,000 to 800,000 pizzas a day across the network.",
    hints: ["Work per store per day, then multiply by store count. Do not try to size national demand directly."],
    moves: [
      { label: "Move 1", text: "Size the network at roughly 2,000 stores across India." },
      { label: "Move 2", text: "Estimate orders per store per day. A busy outlet might take 250 to 400 orders, concentrated at meal times." },
      { label: "Move 3", text: "Convert orders to pizzas. An average order contains more than one pizza, perhaps 1.5." },
      { label: "Move 4", text: "Adjust for store mix, since a metro high-street store far outsells a small-town outlet." },
      { label: "Check", text: "Multiply out to annual revenue and compare against the company's reported scale. A wild mismatch means an assumption is off." },
    ],
    pitfalls: [
      "Treating orders and pizzas as the same thing.",
      "Applying metro store performance to the whole network.",
      "Ignoring that demand concentrates into two narrow windows, which is what limits capacity.",
    ],
  },
  {
    slug: "mall-annual-footfall",
    shape: "guesstimate",
    title: "Estimate the annual footfall of a large Indian mall.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 10 to 18 million visits a year for a large metro mall.",
    hints: ["Weekend days can carry three to four times a weekday. Averaging them destroys the answer."],
    moves: [
      { label: "Move 1", text: "Estimate a weekday. A large metro mall might see 20,000 to 30,000 visitors." },
      { label: "Move 2", text: "Estimate a weekend day at three to four times that, since malls in India are a leisure destination." },
      { label: "Move 3", text: "Weight across the week, then annualise, adding festival peaks around Diwali and end-of-season sales." },
      { label: "Move 4", text: "Distinguish footfall from shoppers. A large share visit for cinema and food without entering a store." },
      { label: "Check", text: "Convert to revenue per visit and compare against plausible mall turnover to confirm the figure is not absurd." },
    ],
    pitfalls: [
      "Using one flat daily figure across the year.",
      "Treating every visitor as a shopper.",
      "Forgetting festival peaks, which are a large share of annual retail.",
    ],
  },
  {
    slug: "solar-panels-mid-size-factory",
    shape: "guesstimate",
    title: "How many solar panels would power a mid-size Indian factory?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 2,000 to 5,000 panels, and roof area rather than demand is usually the binding constraint.",
    hints: ["Solar output is not constant. Convert capacity to units generated using realistic sun hours."],
    moves: [
      { label: "Move 1", text: "Size demand. A mid-size factory might draw 500 kW, running two shifts, giving several thousand units a day." },
      { label: "Move 2", text: "Convert to solar capacity using effective sun hours, roughly 4.5 to 5 a day in most of India." },
      { label: "Move 3", text: "Divide required capacity by panel rating, commonly 400 to 550 watts per modern panel." },
      { label: "Move 4", text: "Check the roof. At roughly 2 square metres per panel, the array may not physically fit, which is the real answer." },
      { label: "Check", text: "Note that solar covers daytime load only. Night shifts still need the grid unless storage is added." },
    ],
    pitfalls: [
      "Treating rated capacity as continuous output, which overstates generation by a factor of four or five.",
      "Ignoring available roof area, which usually binds before demand does.",
      "Assuming solar can serve a night shift without storage.",
    ],
  },
  {
    slug: "school-uniform-market-india",
    shape: "guesstimate",
    title: "Estimate the size of the school uniform market in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25,000 to 40,000 crore rupees a year, heavily concentrated in one buying season.",
    hints: ["Children outgrow uniforms, so replacement is annual rather than every few years."],
    moves: [
      { label: "Move 1", text: "Size school enrolment at roughly 250 million children across all school stages." },
      { label: "Move 2", text: "Apply the share required to wear a uniform, which is high in private and most government schools." },
      { label: "Move 3", text: "Estimate sets per child per year, typically two, and spend per set, which varies sharply by school type." },
      { label: "Move 4", text: "Weight by school type. A private school uniform may cost several times a government one." },
      { label: "Check", text: "Note the seasonality. Nearly all of this is bought in a few weeks, which defines the whole supply chain." },
    ],
    pitfalls: [
      "Applying one average price across government and private schools.",
      "Assuming one uniform lasts several years when children outgrow them annually.",
      "Ignoring shoes and accessories, which may or may not be in scope. Say which you assumed.",
    ],
  },
  {
    slug: "trucks-crossing-delhi-border",
    shape: "guesstimate",
    title: "How many trucks cross the Delhi border each day?",
    type: "Volume estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 60,000 to 100,000 truck movements, most of it passing through rather than delivering.",
    hints: ["Separate trucks delivering into Delhi from trucks merely passing through it."],
    moves: [
      { label: "Move 1", text: "Size consumption. Twenty million people consume food, fuel and goods that arrive almost entirely by road." },
      { label: "Move 2", text: "Convert tonnage to trucks. Daily consumption in the tens of thousands of tonnes divided by 10 to 20 tonnes a truck." },
      { label: "Move 3", text: "Add construction material, which is heavy, high volume and constant in a growing city." },
      { label: "Move 4", text: "Add transit traffic. Delhi sits on major national corridors, so a large share of trucks are only passing through." },
      { label: "Check", text: "Note that restrictions push most of this into night hours, which is what makes the peak so concentrated." },
    ],
    pitfalls: [
      "Counting only deliveries and missing transit traffic, which is often the larger share.",
      "Using one truck size for everything from vegetables to cement.",
      "Ignoring night-time entry restrictions, which shape the entire pattern.",
    ],
  },
  {
    slug: "multiplex-screen-annual-revenue",
    shape: "guesstimate",
    title: "Estimate the annual revenue of a single multiplex screen.",
    type: "Revenue estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 3 to 5 crore rupees a year including food and beverage.",
    hints: ["Occupancy across the whole year is far lower than people assume. Around 25 to 30% is realistic."],
    moves: [
      { label: "Move 1", text: "Fix capacity. A multiplex screen seats roughly 200 people and runs four to five shows a day." },
      { label: "Move 2", text: "Apply blended occupancy near 25 to 30%, since weekday afternoons are close to empty." },
      { label: "Move 3", text: "Apply ticket price, perhaps 200 to 250 rupees in a metro, lower elsewhere." },
      { label: "Move 4", text: "Add food and beverage at roughly 30 to 40% of ticket revenue but at much higher margin." },
      { label: "Check", text: "Note that a handful of big releases carry most of the year, so the average conceals extreme variance." },
    ],
    pitfalls: [
      "Assuming healthy occupancy across all shows and all seasons.",
      "Forgetting food and beverage, which is where the profit sits.",
      "Reporting box office as revenue the cinema keeps, when the distributor takes a large early share.",
    ],
  },
  {
    slug: "mumbai-local-train-daily-riders",
    shape: "guesstimate",
    title: "How many people travel by Mumbai local trains daily?",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 6 to 8 million journeys a day, which is fewer unique people because most travel is return.",
    hints: ["Journeys and people are different. Decide which the question wants and say so."],
    moves: [
      { label: "Move 1", text: "Size the working population. Of roughly 20 million people, perhaps 8 million commute for work or study." },
      { label: "Move 2", text: "Apply the rail share. Suburban rail carries the majority of long commutes in Mumbai." },
      { label: "Move 3", text: "Convert commuters to journeys by doubling for the return trip." },
      { label: "Move 4", text: "Cross-check with capacity. Train frequency multiplied by realistic crush loading should produce a similar number." },
      { label: "Check", text: "State whether you answered journeys or unique travellers. The two differ by roughly a factor of two." },
    ],
    pitfalls: [
      "Reporting journeys as if they were unique people.",
      "Ignoring that a large share of the city walks or uses buses for short trips.",
      "Not cross-checking against physical train capacity.",
    ],
  },
  {
    slug: "wedding-photography-market-india",
    shape: "guesstimate",
    title: "Estimate the size of the Indian wedding photography market.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 10,000 to 20,000 crore rupees a year, with a small share of weddings driving most of the value.",
    hints: ["Spend per wedding is wildly skewed. Segment by wedding budget before applying any average."],
    moves: [
      { label: "Move 1", text: "Start from roughly 9 to 10 million weddings a year." },
      { label: "Move 2", text: "Segment by budget. Perhaps 10% are high-spend, 30% mid, and the rest minimal or family-photographed." },
      { label: "Move 3", text: "Apply spend per segment, ranging from a few thousand rupees to several lakh for a premium shoot." },
      { label: "Move 4", text: "Weight and sum, noting that the top decile likely contributes more than half of total value." },
      { label: "Check", text: "Compare against total wedding spend. Photography typically runs a few percent of a wedding budget, which sense-checks the figure." },
    ],
    pitfalls: [
      "Applying one average spend to all 10 million weddings.",
      "Ignoring that most weddings involve no professional photographer at all.",
      "Confusing photography with the entire wedding services market.",
    ],
  },
  {
    slug: "street-lights-bengaluru",
    shape: "guesstimate",
    title: "How many street lights does Bengaluru have?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 15,
    answer: "Roughly 400,000 to 600,000 lights across the municipal area.",
    hints: ["Work from road length and spacing. Population is only useful for estimating road length."],
    moves: [
      { label: "Move 1", text: "Estimate road length. A city of 13 million across roughly 700 square kilometres has several thousand kilometres of roads." },
      { label: "Move 2", text: "Apply spacing, roughly 30 metres between poles on a lit road, which gives about 33 poles per kilometre." },
      { label: "Move 3", text: "Adjust for lit share, since not every lane and bylane is lit to the same standard." },
      { label: "Move 4", text: "Account for wide roads lit from both sides, which doubles the count on major corridors." },
      { label: "Check", text: "Convert to annual electricity cost and check it is a plausible line in a municipal budget." },
    ],
    pitfalls: [
      "Estimating from population with no road length step in between.",
      "Using one spacing figure for arterial roads and residential lanes.",
      "Forgetting double-sided lighting on major roads.",
    ],
  },
  {
    slug: "school-textbook-paper-india",
    shape: "guesstimate",
    title: "Estimate India's annual paper consumption for school textbooks.",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 1 to 1.5 million tonnes of paper a year.",
    hints: ["Get to grams per book, then multiply. Estimating tonnage directly hides every assumption."],
    moves: [
      { label: "Move 1", text: "Size enrolment at roughly 250 million school children." },
      { label: "Move 2", text: "Apply books per child per year, perhaps six to eight across subjects." },
      { label: "Move 3", text: "Estimate paper per book. Roughly 150 pages at 60 gsm gives something near 250 to 300 grams." },
      { label: "Move 4", text: "Multiply out and convert to tonnes, then subtract the share of reused or handed-down books." },
      { label: "Check", text: "Compare against total Indian paper production. Textbooks should be a visible but minority share." },
    ],
    pitfalls: [
      "Skipping the grams-per-book step and guessing tonnage.",
      "Ignoring reuse, which is significant in government schooling.",
      "Forgetting notebooks are a separate and larger category unless included deliberately.",
    ],
  },
  {
    slug: "cattle-supplying-amul-milk",
    shape: "guesstimate",
    title: "How many cattle are needed to supply Amul's daily milk?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 6 to 10 million milking animals, spread across millions of very small farmers.",
    hints: ["Yield per animal in India is low. Using a Western figure will cut your answer by a factor of three."],
    moves: [
      { label: "Move 1", text: "Size collection. Amul procures on the order of 25 to 30 million litres a day at peak." },
      { label: "Move 2", text: "Apply yield per animal. Indian averages sit near 3 to 5 litres a day, far below Western herds." },
      { label: "Move 3", text: "Divide to get milking animals, then gross up for animals not currently in milk." },
      { label: "Move 4", text: "Convert to farmers. At two or three animals each, this implies millions of supplying households." },
      { label: "Check", text: "That farmer count is the actual insight. The cooperative model exists precisely because supply is this fragmented." },
    ],
    pitfalls: [
      "Using Western yield per cow, which understates animal count dramatically.",
      "Forgetting that only a portion of a herd is in milk at any time.",
      "Answering in animals without translating to farmers, which is the meaningful unit here.",
    ],
  },
  {
    slug: "tractors-sold-india-annually",
    shape: "guesstimate",
    title: "Estimate the number of tractors sold in India each year.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 800,000 to 950,000 units, with monsoon quality swinging it sharply year to year.",
    hints: ["Most Indian farms are too small to justify a tractor. Size the farms that actually can."],
    moves: [
      { label: "Move 1", text: "Size landholdings. India has roughly 145 million holdings, but the large majority are under two hectares." },
      { label: "Move 2", text: "Apply the addressable share. Only medium and large holdings, plus rental operators, realistically buy tractors." },
      { label: "Move 3", text: "Apply a replacement cycle near ten years on the existing tractor base." },
      { label: "Move 4", text: "Add first-time buying driven by rising rural incomes and custom hiring services." },
      { label: "Check", text: "Name the swing factor. A weak monsoon can move this number 20% in either direction, which is the real point." },
    ],
    pitfalls: [
      "Sizing from total farm holdings without filtering for viable farm size.",
      "Ignoring rental and custom hiring, which lets small farmers access tractors without owning one.",
      "Treating this as a stable market when it is highly monsoon-dependent.",
    ],
  },
  {
    slug: "railway-station-retail-revenue",
    shape: "guesstimate",
    title: "How much revenue does a busy railway station's retail generate?",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 50 to 150 crore rupees a year at a major terminus, dominated by food and drink.",
    hints: ["Footfall is huge but conversion and basket size are tiny. Both matter equally."],
    moves: [
      { label: "Move 1", text: "Size footfall. A major terminus may see 300,000 to 500,000 people a day including those meeting travellers." },
      { label: "Move 2", text: "Apply conversion. Perhaps 30 to 40% buy something, mostly water, tea or a snack." },
      { label: "Move 3", text: "Apply basket size, which is small, perhaps 40 to 80 rupees on average." },
      { label: "Move 4", text: "Add higher-value categories such as pharmacy, books and branded quick service outlets." },
      { label: "Check", text: "Note that a waiting passenger is a captive customer, which is why per-square-foot yields here beat many high streets." },
    ],
    pitfalls: [
      "Applying mall basket sizes to a station.",
      "Assuming everyone in the station is a customer.",
      "Ignoring that dwell time, not footfall, is what drives spend.",
    ],
  },
  {
    slug: "engineering-graduates-india-yearly",
    shape: "guesstimate",
    title: "Estimate the number of engineering graduates India produces yearly.",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 1.2 to 1.5 million graduates a year across all engineering disciplines.",
    hints: ["Work from colleges times seats times pass rate, not from the population."],
    moves: [
      { label: "Move 1", text: "Size institutions. India has several thousand engineering colleges of widely varying size." },
      { label: "Move 2", text: "Apply average intake, perhaps 300 to 500 seats per college across all branches." },
      { label: "Move 3", text: "Adjust for unfilled seats, which are substantial in the lower tier of colleges." },
      { label: "Move 4", text: "Apply completion rate, since not every admitted student graduates on time." },
      { label: "Check", text: "Compare against the annual cohort of roughly 24 million. Engineering graduates being around 5% of it is plausible." },
    ],
    pitfalls: [
      "Assuming every sanctioned seat is filled, which has not been true for years.",
      "Ignoring dropout and backlog, which delay graduation.",
      "Confusing enrolment with graduation.",
    ],
  },
  {
    slug: "delivery-riders-city-five-million",
    shape: "guesstimate",
    title: "How many delivery riders does a city of 5 million need?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25,000 to 45,000 active riders across food, grocery and parcel delivery.",
    hints: ["Peak-hour demand sizes the fleet, not daily order volume."],
    moves: [
      { label: "Move 1", text: "Size orders. Perhaps 400,000 to 600,000 daily deliveries across food, quick commerce and e-commerce parcels." },
      { label: "Move 2", text: "Estimate rider throughput. A food rider completes perhaps 15 to 20 deliveries in a shift, a parcel rider more." },
      { label: "Move 3", text: "Divide to get riders required, then account for the peak, since food demand concentrates into a few hours." },
      { label: "Move 4", text: "Gross up for part-time working and unavailability, since a large share of riders work limited hours." },
      { label: "Check", text: "The binding constraint is the dinner peak, not the daily total. Say that, because it is what actually sizes the fleet." },
    ],
    pitfalls: [
      "Sizing from daily orders and ignoring that most food demand lands in two short windows.",
      "Assuming every rider works a full shift.",
      "Treating food, grocery and parcel delivery as one interchangeable pool.",
    ],
  },
  {
    slug: "paint-sales-india-annual",
    shape: "guesstimate",
    title: "Estimate the annual sales of paint in India.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 70,000 to 90,000 crore rupees, with decorative paint the large majority.",
    hints: ["Decorative and industrial paint are different businesses. Size the larger one first."],
    moves: [
      { label: "Move 1", text: "Split the market. Decorative paint for buildings is roughly three-quarters of value, industrial the rest." },
      { label: "Move 2", text: "For decorative, work from housing stock and a repainting cycle of five to seven years." },
      { label: "Move 3", text: "Apply paint volume per repaint and price per litre, separating premium emulsions from distemper." },
      { label: "Move 4", text: "Add new construction demand, which is smaller in units but growing faster." },
      { label: "Check", text: "Note the seasonality. Repainting clusters before Diwali, which shapes the entire supply chain." },
    ],
    pitfalls: [
      "Sizing only new construction and missing repainting, which is most of the demand.",
      "Using one price per litre across distemper and premium emulsion.",
      "Ignoring the industrial and automotive segments entirely without saying so.",
    ],
  },
  {
    slug: "cinemas-needed-tier-two-city",
    shape: "guesstimate",
    title: "How many cinema screens would a new tier-two city of 1 million need?",
    type: "Resource estimation",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25 to 45 screens, sized by weekend peak rather than average demand.",
    hints: ["Weekend evenings define capacity. An average across the week will undersize it badly."],
    moves: [
      { label: "Move 1", text: "Size the audience. Of 1 million people, perhaps 400,000 are realistic cinema-goers." },
      { label: "Move 2", text: "Apply frequency, perhaps three to five visits a year each, giving 1.5 to 2 million admissions annually." },
      { label: "Move 3", text: "Convert to seats. Divide annual admissions by shows per year and realistic average occupancy." },
      { label: "Move 4", text: "Size for the weekend peak rather than the average, since that is when capacity actually binds." },
      { label: "Check", text: "Compare screens per million against national benchmarks, where India is famously under-screened." },
    ],
    pitfalls: [
      "Sizing on average occupancy and leaving no weekend capacity.",
      "Applying metro cinema-going frequency to a tier-two city.",
      "Ignoring that a few large releases drive most annual admissions.",
    ],
  },
  {
    slug: "packaged-drinking-water-india",
    shape: "guesstimate",
    title: "Estimate the size of India's packaged drinking water market.",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 25,000 to 40,000 crore rupees, with bulk jars a large share of volume but a small share of value.",
    hints: ["Bottles and 20-litre jars are two different businesses. Separate them before pricing anything."],
    moves: [
      { label: "Move 1", text: "Split by format. Single-serve bottles sold on the move, and 20-litre jars delivered to homes and offices." },
      { label: "Move 2", text: "For bottles, work from urban population, purchase occasions per person, and a price near 20 rupees a litre." },
      { label: "Move 3", text: "For jars, work from households and offices using delivered water, at a small fraction of the per-litre price." },
      { label: "Move 4", text: "Add the institutional channel: hotels, airlines, railways and events, which buy in bulk." },
      { label: "Check", text: "Note jars dominate volume while bottles dominate value. Reporting one without the other misleads." },
    ],
    pitfalls: [
      "Applying bottle pricing to jar volumes, which inflates the market enormously.",
      "Ignoring the unbranded local jar suppliers who hold much of the market.",
      "Confusing volume share with value share.",
    ],
  },
  {
    slug: "ambulances-needed-delhi",
    shape: "guesstimate",
    title: "How many ambulances does Delhi need?",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 20,
    answer: "Roughly 1,500 to 2,500 vehicles, sized by response time rather than by call volume.",
    hints: ["This is a coverage problem. Response time targets drive the number far more than total calls do."],
    moves: [
      { label: "Move 1", text: "Size emergency calls. A population of 20 million might generate several thousand medical emergencies a day." },
      { label: "Move 2", text: "Estimate cycle time. Each call consumes roughly 60 to 90 minutes including travel, loading and handover." },
      { label: "Move 3", text: "Divide to get vehicles needed for volume alone, which gives a surprisingly low number." },
      { label: "Move 4", text: "Then apply the coverage constraint. Meeting a 15-minute response target requires vehicles distributed across the city, not pooled." },
      { label: "Check", text: "Coverage, not throughput, is the binding constraint. Recognising that is the whole answer." },
    ],
    pitfalls: [
      "Sizing purely from call volume, which ignores geography completely.",
      "Assuming a vehicle is free the moment it delivers a patient.",
      "Ignoring peak clustering, since emergencies are not evenly spread through the day.",
    ],
  },
  {
    slug: "kota-coaching-chain-revenue",
    shape: "guesstimate",
    title: "Estimate the annual revenue of a coaching centre chain in Kota.",
    type: "Revenue estimation",
    difficulty: 2,
    minutes: 25,
    answer: "Roughly 500 to 1,500 crore rupees for a large chain, driven by batch size more than by fee level.",
    hints: ["Batch size is the lever. One teacher in front of 200 students is a completely different business from one in front of 40."],
    moves: [
      { label: "Move 1", text: "Size enrolment. A large Kota chain may teach 30,000 to 50,000 students across its centres." },
      { label: "Move 2", text: "Apply fees, typically 1.5 to 2.5 lakh rupees a year for a full classroom programme." },
      { label: "Move 3", text: "Multiply out, then adjust for scholarships and fee waivers used to attract high-scoring students." },
      { label: "Move 4", text: "Add ancillary revenue from test series, study material, and hostel or mess operations." },
      { label: "Check", text: "Note the concentration risk. Results in one exam season drive the following year's enrolment almost entirely." },
    ],
    pitfalls: [
      "Ignoring scholarships, which meaningfully reduce realised fee per student.",
      "Forgetting hostel and material revenue, which can be a large share.",
      "Treating enrolment as stable when it swings on last year's exam results.",
    ],
  },
  {
    slug: "domestic-air-passengers-india",
    shape: "guesstimate",
    title: "How many domestic air passengers fly in India annually?",
    type: "Volume estimation",
    difficulty: 1,
    minutes: 15,
    answer: "Roughly 150 to 165 million passenger journeys a year.",
    hints: ["Build from the fleet and seats flown, which needs fewer assumptions than building from travellers."],
    moves: [
      { label: "Move 1", text: "Size the fleet at roughly 700 to 800 aircraft, mostly narrow-body." },
      { label: "Move 2", text: "Apply sectors per aircraft per day, around four to six, and seats per aircraft near 180." },
      { label: "Move 3", text: "Apply load factor, which for Indian carriers typically runs 80 to 90%." },
      { label: "Move 4", text: "Annualise, then subtract the international share flown by the same fleet." },
      { label: "Check", text: "That is roughly one journey per ten Indians a year. Low by global standards and exactly why the market is considered underpenetrated." },
    ],
    pitfalls: [
      "Confusing passenger journeys with unique travellers, when frequent flyers fly many times.",
      "Ignoring load factor and assuming full aircraft.",
      "Forgetting to separate domestic from international flying.",
    ],
  },
  {
    slug: "data-centre-campus-mumbai-power",
    shape: "guesstimate",
    title: "Estimate the electricity a data centre campus in Mumbai consumes.",
    type: "Resource estimation",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 400 to 900 million units a year for a large campus, cooling included.",
    hints: ["Cooling is not a detail. In Mumbai's climate it can add 50% on top of the servers themselves."],
    moves: [
      { label: "Move 1", text: "Size the IT load. A large campus might run 50 to 100 MW of computing capacity." },
      { label: "Move 2", text: "Apply near-constant utilisation, since data centres run continuously rather than in shifts." },
      { label: "Move 3", text: "Apply a power usage effectiveness multiplier, roughly 1.4 to 1.6 in a hot, humid climate." },
      { label: "Move 4", text: "Multiply through 8,760 hours a year to reach total units consumed." },
      { label: "Check", text: "Compare against a town's consumption. A single campus drawing as much as a small city is the arresting and correct observation." },
    ],
    pitfalls: [
      "Forgetting cooling overhead, which is a large share of total draw in Mumbai.",
      "Applying an office-style utilisation pattern to a facility that never switches off.",
      "Confusing capacity in megawatts with energy in units.",
    ],
  },
  {
    slug: "books-sold-india-annually",
    shape: "guesstimate",
    title: "How many books are sold in India each year?",
    type: "Market sizing",
    difficulty: 2,
    minutes: 20,
    answer: "Roughly 2.5 to 3.5 billion copies including textbooks, of which trade books are a small minority.",
    hints: ["Textbooks dwarf everything else. Decide whether they are in scope and say so before you start."],
    moves: [
      { label: "Move 1", text: "Separate textbooks from trade books. Educational publishing is the overwhelming majority of unit volume." },
      { label: "Move 2", text: "Size textbooks from 250 million school children and several books each per year." },
      { label: "Move 3", text: "Size trade books from the literate, book-buying population, which is a much narrower group." },
      { label: "Move 4", text: "Apply purchase frequency for that narrower group, perhaps two or three books a year." },
      { label: "Check", text: "Note the value inversion. Trade books carry far higher price per copy, so value share differs greatly from volume share." },
    ],
    pitfalls: [
      "Answering without stating whether textbooks are included, which changes the answer tenfold.",
      "Applying Western reading habits to the Indian trade market.",
      "Ignoring second-hand and pirated copies, which are substantial.",
    ],
  },
  {
    slug: "petrol-vehicles-indian-roads-2035",
    shape: "guesstimate",
    title: "Estimate how many petrol vehicles will still be on Indian roads in 2035.",
    type: "Market sizing",
    difficulty: 3,
    minutes: 25,
    answer: "Roughly 250 to 320 million, since the existing fleet turns over far more slowly than new sales shift.",
    hints: ["New sales mix and fleet mix are different things. Vehicles sold today are still on the road in 2035."],
    moves: [
      { label: "Move 1", text: "Size today's fleet, roughly 300 million vehicles, overwhelmingly two-wheelers." },
      { label: "Move 2", text: "Apply scrappage. At a 15 year average life, only a fraction of today's fleet retires by 2035." },
      { label: "Move 3", text: "Add new petrol sales between now and then, which continue even as the electric share rises." },
      { label: "Move 4", text: "Subtract retirements and sum, keeping two-wheelers and cars separate since they electrify at different speeds." },
      { label: "Check", text: "The key insight is inertia. Even aggressive electric adoption in new sales leaves a very large petrol fleet in 2035." },
    ],
    pitfalls: [
      "Applying the projected electric share of new sales to the whole fleet.",
      "Assuming rapid scrappage in a market where vehicles are kept for a very long time.",
      "Treating cars and two-wheelers as one category when they electrify at completely different rates.",
    ],
  },
];
